/**
 * # Ship Preview Assets
 *
 * Serves pre-rendered ship hull and module PNGs to the ShipUpgradeSelector TGUI
 * so players can see the composited ship before buying.
 *
 * The PNGs and the compositing geometry (slot marker positions, module connector
 * offsets) are generated from the DMMs by tools/ship_previews/generate_ship_previews.py.
 * Re-run that script after editing modular hulls or module maps.
 */

#define SHIP_PREVIEW_DIR "voidcrew/modules/ship_upgrades/previews/"

GLOBAL_LIST(ship_preview_manifest)

/**
 * Lazily load the preview manifest generated by tools/ship_previews.
 * Returns an empty list if the manifest is missing (previews simply won't show).
 */
/proc/get_ship_preview_manifest()
	if(!isnull(GLOB.ship_preview_manifest))
		return GLOB.ship_preview_manifest
	GLOB.ship_preview_manifest = list()
	var/manifest_path = SHIP_PREVIEW_DIR + "manifest.json"
	if(fexists(manifest_path))
		var/list/parsed = json_decode(file2text(manifest_path))
		if(islist(parsed))
			GLOB.ship_preview_manifest = parsed
	else
		log_asset("ship_previews: manifest missing at [manifest_path], ship previews disabled")
	return GLOB.ship_preview_manifest

/datum/asset/simple/ship_previews

/datum/asset/simple/ship_previews/register()
	assets = list()
	var/list/manifest = get_ship_preview_manifest()

	var/list/hulls = manifest["hulls"]
	for(var/hull_key in hulls)
		var/list/hull = hulls[hull_key]
		add_preview_png(hull["png"])

	var/list/modules = manifest["modules"]
	for(var/map_file in modules)
		var/list/entry = modules[map_file]
		add_preview_png(entry["png"])
		var/list/themed_variants = entry["themes"]
		for(var/theme_id in themed_variants)
			var/list/variant = themed_variants[theme_id]
			add_preview_png(variant["png"])

	return ..()

/datum/asset/simple/ship_previews/proc/add_preview_png(png_name)
	if(!png_name || assets[png_name])
		return
	var/png_path = SHIP_PREVIEW_DIR + png_name
	if(!fexists(png_path))
		log_asset("ship_previews: missing preview image [png_path]")
		return
	assets[png_name] = file(png_path)

#undef SHIP_PREVIEW_DIR
