/**
 * # Bounty hunting: what criminals are doing when found
 *
 * Owner: P3 AI. Do not edit this file outside P3.
 *
 * What it owns: the idle activities (spec section 3), each with real objects:
 * - bar: a stool or chair beside a table or counter, a drink in hand, sipped now and then;
 * - chat: turns at talking with a companion (or whoever is at hand);
 * - trade: at a trader's counter or a vending machine, haggling out loud;
 * - explore: three to five things on the site to walk up to and look over;
 * - loot: lockers and crates (zone loot first) opened, gone through and shut again;
 * - camp: a small camp made once (a fire, or a fixed lamp where a fire won't burn; a mattress; a
 *   crate), sat at, with errands;
 * - blend: the routine a trader-outpost fugitive and every one of its decoys share (AR-C6/C7): the
 *   same steps, weights, speed and lines, so nothing in how they act gives the fugitive away.
 * An activity scans for what it uses once, when it starts (or a blend step starts), never per tick.
 * Anything it uses is used from right beside it (Adjacent(): never through a wall or glass), a spot
 * they could not walk to is not picked again while the activity lasts, and at a trader outpost the
 * blend routine only picks spots on the public floor (L5).
 * It runs while they are calm; a flight or a fight puts it away, and it is set up again after.
 * The decoy's AI (/mob/living/basic/bounty_criminal/decoy: blend, and getting out of the way when
 * hit) is here too; what a decoy does when accused is P6's.
 *
 * The shared vars are declared in bounty_types.dm and nowhere else; a var only P3 uses has an
 * `ai_` prefix.
 */

/mob/living/basic/bounty_criminal
	/// What they are doing now (/datum/bounty_activity), if anything
	var/datum/bounty_activity/ai_activity
	/// The kind start_activity() set (BOUNTY_ACTIVITY_*), kept so they go back to it once calm
	var/ai_activity_kind
	/// Weakref to what it happens at
	var/datum/weakref/ai_activity_anchor
	/// world.time before which an activity that could not be set up is not tried again
	var/ai_activity_retry_at = 0
	/// The drink in their hand, held in their contents
	var/obj/item/reagent_containers/cup/glass/drinkingglass/ai_drink
	/// Weakref to the seat they sat down on, so only that one is ever left
	var/datum/weakref/ai_seat_ref
	/// Sitting on the floor
	var/ai_crouching = FALSE
	/// Weakrefs to the camp they made: the fire or lamp, the mattress, the crate
	var/list/ai_camp
	/// The mattress and crate were made; only the fire is ever made again
	var/ai_camp_made = FALSE
	/// Glasses left on tables at the bar; past BOUNTY_BAR_GLASSES_MAX the glass just goes (M4)
	var/ai_glasses_left = 0
	/// Spots they could not walk to (turf = TRUE), not picked again until the activity changes (L5)
	var/list/ai_failed_spots
	/// Where the activity may send them (turf = TRUE), or null for anywhere on their site: a trader outpost's public floor while blending in (L5)
	var/list/ai_allowed_floor

/**
 * Sets what they are doing until a hunter turns up: `kind` is a BOUNTY_ACTIVITY_*, `anchor` the
 * thing it happens at (a stool, a table, a trader, a loot crate, a companion, the camp's spot), or
 * null to find one nearby. BOUNTY_ACTIVITY_BLEND also makes them a blended patron. Returns the
 * activity, or null if nothing could be set up (they stand around and try again later).
 */
/mob/living/basic/bounty_criminal/proc/start_activity(kind, atom/anchor)
	ai_suspend_activity()
	ai_activity_kind = kind
	ai_activity_anchor = anchor ? WEAKREF(anchor) : null
	ai_activity_retry_at = 0
	ai_failed_spots = null
	ai_allowed_floor = null
	if(kind == BOUNTY_ACTIVITY_BLEND)
		ai_start_blend()
	else if(blended)
		ai_end_blend()
	if(!kind)
		return null
	return ai_resume_activity()

/// Their activity, set up again if it was put away. Falls back to standing around when it can't be set up.
/mob/living/basic/bounty_criminal/proc/ai_resume_activity()
	if(ai_activity)
		return ai_activity
	if(!ai_activity_kind || world.time < ai_activity_retry_at)
		return null
	var/atom/anchor = ai_activity_anchor?.resolve()
	var/activity_type = ai_activity_type(ai_activity_kind)
	var/datum/bounty_activity/activity = new activity_type(src, anchor)
	if(!activity.setup())
		qdel(activity)
		activity = new /datum/bounty_activity/loiter(src, anchor)
		if(!activity.setup())
			qdel(activity)
			ai_activity_retry_at = world.time + BOUNTY_ACTIVITY_RETRY
			return null
	ai_activity = activity
	return activity

/// The activity datum for `kind`
/mob/living/basic/bounty_criminal/proc/ai_activity_type(kind)
	switch(kind)
		if(BOUNTY_ACTIVITY_BAR)
			return /datum/bounty_activity/bar
		if(BOUNTY_ACTIVITY_CHAT)
			return /datum/bounty_activity/chat
		if(BOUNTY_ACTIVITY_TRADE)
			return /datum/bounty_activity/trade
		if(BOUNTY_ACTIVITY_EXPLORE)
			return /datum/bounty_activity/explore
		if(BOUNTY_ACTIVITY_LOOT)
			return /datum/bounty_activity/loot
		if(BOUNTY_ACTIVITY_CAMP)
			return /datum/bounty_activity/camp
		if(BOUNTY_ACTIVITY_BLEND)
			return /datum/bounty_activity/blend
	return /datum/bounty_activity/loiter

/// A meek criminal never loots: it looks around instead
/mob/living/basic/bounty_criminal/meek/ai_activity_type(kind)
	if(kind == BOUNTY_ACTIVITY_LOOT)
		return /datum/bounty_activity/explore
	return ..()

/// Puts their activity away (drink down, up from the seat), keeping its kind to go back to
/mob/living/basic/bounty_criminal/proc/ai_suspend_activity()
	if(!ai_activity)
		return
	var/datum/bounty_activity/old = ai_activity
	ai_activity = null
	old.finish()
	qdel(old)

/// Stops their activity for good
/mob/living/basic/bounty_criminal/proc/ai_end_activity()
	ai_activity_kind = null
	ai_activity_anchor = null
	ai_suspend_activity()

/// One step of their activity, where they stand: arriving the first time, then its business. Returns BOUNTY_STEP_*.
/mob/living/basic/bounty_criminal/proc/ai_activity_step(seconds)
	if(!ai_activity)
		return BOUNTY_STEP_DONE
	if(!ai_activity.arrived)
		ai_activity.arrived = TRUE
		ai_activity.arrive()
	return ai_activity ? ai_activity.act(seconds) : BOUNTY_STEP_DONE

// ===== BLENDING IN =====

/// A patron now: moves like every other, can't be pulled, and shots aimed at someone else pass through them
/mob/living/basic/bounty_criminal/proc/ai_start_blend()
	blended = TRUE
	ai_set_pace(BOUNTY_CALM_SPEED)

/**
 * No longer passing as a patron: a fugitive found out does not go back to it. P6's act ends with it
 * (the component's stop_blending(): pulls, containers and the turrets' faction back to normal), so
 * `blended` and the act never disagree (C1).
 */
/mob/living/basic/bounty_criminal/proc/ai_end_blend()
	var/datum/component/bounty_outpost_blend/act = GetComponent(/datum/component/bounty_outpost_blend)
	act?.stop_blending()
	blended = FALSE
	if(ai_activity_kind == BOUNTY_ACTIVITY_BLEND)
		ai_end_activity()

// ===== SEATS, DRINKS, SPOTS =====

/// Sits on `seat` from its tile
/mob/living/basic/bounty_criminal/proc/ai_sit_on(obj/structure/chair/seat)
	if(QDELETED(seat))
		return FALSE
	if(buckled == seat)
		return TRUE
	if(loc != seat.loc || seat.has_buckled_mobs())
		return FALSE
	ai_stand_up()
	if(!seat.buckle_mob(src, force = TRUE))
		return FALSE
	ai_seat_ref = WEAKREF(seat)
	return TRUE

/// Sits down on the floor
/mob/living/basic/bounty_criminal/proc/ai_crouch()
	if(ai_crouching || buckled)
		return
	ai_crouching = TRUE
	add_offsets(BOUNTY_AI_TRAIT, y_add = -4)

/// Up from their seat or the floor. Only a seat they sat on themselves: never out of a bed or a chair someone put them in.
/mob/living/basic/bounty_criminal/proc/ai_stand_up()
	if(ai_crouching)
		ai_crouching = FALSE
		remove_offsets(BOUNTY_AI_TRAIT)
	var/obj/structure/chair/seat = ai_seat_ref?.resolve()
	ai_seat_ref = null
	if(seat && buckled == seat)
		seat.unbuckle_mob(src, force = TRUE)

/// A drink in hand, poured for the occasion
/mob/living/basic/bounty_criminal/proc/ai_take_drink()
	if(!QDELETED(ai_drink))
		return ai_drink
	var/obj/item/reagent_containers/cup/glass/drinkingglass/glass = new(src)
	glass.reagents.add_reagent(pick(/datum/reagent/consumable/ethanol/beer, /datum/reagent/consumable/ethanol/whiskey, /datum/reagent/consumable/ethanol/rum), 25)
	ai_drink = glass
	ai_hand = bounty_ai_update_held(src, ai_hand, glass)
	return glass

/// A sip; an empty glass gets filled again after a while
/mob/living/basic/bounty_criminal/proc/ai_sip()
	if(QDELETED(ai_drink))
		return FALSE
	if(!ai_drink.reagents.total_volume)
		ai_drink.reagents.add_reagent(/datum/reagent/consumable/ethanol/beer, 25)
		visible_message(span_notice("[src] gets another drink."), vision_distance = 5)
	else
		ai_drink.reagents.remove_all(5)
		visible_message(span_notice("[src] takes a sip from [p_their()] glass."), vision_distance = 5)
		playsound(src, 'sound/items/drink.ogg', 20, TRUE, -4)
	ai_hand = bounty_ai_update_held(src, ai_hand, ai_drink)
	return TRUE

/**
 * Sets the drink down on `table` if it is right there (on their side of any glass), up to
 * BOUNTY_BAR_GLASSES_MAX glasses (M4); otherwise, or with no table, it goes.
 */
/mob/living/basic/bounty_criminal/proc/ai_put_drink_down(obj/structure/table/table)
	var/obj/item/glass = ai_drink
	ai_drink = null
	ai_hand = bounty_ai_update_held(src, ai_hand, null)
	if(QDELETED(glass))
		return
	if(stat == CONSCIOUS && ai_glasses_left < BOUNTY_BAR_GLASSES_MAX && !QDELETED(table) && isturf(table.loc) && isturf(loc) && Adjacent(table))
		ai_glasses_left++
		glass.forceMove(table.loc)
		glass.pixel_x = rand(-6, 6)
		glass.pixel_y = rand(0, 6)
		visible_message(span_notice("[src] puts [glass] down on [table]."), vision_distance = 5)
		return
	qdel(glass)

/// A floor tile they can stand on: not space, lava or a chasm, free, on their site
/mob/living/basic/bounty_criminal/proc/ai_standable(turf/tile)
	if(!isopenturf(tile) || isspaceturf(tile) || isgroundlessturf(tile) || islava(tile) || ischasm(tile))
		return FALSE
	if(tile != loc && tile.is_blocked_turf(source_atom = src))
		return FALSE
	return leash_ok(tile)

/// Whether an activity may send them to `tile`: not a spot they failed to reach, and on the floor it is kept to (L5)
/mob/living/basic/bounty_criminal/proc/ai_spot_allowed(turf/tile)
	if(LAZYACCESS(ai_failed_spots, tile))
		return FALSE
	return !ai_allowed_floor || ai_allowed_floor[tile]

/// Remembers `tile` as somewhere they could not walk to, for as long as the activity lasts (a few at most)
/mob/living/basic/bounty_criminal/proc/ai_spot_failed(turf/tile)
	if(!isturf(tile))
		return
	LAZYSET(ai_failed_spots, tile, TRUE)
	if(length(ai_failed_spots) > BOUNTY_FAILED_SPOTS_MAX)
		ai_failed_spots.Cut(1, 2)

/**
 * The nearest free tile within `distance` of `thing` they can stand on (not its own tile), or null.
 * Right beside it (distance 1), nothing may stand between the tile and the thing (Adjacent(): no
 * wall, glass or rail), since they will use it from there.
 */
/mob/living/basic/bounty_criminal/proc/ai_free_tile_beside(atom/thing, distance = 1)
	var/turf/center = get_turf(thing)
	if(!center)
		return null
	var/turf/best
	var/best_distance = INFINITY
	for(var/turf/tile as anything in RANGE_TURFS(distance, center))
		if(tile == center || !ai_standable(tile) || !ai_spot_allowed(tile))
			continue
		if(distance <= 1 && !tile.Adjacent(thing))
			continue
		var/from_us = get_dist(src, tile)
		if(from_us < best_distance)
			best = tile
			best_distance = from_us
	return best

/// A random free tile within `radius` of `center`, in the same area, or null
/mob/living/basic/bounty_criminal/proc/ai_random_tile_near(turf/center, radius)
	if(!center)
		return null
	var/area/here = get_area(src)
	for(var/attempt in 1 to 8)
		var/turf/tile = locate(center.x + rand(-radius, radius), center.y + rand(-radius, radius), center.z)
		if(tile && tile != loc && get_area(tile) == here && ai_standable(tile) && ai_spot_allowed(tile))
			return tile
	return null

/// A table beside `thing`, or null
/mob/living/basic/bounty_criminal/proc/ai_table_beside(atom/thing)
	var/turf/center = get_turf(thing)
	if(!center)
		return null
	for(var/turf/tile as anything in RANGE_TURFS(1, center))
		var/obj/structure/table/table = locate() in tile
		if(table)
			return table
	return null

/**
 * Whether they could sit on `seat`: loose on the floor, nobody on it, on their site. Stools (bar
 * stools too) have can_buckle off for people; they are sat on with a forced buckle all the same.
 */
/mob/living/basic/bounty_criminal/proc/ai_seat_usable(obj/structure/chair/seat)
	if(QDELETED(seat) || !isturf(seat.loc) || istype(seat, /obj/structure/chair/e_chair))
		return FALSE
	if(seat.has_buckled_mobs() && !(src in seat.buckled_mobs))
		return FALSE
	for(var/mob/living/other in seat.loc)
		if(other != src && other.density)
			return FALSE
	return leash_ok(seat.loc) && (seat.loc == loc || ai_spot_allowed(seat.loc))

/// The nearest seat within `range` of `near` they could sit on, beside a table if `needs_table`
/mob/living/basic/bounty_criminal/proc/ai_find_seat(atom/near, range = BOUNTY_ACTIVITY_RANGE, needs_table = TRUE)
	var/turf/center = get_turf(near) || get_turf(src)
	if(!center)
		return null
	var/obj/structure/chair/best
	var/best_distance = INFINITY
	for(var/obj/structure/chair/seat in range(range, center))
		if(!ai_seat_usable(seat) || (needs_table && !ai_table_beside(seat)))
			continue
		var/distance = get_dist(src, seat)
		if(distance < best_distance)
			best = seat
			best_distance = distance
	return best

/// The nearest table within `range` of `near` with room to stand at, or null
/mob/living/basic/bounty_criminal/proc/ai_find_table(atom/near, range = BOUNTY_ACTIVITY_RANGE)
	var/turf/center = get_turf(near) || get_turf(src)
	if(!center)
		return null
	var/obj/structure/table/best
	var/best_distance = INFINITY
	for(var/obj/structure/table/table in range(range, center))
		if(!leash_ok(get_turf(table)))
			continue
		var/distance = get_dist(src, table)
		if(distance < best_distance && ai_free_tile_beside(table))
			best = table
			best_distance = distance
	return best

/// The nearest trader or vending machine within `range`: somewhere to look at goods and haggle
/mob/living/basic/bounty_criminal/proc/ai_find_stall(range = BOUNTY_ACTIVITY_RANGE)
	var/turf/center = get_turf(src)
	if(!center)
		return null
	var/atom/best
	var/best_distance = INFINITY
	for(var/atom/movable/thing in range(range, center))
		if(!istype(thing, /mob/living/basic/outpost_trader) && !istype(thing, /obj/machinery/vending))
			continue
		if(!leash_ok(get_turf(thing)))
			continue
		var/distance = get_dist(src, thing)
		// Only with somewhere in front of it they may stand (never only behind the counter, L5)
		if(distance < best_distance && ai_free_tile_beside(thing, 2))
			best = thing
			best_distance = distance
	return best

/**
 * Someone to talk to within `range`: their own companions first; otherwise someone at hand who is
 * awake and not played (a patron, an outpost regular, another blended patron, one of their own faction).
 */
/mob/living/basic/bounty_criminal/proc/ai_find_chat_partner(range = BOUNTY_ACTIVITY_RANGE, patrons_only = FALSE)
	var/turf/here = get_turf(src)
	if(!here)
		return null
	if(!patrons_only)
		for(var/mob/living/basic/bounty_companion/buddy as anything in ai_companions())
			if(buddy.stat == CONSCIOUS && get_dist(src, buddy) <= range)
				return buddy
	var/list/options = list()
	for(var/mob/living/basic/other in range(range, here))
		if(other == src || other.stat != CONSCIOUS || other.client)
			continue
		if(istype(other, /mob/living/basic/ambient_npc))
			options += other
		else if(istype(other, /mob/living/basic/bounty_criminal))
			var/mob/living/basic/bounty_criminal/patron = other
			if(patron.blended || !patrons_only)
				options += other
		else if(!patrons_only && (other.mob_biotypes & MOB_HUMANOID) && faction_check_atom(other))
			options += other
	return length(options) ? pick(options) : null

/// Whether `thing` is worth walking up to and looking over while exploring
/proc/bounty_ai_is_interesting(obj/thing)
	var/static/list/interesting = typecacheof(list(
		/obj/item/kirbyplants,
		/obj/machinery/computer,
		/obj/machinery/vending,
		/obj/structure/bonfire,
		/obj/structure/bookcase,
		/obj/structure/closet,
		/obj/structure/flora/rock,
		/obj/structure/flora/tree,
		/obj/structure/frame,
		/obj/structure/girder,
		/obj/structure/reagent_dispensers,
		/obj/structure/statue,
		/obj/structure/table,
	))
	return is_type_in_typecache(thing, interesting) && isturf(thing.loc) && !thing.invisibility

/// Three to five things to look at around `anchor`, spread out, or spots on open ground when there is little; as weakrefs
/mob/living/basic/bounty_criminal/proc/ai_find_points_of_interest(atom/anchor)
	var/turf/center = get_turf(anchor) || get_turf(src)
	. = list()
	if(!center)
		return
	var/list/found = list()
	for(var/obj/thing in range(BOUNTY_EXPLORE_RANGE, center))
		if(bounty_ai_is_interesting(thing) && leash_ok(get_turf(thing)))
			found += thing
	shuffle_inplace(found)
	var/list/chosen = list()
	for(var/obj/thing as anything in found)
		var/too_close = FALSE
		for(var/atom/other as anything in chosen)
			if(get_dist(other, thing) < 3)
				too_close = TRUE
				break
		if(too_close)
			continue
		chosen += thing
		if(length(chosen) >= 5)
			break
	for(var/attempt in 1 to 12)
		if(length(chosen) >= 3)
			break
		var/turf/tile = locate(center.x + rand(-BOUNTY_EXPLORE_RANGE, BOUNTY_EXPLORE_RANGE), center.y + rand(-BOUNTY_EXPLORE_RANGE, BOUNTY_EXPLORE_RANGE), center.z)
		if(tile && ai_standable(tile) && ai_spot_allowed(tile))
			chosen += tile
	for(var/atom/point as anything in chosen)
		. += WEAKREF(point)

/// Whether they could go through `box`: loose, not locked or welded, not outpost property, not a body bag, on their site
/mob/living/basic/bounty_criminal/proc/ai_can_rummage(obj/structure/closet/box)
	if(QDELETED(box) || !isturf(box.loc) || box.locked || box.welded)
		return FALSE
	if(istype(box, /obj/structure/closet/body_bag) || box.wall_mounted || (box.resistance_flags & INDESTRUCTIBLE))
		return FALSE
	return leash_ok(box.loc)

/// Up to four containers to go through around `anchor`, zone loot caches first; as weakrefs
/mob/living/basic/bounty_criminal/proc/ai_find_containers(atom/anchor)
	var/turf/center = get_turf(anchor) || get_turf(src)
	. = list()
	if(!center)
		return
	var/list/caches = list()
	var/list/others = list()
	if(istype(anchor, /obj/structure/closet) && ai_can_rummage(anchor))
		caches += anchor
	for(var/obj/structure/closet/box in range(BOUNTY_ACTIVITY_RANGE, center))
		if(box == anchor || !ai_can_rummage(box))
			continue
		if(istype(box, /obj/structure/closet/crate/zone_loot))
			caches += box
		else
			others += box
	shuffle_inplace(others)
	for(var/obj/structure/closet/box as anything in caches + others)
		. += WEAKREF(box)
		if(length(.) >= 4)
			break

/// Shuts `box` after going through it, from right beside it, unless someone is standing in it
/mob/living/basic/bounty_criminal/proc/ai_close_container(obj/structure/closet/box)
	if(QDELETED(box) || !box.opened || !isturf(loc) || !Adjacent(box))
		return
	if(locate(/mob/living) in box.loc)
		return
	if(box.close())
		visible_message(span_notice("[src] shuts [box]."), vision_distance = 7)

/**
 * The camp: a fire in the middle (a fixed lamp where there isn't the air for one), a mattress and
 * an empty crate around it. The mattress and crate are made once; a fire that went out is lit
 * again, and one that is gone is replaced. The fire is solid, so no walk, flight or fight takes
 * anyone through the flames (L4). Returns the fire or lamp, or null.
 */
/mob/living/basic/bounty_criminal/proc/ai_make_camp(turf/center)
	var/atom/fire = ai_camp_fire()
	if(fire)
		var/obj/structure/bonfire/bonfire = fire
		if(istype(bonfire) && !bonfire.burning)
			bonfire.start_burning()
		return fire
	if(!center)
		return null
	var/list/tiles = list()
	for(var/turf/tile as anything in RANGE_TURFS(2, center))
		if(tile != loc && ai_standable(tile) && !(locate(/obj/structure) in tile))
			tiles += tile
	if(!length(tiles))
		return null
	var/turf/fire_turf = (center in tiles) ? center : pick(tiles)
	tiles -= fire_turf
	var/obj/structure/bonfire/bounty_camp/bonfire = new(fire_turf)
	bonfire.start_burning()
	if(bonfire.burning)
		fire = bonfire
	else
		qdel(bonfire)
		fire = new /obj/structure/bounty_camp_lamp(fire_turf)
	LAZYADD(ai_camp, WEAKREF(fire))
	if(ai_camp_made)
		return fire
	ai_camp_made = TRUE
	// The fire's neighbours stay free to sit at
	for(var/turf/beside as anything in tiles.Copy())
		if(get_dist(beside, fire_turf) <= 1)
			tiles -= beside
	if(length(tiles))
		ai_camp += WEAKREF(new /obj/structure/bed/maint(pick_n_take(tiles)))
	if(length(tiles))
		ai_camp += WEAKREF(new /obj/structure/closet/crate(pick_n_take(tiles)))
	return fire

/// Their camp's fire or lamp, if it is still there where they put it (one carried off is gone, L4)
/mob/living/basic/bounty_criminal/proc/ai_camp_fire()
	var/atom/movable/fire = ai_camp_piece(/obj/structure/bonfire) || ai_camp_piece(/obj/structure/bounty_camp_lamp)
	return (fire && isturf(fire.loc)) ? fire : null

/// A camp's fire: solid, so nobody walks through it and catches light (L4)
/obj/structure/bonfire/bounty_camp
	density = TRUE

/// A camp's lamp where a fire won't burn: fixed where it was set down, so nobody carries it off (L4)
/obj/structure/bounty_camp_lamp
	name = "camp lantern"
	desc = "A lantern set down on the ground and left burning."
	icon = 'icons/obj/lighting.dmi'
	icon_state = "lantern-on"
	anchored = TRUE
	density = FALSE
	max_integrity = 50
	light_range = 5
	light_power = 1.5
	light_color = "#ffcc66"

/// They are gone: the camp stays as it is, but the fire burns down
/mob/living/basic/bounty_criminal/proc/ai_put_out_camp()
	var/obj/structure/bonfire/bonfire = ai_camp_piece(/obj/structure/bonfire)
	if(bonfire?.burning)
		bonfire.extinguish()

/// A piece of their camp of `piece_type`, if it is still there
/mob/living/basic/bounty_criminal/proc/ai_camp_piece(piece_type)
	for(var/datum/weakref/ref as anything in ai_camp)
		var/atom/piece = ref?.resolve()
		if(!QDELETED(piece) && istype(piece, piece_type))
			return piece
	return null

/// The patron they are talking to answers them, a moment after they spoke
/mob/living/basic/bounty_criminal/proc/ai_get_reply(datum/weakref/partner_ref)
	var/mob/living/partner = partner_ref?.resolve()
	if(partner && stat == CONSCIOUS && get_dist(src, partner) <= 2)
		bounty_ai_reply(partner, src)

/// A companion or another bounty mob answers `speaker`; anyone else just carries on
/proc/bounty_ai_reply(mob/living/partner, mob/living/speaker)
	if(QDELETED(partner) || partner.stat != CONSCIOUS)
		return
	if(istype(partner, /mob/living/basic/bounty_companion))
		partner.face_atom(speaker)
		INVOKE_ASYNC(partner, TYPE_PROC_REF(/mob/living, bounty_say), "companion_reply")
	else if(istype(partner, /mob/living/basic/bounty_criminal))
		partner.face_atom(speaker)
		INVOKE_ASYNC(partner, TYPE_PROC_REF(/mob/living, bounty_say), "idle_chat")

// ===== PLANNING =====

/// Last in a criminal's tree: while calm, walk to the activity's spot, or carry it on there
/datum/ai_planning_subtree/bounty_activity

/datum/ai_planning_subtree/bounty_activity/SelectBehaviors(datum/ai_controller/controller, seconds_per_tick)
	var/mob/living/basic/bounty_criminal/criminal = controller.pawn
	if(!istype(criminal) || criminal.ai_mode != BOUNTY_AI_CALM || criminal.hidden || !criminal.ai_can_act())
		return
	var/datum/bounty_activity/activity = criminal.ai_activity || criminal.ai_resume_activity()
	if(!activity)
		return
	if(!activity.at_spot())
		controller.set_blackboard_key(BB_BOUNTY_DESTINATION, activity.spot)
		var/walk_type = activity.spot_distance ? /datum/ai_behavior/travel_towards/bounty/adjacent : /datum/ai_behavior/travel_towards/bounty
		controller.queue_behavior(walk_type, BB_BOUNTY_DESTINATION)
		return SUBTREE_RETURN_FINISH_PLANNING
	controller.queue_behavior(/datum/ai_behavior/bounty_activity)
	return SUBTREE_RETURN_FINISH_PLANNING

/// Carries the activity on about once a second, planning going on meanwhile so a hunter is noticed
/datum/ai_behavior/bounty_activity
	action_cooldown = 1 SECONDS
	behavior_flags = AI_BEHAVIOR_CAN_PLAN_DURING_EXECUTION

/datum/ai_behavior/bounty_activity/setup(datum/ai_controller/controller)
	var/mob/living/basic/bounty_criminal/criminal = controller.pawn
	return istype(criminal) && !!criminal.ai_activity

/datum/ai_behavior/bounty_activity/perform(seconds_per_tick, datum/ai_controller/controller)
	var/mob/living/basic/bounty_criminal/criminal = controller.pawn
	var/datum/bounty_activity/activity = criminal.ai_activity
	if(!activity || criminal.ai_mode != BOUNTY_AI_CALM)
		return AI_BEHAVIOR_DELAY | AI_BEHAVIOR_FAILED
	if(!activity.at_spot())
		return AI_BEHAVIOR_DELAY | AI_BEHAVIOR_SUCCEEDED
	switch(criminal.ai_activity_step(seconds_per_tick))
		if(BOUNTY_STEP_MOVE)
			return AI_BEHAVIOR_DELAY | AI_BEHAVIOR_SUCCEEDED
		if(BOUNTY_STEP_DONE)
			criminal.ai_suspend_activity()
			return AI_BEHAVIOR_DELAY | AI_BEHAVIOR_SUCCEEDED
	return AI_BEHAVIOR_DELAY

// ===== ACTIVITIES =====

/**
 * Something a criminal does while nobody is after them. setup() finds what it uses (once) and sets
 * `spot`; they walk there and arrive() runs; act() runs about once a second and may send them
 * elsewhere (go_to(), BOUNTY_STEP_MOVE) or end (BOUNTY_STEP_DONE, and a new one is set up);
 * finish() puts everything back. Tests drive these directly (ai_activity_step()).
 */
/datum/bounty_activity
	/// Short text for the admin panel
	var/name = "standing around"
	var/mob/living/basic/bounty_criminal/doer
	var/datum/weakref/anchor_ref
	/// Where they are headed, or null where they are
	var/turf/spot
	/// How close to `spot` counts as there: 0 on it, 1 beside it
	var/spot_distance = 0
	/// arrive() has run for this spot
	var/arrived = FALSE
	/// world.time of the next line
	var/next_line = 0

/datum/bounty_activity/New(mob/living/basic/bounty_criminal/new_doer, atom/anchor)
	. = ..()
	doer = new_doer
	anchor_ref = anchor ? WEAKREF(anchor) : null

/datum/bounty_activity/Destroy()
	doer = null
	spot = null
	return ..()

/datum/bounty_activity/proc/anchor()
	var/atom/anchor = anchor_ref?.resolve()
	return QDELETED(anchor) ? null : anchor

/// Finds what to use and where to go. FALSE when it can't be done here.
/datum/bounty_activity/proc/setup()
	return TRUE

/// Sends them to `where` next (null: where they are)
/datum/bounty_activity/proc/go_to(turf/where, distance = 0)
	spot = where
	spot_distance = distance
	arrived = FALSE

/datum/bounty_activity/proc/at_spot()
	if(!spot)
		return TRUE
	if(!isturf(doer.loc))
		return FALSE
	return spot_distance ? get_dist(doer, spot) <= spot_distance : doer.loc == spot

/// Got there
/datum/bounty_activity/proc/arrive()
	return

/// About once a second in place. Returns BOUNTY_STEP_*.
/datum/bounty_activity/proc/act(seconds)
	return BOUNTY_STEP_CONTINUE

/// Puts everything back: the drink down, up on their feet
/datum/bounty_activity/proc/finish()
	if(doer?.ai_drink)
		doer.ai_put_drink_down(null)
	doer?.ai_stand_up()

/// They could not get to `spot`: stay where they are, don't pick it again (L5), and let act() pick something else
/datum/bounty_activity/proc/spot_unreachable()
	doer?.ai_spot_failed(spot)
	spot = null
	arrived = FALSE

/// Fallback when nothing else could be set up: standing about, then the real activity is tried again
/datum/bounty_activity/loiter
	name = "standing around"
	var/ends_at = 0

/datum/bounty_activity/loiter/setup()
	ends_at = world.time + rand(60, 120) SECONDS
	next_line = world.time + rand(15, 40) SECONDS
	return TRUE

/datum/bounty_activity/loiter/act(seconds)
	if(world.time >= ends_at)
		return BOUNTY_STEP_DONE
	if(prob(8))
		doer.setDir(pick(GLOB.cardinals))
	if(world.time >= next_line)
		next_line = world.time + rand(30, 60) SECONDS
		doer.ai_bark("idle_chat")
	return BOUNTY_STEP_CONTINUE

// ----- bar -----

/// A seat beside a table or counter, a drink in hand
/datum/bounty_activity/bar
	name = "drinking"
	var/datum/weakref/seat_ref
	var/datum/weakref/table_ref
	var/next_sip = 0
	var/next_look = 0

/datum/bounty_activity/bar/setup()
	var/atom/anchor = anchor()
	var/obj/structure/chair/seat
	var/obj/structure/table/table
	if(istype(anchor, /obj/structure/chair) && doer.ai_seat_usable(anchor))
		seat = anchor
	else if(istype(anchor, /obj/structure/table))
		table = anchor
	if(!seat)
		seat = doer.ai_find_seat(table || anchor || doer, BOUNTY_ACTIVITY_RANGE, TRUE)
	if(seat)
		if(!table || get_dist(table, seat) > 1)
			table = doer.ai_table_beside(seat)
		seat_ref = WEAKREF(seat)
		go_to(get_turf(seat))
	else
		table = table || doer.ai_find_table(anchor || doer)
		var/turf/stand = table && doer.ai_free_tile_beside(table)
		if(!stand)
			return FALSE
		go_to(stand)
	table_ref = table ? WEAKREF(table) : null
	return TRUE

/datum/bounty_activity/bar/arrive()
	var/obj/structure/chair/seat = seat_ref?.resolve()
	var/obj/structure/table/table = table_ref?.resolve()
	if(seat && !doer.ai_sit_on(seat))
		seat_ref = null
	if(table && !doer.buckled)
		doer.face_atom(table)
	doer.ai_take_drink()
	next_sip = world.time + rand(6, 12) SECONDS
	next_line = world.time + rand(8, 20) SECONDS
	next_look = world.time + rand(10, 25) SECONDS

/datum/bounty_activity/bar/act(seconds)
	if(world.time >= next_sip)
		next_sip = world.time + rand(12, 25) SECONDS
		doer.ai_sip()
	if(world.time >= next_line)
		next_line = world.time + rand(20, 45) SECONDS
		doer.ai_bark("bar")
	if(world.time >= next_look)
		next_look = world.time + rand(15, 30) SECONDS
		if(!doer.buckled)
			doer.setDir(pick(GLOB.cardinals))
	return BOUNTY_STEP_CONTINUE

/datum/bounty_activity/bar/finish()
	if(doer?.ai_drink)
		doer.ai_put_drink_down(table_ref?.resolve())
	return ..()

/datum/bounty_activity/bar/spot_unreachable()
	. = ..()
	seat_ref = null

// ----- chat -----

/// Turns at talking with a companion, or whoever is at hand
/datum/bounty_activity/chat
	name = "talking"
	var/datum/weakref/partner_ref
	var/my_turn = TRUE

/datum/bounty_activity/chat/setup()
	var/mob/living/partner = anchor()
	if(!isliving(partner) || partner == doer || partner.stat != CONSCIOUS)
		partner = doer.ai_find_chat_partner(BOUNTY_ACTIVITY_RANGE)
	if(!partner)
		return FALSE
	partner_ref = WEAKREF(partner)
	return approach()

/// Walks up beside their partner, if not there already
/datum/bounty_activity/chat/proc/approach()
	var/mob/living/partner = partner_ref?.resolve()
	if(QDELETED(partner))
		return FALSE
	if(get_dist(doer, partner) <= 1)
		go_to(null)
		return TRUE
	var/turf/stand = doer.ai_free_tile_beside(partner)
	if(!stand)
		return FALSE
	go_to(stand)
	return TRUE

/// Who they are talking to
/datum/bounty_activity/chat/proc/partner()
	var/mob/living/partner = partner_ref?.resolve()
	return QDELETED(partner) ? null : partner

/datum/bounty_activity/chat/arrive()
	var/mob/living/partner = partner()
	if(partner)
		doer.face_atom(partner)
	next_line = world.time + rand(2, 5) SECONDS

/datum/bounty_activity/chat/act(seconds)
	var/mob/living/partner = partner()
	if(!partner || partner.stat != CONSCIOUS)
		return BOUNTY_STEP_DONE
	if(get_dist(doer, partner) > 1)
		if(get_dist(doer, partner) > BOUNTY_ACTIVITY_RANGE || !approach())
			return BOUNTY_STEP_DONE
		return BOUNTY_STEP_MOVE
	doer.face_atom(partner)
	if(world.time >= next_line)
		next_line = world.time + rand(6, 11) SECONDS
		if(my_turn)
			doer.ai_bark("idle_chat")
		else
			bounty_ai_reply(partner, doer)
		my_turn = !my_turn
		if(prob(15))
			doer.manual_emote(pick("laughs.", "shrugs.", "nods.", "shakes [doer.p_their()] head."))
	return BOUNTY_STEP_CONTINUE

// ----- trade -----

/// At a trader's counter or a vending machine, haggling
/datum/bounty_activity/trade
	name = "haggling"
	var/datum/weakref/stall_ref
	var/next_shuffle = 0

/datum/bounty_activity/trade/setup()
	var/atom/stall = anchor()
	if(!istype(stall, /mob/living/basic/outpost_trader) && !istype(stall, /obj/machinery/vending) && !istype(stall, /obj/structure/table))
		stall = doer.ai_find_stall(BOUNTY_ACTIVITY_RANGE)
	if(!stall)
		return FALSE
	stall_ref = WEAKREF(stall)
	return pick_spot()

/// A spot in front of the stall, within two tiles
/datum/bounty_activity/trade/proc/pick_spot()
	var/atom/stall = stall_ref?.resolve()
	var/turf/stand = stall && doer.ai_free_tile_beside(stall, 2)
	if(!stand)
		return FALSE
	go_to(stand)
	return TRUE

/datum/bounty_activity/trade/arrive()
	var/atom/stall = stall_ref?.resolve()
	if(stall)
		doer.face_atom(stall)
	next_line = world.time + rand(3, 8) SECONDS
	if(!next_shuffle)
		next_shuffle = world.time + rand(60, 120) SECONDS

/datum/bounty_activity/trade/act(seconds)
	var/atom/stall = stall_ref?.resolve()
	if(QDELETED(stall))
		return BOUNTY_STEP_DONE
	doer.face_atom(stall)
	if(world.time >= next_line)
		next_line = world.time + rand(12, 20) SECONDS
		doer.ai_bark("trade_haggle")
		if(prob(35))
			doer.manual_emote(pick("counts out a few credits.", "points at something on the shelf.", "shakes [doer.p_their()] head at the price.", "leans on the counter."))
	if(world.time >= next_shuffle)
		next_shuffle = world.time + rand(60, 120) SECONDS
		if(pick_spot())
			return BOUNTY_STEP_MOVE
	return BOUNTY_STEP_CONTINUE

// ----- explore -----

/// Three to five things around the site, walked up to and looked over in turn
/datum/bounty_activity/explore
	name = "looking around"
	/// Weakrefs to the things (or turfs) to look at
	var/list/points
	var/index = 0
	var/linger_until = 0

/datum/bounty_activity/explore/setup()
	points = doer.ai_find_points_of_interest(anchor())
	if(!length(points))
		return FALSE
	return next_point()

/// The thing they are headed for now
/datum/bounty_activity/explore/proc/current()
	if(!index || index > length(points))
		return null
	var/datum/weakref/ref = points[index]
	var/atom/point = ref?.resolve()
	return QDELETED(point) ? null : point

/// On to the next thing
/datum/bounty_activity/explore/proc/next_point()
	for(var/attempt in 1 to length(points))
		index = (index % length(points)) + 1
		var/atom/point = current()
		if(!point)
			continue
		var/turf/stand = isturf(point) ? point : doer.ai_free_tile_beside(point)
		if(!stand)
			continue
		go_to(stand)
		linger_until = 0
		return TRUE
	return FALSE

/datum/bounty_activity/explore/arrive()
	linger_until = world.time + rand(5, 12) SECONDS
	var/atom/point = current()
	if(point && !isturf(point))
		doer.face_atom(point)
		if(prob(60))
			doer.visible_message(span_notice("[doer] looks [point] over."), vision_distance = 5)
	else
		doer.setDir(pick(GLOB.cardinals))
	if(prob(40))
		doer.ai_bark("explore")

/datum/bounty_activity/explore/act(seconds)
	if(world.time < linger_until)
		if(prob(15))
			doer.setDir(pick(GLOB.cardinals))
		return BOUNTY_STEP_CONTINUE
	if(!next_point())
		return BOUNTY_STEP_DONE
	return BOUNTY_STEP_MOVE

/datum/bounty_activity/explore/spot_unreachable()
	if(index && index <= length(points))
		points.Cut(index, index + 1)
		index = max(0, index - 1)
	. = ..()
	arrived = TRUE
	linger_until = 0

// ----- loot -----

/// Lockers and crates around, zone loot caches first: opened, gone through, shut again
/datum/bounty_activity/loot
	name = "going through the crates"
	/// Weakrefs to the containers
	var/list/containers
	var/index = 0
	/// 0 on the way, 1 going through it, 2 a pause before the next
	var/stage = 0
	var/stage_until = 0

/datum/bounty_activity/loot/setup()
	containers = doer.ai_find_containers(anchor())
	if(!length(containers))
		return FALSE
	return next_container()

/// The container they are at now
/datum/bounty_activity/loot/proc/current()
	if(!index || index > length(containers))
		return null
	var/datum/weakref/ref = containers[index]
	var/obj/structure/closet/box = ref?.resolve()
	return QDELETED(box) ? null : box

/// On to the next container they can get into
/datum/bounty_activity/loot/proc/next_container()
	for(var/attempt in 1 to length(containers))
		index = (index % length(containers)) + 1
		var/obj/structure/closet/box = current()
		if(!box || !doer.ai_can_rummage(box))
			continue
		var/turf/stand = doer.ai_free_tile_beside(box)
		if(!stand)
			continue
		go_to(stand)
		stage = 0
		return TRUE
	return FALSE

/datum/bounty_activity/loot/arrive()
	var/obj/structure/closet/box = current()
	stage = 2
	stage_until = world.time + 2 SECONDS
	if(!box || !isturf(doer.loc) || !doer.Adjacent(box))
		return
	doer.face_atom(box)
	if(!box.opened && !box.open())
		return
	doer.visible_message(span_notice("[doer] opens [box] and starts going through it."), vision_distance = 7)
	stage = 1
	stage_until = world.time + rand(5, 9) SECONDS

/datum/bounty_activity/loot/act(seconds)
	var/obj/structure/closet/box = current()
	if(stage == 1)
		if(!box)
			stage = 2
			stage_until = world.time
			return BOUNTY_STEP_CONTINUE
		if(world.time < stage_until)
			if(prob(50))
				box.Shake(1, 0, 0.3 SECONDS)
				playsound(box, SFX_RUSTLE, 30, TRUE, -4)
			if(prob(15))
				doer.ai_bark("loot")
			return BOUNTY_STEP_CONTINUE
		doer.ai_close_container(box)
		stage = 2
		stage_until = world.time + rand(4, 10) SECONDS
		return BOUNTY_STEP_CONTINUE
	if(world.time < stage_until)
		return BOUNTY_STEP_CONTINUE
	if(!next_container())
		return BOUNTY_STEP_DONE
	return BOUNTY_STEP_MOVE

/// A container they can't get to is struck off the list
/datum/bounty_activity/loot/spot_unreachable()
	if(index && index <= length(containers))
		containers.Cut(index, index + 1)
		index = max(0, index - 1)
	. = ..()
	arrived = TRUE
	stage = 2
	stage_until = world.time

// ----- camp -----

/// A small camp: sitting at the fire, with errands now and then (the crate, a walk round)
/datum/bounty_activity/camp
	name = "at the camp"
	var/datum/weakref/fire_ref
	/// null sitting at the fire, "crate" or "walk"
	var/errand
	var/errand_until = 0
	var/next_errand = 0

/datum/bounty_activity/camp/setup()
	var/turf/center = get_turf(anchor()) || get_turf(doer)
	var/atom/fire = doer.ai_make_camp(center)
	if(!fire)
		return FALSE
	fire_ref = WEAKREF(fire)
	return sit_down()

/// Back to a spot beside the fire
/datum/bounty_activity/camp/proc/sit_down()
	var/atom/fire = fire_ref?.resolve()
	var/turf/stand = fire && doer.ai_free_tile_beside(fire)
	if(!stand)
		return FALSE
	errand = null
	go_to(stand)
	return TRUE

/datum/bounty_activity/camp/arrive()
	var/atom/fire = fire_ref?.resolve()
	switch(errand)
		if("crate")
			var/obj/structure/closet/crate/box = doer.ai_camp_piece(/obj/structure/closet/crate)
			if(box && isturf(doer.loc) && doer.Adjacent(box) && (box.opened || box.open()))
				doer.face_atom(box)
				doer.visible_message(span_notice("[doer] goes through [box]."), vision_distance = 7)
			errand_until = world.time + rand(4, 8) SECONDS
		if("walk")
			doer.setDir(pick(GLOB.cardinals))
			errand_until = world.time + rand(3, 6) SECONDS
		else
			if(fire)
				doer.face_atom(fire)
			doer.ai_crouch()
			next_line = world.time + rand(8, 20) SECONDS
			next_errand = world.time + rand(60, 120) SECONDS

/datum/bounty_activity/camp/act(seconds)
	var/atom/fire = fire_ref?.resolve()
	if(!fire)
		return BOUNTY_STEP_DONE
	if(!errand)
		if(world.time >= next_line)
			next_line = world.time + rand(25, 50) SECONDS
			doer.ai_bark("camp")
		if(prob(2))
			doer.manual_emote(istype(fire, /obj/structure/bonfire) ? pick("warms [doer.p_their()] hands by the fire.", "pokes at the fire.") : pick("turns the lantern up a little.", "stretches."))
		if(world.time < next_errand)
			return BOUNTY_STEP_CONTINUE
		doer.ai_stand_up()
		var/obj/structure/closet/crate/box = doer.ai_camp_piece(/obj/structure/closet/crate)
		var/turf/stand = box && prob(50) ? doer.ai_free_tile_beside(box) : null
		if(stand)
			errand = "crate"
			go_to(stand)
			return BOUNTY_STEP_MOVE
		stand = doer.ai_random_tile_near(get_turf(fire), 3)
		if(stand)
			errand = "walk"
			go_to(stand)
			return BOUNTY_STEP_MOVE
		next_errand = world.time + rand(60, 120) SECONDS
		return BOUNTY_STEP_CONTINUE
	if(world.time < errand_until)
		return BOUNTY_STEP_CONTINUE
	if(errand == "crate")
		doer.ai_close_container(doer.ai_camp_piece(/obj/structure/closet/crate))
	if(!sit_down())
		return BOUNTY_STEP_DONE
	return BOUNTY_STEP_MOVE

/datum/bounty_activity/camp/spot_unreachable()
	. = ..()
	arrived = TRUE
	errand = "walk"
	errand_until = world.time

// ----- blend -----

/**
 * Passing as a patron at a trader outpost. The fugitive and every decoy run exactly this, with the
 * same steps and weights, the same pace (BOUNTY_CALM_SPEED) and the same lines ("idle_chat"): a
 * seat at the bar with a drink, talking with another patron, looking over a stall, or just
 * standing about somewhere in the room.
 */
/datum/bounty_activity/blend
	name = "blending in"
	/// "bar", "chat", "stall" or "mingle"
	var/step_kind
	var/step_until = 0
	var/datum/weakref/step_target
	var/datum/weakref/seat_ref
	var/datum/weakref/table_ref
	var/next_sip = 0

/datum/bounty_activity/blend/Destroy()
	if(doer)
		doer.ai_allowed_floor = null
	return ..()

/// A bar stool as the anchor (what P5 places them at) makes the first step a drink there. At a trader outpost, only its public floor is used (L5).
/datum/bounty_activity/blend/setup()
	doer.ai_allowed_floor = bounty_ai_outpost_floor(doer)
	var/obj/structure/chair/seat = anchor()
	if(istype(seat) && doer.ai_seat_usable(seat))
		seat_ref = WEAKREF(seat)
		var/obj/structure/table/table = doer.ai_table_beside(seat)
		table_ref = table ? WEAKREF(table) : null
		go_to(get_turf(seat))
		step_kind = "bar"
		step_until = 0
		return TRUE
	return next_step()

/// Picks the next step, by the same weights for everyone
/datum/bounty_activity/blend/proc/next_step()
	end_step()
	var/list/options = list("bar" = 3, "chat" = 3, "stall" = 2, "mingle" = 3)
	while(length(options))
		var/choice = pick_weight(options)
		options -= choice
		if(start_step(choice))
			return TRUE
	return start_step("mingle", in_place = TRUE)

/datum/bounty_activity/blend/proc/start_step(choice, in_place = FALSE)
	switch(choice)
		if("bar")
			var/obj/structure/chair/seat = doer.ai_find_seat(doer, BOUNTY_ACTIVITY_RANGE + 2, TRUE)
			if(!seat)
				return FALSE
			seat_ref = WEAKREF(seat)
			var/obj/structure/table/table = doer.ai_table_beside(seat)
			table_ref = table ? WEAKREF(table) : null
			go_to(get_turf(seat))
		if("chat")
			var/mob/living/partner = doer.ai_find_chat_partner(BOUNTY_ACTIVITY_RANGE, patrons_only = TRUE)
			if(!partner)
				return FALSE
			var/turf/stand = get_dist(doer, partner) <= 1 ? null : doer.ai_free_tile_beside(partner)
			if(!stand && get_dist(doer, partner) > 1)
				return FALSE
			step_target = WEAKREF(partner)
			go_to(stand)
		if("stall")
			var/atom/stall = doer.ai_find_stall(BOUNTY_ACTIVITY_RANGE + 2)
			var/turf/stand = stall && doer.ai_free_tile_beside(stall, 2)
			if(!stand)
				return FALSE
			step_target = WEAKREF(stall)
			go_to(stand)
		else
			var/turf/stand = in_place ? null : doer.ai_random_tile_near(get_turf(doer), 5)
			if(!in_place && !stand)
				return FALSE
			go_to(stand)
	step_kind = choice
	step_until = 0
	return TRUE

/datum/bounty_activity/blend/arrive()
	var/atom/target = step_target?.resolve()
	switch(step_kind)
		if("bar")
			var/obj/structure/chair/seat = seat_ref?.resolve()
			if(!seat || !doer.ai_sit_on(seat))
				step_until = world.time
				return
			doer.ai_take_drink()
			next_sip = world.time + rand(6, 12) SECONDS
			step_until = world.time + rand(40, 90) SECONDS
		if("chat")
			if(target)
				doer.face_atom(target)
			step_until = world.time + rand(20, 40) SECONDS
		if("stall")
			if(target)
				doer.face_atom(target)
				if(prob(50))
					doer.manual_emote("looks over the goods.")
			step_until = world.time + rand(15, 30) SECONDS
		else
			doer.setDir(pick(GLOB.cardinals))
			step_until = world.time + rand(10, 25) SECONDS
	next_line = world.time + rand(5, 15) SECONDS

/datum/bounty_activity/blend/act(seconds)
	if(world.time >= step_until)
		return next_step() ? BOUNTY_STEP_MOVE : BOUNTY_STEP_CONTINUE
	var/atom/target = step_target?.resolve()
	switch(step_kind)
		if("bar")
			if(world.time >= next_sip)
				next_sip = world.time + rand(12, 25) SECONDS
				doer.ai_sip()
		if("chat")
			var/mob/living/partner = target
			if(!isliving(partner) || partner.stat != CONSCIOUS || get_dist(doer, partner) > 2)
				step_until = world.time
				return BOUNTY_STEP_CONTINUE
			doer.face_atom(partner)
		if("stall")
			if(target)
				doer.face_atom(target)
		else
			if(prob(10))
				doer.setDir(pick(GLOB.cardinals))
	if(world.time >= next_line)
		next_line = world.time + rand(15, 30) SECONDS
		if(prob(step_kind == "chat" ? 70 : 30))
			doer.ai_bark("idle_chat")
			if(step_kind == "chat" && isliving(target))
				addtimer(CALLBACK(doer, TYPE_PROC_REF(/mob/living/basic/bounty_criminal, ai_get_reply), WEAKREF(target)), rand(3, 6) SECONDS, TIMER_DELETE_ME)
	return BOUNTY_STEP_CONTINUE

/// Ends the step: the glass goes with them (never left on the bar, M4), up from the seat
/datum/bounty_activity/blend/proc/end_step()
	if(doer?.ai_drink)
		doer.ai_put_drink_down(null)
	doer?.ai_stand_up()
	step_target = null
	seat_ref = null
	table_ref = null

/datum/bounty_activity/blend/finish()
	end_step()
	doer?.ai_allowed_floor = null
	return ..()

/**
 * The public floor of the trader outpost `patron` blends in at (P6's bounty_outpost_public_floor(),
 * as turf = TRUE), shared for BOUNTY_OUTPOST_FLOOR_CACHE between everyone there; null anywhere else,
 * or when the outpost has none (a broken load).
 */
/proc/bounty_ai_outpost_floor(mob/living/basic/bounty_criminal/patron)
	var/datum/component/bounty_outpost_blend/act = patron?.GetComponent(/datum/component/bounty_outpost_blend)
	var/obj/structure/overmap/trader_outpost/outpost = act?.outpost_ref?.resolve()
	if(!istype(outpost))
		return null
	var/static/list/cache = list()
	var/datum/weakref/key = WEAKREF(outpost)
	var/list/entry = cache[key]
	if(entry && world.time < entry[1])
		return entry[2]
	var/list/floor = list()
	for(var/turf/tile as anything in bounty_outpost_public_floor(outpost))
		floor[tile] = TRUE
	if(!length(floor))
		floor = null
	cache[key] = list(world.time + BOUNTY_OUTPOST_FLOOR_CACHE, floor)
	return floor

/datum/bounty_activity/blend/spot_unreachable()
	. = ..()
	arrived = TRUE
	step_until = world.time

// ===== DECOYS =====

/**
 * A decoy's AI: it blends in exactly like the fugitive (the blend activity, set by P6 with
 * start_activity(BOUNTY_ACTIVITY_BLEND)). While blended it shows no reaction of its own to
 * anything: what it says and does when accused or hit is P6's, which can move it out of the way
 * with ai_flee_from(). It never stops being a patron.
 *
 * P6 gives each production decoy its fugitive's controller type (so the two run the same routine);
 * this controller is only the default for a decoy made some other way. Every criminal tree carries
 * bounty_flee_and_calm, so a decoy that runs on any of them runs and then calms down (M3).
 */
/mob/living/basic/bounty_criminal/decoy
	ai_controller = /datum/ai_controller/basic_controller/bounty/criminal/decoy

/datum/ai_controller/basic_controller/bounty/criminal/decoy
	planning_subtrees = list(
		/datum/ai_planning_subtree/bounty_gate,
		/datum/ai_planning_subtree/bounty_flee_and_calm,
		/datum/ai_planning_subtree/bounty_activity,
	)

/// Always a patron
/mob/living/basic/bounty_criminal/decoy/ai_expose()
	return

/// Made to react (P6, or a decoy no longer blending in): they back away, then go back to their evening
/mob/living/basic/bounty_criminal/decoy/ai_react(mob/living/threat, bark)
	ai_flee_from(threat)

/**
 * Fleeing without sprinting or hiding (a decoy that got out of the way, on whichever tree it runs):
 * away from the threat while it can see them, then still, then calm again once they have been out
 * of sight for half the meek's time. First in line for a fleeing mob on every criminal tree that
 * has no flight of its own (M3).
 */
/datum/ai_planning_subtree/bounty_flee_and_calm

/datum/ai_planning_subtree/bounty_flee_and_calm/SelectBehaviors(datum/ai_controller/controller, seconds_per_tick)
	var/mob/living/basic/bounty_criminal/criminal = controller.pawn
	if(!istype(criminal) || criminal.ai_mode != BOUNTY_AI_FLEEING)
		return
	var/seen = criminal.ai_sees_threat(BOUNTY_FLEE_DISTANCE)
	if(!criminal.ai_threat() || world.time - criminal.ai_threat_seen_at > BOUNTY_MEEK_CALM_AFTER / 2)
		criminal.ai_calm_down()
		return
	if(!seen)
		controller.queue_behavior(/datum/ai_behavior/bounty_watch)
		return SUBTREE_RETURN_FINISH_PLANNING
	controller.set_blackboard_key(BB_BASIC_MOB_FLEE_TARGET, bounty_ai_target_for(criminal.ai_threat()))
	controller.queue_behavior(/datum/ai_behavior/run_away_from_target/bounty, BB_BASIC_MOB_FLEE_TARGET, BB_BASIC_MOB_FLEE_TARGET_HIDING_LOCATION)
	// Nowhere to run: they stand their ground, facing them, and plan on
	if(!controller.current_behaviors[GET_AI_BEHAVIOR(/datum/ai_behavior/run_away_from_target/bounty)])
		controller.queue_behavior(/datum/ai_behavior/bounty_watch)
	return SUBTREE_RETURN_FINISH_PLANNING
