/**
 * # Bounty hunting: the criminal's body
 *
 * Owner: P2 body. Owns this file, bounty_restraints.dm, voidcrew/_DEFINES/bounty_criminals.dm, the
 * bounty exemption line in voidcrew/_HELPERS/hostile_creatures.dm and the tests in
 * voidcrew/modules/unit_tests/voidcrew_bounty_criminal.dm. Do not edit this file outside P2.
 *
 * What it owns: the criminal mob's body (health, stamina, status flags and the built-in values of
 * /mob/living/basic/bounty_criminal, /meek and /normal), the downed state and its mercy rule and
 * recovery, capture_state(), refusing teleports and polymorph, the planet-sweep protection,
 * spawn_bounty_criminal(), the leash and who it may attack (spec sections 4 and 12).
 *
 * The body, in short:
 * - Health: meek BOUNTY_MEEK_HEALTH; normal by tier times its style; mini-bosses per kit (P4).
 * - Stamina: max_stamina is always 100 (tg's basic mobs leave stamina crit by comparing raw points
 *   with a percentage), so a pool of another size is the stamina damage coefficient, 100 / pool.
 * - Downed at BOUNTY_DOWNED_BELOW percent: floored, harmless and draggable. A hit on one still on its
 *   feet stops just under the line (the mercy rule), so killing it is always a choice; a hit on one
 *   that is down can kill. It gets up after its recovery time, groaning for the last
 *   BOUNTY_BODY_STIRRING_TELL, at BOUNTY_RECOVER_TO percent. Cuffed, it stays down; healing does not
 *   stand it up; a stamina hit starts the clock again (C1). A mini-boss that gets up rallies for
 *   BOUNTY_BODY_RALLY_TIME: stamina does nothing to it.
 * - On its site, damage with nobody's mind behind it (turrets, traps, fire, fauna) stops at
 *   BOUNTY_AUTOMATED_FLOOR percent. /datum/component/bounty_body keeps the ledger (AR-D3): a hit is a
 *   player's when someone with a mind made it, fired it (a mech's or vehicle's shot counts its pilot),
 *   last touched the explosive, or stands near an explosion.
 * - Fire and heat burn it like a suited person (L3), within the mercy line and the floor.
 * - worst_state only ever gets worse (spec 12.1); P5 pays on it, and carries it to a respawned copy
 *   with body_restore_worst_state().
 * - On the floor and draggable (down, stunned, cuffed or dead), it can be fireman carried like a
 *   person. It squirms off the carrier's shoulders once it can't be dragged any more.
 * - Dead, the body stays and can't be revived (AR-A5). A dead body destroyed with its posting open
 *   (gibbed, dusted, lost in a chasm) asks P5's bounty_drop_proof() for proof of death, unless it was
 *   removed on purpose (P5's TRAIT_BOUNTY_REMOVED, or body_mark_removed()). A live one deleted never
 *   does. P5 decides where the proof goes.
 * - Its site: the site's rectangle (or the pirate ship it is wanted aboard), less every ship, hangar,
 *   player outpost and planet dock strip inside it (H1). Leashed to it (AR-D2): its own feet never
 *   take it off, nor onto a trader outpost's lift alcove, lava, a chasm or space. Once off (woken
 *   aboard a ship, dragged away), it may walk about where it is and back, but never on into another
 *   ship or hangar or into a player outpost (M3). Anyone can still drag it anywhere, and a scripted
 *   walk (TRAIT_BOUNTY_SCRIPTED_MOVE, or godmode) goes where it is sent. Off its site, and anywhere at
 *   a trader outpost, it fights only those on its grudge list and never structures (AR-D1, AR-C8).
 * - No teleports (the pad deletes it), and a container it is in can't be teleported either; no
 *   fultons, no polymorph, no type change, no sentience (M2). Turrets at trader outposts leave it
 *   alone, and no turret shoots one that is down, stunned or restrained (bounty_turret_ignores()).
 * Restraints are in bounty_restraints.dm.
 *
 * The shared vars are declared in bounty_types.dm and nowhere else; a var only P2 uses goes here
 * with a `body_` prefix.
 */

// ===== BUILT-IN VALUES =====

/mob/living/basic/bounty_criminal
	name = "criminal"
	desc = "Someone with a price on their head."
	icon = 'icons/mob/simple/simple_human.dmi'
	unique_name = FALSE
	maxHealth = BOUNTY_NORMAL_HEALTH_WANTED
	health = BOUNTY_NORMAL_HEALTH_WANTED
	speed = BOUNTY_BODY_NORMAL_SPEED_MELEE
	mob_biotypes = MOB_ORGANIC | MOB_HUMANOID
	mob_size = MOB_SIZE_HUMAN
	sentience_type = BOUNTY_CRIMINAL_NO_SENTIENCE
	density = TRUE
	// Too heavy to shove about while free and on its feet; see body_update_drag().
	move_resist = MOVE_FORCE_VERY_STRONG
	// No DEL_ON_DEATH: the body is the proof (AR-A5).
	basic_mob_flags = NONE
	// Batons knock them down, as they do people.
	status_flags = CANPUSH | CANSTUN | CANKNOCKDOWN
	max_stamina = BOUNTY_CRIMINAL_MAX_STAMINA
	stamina_crit_threshold = BOUNTY_CRIMINAL_STAMCRIT_AT
	stamina_regen_time = BOUNTY_NORMAL_STAMCRIT_TIME
	// Downed, stunned or dead, they lie on the floor like a person.
	mobility_flags = MOBILITY_FLAGS_REST_CAPABLE_DEFAULT
	rotate_on_lying = TRUE
	blood_volume = BLOOD_VOLUME_NORMAL
	// Dressed for out there: vacuum and cold don't hurt them (D-A9). Weapons, lava, chasms and fire do;
	// fire and heat through Life(), not tg's element, so the mercy line holds.
	unsuitable_atmos_damage = 0
	unsuitable_cold_damage = 0
	unsuitable_heat_damage = 0
	// tg's human deathgasp
	death_message = "seizes up and falls limp, their eyes dead and lifeless..."
	response_help_continuous = "taps"
	response_help_simple = "tap"
	/// Runs while it is down: the stirring tell, then getting up
	var/body_recovery_timer
	/// Down, and groaning as it tries to get up
	var/body_stirring = FALSE
	/// Its recovery came due while it was cuffed: it gets up once the cuffs are off
	var/body_recovery_due = FALSE
	/// world.time until which a mini-boss that just got up shrugs off stamina, and the timer that ends it
	var/body_rally_until = 0
	var/body_rally_timer
	/// world.time a projectile last got through to it, for the meek's dodge
	var/body_last_shot_at = -1
	/// Removed on purpose (beamed out by the pad, cleaned up by its posting, its site unloading): being deleted is not a death, so it leaves no proof
	var/body_removed = FALSE
	/// Its proof of death is down already
	var/body_proof_dropped = FALSE
	/// Weakref to the overmap object of its site: the planet, ruin, pirate ship or trader outpost
	var/datum/weakref/body_site_ref
	/// The top row of its planet's dock strip, or null
	var/body_dock_top_y
	/// Someone is putting restraints on it or taking them off (bounty_restraints.dm)
	var/body_cuff_work = FALSE
	/// The timers for its restraints slipping: the visible struggle, then the slip (bounty_restraints.dm)
	var/body_slip_warn_timer
	var/body_slip_timer
	/// Weakref to the container holding it (a locker, a crate, a body bag), kept from being teleported while it is inside
	var/datum/weakref/body_holder_ref
	/// The last balloon floated over it for hunters (body_alert_hunters()): "worn out"
	var/body_last_alert

/mob/living/basic/bounty_criminal/meek
	maxHealth = BOUNTY_MEEK_HEALTH
	health = BOUNTY_MEEK_HEALTH
	speed = BOUNTY_BODY_MEEK_SPEED
	max_stamina_slowdown = BOUNTY_MEEK_STAMINA_SLOWDOWN
	stamina_regen_time = BOUNTY_MEEK_STAMCRIT_TIME

/mob/living/basic/bounty_criminal/Initialize(mapload)
	. = ..()
	// Its own copy: the stamina pool here, and a mini-boss's armour (P4), change it per mob.
	damage_coeff = damage_coeff.Copy()
	body_update_stamina_coeff()
	// TRAIT_CAN_MOUNT_HUMANS: someone can carry it over their shoulders (body_can_be_carried())
	add_traits(list(TRAIT_NO_TELEPORT, TRAIT_NOMOBSWAP, TRAIT_CAN_MOUNT_HUMANS), BOUNTY_BODY_TRAIT)
	AddComponent(/datum/component/bounty_body)
	AddElement(/datum/element/footstep, footstep_type = FOOTSTEP_MOB_SHOE)

/mob/living/basic/bounty_criminal/Destroy()
	if(body_leaves_proof())
		body_drop_proof()
	deltimer(body_recovery_timer)
	body_recovery_timer = null
	body_remove_cuffs()
	body_set_holder(null)
	grudge?.Cut()
	body_site_ref = null
	return ..()

// Fire and heat burn it like a suited person (L3). Not forced, so the mercy line and the automated floor hold. Mini-bosses keep P4's own fire rules.
/mob/living/basic/bounty_criminal/Life(seconds_per_tick = SSMOBS_DT, times_fired)
	. = ..()
	if(stat == DEAD || istype(src, /mob/living/basic/bounty_criminal/boss))
		return
	if(on_fire || bodytemperature > BOUNTY_CRIMINAL_MAX_TEMP)
		adjustFireLoss(BOUNTY_CRIMINAL_BURN_DAMAGE * seconds_per_tick)

// ===== SPAWNING =====

/**
 * Spawns the criminal for `record` at `where`, wanted on `posting` (or on nothing, for an admin
 * spawn): the subtype for its archetype and kit, with the body for its tier and style, leashed to the
 * posting's site, protected from the planet sweep and dressed in its look. Returns the mob. Decoys
 * are made by P6 directly.
 */
/proc/spawn_bounty_criminal(datum/bounty_record/record, turf/where, datum/criminal_bounty/posting)
	where = get_turf(where)
	if(!where)
		return null
	var/criminal_type = bounty_criminal_type(record, posting)
	var/mob/living/basic/bounty_criminal/criminal = new criminal_type(where)
	criminal.body_setup(record, posting)
	return criminal

/// The criminal type for `record` wanted on `posting`: meek, normal, or the mini-boss of its kit. A mini-boss never goes to a trader outpost; a normal criminal stands in (D-A8).
/proc/bounty_criminal_type(datum/bounty_record/record, datum/criminal_bounty/posting)
	var/archetype = record?.archetype
	if(archetype == BOUNTY_ARCHETYPE_BOSS && posting?.placement_kind == BOUNTY_PLACEMENT_TRADER_OUTPOST)
		archetype = BOUNTY_ARCHETYPE_NORMAL
	switch(archetype)
		if(BOUNTY_ARCHETYPE_MEEK)
			return /mob/living/basic/bounty_criminal/meek
		if(BOUNTY_ARCHETYPE_BOSS)
			switch(record.kit)
				if(BOUNTY_KIT_JUGGERNAUT)
					return /mob/living/basic/bounty_criminal/boss/juggernaut
				if(BOUNTY_KIT_PYROMANIAC)
					return /mob/living/basic/bounty_criminal/boss/pyromaniac
				if(BOUNTY_KIT_DEMOLITIONIST)
					return /mob/living/basic/bounty_criminal/boss/demolitionist
				if(BOUNTY_KIT_GHOST)
					return /mob/living/basic/bounty_criminal/boss/ghost
				if(BOUNTY_KIT_HEAVY)
					return /mob/living/basic/bounty_criminal/boss/heavy
			return pick(
				/mob/living/basic/bounty_criminal/boss/juggernaut,
				/mob/living/basic/bounty_criminal/boss/pyromaniac,
				/mob/living/basic/bounty_criminal/boss/demolitionist,
				/mob/living/basic/bounty_criminal/boss/ghost,
				/mob/living/basic/bounty_criminal/boss/heavy,
			)
	return /mob/living/basic/bounty_criminal/normal

/**
 * Makes it the person in `new_record`, wanted on `new_posting` (either may be null): name, the body
 * for its tier and style, the leash to the posting's site, the planet-sweep protection, and its look,
 * put on in the background. spawn_bounty_criminal() calls it once, right after making the mob.
 */
/mob/living/basic/bounty_criminal/proc/body_setup(datum/bounty_record/new_record, datum/criminal_bounty/new_posting)
	record = new_record
	posting_ref = new_posting ? WEAKREF(new_posting) : null
	if(record?.name)
		name = record.name
		real_name = record.name
	if(record?.gender == MALE || record?.gender == FEMALE)
		gender = record.gender
	var/tier_health = body_tier_health()
	if(tier_health)
		maxHealth = tier_health
		updatehealth()
	if(istype(src, /mob/living/basic/bounty_criminal/normal))
		var/ranged = record?.style == BOUNTY_STYLE_PISTOL || record?.style == BOUNTY_STYLE_BOTTLE
		set_varspeed(ranged ? BOUNTY_BODY_NORMAL_SPEED_RANGED : BOUNTY_BODY_NORMAL_SPEED_MELEE)
	body_update_stamina_coeff()
	body_set_site(new_posting?.site_ref?.resolve())
	if(new_posting)
		// The planet's fauna sweep leaves it be while it is wanted (missions/objectives/combat.dm). P5 takes it off when the posting ends.
		ADD_TRAIT(src, TRAIT_MISSION_FIELD_MOB, BOUNTY_TRAIT)
	INVOKE_ASYNC(src, PROC_REF(body_dress))

/// A normal criminal's health: its tier's, times its style's. Null for anyone else, who keeps their built-in health.
/mob/living/basic/bounty_criminal/proc/body_tier_health()
	if(!istype(src, /mob/living/basic/bounty_criminal/normal))
		return null
	var/base = BOUNTY_NORMAL_HEALTH_WANTED
	switch(record?.tier)
		if(BOUNTY_TIER_PETTY)
			base = BOUNTY_NORMAL_HEALTH_PETTY
		if(BOUNTY_TIER_MOST_WANTED)
			base = BOUNTY_NORMAL_HEALTH_MOST
	return round(base * bounty_style_health_mult(record?.style), 1)

/// How much tougher or frailer than its tier a fighting style makes a normal criminal
/proc/bounty_style_health_mult(style)
	switch(style)
		if(BOUNTY_STYLE_BRAWLER)
			return BOUNTY_STYLE_HEALTH_BRAWLER
		if(BOUNTY_STYLE_KNIFE)
			return BOUNTY_STYLE_HEALTH_KNIFE
		if(BOUNTY_STYLE_PISTOL)
			return BOUNTY_STYLE_HEALTH_PISTOL
		if(BOUNTY_STYLE_SHOTGUN)
			return BOUNTY_STYLE_HEALTH_SHOTGUN
		if(BOUNTY_STYLE_CLUB)
			return BOUNTY_STYLE_HEALTH_CLUB
		if(BOUNTY_STYLE_BOTTLE)
			return BOUNTY_STYLE_HEALTH_BOTTLE
	return 1

/// How much stamina damage stamina-crits it: a meek criminal's pool, or anyone else's health
/mob/living/basic/bounty_criminal/proc/body_stamina_pool()
	if(istype(src, /mob/living/basic/bounty_criminal/meek))
		return BOUNTY_MEEK_STAMINA
	return maxHealth

/// Sets its stamina damage coefficient from its pool (max_stamina / pool), times its style's. A mini-boss's is P4's.
/mob/living/basic/bounty_criminal/proc/body_update_stamina_coeff()
	if(istype(src, /mob/living/basic/bounty_criminal/boss))
		return
	var/pool = body_stamina_pool()
	if(pool <= 0)
		return
	var/style_mult = record?.style == BOUNTY_STYLE_BRAWLER ? BOUNTY_STYLE_STAMINA_BRAWLER : 1
	damage_coeff[STAMINA] = style_mult * max_stamina / pool

/**
 * Gives it the same body as `other`: health, pace and stamina. For a trader-outpost decoy (P6), which
 * must be as tough and as quick as the fugitive it stands in for (AR-C6).
 */
/mob/living/basic/bounty_criminal/proc/body_match(mob/living/basic/bounty_criminal/other)
	if(QDELETED(other) || other == src)
		return
	maxHealth = other.maxHealth
	setBruteLoss(other.getBruteLoss())
	updatehealth()
	set_varspeed(other.speed)
	damage_coeff[STAMINA] = other.damage_coeff[STAMINA]
	stamina_regen_time = other.stamina_regen_time
	if(max_stamina_slowdown != other.max_stamina_slowdown)
		// The same arguments make_stamina_slowable() added it with, or the element is not found.
		RemoveElement(/datum/element/basic_stamina_slowdown, minium_stamina_threshold = max_stamina / 3, maximum_stamina = max_stamina, maximum_slowdown = max_stamina_slowdown)
		max_stamina_slowdown = other.max_stamina_slowdown
		make_stamina_slowable()

// ===== THE SITE =====

/**
 * Leashes it to `site`, the overmap object of its planet, ruin, pirate ship or trader outpost: the
 * site's rectangle, or for a pirate ship the hull itself. A site with no rectangle to read gets a box
 * around where it stands. With no site at all (an admin spawn) it has no leash.
 */
/mob/living/basic/bounty_criminal/proc/body_set_site(atom/site)
	body_site_ref = site ? WEAKREF(site) : null
	site_bounds = bounty_site_bounds(site)
	body_dock_top_y = bounty_site_dock_top(site)
	if(!site || site_bounds || istype(site, /obj/structure/overmap/ship))
		return
	var/turf/here = get_turf(src)
	if(here)
		site_bounds = list(here.x - BOUNTY_BODY_FALLBACK_LEASH, here.y - BOUNTY_BODY_FALLBACK_LEASH, here.x + BOUNTY_BODY_FALLBACK_LEASH, here.y + BOUNTY_BODY_FALLBACK_LEASH, here.z)

/// The rectangle of an overmap site's interior, list(min_x, min_y, max_x, max_y, z), or null: a trader outpost's reservation, anything else's footprint. A ship has none (it moves).
/proc/bounty_site_bounds(atom/site)
	if(istype(site, /obj/structure/overmap/trader_outpost))
		var/obj/structure/overmap/trader_outpost/outpost = site
		var/datum/turf_reservation/reservation = outpost.reservation
		if(!length(reservation?.bottom_left_turfs) || !length(reservation.top_right_turfs))
			return null
		var/turf/low = reservation.bottom_left_turfs[1]
		var/turf/high = reservation.top_right_turfs[1]
		if(!low || !high)
			return null
		return list(low.x, low.y, high.x, high.y, low.z)
	if(!istype(site, /obj/structure/overmap) || istype(site, /obj/structure/overmap/ship))
		return null
	var/obj/structure/overmap/overmap_site = site
	var/datum/map_footprint/footprint = overmap_site.get_interior_footprint()
	if(!footprint || isnull(footprint.low_x) || !footprint.z_value)
		return null
	return list(footprint.low_x, footprint.low_y, footprint.high_x, footprint.high_y, footprint.z_value)

/// The top row of a planet's dock strip, where ships land, or null for anything else
/proc/bounty_site_dock_top(atom/site)
	var/obj/structure/overmap/planet/planet = site
	if(!istype(planet))
		return null
	var/datum/space_level/level = length(planet.mapzone?.z_levels) ? planet.mapzone.z_levels[1] : null
	return planet.get_dock_strip_top_y(level)

/// The overmap object of its site: the one it was spawned for, else its posting's
/mob/living/basic/bounty_criminal/proc/body_site()
	var/obj/structure/overmap/site = body_site_ref?.resolve() || posting()?.site_ref?.resolve()
	return (istype(site) && !QDELETED(site)) ? site : null

/// The pirate ship that is its site, if it is wanted aboard one
/mob/living/basic/bounty_criminal/proc/body_site_ship()
	var/obj/structure/overmap/ship/site_ship = body_site()
	return istype(site_ship) ? site_ship : null

/// Whether it has a site to be leashed to
/mob/living/basic/bounty_criminal/proc/body_has_site()
	return !!site_bounds || !!body_site_ship()

/**
 * Whether `place` is on its site: inside the site's rectangle (or aboard the pirate ship it is wanted
 * on), and not part of a ship, a hangar, a player outpost or a planet's dock strip that happens to lie
 * inside that rectangle (H1). With no site, anywhere but those is.
 */
/mob/living/basic/bounty_criminal/proc/body_on_site(turf/place)
	place = get_turf(place)
	if(!place || body_forbidden_turf(place))
		return FALSE
	if(site_bounds)
		return place.z == site_bounds[5] && place.x >= site_bounds[1] && place.x <= site_bounds[3] && place.y >= site_bounds[2] && place.y <= site_bounds[4]
	var/obj/structure/overmap/ship/site_ship = body_site_ship()
	if(site_ship)
		return site_ship.is_aboard(place)
	return TRUE

/// Whether `place` is never its ground: a ship (other than the pirate ship it is wanted aboard), a hangar, a player outpost, or its planet's dock strip
/mob/living/basic/bounty_criminal/proc/body_forbidden_turf(turf/place)
	return !!body_hold(place) || body_on_dock_strip(place)

/**
 * The ship, hangar or player outpost `place` is part of, or null: the pirate ship it is wanted aboard
 * is its site, not a hold. A ship is known by its docking port, so every room aboard is one hold.
 */
/mob/living/basic/bounty_criminal/proc/body_hold(turf/place)
	var/area/place_area = get_area(place)
	if(istype(place_area, /area/shuttle))
		var/obj/structure/overmap/ship/site_ship = body_site_ship()
		if(site_ship?.is_aboard(place))
			return null
		var/area/shuttle/voidcrew/ship_area = place_area
		return (istype(ship_area) && ship_area.shuttle_port) || place_area
	if(istype(place_area, /area/voidcrew/outpost_hangar) || istype(place_area, /area/voidcrew/player_outpost))
		return place_area
	return null

/// Whether `place` is on its planet's dock strip, where ships land (L1)
/mob/living/basic/bounty_criminal/proc/body_on_dock_strip(turf/place)
	if(isnull(body_dock_top_y) || !place)
		return FALSE
	return (!site_bounds || place.z == site_bounds[5]) && place.y <= body_dock_top_y

/// Whether it is at a trader outpost, wanted there or standing in one: there it fights only its grudge list (AR-C8)
/mob/living/basic/bounty_criminal/proc/body_at_trader_outpost()
	return posting()?.placement_kind == BOUNTY_PLACEMENT_TRADER_OUTPOST || istype(get_area(src), /area/voidcrew/trader_outpost)

/**
 * Whether it may go onto `destination` by itself (AR-D2, AR-E1, L1): on its site (so never a ship, a
 * hangar, a player outpost or a dock strip), never a lift alcove that would carry it off, and never
 * lava, a chasm or open space. P3 checks hiding spots and flight paths with it; its own steps are held
 * to it too (Move()).
 */
/mob/living/basic/bounty_criminal/proc/leash_ok(turf/destination)
	destination = get_turf(destination)
	if(!destination || !body_on_site(destination))
		return FALSE
	var/obj/structure/overmap/site = body_site()
	if(site && (destination in site.lobby_alcove_turfs))
		return FALSE
	return destination.can_cross_safely(src)

// Its own steps stay on the leash (M3). Dragged, carried along, thrown or walked by a script, it goes where it is taken.
/mob/living/basic/bounty_criminal/Move(atom/newloc, direct, glide_size_override)
	if(!body_move_allowed(newloc))
		return FALSE
	return ..()

/// Whether a script is walking it on purpose: TRAIT_BOUNTY_SCRIPTED_MOVE, or godmode (P6's walk out to the lift)
/mob/living/basic/bounty_criminal/proc/body_scripted()
	return HAS_TRAIT(src, TRAIT_BOUNTY_SCRIPTED_MOVE) || HAS_TRAIT(src, TRAIT_GODMODE)

/**
 * Whether a step of its own onto `newloc` is allowed. Onto its leash, always. Off it from on it,
 * never. Already off it (woken aboard a ship, dragged off its site, carried somewhere), it may walk
 * about and back toward its site, but never into a hazard and never on into a ship, hangar or player
 * outpost other than the one it is already in (M3).
 */
/mob/living/basic/bounty_criminal/proc/body_move_allowed(atom/newloc)
	if(!isturf(newloc) || !isturf(loc) || pulledby || buckled || throwing || stat == DEAD || body_scripted())
		return TRUE
	var/turf/destination = newloc
	if(leash_ok(destination))
		return TRUE
	if(leash_ok(loc) || !destination.can_cross_safely(src))
		return FALSE
	var/destination_hold = body_hold(destination)
	return !destination_hold || destination_hold == body_hold(loc)

/**
 * Whether environment damage aimed at `target_turf` is allowed (AR-D2), for P4's abilities that
 * break walls, windows and floors: only on its own site, never at a trader outpost, and never within
 * BOUNTY_ENV_SAFE_RANGE tiles of a ship (other than the pirate ship it is aboard), a hangar, a player
 * outpost or a planet's dock strip.
 */
/mob/living/basic/bounty_criminal/proc/environment_damage_allowed(turf/target_turf)
	target_turf = get_turf(target_turf)
	if(!target_turf || !body_on_site(target_turf) || body_at_trader_outpost())
		return FALSE
	if(!isnull(body_dock_top_y) && (!site_bounds || target_turf.z == site_bounds[5]) && target_turf.y <= body_dock_top_y + BOUNTY_ENV_SAFE_RANGE)
		return FALSE
	var/list/checked_areas = list()
	for(var/turf/nearby as anything in RANGE_TURFS(BOUNTY_ENV_SAFE_RANGE, target_turf))
		var/area/nearby_area = nearby.loc
		if(checked_areas[nearby_area])
			continue
		checked_areas[nearby_area] = TRUE
		if(body_hold(nearby))
			return FALSE
	return TRUE

// ===== WHO IT FIGHTS =====

/**
 * Whether it may attack `target` (AR-D1, AR-C8, C4). Never while down, restrained or surrendered,
 * never someone who is down, and never its own side. Off its site, and anywhere at a trader outpost,
 * only those on its grudge list, and no structures. On its site it may break structures that are on
 * its site and not part of a ship, a hangar or an outpost. Its melee and ranged attacks are held to it.
 */
/mob/living/basic/bounty_criminal/proc/may_attack(atom/target)
	if(QDELETED(target) || target == src)
		return FALSE
	if(stat != CONSCIOUS || downed || is_restrained() || HAS_TRAIT(src, TRAIT_BOUNTY_SURRENDERED))
		return FALSE
	return may_attack_scope(target)

/**
 * P3 REVIEW ROUND (H3): may_attack() split in two. This half is only who and what is fair game on
 * its side, whatever state it is in itself: never someone who is down, never its own side, only its
 * grudge list off its site and at a trader outpost, structures only on its own ground. Its
 * companions go by this alone, so they fight on when it is down, cuffed, dead or has given up.
 */
/mob/living/basic/bounty_criminal/proc/may_attack_scope(atom/target)
	if(QDELETED(target) || target == src)
		return FALSE
	// A ship, hangar, outpost or dock strip inside the site's rectangle is not its site (H1)
	var/limited = !body_on_site(get_turf(src)) || body_at_trader_outpost()
	var/list/people
	if(isliving(target))
		people = list(target)
	else if(istype(target, /obj/vehicle/sealed))
		var/obj/vehicle/sealed/vehicle = target
		people = list()
		for(var/mob/living/pilot in vehicle.occupants)
			people += pilot
	else
		// A structure, a machine, a wall: only on its own ground, and never part of a ship, a hangar or an outpost.
		if(limited)
			return FALSE
		var/turf/target_turf = get_turf(target)
		return body_on_site(target_turf) && !body_forbidden_turf(target_turf)
	for(var/mob/living/person as anything in people)
		if(person.stat != CONSCIOUS || istype(person, /mob/living/basic/bounty_criminal) || istype(person, /mob/living/basic/bounty_companion))
			continue
		if(!limited || body_has_grudge(person))
			return TRUE
	return FALSE

/// Remembers `who` as someone it may fight anywhere: they attacked it, confronted it or cuffed it. P3 calls it when someone confronts it.
/mob/living/basic/bounty_criminal/proc/body_add_grudge(mob/living/who)
	if(!isliving(who) || who == src || istype(who, /mob/living/basic/bounty_criminal) || istype(who, /mob/living/basic/bounty_companion))
		return
	var/datum/weakref/who_ref = WEAKREF(who)
	if(who_ref in grudge)
		return
	grudge += who_ref
	if(length(grudge) > BOUNTY_GRUDGE_MAX)
		grudge.Cut(1, 2)

/// Whether `who` is on its grudge list
/mob/living/basic/bounty_criminal/proc/body_has_grudge(mob/living/who)
	return !isnull(who?.weak_reference) && (who.weak_reference in grudge)

// Its own fists follow may_attack().
/mob/living/basic/bounty_criminal/early_melee_attack(atom/target, list/modifiers, ignore_cooldown = FALSE)
	if(!may_attack(target))
		return FALSE
	return ..()

// ===== CAPTURE STATE =====

/**
 * What the pad pays on (BOUNTY_STATE_*), checked in order (AR-A3): dead; downed (even if cuffed or
 * healed); restrained with its own restraints; stunned (stamina crit, knocked down, stunned,
 * paralysed, unconscious, or surrendered); free.
 */
/mob/living/basic/bounty_criminal/proc/capture_state()
	if(stat == DEAD)
		return BOUNTY_STATE_DEAD
	if(downed)
		return BOUNTY_STATE_DOWNED
	if(is_restrained())
		return BOUNTY_STATE_RESTRAINED
	if(body_is_stunned())
		return BOUNTY_STATE_STUNNED
	return BOUNTY_STATE_FREE

/// Whether it is down and alive: floored and harmless until it recovers
/mob/living/basic/bounty_criminal/proc/is_downed()
	return downed && stat != DEAD

/// Whether its own restraints are on it
/mob/living/basic/bounty_criminal/proc/is_restrained()
	return !QDELETED(restraints) && restraints.loc == src

/// Whether it is stunned: stamina crit, knocked down, stunned, paralysed, out cold, or surrendered (TRAIT_BOUNTY_SURRENDERED)
/mob/living/basic/bounty_criminal/proc/body_is_stunned()
	if(HAS_TRAIT(src, TRAIT_BOUNTY_SURRENDERED) || has_status_effect(/datum/status_effect/incapacitating/stamcrit))
		return TRUE
	return IsKnockdown() || IsStun() || IsParalyzed() || IsUnconscious() || IsSleeping()

/// How bad a capture state is: lower is worse. Restrained and stunned pay the same.
/proc/bounty_state_rank(state)
	switch(state)
		if(BOUNTY_STATE_DEAD)
			return 1
		if(BOUNTY_STATE_DOWNED)
			return 2
		if(BOUNTY_STATE_RESTRAINED, BOUNTY_STATE_STUNNED)
			return 3
	return 4

/// Records its capture state in worst_state if it is as bad or worse: once downed or dead, it never gets better (spec 12.1)
/mob/living/basic/bounty_criminal/proc/body_note_state()
	var/state = capture_state()
	if(bounty_state_rank(state) <= bounty_state_rank(worst_state))
		worst_state = state

/**
 * Carries a worst state over from an earlier copy of this criminal (M4): P5 respawns the same record
 * when its site loads again, and pay must not forget that it was downed or killed before. Only ever
 * makes worst_state worse. Returns the worst state now.
 */
/mob/living/basic/bounty_criminal/proc/body_restore_worst_state(state)
	if(state && bounty_state_rank(state) < bounty_state_rank(worst_state))
		worst_state = state
	return worst_state

/// Something about its state changed: worst_state, and whether it can be dragged or carried
/mob/living/basic/bounty_criminal/proc/body_state_changed()
	body_note_state()
	body_update_drag()
	body_update_carry()

/mob/living/basic/bounty_criminal/set_stat(new_stat)
	. = ..()
	body_state_changed()

/mob/living/basic/bounty_criminal/on_floored_trait_gain(datum/source)
	. = ..()
	body_state_changed()

/mob/living/basic/bounty_criminal/on_floored_trait_loss(datum/source)
	. = ..()
	body_state_changed()

/mob/living/basic/bounty_criminal/on_incapacitated_trait_gain(datum/source)
	. = ..()
	body_state_changed()

/mob/living/basic/bounty_criminal/on_incapacitated_trait_loss(datum/source)
	. = ..()
	body_state_changed()

// ===== DRAGGING =====

/**
 * Whether it can be dragged: dead, downed, restrained or stunned. Blending in at a trader outpost it
 * shakes off any hand until it is down or cuffed (AR-C7), the same for the fugitive and its decoys.
 * Free and on its feet it pulls away.
 */
/mob/living/basic/bounty_criminal/proc/body_can_be_dragged()
	if(stat == DEAD || downed || is_restrained())
		return TRUE
	if(blended)
		return FALSE
	return body_is_stunned()

/// Too heavy to shove while free; ordinary once it can be dragged. Anyone dragging it loses their grip when it can't be.
/mob/living/basic/bounty_criminal/proc/body_update_drag()
	var/draggable = body_can_be_dragged()
	move_resist = draggable ? MOVE_RESIST_DEFAULT : MOVE_FORCE_VERY_STRONG
	if(draggable || !pulledby)
		return
	visible_message(span_warning("[src] pulls free of [pulledby]."))
	pulledby.stop_pulling()

/mob/living/basic/bounty_criminal/can_be_pulled(user, force)
	if(!body_can_be_dragged())
		// P3 REVIEW ROUND (L1): the pull attempt is still announced before it is refused, so P3 hears
		// it (pulling at a hider finds it) and P6's blend hooks see it. A hider shows no balloon: it
		// is being found instead.
		SEND_SIGNAL(src, COMSIG_ATOM_CAN_BE_PULLED, user)
		if(ismob(user) && !hidden)
			balloon_alert(user, "[p_they()] pull[p_s()] away!")
		return FALSE
	body_update_drag()
	return ..()

// ===== CARRYING =====

/// Whether someone can lift it over their shoulders (a fireman carry): on the floor, and in a state to be dragged
/mob/living/basic/bounty_criminal/proc/body_can_be_carried()
	return body_position == LYING_DOWN && body_can_be_dragged()

/// Carried, and no longer in a state to be dragged (it came round, or got up): it gets off whoever is carrying it
/mob/living/basic/bounty_criminal/proc/body_update_carry()
	if(!ishuman(buckled) || body_can_be_dragged())
		return
	var/mob/living/carrier = buckled
	carrier.unbuckle_mob(src, force = TRUE)
	visible_message(span_warning("[src] squirms off [carrier]'s shoulders."))

/**
 * Turns `body` flat when it lies down out of a chair or off someone's shoulders (set_lying_down()).
 * tg turns only carbons there (/mob/living/carbon/on_lying_down()); any other mob gets its angle from
 * on_floored_start(), which is skipped while a chair holds it up. Without this, a criminal or a goon
 * unbuckled while down or dead lies down but still looks like it is standing.
 */
/proc/bounty_body_lie_flat(mob/living/body, new_lying_angle)
	if(!body.rotate_on_lying || body.body_position != LYING_DOWN || body.lying_angle)
		return
	if(body.buckled && body.buckled.buckle_lying == 0)
		return
	body.set_lying_angle(new_lying_angle || pick(LYING_ANGLE_EAST, LYING_ANGLE_WEST))

/mob/living/basic/bounty_criminal/set_lying_down(new_lying_angle)
	. = ..()
	bounty_body_lie_flat(src, new_lying_angle)

// A criminal lying on the floor can be carried like a person, as long as it can be dragged
/mob/living/carbon/human/can_be_firemanned(mob/living/carbon/target)
	if(istype(target, /mob/living/basic/bounty_criminal))
		var/mob/living/basic/bounty_criminal/criminal = target
		return criminal.body_can_be_carried()
	return ..()

// ===== DOWNED, MERCY AND RECOVERY =====

/// Its health at the downed line
/mob/living/basic/bounty_criminal/proc/body_downed_line()
	return maxHealth * BOUNTY_DOWNED_BELOW / 100

// Every kind of damage a basic mob takes comes through here: the mercy rule and the automated floor hold it back.
/mob/living/basic/bounty_criminal/adjust_health(amount, updating_health = TRUE, forced = FALSE)
	if(amount > 0 && !forced && stat != DEAD)
		amount = body_allowed_damage(amount)
	return ..(amount, updating_health, forced)

/**
 * How much of `amount` damage gets through. On its feet (stamina crit counts), a hit stops at 1 under
 * the downed line: the rest is dropped. On its site, damage with no mind behind it stops at
 * BOUNTY_AUTOMATED_FLOOR percent. Down, its own side's blows miss it entirely. Anything else gets through.
 */
/mob/living/basic/bounty_criminal/proc/body_allowed_damage(amount)
	var/datum/component/bounty_body/ledger = GetComponent(/datum/component/bounty_body)
	var/player_hit = ledger?.player_hit_now()
	if(downed && !player_hit && ledger?.own_side_hit_now())
		return 0
	var/floor = downed ? 0 : body_downed_line() - 1
	if(!player_hit && body_has_site() && body_on_site(get_turf(src)))
		floor = max(floor, maxHealth * BOUNTY_AUTOMATED_FLOOR / 100)
	var/health_left = maxHealth - bruteloss
	if(health_left - amount >= floor)
		return amount
	return max(0, health_left - floor)

// An explosion names no attacker; the ledger works out whose it was before the blast lands (M1).
/mob/living/basic/bounty_criminal/ex_act(severity, target, origin)
	var/datum/component/bounty_body/ledger = GetComponent(/datum/component/bounty_body)
	ledger?.note_explosion(origin)
	return ..()

/mob/living/basic/bounty_criminal/updatehealth()
	. = ..()
	body_check_downed()

/// Downs it once its health reaches the downed line
/mob/living/basic/bounty_criminal/proc/body_check_downed()
	if(downed || stat == DEAD || QDELETED(src) || health > body_downed_line())
		return
	body_go_down()

/// Down: floored, harmless, draggable, its AI paused, and its recovery clock running. The line is forced: it is the moment the fight ends (BUG-1).
/mob/living/basic/bounty_criminal/proc/body_go_down()
	downed = TRUE
	body_recovery_due = FALSE
	body_rally_until = 0
	deltimer(body_rally_timer)
	body_rally_timer = null
	add_traits(list(TRAIT_FLOORED, TRAIT_INCAPACITATED, TRAIT_IMMOBILIZED), BOUNTY_BODY_DOWNED_TRAIT)
	body_update_held()
	ai_controller?.CancelActions()
	if(pulling)
		stop_pulling()
	body_start_recovery()
	body_state_changed()
	visible_message(span_danger("[src] collapses."))
	SEND_SIGNAL(src, COMSIG_BOUNTY_CRIMINAL_DOWNED)
	INVOKE_ASYNC(src, TYPE_PROC_REF(/mob/living, bounty_say), "downed", null, TRUE)

/**
 * Floats `text` over it for every hunter who can see it (bounty_ai_is_hunter()), and nobody else.
 * Kept in body_last_alert. Returns how many hunters saw it.
 */
/mob/living/basic/bounty_criminal/proc/body_alert_hunters(text)
	. = 0
	body_last_alert = text
	for(var/mob/living/viewer in get_hearers_in_view(DEFAULT_MESSAGE_RANGE, src, RECURSIVE_CONTENTS_CLIENT_MOBS))
		if(viewer.is_blind() || !bounty_ai_is_hunter(viewer))
			continue
		balloon_alert(viewer, text)
		.++

/// Restrained or down, its AI plans nothing: TRAIT_BOUNTY_HELD for P3's controller, and TRAIT_AI_PAUSED
/mob/living/basic/bounty_criminal/proc/body_update_held()
	if(downed || is_restrained())
		add_traits(list(TRAIT_BOUNTY_HELD, TRAIT_AI_PAUSED), BOUNTY_BODY_HELD_TRAIT)
	else
		remove_traits(list(TRAIT_BOUNTY_HELD, TRAIT_AI_PAUSED), BOUNTY_BODY_HELD_TRAIT)

/// How long it stays down: meek, normal or mini-boss
/mob/living/basic/bounty_criminal/proc/body_recovery_time()
	if(istype(src, /mob/living/basic/bounty_criminal/boss))
		return BOUNTY_RECOVER_TIME_BOSS
	if(istype(src, /mob/living/basic/bounty_criminal/meek))
		return BOUNTY_RECOVER_TIME_MEEK
	return BOUNTY_RECOVER_TIME_NORMAL

/// (Re)starts its recovery clock from the top: on going down, and on every stamina hit while down, cuffed or not (L4)
/mob/living/basic/bounty_criminal/proc/body_start_recovery()
	deltimer(body_recovery_timer)
	body_stirring = FALSE
	body_recovery_due = FALSE
	body_recovery_timer = addtimer(CALLBACK(src, PROC_REF(body_stir)), max(0, body_recovery_time() - BOUNTY_BODY_STIRRING_TELL), TIMER_STOPPABLE | TIMER_DELETE_ME)

/// Stops its recovery clock
/mob/living/basic/bounty_criminal/proc/body_cancel_recovery()
	deltimer(body_recovery_timer)
	body_recovery_timer = null
	body_stirring = FALSE

/// The tell before it gets up: it groans and tries to rise, and is up BOUNTY_BODY_STIRRING_TELL later. Cuffed, it waits for the cuffs to come off.
/mob/living/basic/bounty_criminal/proc/body_stir()
	body_recovery_timer = null
	if(!downed || stat == DEAD || QDELETED(src))
		return
	if(is_restrained())
		body_recovery_due = TRUE
		return
	body_stirring = TRUE
	visible_message(span_warning("[src] groans and tries to get up."))
	Shake(1, 0, 0.5 SECONDS)
	body_recovery_timer = addtimer(CALLBACK(src, PROC_REF(body_stand_up)), BOUNTY_BODY_STIRRING_TELL, TIMER_STOPPABLE | TIMER_DELETE_ME)

/**
 * Up again at BOUNTY_RECOVER_TO percent of its health, or more if it was healed while down. A
 * mini-boss rallies. Cuffed, it stays down until the cuffs come off (C1). Returns TRUE if it got up.
 */
/mob/living/basic/bounty_criminal/proc/body_stand_up()
	body_recovery_timer = null
	body_stirring = FALSE
	if(!downed || stat == DEAD || QDELETED(src))
		return FALSE
	if(is_restrained())
		body_recovery_due = TRUE
		return FALSE
	var/stand_health = maxHealth * BOUNTY_RECOVER_TO / 100
	var/health_now = maxHealth - bruteloss
	if(health_now < stand_health)
		adjust_health(health_now - stand_health, forced = TRUE)
	downed = FALSE
	body_recovery_due = FALSE
	remove_traits(list(TRAIT_FLOORED, TRAIT_INCAPACITATED, TRAIT_IMMOBILIZED), BOUNTY_BODY_DOWNED_TRAIT)
	body_update_held()
	var/rally = body_rally_time()
	if(rally > 0)
		body_rally_until = world.time + rally
		deltimer(body_rally_timer)
		body_rally_timer = addtimer(CALLBACK(src, PROC_REF(body_end_rally)), rally, TIMER_STOPPABLE | TIMER_DELETE_ME)
	body_state_changed()
	visible_message(span_warning("[src] gets back up."))
	SEND_SIGNAL(src, COMSIG_BOUNTY_CRIMINAL_RECOVERED)
	INVOKE_ASYNC(src, TYPE_PROC_REF(/mob/living, bounty_say), "recover")
	return TRUE

/// How long it rallies after getting up: a mini-boss only (C1). P4 may override it per kit.
/mob/living/basic/bounty_criminal/proc/body_rally_time()
	return istype(src, /mob/living/basic/bounty_criminal/boss) ? BOUNTY_BODY_RALLY_TIME : 0

/// Whether it is rallying after getting up: stamina does nothing, and it won't surrender (P3)
/mob/living/basic/bounty_criminal/proc/body_is_rallying()
	return world.time < body_rally_until

/// The rally is over: stamina works on it again, as far as its tiredness lets it (P4's boss_update_tired())
/mob/living/basic/bounty_criminal/proc/body_end_rally()
	body_rally_timer = null
	body_rally_until = 0
	if(QDELETED(src) || stat == DEAD)
		return
	boss_update_tired(force = TRUE)

/**
 * A mini-boss re-reads how tired it is: its stamina coefficient and stun flags (P4). Nothing for
 * anyone else. P4 overrides it on /boss; the override must not repeat the `proc/` keyword.
 */
/mob/living/basic/bounty_criminal/proc/boss_update_tired(silent = FALSE, force = FALSE)
	return

// A stamina hit while it is down starts its recovery over; rallying, it shrugs stamina off.
/mob/living/basic/bounty_criminal/adjustStaminaLoss(amount, updating_stamina = TRUE, forced = FALSE, required_biotype)
	if(amount > 0 && !forced && stat != DEAD)
		if(body_is_rallying())
			return 0
		if(downed)
			body_start_recovery()
	return ..()

// ===== DEATH =====

// The body stays as proof; the cuffs come off it.
/mob/living/basic/bounty_criminal/death(gibbed)
	body_cancel_recovery()
	. = ..()
	if(QDELETED(src))
		return
	body_remove_cuffs()
	body_state_changed()
	// Fallen into a chasm: the body is in the chasm's depths for good. P5 puts the proof on safe ground
	// beside the chasm (get_turf() here is the chasm itself).
	if(istype(loc, /obj/effect/abstract/chasm_storage) && body_leaves_proof())
		body_drop_proof()

// Nothing brings it back: dead is the dead share (AR-A5).
/mob/living/basic/bounty_criminal/can_be_revived()
	return FALSE

/mob/living/basic/bounty_criminal/Moved(atom/old_loc, movement_dir, forced, list/old_locs, momentum_change = TRUE)
	. = ..()
	body_set_holder(isturf(loc) ? null : loc)
	// A body dragged into a chasm is gone for good too; P5 puts the proof beside it.
	if(stat == DEAD && istype(loc, /obj/effect/abstract/chasm_storage) && body_leaves_proof())
		body_drop_proof()

/**
 * Keeps whatever holds it (`holder`, the outermost thing it is inside, or null on a turf) from being
 * teleported while it is inside (M2): a ship's transporter can't beam up a locker, crate or body bag
 * with a criminal in it, any more than the criminal itself. Moves the block when it changes hands.
 */
/mob/living/basic/bounty_criminal/proc/body_set_holder(atom/movable/holder)
	while(ismovable(holder?.loc))
		holder = holder.loc
	var/atom/movable/old_holder = body_holder_ref?.resolve()
	if(old_holder == holder)
		return
	if(old_holder)
		REMOVE_TRAIT(old_holder, TRAIT_NO_TELEPORT, REF(src))
	body_holder_ref = null
	if(!ismovable(holder) || QDELETED(holder))
		return
	ADD_TRAIT(holder, TRAIT_NO_TELEPORT, REF(src))
	body_holder_ref = WEAKREF(holder)

/**
 * Marks it as removed on purpose, before it is deleted: its deletion is then not a death and leaves
 * no proof. P5 marks removals with TRAIT_BOUNTY_REMOVED instead (the pad, closing, relisting, a site
 * unloading); this is for anything else that takes a criminal away on purpose.
 */
/mob/living/basic/bounty_criminal/proc/body_mark_removed()
	body_removed = TRUE

/**
 * Whether destroying its body now should ask for proof of death: dead (gibs, dust and chasms all kill
 * first; a live one deleted is never a death, M5), not removed on purpose, and its posting still open.
 * P5's bounty_drop_proof() makes the final call (a site unloading, a relist) and places the proof.
 */
/mob/living/basic/bounty_criminal/proc/body_leaves_proof()
	if(stat != DEAD || body_removed || body_proof_dropped || HAS_TRAIT(src, TRAIT_BOUNTY_REMOVED))
		return FALSE
	var/datum/criminal_bounty/wanted_on = posting()
	return wanted_on?.status == BOUNTY_POSTING_OPEN

/// Leaves proof of death through P5's bounty_drop_proof(), once
/mob/living/basic/bounty_criminal/proc/body_drop_proof()
	body_proof_dropped = TRUE
	bounty_drop_proof(src)

// ===== LOOKS =====

/// Puts its look on: its record's face in the outfit for its archetype and zone. Sleeps.
/mob/living/basic/bounty_criminal/proc/body_dress()
	var/outfit = bounty_outfit()
	if(record)
		apply_bounty_look(src, record, outfit)
	else
		set_outpost_npc_look(src, outfit, gender, 1)
	if(QDELETED(src))
		return
	update_appearance(UPDATE_OVERLAYS)

/// The outfit it wears: a mini-boss its kit's (boss_kit_outfit(), P4), anyone else plain clothes for their archetype and the zone of their site
/mob/living/basic/bounty_criminal/proc/bounty_outfit()
	if(istype(src, /mob/living/basic/bounty_criminal/boss))
		return boss_kit_outfit() || boss_outfit()
	var/meek = istype(src, /mob/living/basic/bounty_criminal/meek)
	switch(body_zone())
		if(ZONE_RED)
			return meek ? /datum/outfit/bounty_criminal/drifter : /datum/outfit/bounty_criminal/tough
		if(ZONE_YELLOW)
			return meek ? /datum/outfit/bounty_criminal/spacer : /datum/outfit/bounty_criminal/hauler
	return meek ? /datum/outfit/bounty_criminal : /datum/outfit/bounty_criminal/local

/// A mini-boss's kit outfit, or null. P4 overrides it on /boss; the override must not repeat the `proc/` keyword.
/mob/living/basic/bounty_criminal/proc/boss_kit_outfit()
	return null

/// What a mini-boss wears when its kit has no outfit: plain rough clothes
/mob/living/basic/bounty_criminal/proc/boss_outfit()
	return /datum/outfit/bounty_criminal/tough

/// ZONE_GREEN, ZONE_YELLOW or ZONE_RED for where its site is (or where it stands), green if unknown
/mob/living/basic/bounty_criminal/proc/body_zone()
	var/atom/site = body_site_ref?.resolve()
	var/zone = site ? SSovermap_zones?.get_zone_type(get_turf(site)) : SSovermap_zones?.get_zone_type_anywhere(get_turf(src))
	return zone || ZONE_GREEN

/mob/living/basic/bounty_criminal/update_overlays()
	. = ..()
	if(is_restrained() && !hidden)
		// tg's own cuff overlay, as people wear it
		. += mutable_appearance('icons/mob/simple/mob.dmi', "handcuff1")

/// Plain clothes for a meek criminal in green space
/datum/outfit/bounty_criminal
	name = "Bounty criminal: civilian"
	uniform = /obj/item/clothing/under/pants/jeans
	suit = /obj/item/clothing/suit/toggle/jacket/sweater
	shoes = /obj/item/clothing/shoes/sneakers/brown

/// A meek criminal in yellow space
/datum/outfit/bounty_criminal/spacer
	name = "Bounty criminal: spacer"
	uniform = /obj/item/clothing/under/color/grey
	suit = /obj/item/clothing/suit/jacket/bomber
	shoes = /obj/item/clothing/shoes/workboots
	head = /obj/item/clothing/head/beanie

/// A meek criminal in red space
/datum/outfit/bounty_criminal/drifter
	name = "Bounty criminal: drifter"
	uniform = /obj/item/clothing/under/color/black
	suit = /obj/item/clothing/suit/jacket/leather
	shoes = /obj/item/clothing/shoes/jackboots
	head = /obj/item/clothing/head/soft/grey

/// A normal criminal in green space
/datum/outfit/bounty_criminal/local
	name = "Bounty criminal: local"
	uniform = /obj/item/clothing/under/costume/buttondown/slacks
	suit = /obj/item/clothing/suit/jacket/letterman
	shoes = /obj/item/clothing/shoes/sneakers/black

/// A normal criminal in yellow space
/datum/outfit/bounty_criminal/hauler
	name = "Bounty criminal: hauler"
	uniform = /obj/item/clothing/under/pants/jeans
	suit = /obj/item/clothing/suit/jacket/miljacket
	gloves = /obj/item/clothing/gloves/fingerless
	shoes = /obj/item/clothing/shoes/workboots

/// A normal criminal in red space, and the fallback for a mini-boss
/datum/outfit/bounty_criminal/tough
	name = "Bounty criminal: tough"
	uniform = /obj/item/clothing/under/color/black
	suit = /obj/item/clothing/suit/jacket/leather/biker
	gloves = /obj/item/clothing/gloves/fingerless
	shoes = /obj/item/clothing/shoes/jackboots

// ===== EXAMINE =====

/**
 * How hurt it looks, its distinguishing features, and whether it is restrained, down or has given up.
 * Blending in, the fugitive and its decoys show one layout: how hurt, then the features. Hidden (a
 * disguise, a locker), it adds nothing.
 */
/mob/living/basic/bounty_criminal/examine(mob/user)
	. = ..()
	if(hidden)
		return
	if(stat != DEAD)
		. += body_health_line()
	for(var/line in record?.feature_lines())
		. += span_notice(line)
	if(blended || stat == DEAD)
		return
	if(is_restrained())
		. += span_warning("[p_They()] [p_are()] restrained with [restraints].")
	if(downed)
		if(body_stirring)
			. += span_warning("[p_They()] [p_are()] trying to get up.")
		else
			. += span_notice("[p_They()] [p_are()] down.")
	else if(HAS_TRAIT(src, TRAIT_BOUNTY_SURRENDERED))
		. += span_notice("[p_They()] [p_have()] given up.")

/// One line on how hurt it looks
/mob/living/basic/bounty_criminal/proc/body_health_line()
	var/fraction = maxHealth > 0 ? health / maxHealth : 0
	if(fraction >= 0.9)
		return span_notice("[p_They()] look[p_s()] unhurt.")
	if(fraction >= 0.6)
		return span_warning("[p_They()] [p_have()] a few cuts and bruises.")
	if(fraction > BOUNTY_DOWNED_BELOW / 100)
		return span_warning("[p_They()] [p_are()] badly hurt.")
	return span_danger("[p_They()] [p_are()] barely conscious.")

// ===== THE LEDGER AND THE BODY'S SIGNALS =====

/**
 * Who has been hurting a criminal, and the rest of the body's signal hooks, kept on a component so the
 * AI packages can register the same signals on the mob without clashing. The ledger (in the style of
 * experiment_damage_ledger) tells a hit with someone's mind behind it from one without, so turrets,
 * traps, fire and fauna can't finish off a criminal on its site (AR-D3), and puts attackers on its
 * grudge list. Damage and the attack report arrive in the same tick: a projectile's pre-hit and an item
 * attack's attackby come before the damage, so the tick's attacker is known when the damage lands.
 * It also refuses teleports, polymorph and type changes, lets a sprinting meek criminal duck shots,
 * holds ranged attacks to may_attack(), and stops a free criminal being dragged onto things.
 */
/datum/component/bounty_body
	dupe_mode = COMPONENT_DUPE_UNIQUE
	/// world.time someone with a mind behind them last attacked it
	var/player_hit_at = -1
	/// world.time another criminal or a companion last attacked it
	var/own_side_hit_at = -1

/datum/component/bounty_body/Initialize()
	if(!istype(parent, /mob/living/basic/bounty_criminal))
		return COMPONENT_INCOMPATIBLE

/datum/component/bounty_body/RegisterWithParent()
	var/mob/living/basic/bounty_criminal/criminal = parent
	criminal.AddElement(/datum/element/relay_attackers)
	RegisterSignal(criminal, COMSIG_ATOM_WAS_ATTACKED, PROC_REF(on_attacked))
	RegisterSignal(criminal, COMSIG_ATOM_ATTACKBY, PROC_REF(on_attackby))
	RegisterSignal(criminal, COMSIG_PROJECTILE_PREHIT, PROC_REF(on_projectile_prehit))
	RegisterSignal(criminal, COMSIG_MOVABLE_TELEPORTING, PROC_REF(refuse_teleport))
	RegisterSignal(criminal, COMSIG_LIVING_PRE_WABBAJACKED, PROC_REF(refuse_polymorph))
	RegisterSignal(criminal, COMSIG_PRE_MOB_CHANGED_TYPE, PROC_REF(refuse_type_change))
	RegisterSignal(criminal, COMSIG_BASICMOB_PRE_ATTACK_RANGED, PROC_REF(on_pre_ranged_attack))
	RegisterSignal(criminal, COMSIG_MOUSEDROP_ONTO, PROC_REF(on_mousedrop))
	RegisterSignals(criminal, list(SIGNAL_ADDTRAIT(TRAIT_BOUNTY_SURRENDERED), SIGNAL_REMOVETRAIT(TRAIT_BOUNTY_SURRENDERED)), PROC_REF(on_state_signal))
	// A stun's traits land before the stun is on its list, so the trait handlers alone would miss it.
	RegisterSignals(criminal, list(COMSIG_LIVING_STATUS_APPLIED, COMSIG_LIVING_STATUS_REMOVED), PROC_REF(on_state_signal))

/datum/component/bounty_body/UnregisterFromParent()
	UnregisterSignal(parent, list(
		COMSIG_ATOM_WAS_ATTACKED,
		COMSIG_ATOM_ATTACKBY,
		COMSIG_PROJECTILE_PREHIT,
		COMSIG_MOVABLE_TELEPORTING,
		COMSIG_LIVING_PRE_WABBAJACKED,
		COMSIG_PRE_MOB_CHANGED_TYPE,
		COMSIG_BASICMOB_PRE_ATTACK_RANGED,
		COMSIG_MOUSEDROP_ONTO,
		SIGNAL_ADDTRAIT(TRAIT_BOUNTY_SURRENDERED),
		SIGNAL_REMOVETRAIT(TRAIT_BOUNTY_SURRENDERED),
		COMSIG_LIVING_STATUS_APPLIED,
		COMSIG_LIVING_STATUS_REMOVED,
	))

/// Whether someone with a mind behind them attacked it this tick
/datum/component/bounty_body/proc/player_hit_now()
	return player_hit_at == world.time

/// Whether its own side (another criminal, a companion) attacked it this tick
/datum/component/bounty_body/proc/own_side_hit_now()
	return own_side_hit_at == world.time

/// `attacker` went for it: noted for the ledger, and they go on its grudge list
/datum/component/bounty_body/proc/note_attacker(atom/attacker)
	var/mob/living/basic/bounty_criminal/criminal = parent
	if(bounty_player_behind(attacker))
		player_hit_at = world.time
	if(istype(attacker, /mob/living/basic/bounty_criminal) || istype(attacker, /mob/living/basic/bounty_companion))
		own_side_hit_at = world.time
	if(istype(attacker, /obj/vehicle/sealed))
		var/obj/vehicle/sealed/vehicle = attacker
		for(var/mob/living/pilot in vehicle.occupants)
			criminal.body_add_grudge(pilot)
	else if(isliving(attacker))
		criminal.body_add_grudge(attacker)

/**
 * An explosion is about to hit it (M1). ex_act() carries no attacker, so the blast counts as a
 * player's when the explosive was last handled by one (`origin`'s last fingerprints: a grenade
 * someone threw or set), or when someone with a mind stands within BOUNTY_EXPLOSION_WITNESS_RANGE
 * tiles. Anything else is automated, like fire.
 */
/datum/component/bounty_body/proc/note_explosion(atom/origin)
	var/mob/living/basic/bounty_criminal/criminal = parent
	if(isatom(origin) && origin.fingerprintslast)
		player_hit_at = world.time
		return
	var/turf/here = get_turf(criminal)
	if(!here)
		return
	for(var/mob/living/person in range(BOUNTY_EXPLOSION_WITNESS_RANGE, here))
		if(bounty_player_behind(person))
			player_hit_at = world.time
			return

/datum/component/bounty_body/proc/on_attacked(datum/source, atom/attacker, attack_flags)
	SIGNAL_HANDLER
	if(!(attack_flags & (ATTACKER_DAMAGING_ATTACK | ATTACKER_STAMINA_ATTACK | ATTACKER_SHOVING)))
		return
	note_attacker(attacker)

// Before an item's damage lands (relay_attackers only reports it after), so the ledger knows whose it is.
/datum/component/bounty_body/proc/on_attackby(datum/source, obj/item/attacking_item, mob/living/user, list/modifiers, list/attack_modifiers)
	SIGNAL_HANDLER
	if(attacking_item?.force > 0 || user?.combat_mode)
		note_attacker(user)

/// Whose shot it is, even a mech's or a vehicle's (relay_attackers only reports mobs, M1); and a sprinting meek criminal ducks some shots (C5), though one that gets through spoils the next second's dodging
/datum/component/bounty_body/proc/on_projectile_prehit(datum/source, obj/projectile/shot)
	SIGNAL_HANDLER
	var/mob/living/basic/bounty_criminal/criminal = parent
	if(shot?.firer && shot.is_hostile_projectile())
		note_attacker(shot.firer)
	if(prob(criminal.body_dodge_chance()))
		criminal.visible_message(span_warning("[criminal] ducks out of the way of [shot]!"))
		return PROJECTILE_INTERRUPT_HIT_PHASE
	criminal.body_last_shot_at = world.time
	return NONE

/// The pad deletes a criminal; nothing teleports one (D-A10)
/datum/component/bounty_body/proc/refuse_teleport(datum/source, atom/destination, channel)
	SIGNAL_HANDLER
	var/mob/living/basic/bounty_criminal/criminal = parent
	if(isturf(criminal.loc))
		criminal.visible_message(span_notice("[criminal] flickers for a moment, but stays where [criminal.p_they()] [criminal.p_are()]."))
	return TRUE

/datum/component/bounty_body/proc/refuse_polymorph(datum/source, what_to_randomize)
	SIGNAL_HANDLER
	var/mob/living/basic/bounty_criminal/criminal = parent
	criminal.visible_message(span_notice("[criminal] shimmers for a moment, then looks the same as before."))
	return STOP_WABBAJACK

/datum/component/bounty_body/proc/refuse_type_change(datum/source)
	SIGNAL_HANDLER
	return COMPONENT_BLOCK_MOB_CHANGE

/datum/component/bounty_body/proc/on_pre_ranged_attack(datum/source, atom/target, modifiers)
	SIGNAL_HANDLER
	var/mob/living/basic/bounty_criminal/criminal = parent
	if(!criminal.may_attack(target))
		return COMPONENT_CANCEL_RANGED_ATTACK

/datum/component/bounty_body/proc/on_mousedrop(datum/source, atom/over, mob/user)
	SIGNAL_HANDLER
	var/mob/living/basic/bounty_criminal/criminal = parent
	if(!criminal.body_can_be_dragged())
		return COMPONENT_CANCEL_MOUSEDROP_ONTO

/// It surrendered or stopped, or a stun, knockdown or stamina crit came or went: its capture state may have changed
/datum/component/bounty_body/proc/on_state_signal(datum/source)
	SIGNAL_HANDLER
	var/mob/living/basic/bounty_criminal/criminal = parent
	criminal.body_state_changed()

/// The chance, in percent, that it ducks a shot now: a meek criminal sprinting freely (TRAIT_BOUNTY_SPRINTING, from P3), not shot in the last second
/mob/living/basic/bounty_criminal/proc/body_dodge_chance()
	if(!istype(src, /mob/living/basic/bounty_criminal/meek) || !HAS_TRAIT(src, TRAIT_BOUNTY_SPRINTING))
		return 0
	if(stat != CONSCIOUS || downed || is_restrained() || !isturf(loc) || pulledby || buckled)
		return 0
	if(HAS_TRAIT(src, TRAIT_INCAPACITATED) || HAS_TRAIT(src, TRAIT_IMMOBILIZED) || HAS_TRAIT(src, TRAIT_FLOORED))
		return 0
	if(world.time - body_last_shot_at < BOUNTY_MEEK_DODGE_AFTER_HIT)
		return 0
	return BOUNTY_MEEK_DODGE

/**
 * Whether a turret leaves `creature` alone for being part of a bounty (L2; hostile_creatures.dm).
 * `at_trader_outpost`: it stands in a trader outpost's concourse. There, criminals, decoys and
 * companions are left to the hunters (spec 4). Anywhere else a criminal is left alone only once it is
 * down, stunned, restrained or dead, so a crew's own turrets don't finish off their catch; a free one,
 * and any companion, is judged like any other creature.
 */
/proc/bounty_turret_ignores(mob/living/creature, at_trader_outpost)
	var/mob/living/basic/bounty_criminal/criminal = creature
	if(istype(criminal))
		// At a trader outpost, turrets leave it alone unless an exposed fugitive hurt someone outside its grudge list (AR-C8, P6's outpost_turret_target()).
		if(at_trader_outpost)
			return !criminal.outpost_turret_target()
		return criminal.capture_state() != BOUNTY_STATE_FREE
	return at_trader_outpost && istype(creature, /mob/living/basic/bounty_companion)

/// Whether someone with a mind is behind `attacker`: a person, a borg, or the pilot of a mech or other vehicle. Criminals and their companions never count.
/proc/bounty_player_behind(atom/attacker)
	if(istype(attacker, /obj/vehicle/sealed))
		var/obj/vehicle/sealed/vehicle = attacker
		for(var/mob/living/pilot in vehicle.occupants)
			if(pilot.mind || pilot.ckey)
				return TRUE
		return FALSE
	var/mob/living/person = attacker
	if(!istype(person) || istype(person, /mob/living/basic/bounty_criminal) || istype(person, /mob/living/basic/bounty_companion))
		return FALSE
	return !isnull(person.mind) || !isnull(person.ckey)
