/**
 * # Bounty lairs: map templates
 *
 * Owner: P11 mafia club map. Do not edit this file outside P11.
 *
 * The lair ruin templates (unpickable, never seeded naturally). Spec section 14.4.
 *
 * ## Club Volga (bounty_lair_mafia_club.dmm, 45 x 42)
 *
 * A Russian mob nightclub in space, cleared one room at a time to the garage at its centre, where the don
 * waits in his mech. Every wall is indestructible, so the rooms come in order and nothing opens to space.
 * Every door is one tile wide and opaque, and each room is its own area, so a room's goons can be kept to
 * it (balance/lairs.md section 9.2).
 *
 * The walk, with each room's zone_mobs/mafia marker and the goons balance/lairs.md section 2 gives it:
 * 1. foyer, the doormen (3)
 * 2. cloakroom and lounge (3)
 * 3. casino floor (5)
 * 4. main floor: bar, dance floor, stage (4). The staff room opens off it: two rechargers, a first aid
 *    locker, a door with a bolt button inside, and no goons.
 * 5. kitchen and back corridor (3)
 * 6. VIP lounge (4)
 * 7. counting room, with the vault and its one plunder cache (3)
 * 8. back office: Tommy's desk, Brute's storage, both gatekeeper landmarks, and one goon (1). The garage
 *    door (three hardened blast doors, id "bounty_lair_gate") is in its west wall.
 *
 * The garage is 13 x 13 with four 2 x 2 pillars, no windows and nothing breakable. The don's mech is parked
 * on the bay against its west wall, eleven tiles from the garage door.
 */

/// Lair templates: surfaced by a bounty posting only. Never seeded, never respawned, never on a chart.
/datum/map_template/ruin/space/bounty_lair
	prefix = "_maps/voidcrew/RandomRuins/SpaceRuins/"
	unpickable = TRUE
	allow_duplicates = FALSE

/datum/map_template/ruin/space/bounty_lair/mafia_club
	id = "bounty_lair_mafia_club"
	suffix = "bounty_lair_mafia_club.dmm"
	name = "Club Volga"
	description = "A nightclub on a quiet orbit, run by a Russian crime family. The doors are guarded, the tables are busy, and the don keeps an armoured exosuit in the garage at the middle of the club."

// ===== AREAS =====

/**
 * Club Volga's areas: one per room, so goons can be kept to the room they spawned in.
 *
 * They inherit UNIQUE_AREA from /area/ruin, but the overmap's ruin placer gives every load its own
 * instances (planet_ruin_area_instancing_begin()), so never look a club room up through
 * GLOB.areas_by_type. NOTELEPORT stops a teleporter skipping the rooms or landing in the garage.
 */
/area/ruin/space/has_grav/powered/mafia_club
	name = "Club Volga"
	icon_state = "away"
	area_flags = HIDDEN_AREA | UNIQUE_AREA | NOTELEPORT
	ambience_index = AMBIENCE_DANGER
	sound_environment = SOUND_AREA_MEDIUM_SOFTFLOOR

/area/ruin/space/has_grav/powered/mafia_club/foyer
	name = "Club Volga Foyer"

/area/ruin/space/has_grav/powered/mafia_club/cloakroom
	name = "Club Volga Cloakroom"

/area/ruin/space/has_grav/powered/mafia_club/casino
	name = "Club Volga Casino"
	sound_environment = SOUND_AREA_LARGE_SOFTFLOOR

/area/ruin/space/has_grav/powered/mafia_club/bar
	name = "Club Volga Main Floor"
	sound_environment = SOUND_AREA_LARGE_SOFTFLOOR

/// Off the main floor: rechargers and first aid, and never any goons
/area/ruin/space/has_grav/powered/mafia_club/staff
	name = "Club Volga Staff Room"
	sound_environment = SOUND_AREA_SMALL_ENCLOSED

/area/ruin/space/has_grav/powered/mafia_club/kitchen
	name = "Club Volga Kitchen"
	sound_environment = SOUND_AREA_SMALL_ENCLOSED

/area/ruin/space/has_grav/powered/mafia_club/vip
	name = "Club Volga VIP Lounge"

/area/ruin/space/has_grav/powered/mafia_club/counting
	name = "Club Volga Counting Room"
	sound_environment = SOUND_AREA_SMALL_ENCLOSED

/// The lieutenants' room. The garage door tiles belong to it, not to the garage.
/area/ruin/space/has_grav/powered/mafia_club/back_office
	name = "Club Volga Back Office"

/// The arena: the 13 x 13 floor behind the garage door, and its pillars. The don's mech is kept to it.
/area/ruin/space/has_grav/powered/mafia_club/garage
	name = "Club Volga Garage"
	sound_environment = SOUND_AREA_LARGE_ENCLOSED

// ===== THE BAR SIGN =====

/// The main floor's sign, lit from the start (a mapped bar sign otherwise starts switched off)
/obj/machinery/barsign/all_access/mafia_club

/obj/machinery/barsign/all_access/mafia_club/Initialize(mapload)
	. = ..()
	// The parent lets a mapped sign rename its area; the club keeps its own room names.
	change_area_name = FALSE
	set_sign(new /datum/barsign/maltesefalcon)

MAPPING_DIRECTIONAL_HELPERS(/obj/machinery/barsign/all_access/mafia_club, 32)
