/**
 * # Bounty hunting: how a criminal looks
 *
 * Owner: P1 identity. Do not edit this file outside P1.
 *
 * What it owns: the look builder that puts the same face (a /datum/bounty_look) on any mob in any
 * outfit, for any species in the pool, cached per record and outfit; the old look a trader-outpost
 * fugitive's mugshot shows (AR-C1); and the mugshot, built once per record and served to the UI
 * through ui_static_data() as base64 (spec sections 2, 8 and 10; AR-G1). Mugshots never go through
 * a ui_data() payload.
 *
 * How a look is built: a throwaway human dummy gets the look's species features first (a species'
 * visible organs take their shape from dna.features as they go in), then its species, body, skin,
 * hair and eyes, then the outfit (visuals only), then the glasses or scarf a record's features name
 * when the outfit leaves the eyes or neck free (no scarf with a prisoner's outfit). Its appearance
 * is cached under "[record id]|[outfit]" and copied onto the mob the way set_outpost_npc_look()
 * does. A dummy is built once per record and outfit, and once per record for the mugshot.
 *
 * The proc that makes a dummy is always the one that deletes it, and the risky work (species,
 * outfit, flattening) happens in procs it calls: a runtime there ends only that proc, so the dummy
 * is still deleted and nothing half-built is cached.
 *
 * Mugshots are built from a queue, at most one per tick (each costs a dummy and a flat icon). UI
 * code asks with bounty_mugshot_cached(), which never builds or sleeps.
 *
 * The shared vars are declared in bounty_types.dm and nowhere else; a var only P1 uses goes in
 * bounty_identity.dm with an `identity_` prefix.
 */

/// Built looks: "[record id]|[outfit]" -> appearance, oldest first
GLOBAL_LIST_EMPTY(bounty_looks)
/// Whose each built look is: the same key -> weakref to the record, so a closed or deleted record's looks can go
GLOBAL_LIST_EMPTY(bounty_look_owners)
/// Looks built this round, one per record and outfit (the tests check a cached look isn't built again)
GLOBAL_VAR_INIT(bounty_look_builds, 0)
/// Mugshots built this round; each record's is built once
GLOBAL_VAR_INIT(bounty_mugshot_builds, 0)
/// Weakrefs to records waiting for their mugshot, oldest first; one is built per tick
GLOBAL_LIST_EMPTY(bounty_mugshot_queue)

// ===== DRESSING A MOB =====

/**
 * Dresses `target` as the person in `record` wearing `outfit` (a typepath): the same face in any
 * outfit. A record with no look gets one rolled for its species and gender first, and keeps it.
 * Updates the target's own overlays afterwards (cuffs and the like). Can sleep, so call it from an
 * async proc.
 */
/proc/apply_bounty_look(mob/living/target, datum/bounty_record/record, outfit)
	if(QDELETED(target) || !record)
		return
	var/look = get_bounty_look(record, outfit)
	if(QDELETED(target) || !look)
		return
	target.icon = 'icons/mob/human/human.dmi'
	target.icon_state = ""
	target.appearance_flags |= KEEP_TOGETHER
	target.copy_overlays(look, cut_old = TRUE)
	target.update_appearance(UPDATE_OVERLAYS)

/**
 * The appearance of `record`'s person in `outfit`, built the first time it's asked for and cached
 * per record and outfit (an outfit passed as a datum is built every time). Null if the build
 * failed. Can sleep.
 */
/proc/get_bounty_look(datum/bounty_record/record, outfit)
	var/datum/bounty_look/look = bounty_ensure_look(record)
	var/key = (isnull(outfit) || ispath(outfit)) ? "[record.id]|[outfit]" : null
	if(key && GLOB.bounty_looks[key])
		return GLOB.bounty_looks[key]
	// Glasses are theirs anywhere; a scarf stays with their things when they go to prison.
	var/neckwear = !ispath(outfit, /datum/outfit/outpost_prisoner)
	var/mob/living/carbon/human/dummy/dummy = new
	var/dressed = bounty_dress_dummy(dummy, look, outfit, record.features, neckwear)
	var/built = dressed ? dummy.appearance : null
	qdel(dummy)
	if(!built)
		return null
	GLOB.bounty_look_builds++
	if(!key)
		return built
	// Two mobs can build the same look at once; the first one built is kept.
	if(!GLOB.bounty_looks[key])
		bounty_trim_look_cache()
		GLOB.bounty_looks[key] = built
		GLOB.bounty_look_owners[key] = WEAKREF(record)
	return GLOB.bounty_looks[key]

/**
 * A new human dummy looking like `look` in `outfit`, or null if dressing it failed (the dummy is
 * deleted then). For tests and tools; the caller deletes the dummy. Can sleep.
 */
/proc/bounty_look_dummy(datum/bounty_look/look, outfit, list/features, neckwear = TRUE)
	var/mob/living/carbon/human/dummy/dummy = new
	if(bounty_dress_dummy(dummy, look, outfit, features, neckwear))
		return dummy
	qdel(dummy)
	return null

/**
 * Makes `dummy` look like `look` in `outfit`, wearing the glasses and (when `neckwear`) the scarf
 * that `features` name where the outfit leaves room. Returns TRUE when done; a runtime part way
 * returns null to the caller, which still deletes the dummy. Can sleep.
 */
/proc/bounty_dress_dummy(mob/living/carbon/human/dummy/dummy, datum/bounty_look/look, outfit, list/features, neckwear = TRUE)
	if(QDELETED(dummy) || !look)
		return FALSE
	// Before the species: its visible organs take their shape from dna.features as they go in.
	for(var/feature in look.features)
		dummy.dna.features[feature] = look.features[feature]
	dummy.gender = look.physique == FEMALE ? FEMALE : MALE
	dummy.physique = dummy.gender
	if(ispath(look.species, /datum/species) && dummy.dna.species.type != look.species)
		dummy.set_species(look.species)
	if(look.skin_tone)
		dummy.skin_tone = look.skin_tone
	dummy.set_hairstyle(look.hairstyle || "Bald", update = FALSE)
	if(look.hair_color)
		dummy.set_haircolor(look.hair_color, update = FALSE)
	dummy.set_facial_hairstyle(look.facial_hairstyle || "Shaved", update = FALSE)
	if(look.facial_hair_color || look.hair_color)
		dummy.set_facial_haircolor(look.facial_hair_color || look.hair_color, update = FALSE)
	if(look.eye_color)
		dummy.set_eye_color(look.eye_color)
	dummy.underwear = "Nude"
	dummy.undershirt = "Nude"
	dummy.socks = "Nude"
	// Without is_creating the limbs keep the colours they were made with.
	dummy.update_body(is_creating = TRUE)
	if(outfit)
		dummy.equipOutfit(outfit, visuals_only = TRUE)
	bounty_wear_features(dummy, features, neckwear)
	return !QDELETED(dummy)

/// Puts on the glasses and (when `neckwear`) the scarf that `features` name, where `dummy`'s outfit left the eyes or neck free
/proc/bounty_wear_features(mob/living/carbon/human/dummy/dummy, list/features, neckwear = TRUE)
	if(!length(features))
		return
	var/glasses = features[BOUNTY_FEATURE_GLASSES]
	var/glasses_type = istext(glasses) ? bounty_glasses_items()[glasses] : null
	if(glasses_type && !dummy.glasses)
		dummy.equip_to_slot_or_del(new glasses_type(dummy), ITEM_SLOT_EYES, initial = TRUE)
	var/scarf = features[BOUNTY_FEATURE_CLOTHING]
	var/scarf_type = (neckwear && istext(scarf)) ? bounty_scarf_items()[scarf] : null
	if(scarf_type && !dummy.wear_neck)
		dummy.equip_to_slot_or_del(new scarf_type(dummy), ITEM_SLOT_NECK, initial = TRUE)

/// Makes room in the look cache for one more: drops the looks of closed or deleted records, then the oldest
/proc/bounty_trim_look_cache()
	var/static/list/closed = list(BOUNTY_RECORD_RELEASED, BOUNTY_RECORD_ESCAPED, BOUNTY_RECORD_DEAD, BOUNTY_RECORD_CLOSED)
	for(var/key in GLOB.bounty_look_owners.Copy())
		var/datum/weakref/owner_ref = GLOB.bounty_look_owners[key]
		var/datum/bounty_record/owner = owner_ref?.resolve()
		if(!owner || (owner.status in closed))
			GLOB.bounty_looks -= key
			GLOB.bounty_look_owners -= key
	while(length(GLOB.bounty_looks) >= BOUNTY_LOOK_CACHE_MAX)
		var/oldest = GLOB.bounty_looks[1]
		GLOB.bounty_looks -= oldest
		GLOB.bounty_look_owners -= oldest

/// Forgets every built look of `record`, for when it closes. Mobs already dressed keep their look.
/proc/bounty_forget_looks(datum/bounty_record/record)
	if(!record)
		return
	var/prefix = "[record.id]|"
	for(var/key in GLOB.bounty_looks.Copy())
		if(findtext(key, prefix) == 1)
			GLOB.bounty_looks -= key
			GLOB.bounty_look_owners -= key

// ===== THE OLD LOOK (AR-C1) =====

/**
 * Gives `record` an older look (record.old_look) for a trader-outpost fugitive's mugshot. The hair
 * (style, colour and beard) is re-rolled from scratch, independently of the current hair, until
 * nothing about it matches the current hair (bounty_hair_nothing_alike()). Decoys are held to the
 * same rule against the old look (bounty_reroll_decoy_hair()), so the mugshot's hair matches none
 * of the patrons and tells them apart by nothing. Species, skin, eyes and body features stay: they
 * are the face every patron shares. The mugshot also leaves out their eyewear and is taken in
 * plain civilian clothes. A species without hair keeps its look.
 *
 * Idempotent: a record that has an old look keeps it. Clears a mugshot built before, so the next
 * one shows the old look. Doesn't sleep.
 */
/proc/make_old_look(datum/bounty_record/record)
	if(!record)
		return null
	if(record.old_look)
		return record.old_look
	var/datum/bounty_look/current = bounty_ensure_look(record)
	var/datum/bounty_look/old = bounty_copy_look(current)
	if(bounty_species_has_hair(old.species))
		for(var/attempt in 1 to BOUNTY_HAIR_ROLL_ATTEMPTS)
			bounty_roll_hair(old)
			if(bounty_hair_nothing_alike(old, current))
				break
	record.old_look = old
	record.mugshot = null
	return old

// ===== MUGSHOTS =====

/// Plain civilian clothes for a mugshot: a button-down shirt
/datum/outfit/bounty_mugshot
	name = "Bounty mugshot"
	uniform = /obj/item/clothing/under/costume/buttondown/slacks
	shoes = /obj/item/clothing/shoes/sneakers/black

/// Plain civilian clothes for a mugshot: a bomber jacket
/datum/outfit/bounty_mugshot/bomber
	name = "Bounty mugshot (bomber)"
	uniform = /obj/item/clothing/under/color/black
	suit = /obj/item/clothing/suit/jacket/bomber

/// Plain civilian clothes for a mugshot: a sweater
/datum/outfit/bounty_mugshot/sweater
	name = "Bounty mugshot (sweater)"
	uniform = /obj/item/clothing/under/color/grey
	suit = /obj/item/clothing/suit/toggle/jacket/sweater

/**
 * The features a record's mugshot is drawn with: their own, or with no eyewear when the mugshot
 * shows their old look (worn things are what a fugitive changes, AR-C1).
 */
/proc/bounty_mugshot_features(datum/bounty_record/record)
	var/list/features = record.features?.Copy() || list()
	if(record.old_look)
		features -= BOUNTY_FEATURE_GLASSES
	return features

/**
 * Their mugshot as a base64 PNG (no "data:" prefix), built once and cached on record.mugshot:
 * head and shoulders against a height-lined wall, in plain civilian clothes, showing
 * record.old_look when they have one. Sends COMSIG_BOUNTY_RECORD_MUGSHOT_READY on the record when
 * built. Builds a dummy on the spot the first time: UI code uses bounty_mugshot_cached() instead.
 * Returns "" if the build failed; it can be asked for again.
 */
/proc/bounty_record_mugshot(datum/bounty_record/record)
	if(!record)
		return ""
	if(record.mugshot)
		return record.mugshot
	bounty_ensure_look(record)
	var/static/list/outfits = list(/datum/outfit/bounty_mugshot, /datum/outfit/bounty_mugshot/bomber, /datum/outfit/bounty_mugshot/sweater)
	var/icon/portrait = bounty_mugshot_icon(record.old_look || record.look, bounty_mugshot_features(record), pick(outfits))
	// Another build may have finished while this one waited on the dummy.
	if(record.mugshot)
		return record.mugshot
	if(!portrait)
		return ""
	GLOB.bounty_mugshot_builds++
	var/encoded = icon2base64(portrait)
	if(!istext(encoded) || !length(encoded))
		return ""
	record.mugshot = encoded
	SEND_SIGNAL(record, COMSIG_BOUNTY_RECORD_MUGSHOT_READY)
	return record.mugshot

/**
 * THE getter for UI code (ui_static_data(), boards, cards): `record`'s mugshot as base64, shown as
 * `data:image/png;base64,<value>`, or "" until it's built. Never builds, never sleeps: the first ask
 * puts the record in the mugshot queue (one build per tick), and the record sends
 * COMSIG_BOUNTY_RECORD_MUGSHOT_READY when it's ready, so the UI can resend its static data.
 */
/proc/bounty_mugshot_cached(datum/bounty_record/record)
	if(!record)
		return ""
	if(record.mugshot)
		return record.mugshot
	bounty_queue_mugshot(record)
	return ""

/// The same as bounty_mugshot_cached() (the name P0 gave it): base64 or "", never builds or sleeps
/proc/bounty_mugshot_asset(datum/bounty_record/record)
	return bounty_mugshot_cached(record)

/// Puts `record` in the mugshot queue, once, and makes sure the queue is being worked through
/proc/bounty_queue_mugshot(datum/bounty_record/record)
	if(!record || record.mugshot || record.identity_mugshot_queued)
		return
	record.identity_mugshot_queued = TRUE
	GLOB.bounty_mugshot_queue += WEAKREF(record)
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(bounty_build_next_mugshot)), 1, TIMER_UNIQUE)

/**
 * Builds the next queued mugshot, one per call; the queue calls it once per tick until it's empty.
 * The next call is set up before building, and the record's queued mark is cleared first, so a
 * build that fails neither stalls the queue nor stops the record being asked for again.
 */
/proc/bounty_build_next_mugshot()
	var/datum/bounty_record/record
	while(!record && length(GLOB.bounty_mugshot_queue))
		var/datum/weakref/next_ref = GLOB.bounty_mugshot_queue[1]
		GLOB.bounty_mugshot_queue.Cut(1, 2)
		record = next_ref?.resolve()
		if(record?.mugshot)
			record.identity_mugshot_queued = FALSE
			record = null
	if(length(GLOB.bounty_mugshot_queue))
		addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(bounty_build_next_mugshot)), 1, TIMER_UNIQUE)
	if(!record)
		return
	record.identity_mugshot_queued = FALSE
	bounty_record_mugshot(record)

/**
 * The mugshot image of `look` in `outfit`: head and shoulders, cropped and scaled up, against a
 * wall. Null if building the dummy failed. Can sleep.
 */
/proc/bounty_mugshot_icon(datum/bounty_look/look, list/features, outfit = /datum/outfit/bounty_mugshot)
	var/mob/living/carbon/human/dummy/dummy = new
	var/icon/body = bounty_mugshot_body(dummy, look, outfit, features)
	qdel(dummy)
	if(!body)
		return null
	var/icon/portrait = icon('icons/blanks/32x32.dmi', "nothing")
	portrait.DrawBox(BOUNTY_MUGSHOT_BACKDROP, 1, 1, 32, 32)
	for(var/line_y in list(22, 27, 32))
		portrait.DrawBox(BOUNTY_MUGSHOT_LINES, 1, line_y, 32, line_y)
	portrait.Blend(body, ICON_OVERLAY)
	portrait.Crop(BOUNTY_MUGSHOT_X1, BOUNTY_MUGSHOT_Y1, BOUNTY_MUGSHOT_X2, BOUNTY_MUGSHOT_Y2)
	portrait.Scale((BOUNTY_MUGSHOT_X2 - BOUNTY_MUGSHOT_X1 + 1) * BOUNTY_MUGSHOT_SCALE, (BOUNTY_MUGSHOT_Y2 - BOUNTY_MUGSHOT_Y1 + 1) * BOUNTY_MUGSHOT_SCALE)
	return portrait

/// Dresses `dummy` (no scarf) and flattens it facing forward; null if dressing failed. The caller deletes the dummy.
/proc/bounty_mugshot_body(mob/living/carbon/human/dummy/dummy, datum/bounty_look/look, outfit, list/features)
	if(!bounty_dress_dummy(dummy, look, outfit, features, neckwear = FALSE))
		return null
	dummy.setDir(SOUTH)
	return getFlatIcon(dummy, SOUTH, no_anim = TRUE)
