/**
 * # Bounty hunting: the board
 *
 * Owner: P5 board. Owns this file, bounty_posting.dm, bounty_placement.dm, bounty_turn_in.dm,
 * voidcrew/_DEFINES/bounty_board.dm, the ui_data() and ui_act() additions in
 * voidcrew/modules/missions/mission_board.dm, tgui/packages/tgui/interfaces/MissionBoard.tsx and
 * the tests in voidcrew/modules/unit_tests/voidcrew_bounty_board.dm. Do not edit this file outside
 * P5.
 *
 * What it owns: SScriminal_bounties, the board manager: posting public bounties and private offers
 * up to their caps, the zone, tier, archetype and placement rolls, the value fixed at posting, the
 * board's ten-second tick (spec sections 1, 2 and 10, and 12.1), and the mission board console's
 * Wanted section: its data, static data (mugshots), actions and warrant printer.
 *
 * Public bounties are Wanted or Most Wanted, posted one per BOUNTY_PUBLIC_POST_GAP up to
 * 1 + active ships / 4 (at most 4). Petty ones are private offers, two per ship, made when that
 * ship's board is looked at. The shared vars are declared in bounty_types.dm; a var only P5 uses is
 * here with a `board_` prefix.
 */

// The record's "mugshot built" signal is P1's (COMSIG_BOUNTY_RECORD_MUGSHOT_READY, _DEFINES/bounty_identity.dm).
// The literal stands in for it where P1's defines aren't there yet.
#ifdef COMSIG_BOUNTY_RECORD_MUGSHOT_READY
#define BOUNTY_BOARD_MUGSHOT_READY COMSIG_BOUNTY_RECORD_MUGSHOT_READY
#else
#define BOUNTY_BOARD_MUGSHOT_READY "bounty_record_mugshot_ready"
#endif

SUBSYSTEM_DEF(criminal_bounties)
	name = "Criminal Bounties"
	wait = 10 SECONDS
	// Nothing to set up while the world loads: the board fills itself from its ticks. If an
	// Initialize() is ever added, drop SS_NO_INIT and list the subsystems it needs in
	// `dependencies`; the MC orders init by those and overwrites init_order.
	flags = SS_BACKGROUND | SS_NO_INIT
	runlevels = RUNLEVEL_GAME
	/// world.time of the last tick, so a hunt holds a clock for exactly the time that passed
	var/board_last_tick = 0
	/// world.time the next public bounty may go up
	var/board_next_public_post = 0
	/// world.time until which the board's own public postings go up without news (the round's opening fill)
	var/board_quiet_until = 0
	/// Goes up whenever a posting goes up, relists or comes down (a count for the logs and admins; each console watches its own postings' static_data_serial)
	var/board_static_serial = 0
	/// Weakref of a ship -> world.time it may be offered its next private bounty
	var/list/board_private_next = list()
#ifdef UNIT_TESTS
	/// Whether the board posts public bounties on its own clock. Off in tests, which post their own.
	var/board_auto_post = FALSE
#else
	/// Whether the board posts public bounties on its own clock. Off in tests, which post their own.
	var/board_auto_post = TRUE
#endif

/datum/controller/subsystem/criminal_bounties/fire(resumed)
	board_tick()

/datum/controller/subsystem/criminal_bounties/stat_entry(msg)
	msg = "P:[length(GLOB.criminal_bounties)]|C:[board_live_criminals()]"
	return ..()

/**
 * The board's tick, every 10 seconds of the round: each posting's clock, expiry, relist, spawn and
 * sighting, then a public posting when the gap has passed and the board is under its cap.
 */
/datum/controller/subsystem/criminal_bounties/proc/board_tick()
	var/now = world.time
	var/elapsed = board_last_tick ? clamp(now - board_last_tick, 0, 1 MINUTES) : 0
	if(!board_last_tick)
		board_quiet_until = now + BOUNTY_OPENING_QUIET
	board_last_tick = now
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties.Copy())
		if(QDELETED(posting))
			GLOB.criminal_bounties -= posting
			continue
		posting.board_process(elapsed)
	if(board_auto_post)
		board_post_public_if_due(now)

/// Posts a public bounty if the gap since the last has passed and the board is under its cap. Returns the posting, or null.
/datum/controller/subsystem/criminal_bounties/proc/board_post_public_if_due(now = world.time)
	if(now < board_next_public_post)
		return null
	if(board_public_count() >= board_public_cap())
		return null
	// Crews are still boarding at round start: the opening fill goes up without news
	var/datum/criminal_bounty/posted = post_criminal_bounty(board_roll_public_tier(), null, quiet = now < board_quiet_until)
	board_next_public_post = now + (posted ? BOUNTY_PUBLIC_POST_GAP : BOUNTY_PUBLIC_POST_RETRY)
	return posted

/**
 * The admin panel's "skip the post gap" (P8): posts a public bounty now, as the board would once
 * its gap ran out, and starts the next gap from now. Still held to the public cap unless
 * `ignore_cap`. Returns the posting, or null.
 */
/datum/controller/subsystem/criminal_bounties/proc/admin_skip_post_gap(ignore_cap = FALSE)
	if(!ignore_cap)
		board_next_public_post = world.time
		return board_post_public_if_due()
	var/datum/criminal_bounty/posted = post_criminal_bounty(board_roll_public_tier(), null)
	if(posted)
		board_next_public_post = world.time + BOUNTY_PUBLIC_POST_GAP
	return posted

/**
 * Moves the board's clock forward by `seconds` (P8's admin panel): every posting's expiry,
 * relist and sighting, every ship's next private offer, and the next public posting come that much
 * sooner. Then the board ticks once.
 */
/datum/controller/subsystem/criminal_bounties/proc/board_fast_forward(seconds)
	var/step = max(0, seconds) * (1 SECONDS)
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		posting.expires_at -= step
		posting.board_relist_at -= step
		posting.board_next_sighting -= step
		for(var/datum/weakref/ref as anything in posting.board_hunt_started)
			posting.board_hunt_started[ref] -= step
	for(var/datum/weakref/ref as anything in board_private_next)
		board_private_next[ref] -= step
	board_next_public_post -= step
	board_quiet_until -= step
	board_tick()

/// Something about the set of postings changed: open boards resend their static data (the mugshots)
/datum/controller/subsystem/criminal_bounties/proc/board_changed()
	board_static_serial++

/// Its record's mugshot has been built (P1): the boards showing it resend their static data
/datum/criminal_bounty/proc/board_on_mugshot_ready(datum/source)
	SIGNAL_HANDLER
	static_data_serial++
	SScriminal_bounties.board_changed()

// ===== CAPS AND COUNTS =====

/// Open public bounties
/datum/controller/subsystem/criminal_bounties/proc/board_public_count()
	var/count = 0
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(posting.is_open() && !posting.private_to && !istype(posting, /datum/criminal_bounty/kill_only) && !istype(posting, /datum/criminal_bounty/kingpin)) // BOUNTY P10/P9: lairs, the lich and the kingpin are events and don't take a public slot
			count++
	return count

/// Public bounties the board holds: 1 + active ships / 4, at most BOUNTY_MAX_PUBLIC (12.1)
/datum/controller/subsystem/criminal_bounties/proc/board_public_cap(active_ships = board_active_ships())
	return min(BOUNTY_MAX_PUBLIC, BOUNTY_PUBLIC_CAP_BASE + floor(active_ships / BOUNTY_PUBLIC_CAP_PER_SHIPS))

/// Player ships with at least one living, connected crew member, wherever they are
/datum/controller/subsystem/criminal_bounties/proc/board_active_ships()
	var/count = 0
	for(var/obj/structure/overmap/ship/ship as anything in SSovermap.simulated_ships)
		if(QDELETED(ship) || ship.abandoned || istype(ship, /obj/structure/overmap/ship/npc))
			continue
		if(board_ship_crewed(ship))
			count++
	return count

/// Whether `ship` has a living, connected crew member anywhere
/datum/controller/subsystem/criminal_bounties/proc/board_ship_crewed(obj/structure/overmap/ship/ship)
	// `as anything` skips the type filter, and a hard-deleted mind is nulled in place in this list
	for(var/datum/mind/member as anything in ship.ship_team?.members)
		var/mob/living/body = member?.current
		if(QDELETED(body) || !isliving(body) || body.stat == DEAD)
			continue
		if(GET_CLIENT(body))
			return TRUE
	return FALSE

/// Public bounties `ship` is hunting
/datum/controller/subsystem/criminal_bounties/proc/board_public_hunts(obj/structure/overmap/ship/ship)
	var/count = 0
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(posting.is_open() && !posting.private_to && posting.is_hunting(ship))
			count++
	return count

/// Open private offers for `ship`
/datum/controller/subsystem/criminal_bounties/proc/board_private_count(obj/structure/overmap/ship/ship)
	var/count = 0
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(posting.is_open() && posting.private_to && posting.offered_to() == ship)
			count++
	return count

/// Criminals alive in the world, server-wide (a body is proof, not a criminal)
/datum/controller/subsystem/criminal_bounties/proc/board_live_criminals()
	var/count = 0
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		var/mob/living/basic/bounty_criminal/criminal = posting.criminal()
		if(criminal && criminal.stat != DEAD)
			count++
	return count

/// Criminals alive plus spawns under way: what BOUNTY_MAX_LIVE_CRIMINALS caps (a spawn can yield, so several may be in flight at once)
/datum/controller/subsystem/criminal_bounties/proc/board_criminal_slots_used()
	var/count = board_live_criminals()
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(posting.board_spawning)
			count++
	return count

/// Companions alive in the world, server-wide
/datum/controller/subsystem/criminal_bounties/proc/board_live_companions()
	var/count = 0
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		for(var/datum/weakref/ref as anything in posting.companions.Copy())
			var/mob/living/companion = ref?.resolve()
			if(QDELETED(companion))
				posting.companions -= ref
				continue
			if(companion.stat != DEAD)
				count++
	return count

/// Open postings at `site`
/datum/controller/subsystem/criminal_bounties/proc/board_postings_at(obj/structure/overmap/site)
	var/count = 0
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(posting.is_open() && posting.site() == site)
			count++
	return count

// ===== PRIVATE OFFERS =====

/**
 * Tops `ship`'s private petty offers up to BOUNTY_PRIVATE_MAX, as its board is looked at. After an
 * offer ends, the ship's next one waits BOUNTY_PRIVATE_GAP. Returns the offers made.
 */
/datum/controller/subsystem/criminal_bounties/proc/board_offer_private(obj/structure/overmap/ship/ship)
	var/list/made = list()
	if(QDELETED(ship) || istype(ship, /obj/structure/overmap/ship/npc))
		return made
	var/datum/weakref/ship_ref = WEAKREF(ship)
	if(world.time < board_private_next[ship_ref])
		return made
	var/wanted = BOUNTY_PRIVATE_MAX - board_private_count(ship)
	for(var/i in 1 to wanted)
		var/datum/criminal_bounty/offer = post_criminal_bounty(BOUNTY_TIER_PETTY, null, null, ship)
		if(!offer)
			// Nowhere to put one right now; don't search the sector again every second
			board_private_next[ship_ref] = world.time + BOUNTY_PUBLIC_POST_RETRY
			break
		made += offer
	return made

// ===== POSTING =====

/**
 * Posts a bounty now: a criminal of `tier` (BOUNTY_TIER_*) at a `placement_kind`
 * (BOUNTY_PLACEMENT_*) site, at `site` (an /obj/structure/overmap planet, ruin, pirate ship or
 * trader outpost) or one the board picks, public or offered only to the ship `private_to`.
 * A `quiet` Most Wanted isn't announced to every crew.
 * Returns the posting (/datum/criminal_bounty), or null if none could be made.
 */
/proc/post_criminal_bounty(tier, placement_kind, obj/structure/overmap/site = null, obj/structure/overmap/ship/private_to = null, quiet = FALSE)
	return SScriminal_bounties.board_post(tier, placement_kind, site, private_to, quiet)

/// post_criminal_bounty()'s body; see there
/datum/controller/subsystem/criminal_bounties/proc/board_post(tier, placement_kind, obj/structure/overmap/site, obj/structure/overmap/ship/private_to, quiet = FALSE)
	if(private_to && QDELETED(private_to))
		return null
	if(!tier)
		tier = private_to ? BOUNTY_TIER_PETTY : board_roll_public_tier()
	tier = clamp(tier, BOUNTY_TIER_PETTY, BOUNTY_TIER_MOST_WANTED)

	var/kind = placement_kind
	var/archetype
	var/zone
	if(site)
		if(QDELETED(site))
			return null
		kind = kind || board_kind_of_site(site)
		if(!kind || board_kind_of_site(site) != kind)
			return null
		archetype = board_roll_archetype(tier, kind)
		if(!board_kind_allowed(kind, tier, archetype))
			return null
	else
		zone = board_roll_zone(private_to)
		var/list/placement = board_pick_placement(tier, null, kind, zone, only_kind = !!kind)
		if(!placement)
			return null
		kind = placement[1]
		site = placement[2]
		archetype = board_roll_archetype(tier, kind)
	zone = board_site_zone(site)

	var/datum/bounty_record/record = generate_bounty_record(tier, archetype, kind)
	if(!record)
		return null
	record.tier = tier
	if(!record.archetype)
		record.archetype = archetype
	record.base_value = board_roll_base_value(tier)
	record.status = BOUNTY_RECORD_WANTED
	// The card's mugshot is how they looked before; built now, before anything can cache the mugshot (AR-C1)
	if(kind == BOUNTY_PLACEMENT_TRADER_OUTPOST && !record.old_look)
		make_old_look(record)

	var/datum/criminal_bounty/posting = new
	posting.record = record
	posting.placement_kind = kind
	posting.board_zone = zone
	posting.value = board_value_for(record.base_value, zone)
	posting.board_vouchers = board_vouchers_for(tier, zone)
	posting.private_to = private_to ? WEAKREF(private_to) : null
	posting.board_posted_at = world.time
	posting.expires_at = world.time + (private_to ? BOUNTY_PRIVATE_EXPIRY : BOUNTY_PUBLIC_EXPIRY)
	posting.board_gps_tag = "[BOUNTY_GPS_TAG_PREFIX]-[record.id]"
	posting.RegisterSignal(record, BOUNTY_BOARD_MUGSHOT_READY, TYPE_PROC_REF(/datum/criminal_bounty, board_on_mugshot_ready))
	GLOB.criminal_bounties += posting
	posting.board_set_site(site)
	board_changed()
	log_game("BOUNTY: posted the [posting.board_log_name()] in zone [zone], worth [posting.value] cr and [posting.board_vouchers] voucher(s)")
	// A Most Wanted is news for every crew (P8); Wanted and petty ones never are
	if(tier == BOUNTY_TIER_MOST_WANTED && !private_to && !quiet)
		board_announce("MOST WANTED: [record.name]. [posting.board_place_text()].")
	posting.board_arm()
	return posting

/**
 * Tells every player crew `message` on their ships, as a lair's kill-only notice does: every ship
 * that isn't an NPC ship or abandoned, except those in `exclude`. Returns the ships told.
 */
/datum/controller/subsystem/criminal_bounties/proc/board_announce(message, list/exclude)
	var/list/told = list()
	for(var/obj/structure/overmap/ship/ship as anything in SSovermap.simulated_ships)
		if(QDELETED(ship) || ship.abandoned || istype(ship, /obj/structure/overmap/ship/npc) || (exclude && (ship in exclude)))
			continue
		ship.ship_notify(message, "MISSION CONTROL", SHIP_NOTIFY_NOTICE, 'voidcrew/sound/notify.ogg', 50)
		told += ship
	return told

/// The value in credits of a bounty with `base_value` in zone band `zone`, fixed at posting (AR-A9)
/datum/controller/subsystem/criminal_bounties/proc/board_value_for(base_value, zone)
	return round(base_value * board_zone_mult(zone), 10)

/// The credit multiplier of zone band `zone`, the mission system's
/datum/controller/subsystem/criminal_bounties/proc/board_zone_mult(zone)
	switch(zone)
		if(ZONE_YELLOW)
			return BOUNTY_ZONE_MULT_YELLOW
		if(ZONE_RED)
			return BOUNTY_ZONE_MULT_RED
	return BOUNTY_ZONE_MULT_GREEN

/// Vouchers a full-share turn-in pays for `tier` in zone band `zone`: red adds one to any that pays them
/datum/controller/subsystem/criminal_bounties/proc/board_vouchers_for(tier, zone)
	var/vouchers = BOUNTY_VOUCHERS_PETTY
	switch(tier)
		if(BOUNTY_TIER_WANTED)
			vouchers = BOUNTY_VOUCHERS_WANTED
		if(BOUNTY_TIER_MOST_WANTED)
			vouchers = BOUNTY_VOUCHERS_MOST_WANTED
	if(vouchers > 0 && zone == ZONE_RED)
		vouchers += BOUNTY_RED_VOUCHER_BONUS
	return vouchers

/// A green-space base value for `tier`, from its band
/datum/controller/subsystem/criminal_bounties/proc/board_roll_base_value(tier)
	switch(tier)
		if(BOUNTY_TIER_WANTED)
			return rand(BOUNTY_PAY_WANTED_MIN, BOUNTY_PAY_WANTED_MAX)
		if(BOUNTY_TIER_MOST_WANTED)
			return rand(BOUNTY_PAY_MOST_WANTED_MIN, BOUNTY_PAY_MOST_WANTED_MAX)
	return rand(BOUNTY_PAY_PETTY_MIN, BOUNTY_PAY_PETTY_MAX)

// ===== ROLLS =====

/// A public bounty's tier: Wanted, or the rarer Most Wanted
/datum/controller/subsystem/criminal_bounties/proc/board_roll_public_tier()
	var/static/list/weights = list(
		"[BOUNTY_TIER_WANTED]" = BOUNTY_PUBLIC_WEIGHT_WANTED,
		"[BOUNTY_TIER_MOST_WANTED]" = BOUNTY_PUBLIC_WEIGHT_MOST_WANTED,
	)
	return text2num(pick_weight(weights)) || BOUNTY_TIER_WANTED

/// A new bounty's zone band. An offer to a ship with no combat research stays in green space most of the time, as its missions do.
/datum/controller/subsystem/criminal_bounties/proc/board_roll_zone(obj/structure/overmap/ship/private_to)
	if(private_to && !private_to.has_ship_combat_research() && prob(BOUNTY_UNARMED_GREEN_BIAS))
		return ZONE_GREEN
	var/static/list/weights = list(
		"[ZONE_GREEN]" = BOUNTY_ZONE_WEIGHT_GREEN,
		"[ZONE_YELLOW]" = BOUNTY_ZONE_WEIGHT_YELLOW,
		"[ZONE_RED]" = BOUNTY_ZONE_WEIGHT_RED,
	)
	return text2num(pick_weight(weights)) || ZONE_GREEN

/// The archetype for a criminal of `tier` at a `kind` site (spec 2): pirate ships hold no meek ones, and Most Wanted is always a mini-boss
/datum/controller/subsystem/criminal_bounties/proc/board_roll_archetype(tier, kind)
	switch(tier)
		if(BOUNTY_TIER_MOST_WANTED)
			return BOUNTY_ARCHETYPE_BOSS
		if(BOUNTY_TIER_WANTED)
			if(kind == BOUNTY_PLACEMENT_NPC_SHIP)
				return BOUNTY_ARCHETYPE_NORMAL
			return prob(BOUNTY_BOARD_WANTED_NORMAL_CHANCE) ? BOUNTY_ARCHETYPE_NORMAL : BOUNTY_ARCHETYPE_MEEK
	return prob(BOUNTY_BOARD_PETTY_MEEK_CHANCE) ? BOUNTY_ARCHETYPE_MEEK : BOUNTY_ARCHETYPE_NORMAL

/**
 * Whether a criminal of `tier` and `archetype` (null: any the tier rolls) may be placed at a
 * `kind` site: Most Wanted and mini-bosses never at a trader outpost (AR-C9, D-A8), petty and meek
 * criminals never aboard a pirate ship (spec 6).
 */
/datum/controller/subsystem/criminal_bounties/proc/board_kind_allowed(kind, tier, archetype)
	switch(kind)
		if(BOUNTY_PLACEMENT_TRADER_OUTPOST)
			return tier != BOUNTY_TIER_MOST_WANTED && archetype != BOUNTY_ARCHETYPE_BOSS
		if(BOUNTY_PLACEMENT_NPC_SHIP)
			return tier != BOUNTY_TIER_PETTY && archetype != BOUNTY_ARCHETYPE_MEEK
		if(BOUNTY_PLACEMENT_PLANET, BOUNTY_PLACEMENT_RUIN)
			return TRUE
	return FALSE

/// Placement kinds a criminal of `tier` and `archetype` may go to, with their weights
/datum/controller/subsystem/criminal_bounties/proc/board_kind_weights(tier, archetype)
	var/static/list/all_weights = list(
		BOUNTY_PLACEMENT_PLANET = BOUNTY_PLACEMENT_WEIGHT_PLANET,
		BOUNTY_PLACEMENT_RUIN = BOUNTY_PLACEMENT_WEIGHT_RUIN,
		BOUNTY_PLACEMENT_NPC_SHIP = BOUNTY_PLACEMENT_WEIGHT_NPC_SHIP,
		BOUNTY_PLACEMENT_TRADER_OUTPOST = BOUNTY_PLACEMENT_WEIGHT_TRADER_OUTPOST,
	)
	var/list/weights = list()
	for(var/kind in all_weights)
		if(board_kind_allowed(kind, tier, archetype))
			weights[kind] = all_weights[kind]
	return weights

/**
 * A kind and a site for a criminal of `tier` (and `archetype`, if already decided): `kind` first
 * if given, then a weighted roll over the other kinds the tier allows unless `only_kind`, never one
 * of `avoid_kinds`; zone band `zone` first, then any band if nothing in it will do. Never
 * `exclude`. Returns list(kind, site), or null.
 */
/datum/controller/subsystem/criminal_bounties/proc/board_pick_placement(tier, archetype, kind, zone, obj/structure/overmap/exclude, only_kind = FALSE, list/avoid_kinds)
	var/list/weights = board_kind_weights(tier, archetype)
	for(var/avoided in avoid_kinds)
		weights -= avoided
	if(kind && !(kind in weights))
		if(only_kind)
			return null
		kind = null
	var/list/first_choice = kind ? list(kind) : list()
	for(var/pass in 1 to 2)
		var/want_zone = pass == 1 ? zone : null
		if(pass == 2 && isnull(zone))
			break
		for(var/try_kind in first_choice)
			var/obj/structure/overmap/site = board_pick_site(try_kind, want_zone, exclude)
			if(site)
				return list(try_kind, site)
		if(only_kind && kind)
			continue
		var/list/remaining = weights.Copy()
		remaining -= first_choice
		while(length(remaining))
			var/try_kind = pick_weight(remaining)
			remaining -= try_kind
			var/obj/structure/overmap/site = board_pick_site(try_kind, want_zone, exclude)
			if(site)
				return list(try_kind, site)
	return null

// ===== THE MISSION BOARD'S WANTED SECTION =====
// The console (voidcrew/modules/missions/mission_board.dm) calls in here from its ui_data(),
// ui_act() and GPS upload. The mugshots go through ui_static_data(), never ui_data() (AR-G1).

/obj/machinery/computer/mission_board
	/// What the Wanted section's static data (the mugshots) was last built from: board_static_signature() for this console's ship
	var/board_static_sent
	/// Record id -> world.time this console first asked for its mugshot (board_mugshots_pending())
	var/list/board_mugshots_asked = list()
	/// Between two warrants printed here
	COOLDOWN_DECLARE(board_warrant_cooldown)

/obj/machinery/computer/mission_board/ui_static_data(mob/user)
	var/list/data = ..()
	var/obj/structure/overmap/ship/ship = get_ship()
	board_static_sent = board_static_signature(ship)
	data["wanted_mugshots"] = board_wanted_mugshots(ship)
	return data

/**
 * What the static data depends on for `ship`: each posting its board lists, with that posting's
 * static_data_serial (bumped when its mugshot is built, an offer is taken or it relists). Another
 * ship's offers and other boards' changes leave it alone (L8).
 */
/obj/machinery/computer/mission_board/proc/board_static_signature(obj/structure/overmap/ship/ship)
	if(!ship)
		return ""
	var/list/parts = list()
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(!posting.is_open() || !posting.board_visible_to(ship) || !posting.record)
			continue
		parts += "[posting.record.id]:[posting.static_data_serial]"
	return parts.Join(",")

/**
 * Record id -> mugshot (a base64 PNG, or "" while it's being built) of every posting `ship`'s board
 * lists, this ship's private offers included: they sit in the same list as everything else. Static
 * data only. P1's bounty_mugshot_asset() never sleeps: the first ask queues the build (one a tick),
 * and the record's ready signal bumps the board so the viewers get it (board_on_mugshot_ready()).
 */
/obj/machinery/computer/mission_board/proc/board_wanted_mugshots(obj/structure/overmap/ship/ship)
	var/list/mugshots = list()
	if(!ship)
		return mugshots
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(!posting.is_open() || !posting.board_visible_to(ship) || !posting.record)
			continue
		mugshots[posting.record.id] = bounty_mugshot_asset(posting.record) || ""
	return mugshots

/**
 * Adds the Wanted section to the board's ui_data() `data` for `ship` (spec 11): `wanted`, every
 * public bounty and this ship's private offers. Looking at the board is what makes the ship's private offers. When the set of
 * postings has changed, the viewers get fresh static data (the mugshots) a moment later.
 */
/obj/machinery/computer/mission_board/proc/board_add_wanted_data(list/data, obj/structure/overmap/ship/ship, mob/user)
	SScriminal_bounties.board_offer_private(ship)
	var/list/wanted = list()
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(!posting.is_open() || !posting.board_visible_to(ship))
			continue
		wanted += list(posting.board_ui_entry(ship, linked_pad))
	data["wanted"] = wanted
	var/signature = board_static_signature(ship)
	// Held while pictures are still being made, so a first look sends the pictures once, not once each
	if(board_static_sent != signature && !board_mugshots_pending(ship))
		board_static_sent = signature
		addtimer(CALLBACK(src, TYPE_PROC_REF(/datum, update_static_data_for_all_viewers)), 1, TIMER_UNIQUE | TIMER_DELETE_ME)
	return data

/**
 * Whether a mugshot `ship`'s board lists is still being made: one this console asked for less than
 * BOUNTY_BOARD_MUGSHOT_WAIT ago that isn't built yet. Asks for any it hasn't asked for. A build that
 * fails is only waited on that long, and the board then sends without it.
 */
/obj/machinery/computer/mission_board/proc/board_mugshots_pending(obj/structure/overmap/ship/ship)
	. = FALSE
	var/list/listed = list()
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(!posting.is_open() || !posting.board_visible_to(ship) || !posting.record)
			continue
		var/datum/bounty_record/record = posting.record
		listed[record.id] = TRUE
		if(record.mugshot)
			continue
		if(!board_mugshots_asked[record.id])
			board_mugshots_asked[record.id] = world.time
			bounty_queue_mugshot(record)
		if(world.time - board_mugshots_asked[record.id] < BOUNTY_BOARD_MUGSHOT_WAIT)
			. = TRUE
	// Forget postings that left the board
	for(var/id in board_mugshots_asked)
		if(!listed[id])
			board_mugshots_asked -= id

/**
 * The Wanted section's actions from the board's ui_act(): hunt_wanted, abandon_wanted,
 * print_warrant and turn_in_wanted, each on params["ref"]. The server checks everything.
 */
/obj/machinery/computer/mission_board/proc/board_wanted_act(action, list/params, obj/structure/overmap/ship/ship, mob/user)
	var/datum/criminal_bounty/posting = locate(params["ref"]) in GLOB.criminal_bounties
	if(!posting || !posting.is_open() || !posting.board_visible_to(ship))
		balloon_alert(user, "bounty not available!")
		return TRUE
	switch(action)
		if("hunt_wanted")
			var/result = posting.hunt(ship)
			if(result == TRUE)
				balloon_alert(user, posting.private_to ? "offer accepted!" : "hunting!")
				playsound(src, 'sound/machines/ding.ogg', 50, TRUE)
			else
				balloon_alert(user, "[result]!")
				playsound(src, 'sound/machines/buzz/buzz-sigh.ogg', 50, TRUE)
		if("abandon_wanted")
			var/result = posting.abandon(ship)
			if(result == TRUE)
				balloon_alert(user, "bounty dropped")
			else
				balloon_alert(user, "[result]!")
		if("print_warrant")
			board_print_warrant(posting, ship, user)
		if("turn_in_wanted")
			var/result = posting.turn_in(linked_pad, ship, user)
			if(islist(result))
				balloon_alert(user, "[result[1]] credits awarded!")
				playsound(src, 'sound/effects/cashregister.ogg', 50, TRUE)
			else
				balloon_alert(user, "[result]!")
				playsound(src, 'sound/machines/buzz/buzz-sigh.ogg', 50, TRUE)
	return TRUE

/// Prints a warrant for `posting` on the linked pad (AR-G2: a cooldown per console, a few per ship per bounty)
/obj/machinery/computer/mission_board/proc/board_print_warrant(datum/criminal_bounty/posting, obj/structure/overmap/ship/ship, mob/user)
	if(!linked_pad || QDELETED(linked_pad))
		balloon_alert(user, "no mission pad linked!")
		return FALSE
	if(!COOLDOWN_FINISHED(src, board_warrant_cooldown))
		balloon_alert(user, "printer busy!")
		return FALSE
	var/ship_key = REF(ship)
	if(posting.board_warrants[ship_key] >= BOUNTY_WARRANT_MAX_PER_SHIP)
		balloon_alert(user, "no more warrants for this one!")
		return FALSE
	var/obj/item/paper/bounty_warrant/warrant = posting.print_warrant(get_turf(linked_pad))
	if(!warrant)
		balloon_alert(user, "printing failed!")
		return FALSE
	posting.board_warrants[ship_key] += 1
	COOLDOWN_START(src, board_warrant_cooldown, BOUNTY_WARRANT_PRINT_COOLDOWN)
	linked_pad.do_teleport_effect()
	balloon_alert(user, "warrant printed")
	return TRUE

#undef BOUNTY_BOARD_MUGSHOT_READY
