/**
 * # Bounty hunting: where criminals are
 *
 * Owner: P5 board. Do not edit this file outside P5.
 *
 * What it owns: the site pickers for planets, space ruins, NPC pirate ships and trader outposts;
 * the spawn pickers inside a loaded site (spec 6); placing the criminal when its site's interior
 * loads, and the same record coming back at the next load when the site unloads with it; what
 * happens when the criminal or its site is destroyed (AR-A6); and the sighting marker
 * (/obj/effect/bounty_sighting, its values and its clock) that hunters' GPS units point to, never
 * the mob (AR-C3).
 *
 * The mission target datums (mission_target.dm) belong to a /datum/mission, so the site hooks are
 * replicated here for a posting: the load signal, the ruin's unload signal, and the site's
 * deletion. A planet sends nothing before it unloads, so a criminal deleted while its planet is
 * unloading counts as gone with the site. The shared vars are declared in bounty_types.dm; a var
 * only P5 uses is here with a `board_` prefix.
 */

/obj/effect/bounty_sighting
	name = "last sighting"
	desc = "Where a wanted criminal was last seen."
	invisibility = INVISIBILITY_ABSTRACT
	anchored = TRUE
	mouse_opacity = MOUSE_OPACITY_TRANSPARENT

/obj/effect/bounty_sighting/Destroy()
	var/datum/criminal_bounty/posting = posting_ref?.resolve()
	if(posting?.marker == src)
		posting.marker = null
	posting_ref = null
	return ..()

// ===== SITES =====

/// The placement kind a site is (BOUNTY_PLACEMENT_*), or null for anything else
/datum/controller/subsystem/criminal_bounties/proc/board_kind_of_site(obj/structure/overmap/site)
	if(istype(site, /obj/structure/overmap/planet))
		return BOUNTY_PLACEMENT_PLANET
	if(istype(site, /obj/structure/overmap/space_ruin))
		return BOUNTY_PLACEMENT_RUIN
	if(istype(site, /obj/structure/overmap/ship/npc/pirate))
		return BOUNTY_PLACEMENT_NPC_SHIP
	if(istype(site, /obj/structure/overmap/trader_outpost))
		return BOUNTY_PLACEMENT_TRADER_OUTPOST
	return null

/// The zone band (ZONE_*) a site is in; green when it can't be told
/datum/controller/subsystem/criminal_bounties/proc/board_site_zone(obj/structure/overmap/site)
	var/zone
	if(istype(site, /obj/structure/overmap/planet))
		var/obj/structure/overmap/planet/planet = site
		zone = planet.get_effective_zone_band()
	else if(istype(site, /obj/structure/overmap/ship/npc))
		var/obj/structure/overmap/ship/npc/npc_ship = site
		zone = npc_ship.pool_zone_type
	if(isnull(zone))
		var/turf/site_turf = get_turf(site)
		if(istype(site_turf, /turf/open/overmap))
			zone = SSovermap_zones?.resolve_zone_for_overmap_turf(site_turf)
	return zone || ZONE_GREEN

/// A site of `kind` in zone band `zone` (null: any), never `exclude`; one no crew is at yet where possible (AR-B5)
/datum/controller/subsystem/criminal_bounties/proc/board_pick_site(kind, zone, obj/structure/overmap/exclude)
	switch(kind)
		if(BOUNTY_PLACEMENT_PLANET)
			return board_pick_planet(zone, exclude)
		if(BOUNTY_PLACEMENT_RUIN)
			return board_pick_ruin(zone, exclude)
		if(BOUNTY_PLACEMENT_NPC_SHIP)
			return board_pick_npc_ship(zone, exclude)
		if(BOUNTY_PLACEMENT_TRADER_OUTPOST)
			return board_pick_trader_outpost(zone, exclude)
	return null

/// Picks from the best of three tiers: unloaded with no bounty on it, then unloaded, then anything
/datum/controller/subsystem/criminal_bounties/proc/board_pick_tiered(list/best, list/good, list/any)
	if(length(best))
		return pick(best)
	if(length(good))
		return pick(good)
	if(length(any))
		return pick(any)
	return null

/// A terrain planet on the chart
/datum/controller/subsystem/criminal_bounties/proc/board_pick_planet(zone, obj/structure/overmap/exclude)
	var/list/best = list()
	var/list/good = list()
	var/list/any = list()
	for(var/obj/structure/overmap/planet/planet as anything in GLOB.overmap_planets)
		if(QDELETED(planet) || planet == exclude || planet.unloading)
			continue
		if(!planet.is_terrain_planet() || !istype(get_turf(planet), /turf/open/overmap))
			continue
		if(!isnull(zone) && board_site_zone(planet) != zone)
			continue
		any += planet
		if(planet.loaded)
			continue
		good += planet
		if(!board_postings_at(planet))
			best += planet
	return board_pick_tiered(best, good, any)

/// A plain space ruin on the chart: never the contested cache, a lich lair or a vestige, a rare one, or one a mission holds
/datum/controller/subsystem/criminal_bounties/proc/board_pick_ruin(zone, obj/structure/overmap/exclude)
	var/list/best = list()
	var/list/good = list()
	var/list/any = list()
	for(var/obj/structure/overmap/space_ruin/ruin as anything in GLOB.space_ruin_signals)
		if(QDELETED(ruin) || ruin == exclude || ruin.type != /obj/structure/overmap/space_ruin)
			continue
		if(ruin.rare || ruin.mission_locked || ruin.mission_exclusive || ruin.concerned)
			continue
		if(!istype(get_turf(ruin), /turf/open/overmap))
			continue
		if(!isnull(zone) && board_site_zone(ruin) != zone)
			continue
		any += ruin
		if(ruin.loaded)
			continue
		good += ruin
		if(!board_postings_at(ruin))
			best += ruin
	return board_pick_tiered(best, good, any)

/// An NPC pirate ship with its crew aboard, not claimed, not abandoned, holding no other bounty
/datum/controller/subsystem/criminal_bounties/proc/board_pick_npc_ship(zone, obj/structure/overmap/exclude)
	var/list/candidates = list()
	for(var/obj/structure/overmap/ship/npc/pirate/npc_ship in SSnpc_ships?.active_ships)
		if(QDELETED(npc_ship) || npc_ship == exclude)
			continue
		if(npc_ship.player_controlled || npc_ship.abandoned || npc_ship.spawner_resolved || !npc_ship.crew_ever_spawned)
			continue
		if(!length(npc_ship.shuttle?.shuttle_areas) || !length(npc_ship.tracked_crew))
			continue
		if(!isnull(zone) && board_site_zone(npc_ship) != zone)
			continue
		if(board_postings_at(npc_ship) >= BOUNTY_MAX_PER_NPC_SHIP)
			continue
		candidates += npc_ship
	return length(candidates) ? pick(candidates) : null

/// A trader outpost with room for another fugitive (AR-C9)
/datum/controller/subsystem/criminal_bounties/proc/board_pick_trader_outpost(zone, obj/structure/overmap/exclude)
	var/list/candidates = list()
	for(var/obj/structure/overmap/trader_outpost/outpost as anything in GLOB.trader_outposts)
		if(QDELETED(outpost) || outpost == exclude)
			continue
		if(!isnull(zone) && board_site_zone(outpost) != zone)
			continue
		if(board_postings_at(outpost) >= BOUNTY_MAX_FUGITIVES_PER_OUTPOST)
			continue
		// P6's own count of fugitives set up to blend in there (AR-C9)
		if(!bounty_outpost_has_room(outpost))
			continue
		candidates += outpost
	return length(candidates) ? pick(candidates) : null

// ===== A POSTING'S SITE =====

/// Places the posting at `new_site`: its name for the card, and the signals that tell it the site loaded, unloaded or went away
/datum/criminal_bounty/proc/board_set_site(obj/structure/overmap/new_site)
	board_unhook_site()
	site_ref = new_site ? WEAKREF(new_site) : null
	board_spawn_failures = 0
	if(!new_site)
		return
	board_site_name = board_describe_site(new_site)
	board_hooked_site = WEAKREF(new_site)
	RegisterSignal(new_site, COMSIG_QDELETING, PROC_REF(board_on_site_deleted))
	if(istype(new_site, /obj/structure/overmap/space_ruin))
		var/obj/structure/overmap/space_ruin/ruin = new_site
		// Keeps the signal on the chart where the card and the waypoint point, as a mission's claim does
		ruin.mission_claims++
		RegisterSignal(ruin, COMSIG_VOIDCREW_RUIN_UNLOADING, PROC_REF(board_on_site_unloading))

/// What the card calls a site
/datum/criminal_bounty/proc/board_describe_site(obj/structure/overmap/where)
	// Without \improper: the text macro shows as a stray character in the UI and the logs
	return where ? format_text(where.name) : null

/// Stops listening to the site it was placed at (safe to call with none)
/datum/criminal_bounty/proc/board_unhook_site(obj/structure/overmap/hooked)
	if(!hooked)
		hooked = board_hooked_site?.resolve()
	board_hooked_site = null
	if(!hooked)
		return
	UnregisterSignal(hooked, list(COMSIG_QDELETING, COMSIG_VOIDCREW_PLANET_LOADED, COMSIG_VOIDCREW_RUIN_UNLOADING, COMSIG_VOIDCREW_SITE_LOAD_FINISHED))
	if(istype(hooked, /obj/structure/overmap/space_ruin))
		var/obj/structure/overmap/space_ruin/ruin = hooked
		ruin.mission_claims = max(ruin.mission_claims - 1, 0)

/// Whether the site's interior is there to place a criminal in now
/datum/criminal_bounty/proc/board_site_loaded(obj/structure/overmap/where)
	if(QDELETED(where))
		return FALSE
	if(istype(where, /obj/structure/overmap/planet))
		var/obj/structure/overmap/planet/planet = where
		return planet.loaded && planet.mapzone && !planet.unloading && !planet.loading
	if(istype(where, /obj/structure/overmap/space_ruin))
		var/obj/structure/overmap/space_ruin/ruin = where
		return ruin.loaded && ruin.ruin_bottom_left && !ruin.concerned
	if(istype(where, /obj/structure/overmap/trader_outpost))
		var/obj/structure/overmap/trader_outpost/outpost = where
		return outpost.loaded && outpost.template_bottom_left
	if(istype(where, /obj/structure/overmap/ship))
		var/obj/structure/overmap/ship/npc_ship = where
		return length(npc_ship.shuttle?.shuttle_areas)
	return FALSE

/// Whether the site is tearing its interior down (a planet mid-unload, a ruin that gave its interior back)
/datum/criminal_bounty/proc/board_site_unloading(obj/structure/overmap/where)
	if(istype(where, /obj/structure/overmap/planet))
		var/obj/structure/overmap/planet/planet = where
		return planet.unloading || !planet.loaded
	if(istype(where, /obj/structure/overmap/space_ruin))
		var/obj/structure/overmap/space_ruin/ruin = where
		return !ruin.loaded
	return FALSE

/// The site's footprint as list(min_x, min_y, max_x, max_y, z): the criminal's leash, or null for a pirate ship (it moves)
/datum/criminal_bounty/proc/board_site_bounds(obj/structure/overmap/where)
	if(istype(where, /obj/structure/overmap/trader_outpost))
		var/obj/structure/overmap/trader_outpost/outpost = where
		var/turf/bottom_left = outpost.template_bottom_left
		if(!bottom_left || !outpost.outpost_template)
			return null
		return list(bottom_left.x, bottom_left.y, bottom_left.x + outpost.outpost_template.width - 1, bottom_left.y + outpost.outpost_template.height - 1, bottom_left.z)
	if(istype(where, /obj/structure/overmap/planet) || istype(where, /obj/structure/overmap/space_ruin))
		var/datum/map_footprint/footprint = where.get_interior_footprint()
		if(footprint && !isnull(footprint.low_x) && footprint.z_value)
			return list(footprint.low_x, footprint.low_y, footprint.high_x, footprint.high_y, footprint.z_value)
		if(istype(where, /obj/structure/overmap/planet))
			var/obj/structure/overmap/planet/planet = where
			var/datum/space_level/level = length(planet.mapzone?.z_levels) ? planet.mapzone.z_levels[1] : null
			if(level)
				return list(level.low_x, level.low_y, level.high_x, level.high_y, level.z_value)
	return null

/// Whether `spot` is on the site
/datum/criminal_bounty/proc/board_site_contains(obj/structure/overmap/where, turf/spot)
	if(!where || !spot)
		return FALSE
	if(istype(where, /obj/structure/overmap/ship))
		var/obj/structure/overmap/ship/npc_ship = where
		return npc_ship.is_aboard(spot)
	var/list/bounds = board_site_bounds(where)
	return bounds && bounty_bounds_contain(bounds, spot)

/// Whether `spot` lies in `bounds`, list(min_x, min_y, max_x, max_y, z)
/proc/bounty_bounds_contain(list/bounds, turf/spot)
	if(length(bounds) < 5 || !spot)
		return FALSE
	return spot.z == bounds[5] && spot.x >= bounds[1] && spot.x <= bounds[3] && spot.y >= bounds[2] && spot.y <= bounds[4]

/// Waits for the site's interior to load, then places the criminal
/datum/criminal_bounty/proc/board_wait_for_load(obj/structure/overmap/where)
	if(QDELETED(where))
		return
	if(istype(where, /obj/structure/overmap/trader_outpost))
		RegisterSignal(where, COMSIG_VOIDCREW_SITE_LOAD_FINISHED, PROC_REF(board_on_site_loaded), override = TRUE)
	else if(istype(where, /obj/structure/overmap/planet) || istype(where, /obj/structure/overmap/space_ruin))
		RegisterSignal(where, COMSIG_VOIDCREW_PLANET_LOADED, PROC_REF(board_on_site_loaded), override = TRUE)

/datum/criminal_bounty/proc/board_on_site_loaded(datum/source, loaded)
	SIGNAL_HANDLER
	if(istype(source, /obj/structure/overmap/trader_outpost) && !loaded)
		return
	UnregisterSignal(source, list(COMSIG_VOIDCREW_PLANET_LOADED, COMSIG_VOIDCREW_SITE_LOAD_FINISHED))
	board_arm()

/// A ruin gives its interior back: whatever the bounty put there goes with it, and the same criminal comes back at the next load
/datum/criminal_bounty/proc/board_on_site_unloading(datum/source)
	SIGNAL_HANDLER
	if(!is_open() || board_relisting)
		return
	var/mob/living/basic/bounty_criminal/criminal = criminal()
	// A criminal carried off the site (aboard a ship) is not the site's to take
	if(criminal && !board_site_contains(source, get_turf(criminal)))
		return
	board_site_took_criminal(criminal)

/**
 * The site's interior went away with the criminal in it (spec 6: unload): the criminal, its
 * companions and the marker go, the posting stays open, and the same record comes back at full
 * health on the next load. Cuffs don't survive, but the worst state it reached does (12.1): it
 * never pays more than it did before, and a dead one comes back as proof of death.
 */
/datum/criminal_bounty/proc/board_site_took_criminal(mob/living/basic/bounty_criminal/criminal)
	board_note_worst(criminal)
	board_detach_criminal()
	var/list/extras = list()
	for(var/datum/weakref/ref as anything in companions)
		var/mob/living/companion = ref?.resolve()
		if(!QDELETED(companion))
			extras += companion
	companions.Cut()
	if(!QDELETED(criminal))
		extras += criminal
	for(var/mob/living/leaving as anything in extras)
		ADD_TRAIT(leaving, TRAIT_BOUNTY_REMOVED, BOUNTY_PAD_TRAIT)
		qdel(leaving)
	board_drop_marker()
	board_wait_for_load(site())
	log_game("BOUNTY: the [board_log_name()] waits for its site to load again")

/// Remembers the worst state `criminal` reached, for whatever body of it comes next (12.1)
/datum/criminal_bounty/proc/board_note_worst(mob/living/basic/bounty_criminal/criminal)
	if(!criminal)
		return
	var/state = criminal.stat == DEAD ? BOUNTY_STATE_DEAD : criminal.worst_state
	if(bounty_state_rank(state) < bounty_state_rank(board_worst_state))
		board_worst_state = state

/// The site is gone (a ruin respawning elsewhere, a pirate ship destroyed or despawned)
/datum/criminal_bounty/proc/board_on_site_deleted(datum/source)
	SIGNAL_HANDLER
	board_unhook_site(source)
	site_ref = null
	if(!is_open() || board_relisting)
		return
	// A criminal (or its proof) still standing somewhere keeps the bounty where it is; one still
	// aboard a dying pirate ship goes with it, and its own deletion decides what is left
	if(criminal() || board_proof())
		return
	relist(placement_kind == BOUNTY_PLACEMENT_NPC_SHIP ? "was lost with the [board_site_name || "ship"]" : "has moved on")

// ===== THE CRIMINAL =====

/**
 * Places the criminal if it can now: the posting is open and not relisting, a private offer has
 * been taken, there is no criminal, body or proof already, the site's interior is loaded (else it
 * waits for the load), and the server has room under BOUNTY_MAX_LIVE_CRIMINALS counting spawns
 * still under way (else the board tries again next tick). A pirate ship taken, cleared or
 * abandoned since the posting went up is no place for it any more: the bounty moves on. The spawn
 * runs async, since picking the spot and dressing the look can yield. Returns TRUE if a spawn
 * started.
 */
/datum/criminal_bounty/proc/board_arm()
	if(!is_open() || board_relisting || board_spawning)
		return FALSE
	if(criminal() || board_proof())
		return FALSE
	if(private_to && !board_accepted)
		return FALSE
	var/obj/structure/overmap/where = site()
	if(!where)
		return FALSE
	if(placement_kind == BOUNTY_PLACEMENT_NPC_SHIP && !board_npc_ship_usable(where))
		relist("has moved on")
		return FALSE
	if(!board_site_loaded(where))
		board_wait_for_load(where)
		return FALSE
	if(SScriminal_bounties.board_criminal_slots_used() >= BOUNTY_MAX_LIVE_CRIMINALS)
		return FALSE
	board_spawning = TRUE
	INVOKE_ASYNC(src, PROC_REF(board_spawn_criminal), where)
	return TRUE

/// Whether a pirate ship can still hold a criminal: not claimed by players, not abandoned or resolved, its crew still aboard (M3)
/datum/criminal_bounty/proc/board_npc_ship_usable(obj/structure/overmap/ship/npc/npc_ship)
	if(!istype(npc_ship) || QDELETED(npc_ship))
		return FALSE
	if(npc_ship.player_controlled || npc_ship.abandoned || npc_ship.spawner_resolved)
		return FALSE
	return length(npc_ship.tracked_crew) > 0

/// Whether a spawn at `where` that has yielded is still wanted: the posting open at the same loaded site, with nothing placed meanwhile
/datum/criminal_bounty/proc/board_spawn_still_wanted(obj/structure/overmap/where)
	if(!is_open() || board_relisting || site() != where || !board_site_loaded(where))
		return FALSE
	return !criminal() && !board_proof()

/// Picks the spot at `where` and places the criminal there (board_place_at()). Runs async from board_arm().
/datum/criminal_bounty/proc/board_spawn_criminal(obj/structure/overmap/where)
	var/list/spot = board_pick_spawn(where)
	// The picker can yield: a pirate ship may have been taken meanwhile (M3)
	if(placement_kind == BOUNTY_PLACEMENT_NPC_SHIP && !board_npc_ship_usable(where))
		board_spawning = FALSE
		if(is_open() && !board_relisting)
			relist("has moved on")
		return null
	if(spot && !board_spawn_still_wanted(where))
		board_spawning = FALSE
		return null
	var/atom/movable/placed = spot ? board_place_at(spot["turf"], spot["activity"], spot["anchor"], where) : null
	board_spawning = FALSE
	if(!placed && is_open() && !board_relisting && !criminal() && !board_proof())
		board_spawn_failures++
		// A site that never has room (or a spawn that keeps failing) gives the bounty to another site
		if(board_spawn_failures >= BOUNTY_SPAWN_ATTEMPTS)
			log_game("BOUNTY: the [board_log_name()] found no place to spawn in [board_spawn_failures] tries")
			relist("has moved on")
	return placed

/**
 * Places what the bounty has at `spot`, at site `where` (null for a test or an admin): its criminal,
 * doing `activity` at `anchor` (board_adopt_criminal()), or, when an earlier body of theirs died,
 * its proof of death: a dead criminal never comes back alive (12.1). Returns what it placed, or
 * null. Spawning can sleep; a body spawned for a posting that changed meanwhile is thrown away
 * unseen, and that is no death.
 */
/datum/criminal_bounty/proc/board_place_at(turf/spot, activity, atom/anchor, obj/structure/overmap/where)
	if(!spot || !is_open() || board_relisting)
		return null
	if(board_worst_state == BOUNTY_STATE_DEAD)
		return board_place_proof(spot)
	var/mob/living/basic/bounty_criminal/criminal = spawn_bounty_criminal(record, spot, src)
	board_spawning = FALSE
	if(QDELETED(criminal))
		return null
	var/still_wanted = where ? board_spawn_still_wanted(where) : (is_open() && !board_relisting && !criminal() && !board_proof())
	if(!still_wanted)
		ADD_TRAIT(criminal, TRAIT_BOUNTY_REMOVED, BOUNTY_PAD_TRAIT)
		qdel(criminal)
		return null
	if(!board_adopt_criminal(criminal, where, activity, anchor))
		return null
	return criminal

/// The proof of death of a criminal that died before its site unloaded, laid near where it would have stood
/datum/criminal_bounty/proc/board_place_proof(turf/spot)
	if(!is_open() || board_proof() || !spot)
		return null
	var/obj/item/bounty_proof/proof = new(bounty_proof_spot(spot))
	proof.posting_ref = WEAKREF(src)
	proof.record = record
	if(record?.name)
		proof.name = "evidence tag ([record.name])"
	board_attach_proof(proof)
	return proof

/**
 * Makes `criminal` this posting's, placed at `where`: tracked by weakref, leashed to the site,
 * friends with the site's own (the pirates aboard their ship, the fauna on a planet), companions
 * for a normal criminal, then what they are doing (`activity`, at `anchor`), and the sighting (or
 * the blend at a trader outpost: P6's setup_outpost_blend()). Also used by tests and the admin panel
 * to adopt a criminal spawned by hand.
 */
/datum/criminal_bounty/proc/board_adopt_criminal(mob/living/basic/bounty_criminal/criminal, obj/structure/overmap/where, activity, atom/anchor)
	if(QDELETED(criminal))
		return FALSE
	board_detach_criminal()
	criminal_ref = WEAKREF(criminal)
	criminal.posting_ref = WEAKREF(src)
	if(!criminal.record)
		criminal.record = record
	RegisterSignal(criminal, COMSIG_QDELETING, PROC_REF(board_on_criminal_deleted))
	board_spawn_failures = 0
	// Whatever an earlier body of theirs went through still counts (12.1). Only ever made worse.
	criminal.body_restore_worst_state(board_worst_state)
	if(where)
		criminal.site_bounds = board_site_bounds(where)
		board_add_site_factions(criminal, where)
	if(record?.archetype == BOUNTY_ARCHETYPE_NORMAL && placement_kind != BOUNTY_PLACEMENT_TRADER_OUTPOST)
		board_spawn_companions(criminal)
	criminal.start_activity(activity || board_default_activity(), anchor)
	if(placement_kind == BOUNTY_PLACEMENT_TRADER_OUTPOST)
		// P6 dresses it as a patron and brings its decoys. Refused (no room, say), it can't stay here.
		if(!setup_outpost_blend())
			log_game("BOUNTY: the [board_log_name()] could not blend in at [board_site_name]")
			board_detach_criminal()
			ADD_TRAIT(criminal, TRAIT_BOUNTY_REMOVED, BOUNTY_PAD_TRAIT)
			qdel(criminal)
			relist("has moved on")
			return FALSE
		// Closed or relisted while the setup ran: whoever it placed walks out again
		if(!is_open() || board_relisting)
			outpost_release_site()
			board_remove_mobs(null, board_relisting)
			return FALSE
	else
		board_move_sighting(TRUE)
	log_game("BOUNTY: the [board_log_name()] placed its criminal at [AREACOORD(criminal)]")
	return TRUE

/// Stops tracking the criminal without touching it
/datum/criminal_bounty/proc/board_detach_criminal()
	var/mob/living/basic/bounty_criminal/criminal = criminal()
	if(criminal)
		UnregisterSignal(criminal, COMSIG_QDELETING)
	criminal_ref = null

/// The activity for a placement when the spawn picker gave none
/datum/criminal_bounty/proc/board_default_activity()
	switch(placement_kind)
		if(BOUNTY_PLACEMENT_RUIN)
			return BOUNTY_ACTIVITY_LOOT
		if(BOUNTY_PLACEMENT_NPC_SHIP)
			return BOUNTY_ACTIVITY_CHAT
		if(BOUNTY_PLACEMENT_TRADER_OUTPOST)
			return BOUNTY_ACTIVITY_BLEND
	return BOUNTY_ACTIVITY_EXPLORE

/// Companions for a normal criminal: 0 to BOUNTY_MAX_COMPANIONS in every zone (12.3 C9: the zone scales pay, never the fight), within the server's cap
/datum/criminal_bounty/proc/board_spawn_companions(mob/living/basic/bounty_criminal/criminal)
	var/count = rand(0, BOUNTY_MAX_COMPANIONS)
	// The crew aboard a pirate ship are company enough
	if(placement_kind == BOUNTY_PLACEMENT_NPC_SHIP)
		count = min(count, 1)
	count = min(count, BOUNTY_MAX_LIVE_COMPANIONS - SScriminal_bounties.board_live_companions())
	if(count <= 0)
		return list()
	var/list/spawned = criminal.spawn_companions(count)
	for(var/mob/living/companion in spawned)
		companions |= WEAKREF(companion)
	return spawned

/**
 * Makes the criminal a friend of the site's own, so it doesn't fight the hostiles native to where
 * it hides (spec 3): the crew's factions aboard a pirate ship, the planet's and ruins' hostiles.
 * The neutral faction every player has is never added.
 */
/datum/criminal_bounty/proc/board_add_site_factions(mob/living/basic/bounty_criminal/criminal, obj/structure/overmap/where)
	var/list/added = list(FACTION_HOSTILE)
	if(istype(where, /obj/structure/overmap/ship/npc))
		var/obj/structure/overmap/ship/npc/npc_ship = where
		added |= npc_ship.faction
		for(var/mob/living/crewmember as anything in npc_ship.tracked_crew)
			if(!QDELETED(crewmember))
				added |= crewmember.faction
				break
	else if(istype(where, /obj/structure/overmap/planet))
		added |= FACTION_MINING
	else if(istype(where, /obj/structure/overmap/space_ruin))
		added |= list(FACTION_MINING, FACTION_PIRATE, ROLE_SYNDICATE)
	else if(istype(where, /obj/structure/overmap/trader_outpost))
		added = list()
	added -= FACTION_NEUTRAL
	for(var/faction_name in added)
		if(!istext(faction_name) || findtext(faction_name, "\["))
			continue
		criminal.faction |= faction_name

/// The criminal is being deleted: gone with its site (it comes back on the next load), or destroyed (proof, or a relist)
/datum/criminal_bounty/proc/board_on_criminal_deleted(datum/source)
	SIGNAL_HANDLER
	UnregisterSignal(source, COMSIG_QDELETING)
	if(source.weak_reference != criminal_ref)
		return
	criminal_ref = null
	if(!is_open() || board_relisting)
		return
	var/obj/structure/overmap/where = site()
	var/turf/spot = get_turf(source)
	if(where && board_site_unloading(where) && (!spot || board_site_contains(where, spot)))
		board_note_worst(source)
		board_site_took_criminal()
		return
	// Destroyed. Its proof may be on the way (bounty_drop_proof()), so look a moment later.
	if(board_lost_timer)
		deltimer(board_lost_timer)
	board_lost_timer = addtimer(CALLBACK(src, PROC_REF(board_check_lost)), 1 SECONDS, TIMER_STOPPABLE | TIMER_DELETE_ME)

/**
 * The board's backstop for a criminal nobody can reach any more (H1): in a chasm's depths, or with
 * no turf at all (nullspace). Proof of death at the edge where it can be had; otherwise the body is
 * let go and the bounty lists at a new site. Returns TRUE if it acted.
 */
/datum/criminal_bounty/proc/board_check_unreachable()
	var/mob/living/basic/bounty_criminal/criminal = criminal()
	if(!criminal)
		return FALSE
	var/in_chasm = istype(criminal.loc, /obj/effect/abstract/chasm_storage)
	if(!in_chasm && get_turf(criminal))
		return FALSE
	if(in_chasm && !board_proof() && bounty_drop_proof(criminal))
		return TRUE
	board_detach_criminal()
	ADD_TRAIT(criminal, TRAIT_BOUNTY_REMOVED, BOUNTY_PAD_TRAIT)
	if(board_proof())
		return TRUE
	relist("has vanished")
	return TRUE

/// A moment after the criminal was destroyed: with no proof left either, the bounty relists at a new site (AR-A6)
/datum/criminal_bounty/proc/board_check_lost()
	board_lost_timer = null
	if(!is_open() || board_relisting)
		return
	if(criminal() || board_proof())
		return
	relist(placement_kind == BOUNTY_PLACEMENT_NPC_SHIP && !site() ? "was lost with the [board_site_name || "ship"]" : "has vanished")

// ===== SPAWN PICKERS =====

/**
 * Where in the loaded site the criminal appears, and what it is doing: list("turf", "activity",
 * "anchor"), or null if the site has no fit spot right now. Planets: near a ruin landmark to
 * explore, or open ground to camp. Ruins: near a loot crate or closet to loot. Pirate ships: away
 * from the helm, chatting with the crew or looting. Trader outposts: on the concourse, blending in.
 */
/datum/criminal_bounty/proc/board_pick_spawn(obj/structure/overmap/where)
	switch(placement_kind)
		if(BOUNTY_PLACEMENT_PLANET)
			return board_pick_planet_spawn(where)
		if(BOUNTY_PLACEMENT_RUIN)
			return board_pick_ruin_spawn(where)
		if(BOUNTY_PLACEMENT_NPC_SHIP)
			return board_pick_npc_ship_spawn(where)
		if(BOUNTY_PLACEMENT_TRADER_OUTPOST)
			return board_pick_outpost_spawn(where)
	return null

/**
 * Whether a criminal may appear on `spot`: open, not space, water, lava, a chasm or an open drop,
 * nothing dense on it, and never inside a ship's area (a ship takes off with what is aboard).
 * `allow_ship` lets a pirate ship's own floor through.
 */
/proc/bounty_spawn_turf_ok(turf/spot, allow_ship = FALSE)
	if(!isopenturf(spot) || isspaceturf(spot))
		return FALSE
	if(istype(spot, /turf/open/lava) || istype(spot, /turf/open/chasm) || istype(spot, /turf/open/water) || istype(spot, /turf/open/openspace))
		return FALSE
	if(!allow_ship && istype(get_area(spot), /area/shuttle))
		return FALSE
	if(spot.is_blocked_turf(exclude_mobs = TRUE))
		return FALSE
	return TRUE

/// The turfs of every living player on z-level `z_level`, for the clearance checks below
/proc/bounty_player_turfs(z_level)
	var/list/turfs = list()
	for(var/mob/living/player in GLOB.player_list)
		if(player.stat == DEAD)
			continue
		var/turf/player_turf = get_turf(player)
		if(player_turf?.z == z_level)
			turfs += player_turf
	return turfs

/**
 * Whether no living player is within `radius` tiles of `spot` (AR-B5, C10). Loops over many spots
 * pass `players`, bounty_player_turfs() of the spot's level, worked out once.
 */
/proc/bounty_turf_clear_of_players(turf/spot, radius = BOUNTY_PLAYER_CLEARANCE, list/players)
	if(!spot)
		return FALSE
	if(isnull(players))
		players = bounty_player_turfs(spot.z)
	for(var/turf/player_turf as anything in players)
		if(get_dist(player_turf, spot) <= radius)
			return FALSE
	return TRUE

/// Whether `spot` has room for a small camp: the 3x3 around it is clear ground
/proc/bounty_turf_has_room(turf/spot)
	for(var/turf/around as anything in RANGE_TURFS(1, spot))
		if(!bounty_spawn_turf_ok(around))
			return FALSE
	return TRUE

/**
 * A spawn turf within `radius` of `center`, inside `bounds` (list(min_x, min_y, max_x, max_y, z),
 * or null), passing bounty_spawn_turf_ok(); one no player is near if there is one.
 */
/proc/bounty_turf_near(turf/center, radius, list/bounds, allow_ship = FALSE, obj/structure/overmap/ship/aboard)
	if(!center)
		return null
	var/list/players = bounty_player_turfs(center.z)
	var/list/fits = list()
	var/list/clear = list()
	for(var/turf/spot as anything in RANGE_TURFS(radius, center))
		if(bounds && !bounty_bounds_contain(bounds, spot))
			continue
		if(aboard && !aboard.is_aboard(spot))
			continue
		if(!bounty_spawn_turf_ok(spot, allow_ship))
			continue
		fits += spot
		if(bounty_turf_clear_of_players(spot, BOUNTY_PLAYER_CLEARANCE, players))
			clear += spot
	if(length(clear))
		return pick(clear)
	return length(fits) ? pick(fits) : null

/// A random spawn turf in `bounds`, sampled; `need_room` wants a 3x3 of clear ground. One no player is near if the samples find one.
/proc/bounty_sample_bounds(list/bounds, need_room = FALSE, tries = 60)
	if(length(bounds) < 5 || bounds[1] > bounds[3] || bounds[2] > bounds[4])
		return null
	var/list/players = bounty_player_turfs(bounds[5])
	var/turf/fallback
	for(var/i in 1 to tries)
		var/turf/spot = locate(rand(bounds[1], bounds[3]), rand(bounds[2], bounds[4]), bounds[5])
		if(!bounty_spawn_turf_ok(spot))
			continue
		if(need_room && !bounty_turf_has_room(spot))
			continue
		if(bounty_turf_clear_of_players(spot, BOUNTY_PLAYER_CLEARANCE, players))
			return spot
		fallback ||= spot
	return fallback

/// The part of a planet a criminal may appear in: its site less a margin, above the dock strip (the mission field rule)
/datum/criminal_bounty/proc/board_planet_spawn_bounds(obj/structure/overmap/planet/planet)
	var/list/site = board_site_bounds(planet)
	if(!site || !length(planet.mapzone?.z_levels))
		return null
	var/datum/space_level/level = planet.mapzone.z_levels[1]
	var/min_x = site[1] + BOUNTY_PLANET_MARGIN
	var/max_x = site[3] - BOUNTY_PLANET_MARGIN
	var/min_y = site[2] + BOUNTY_PLANET_MARGIN
	var/max_y = site[4] - BOUNTY_PLANET_MARGIN
	// A landing ship gibs whatever stands on its berth: stay above the dock strip
	var/dock_strip_top = level ? planet.get_dock_strip_top_y(level) : null
	if(!isnull(dock_strip_top) && dock_strip_top + 1 < max_y)
		min_y = max(min_y, dock_strip_top + 1)
	if(min_x > max_x || min_y > max_y)
		return null
	return list(min_x, min_y, max_x, max_y, site[5])

/// Ruin landmarks on the site: the planet's ruins, the places worth exploring
/datum/criminal_bounty/proc/board_site_landmarks(obj/structure/overmap/where, list/bounds)
	var/list/marks = list()
	for(var/obj/effect/landmark/ruin/mark as anything in GLOB.ruin_landmarks)
		if(QDELETED(mark))
			continue
		var/turf/mark_turf = get_turf(mark)
		if(mark_turf && bounty_bounds_contain(bounds, mark_turf))
			marks += mark
	return marks

/// A planet spawn: exploring near one of its ruins, or camping on open ground
/datum/criminal_bounty/proc/board_pick_planet_spawn(obj/structure/overmap/planet/planet)
	var/list/bounds = board_planet_spawn_bounds(planet)
	if(!bounds)
		return null
	var/camp = record?.archetype == BOUNTY_ARCHETYPE_NORMAL && prob(50)
	if(!camp)
		var/list/marks = board_site_landmarks(planet, bounds)
		for(var/i in 1 to min(length(marks), 5))
			var/obj/effect/landmark/ruin/mark = pick_n_take(marks)
			var/turf/near = bounty_turf_near(get_turf(mark), BOUNTY_ANCHOR_RADIUS + 2, bounds)
			if(near)
				return list("turf" = near, "activity" = BOUNTY_ACTIVITY_EXPLORE, "anchor" = mark)
	var/turf/ground = bounty_sample_bounds(bounds, need_room = camp)
	if(!ground && camp)
		camp = FALSE
		ground = bounty_sample_bounds(bounds)
	if(!ground)
		return null
	return list("turf" = ground, "activity" = camp ? BOUNTY_ACTIVITY_CAMP : BOUNTY_ACTIVITY_EXPLORE, "anchor" = camp ? ground : null)

/// A ruin spawn: within reach of a loot crate or a closet, looting it
/datum/criminal_bounty/proc/board_pick_ruin_spawn(obj/structure/overmap/space_ruin/ruin)
	if(!ruin.loaded || !ruin.ruin_bottom_left || !ruin.ruin_template?.width || !ruin.ruin_template?.height)
		return null
	var/turf/bottom_left = ruin.ruin_bottom_left
	var/list/bounds = list(bottom_left.x, bottom_left.y, bottom_left.x + ruin.ruin_template.width - 1, bottom_left.y + ruin.ruin_template.height - 1, bottom_left.z)
	var/list/site = board_site_bounds(ruin)
	if(site)
		bounds[1] = max(bounds[1], site[1])
		bounds[2] = max(bounds[2], site[2])
		bounds[3] = min(bounds[3], site[3])
		bounds[4] = min(bounds[4], site[4])
	var/turf/low = locate(bounds[1], bounds[2], bounds[5])
	var/turf/high = locate(bounds[3], bounds[4], bounds[5])
	if(!low || !high)
		return null
	var/list/loot_crates = list()
	var/list/closets = list()
	for(var/turf/spot as anything in block(low, high))
		CHECK_TICK
		for(var/obj/structure/closet/box in spot)
			if(istype(box, /obj/structure/closet/crate/zone_loot))
				loot_crates += box
			else
				closets += box
	var/list/order = shuffle(loot_crates) + shuffle(closets)
	for(var/i in 1 to min(length(order), 8))
		var/obj/structure/closet/box = order[i]
		var/turf/near = bounty_turf_near(get_turf(box), BOUNTY_ANCHOR_RADIUS, bounds)
		if(near)
			return list("turf" = near, "activity" = BOUNTY_ACTIVITY_LOOT, "anchor" = box)
	var/turf/inside = bounty_sample_bounds(bounds)
	if(!inside)
		return null
	return list("turf" = inside, "activity" = BOUNTY_ACTIVITY_LOOT, "anchor" = null)

/// A pirate ship spawn: on an open floor BOUNTY_NPC_SHIP_HELM_DISTANCE tiles or more from every helm, chatting with the crew or looting its lockers
/datum/criminal_bounty/proc/board_pick_npc_ship_spawn(obj/structure/overmap/ship/npc/npc_ship)
	if(!length(npc_ship.shuttle?.shuttle_areas))
		return null
	var/list/helms = npc_ship.get_ship_machines(/obj/machinery/computer/helm)
	var/turf/chosen
	var/turf/fallback
	var/list/players
	for(var/i in 1 to 40)
		var/turf/spot = npc_ship.get_random_open_ship_turf()
		if(!spot || !bounty_spawn_turf_ok(spot, allow_ship = TRUE) || !board_clear_of_helms(spot, helms))
			continue
		players ||= bounty_player_turfs(spot.z)
		if(bounty_turf_clear_of_players(spot, BOUNTY_PLAYER_CLEARANCE, players))
			chosen = spot
			break
		fallback ||= spot
	chosen ||= fallback
	if(!chosen)
		return null
	if(prob(50))
		for(var/mob/living/crewmember as anything in npc_ship.tracked_crew)
			if(QDELETED(crewmember) || crewmember.stat == DEAD || !npc_ship.is_aboard(crewmember))
				continue
			var/turf/beside = bounty_turf_near(get_turf(crewmember), 2, null, allow_ship = TRUE, aboard = npc_ship)
			if(beside && board_clear_of_helms(beside, helms))
				return list("turf" = beside, "activity" = BOUNTY_ACTIVITY_CHAT, "anchor" = crewmember)
	var/list/lockers = list()
	for(var/area/ship_area as anything in npc_ship.shuttle.shuttle_areas)
		for(var/obj/structure/closet/box in ship_area)
			lockers += box
	for(var/i in 1 to min(length(lockers), 5))
		var/obj/structure/closet/box = pick_n_take(lockers)
		var/turf/near = bounty_turf_near(get_turf(box), BOUNTY_ANCHOR_RADIUS, null, allow_ship = TRUE, aboard = npc_ship)
		if(near && board_clear_of_helms(near, helms))
			return list("turf" = near, "activity" = BOUNTY_ACTIVITY_LOOT, "anchor" = box)
	return list("turf" = chosen, "activity" = BOUNTY_ACTIVITY_CHAT, "anchor" = null)

/// Whether `spot` is BOUNTY_NPC_SHIP_HELM_DISTANCE tiles or more from each of `helms`
/datum/criminal_bounty/proc/board_clear_of_helms(turf/spot, list/helms)
	for(var/obj/machinery/computer/helm/helm as anything in helms)
		if(helm.z == spot.z && get_dist(helm, spot) < BOUNTY_NPC_SHIP_HELM_DISTANCE)
			return FALSE
	return TRUE

/**
 * A trader outpost spawn: a free tile of the floor customers walk (never behind a counter, in a
 * staff room or on the hangar lift), out of every player's sight where it can be (AR-C6, C10).
 * P6's decoy picker, so the fugitive stands where its decoys stand. It blends in (P6's setup).
 */
/datum/criminal_bounty/proc/board_pick_outpost_spawn(obj/structure/overmap/trader_outpost/outpost)
	if(!outpost.template_bottom_left || !outpost.outpost_template)
		return null
	var/list/spots = bounty_outpost_spawn_spots(outpost, 1, null)
	if(!length(spots))
		return null
	return list("turf" = spots[1], "activity" = BOUNTY_ACTIVITY_BLEND, "anchor" = null)

// ===== SIGHTINGS =====

/**
 * Moves the sighting marker to near the criminal: every BOUNTY_SIGHTING_INTERVAL (or now, when
 * `force`d), to the criminal's turf plus up to BOUNTY_SIGHTING_OFFSET tiles either way. It stays
 * put while the criminal hides. None at trader outposts: there, finding them is the game.
 */
/datum/criminal_bounty/proc/board_move_sighting(force = FALSE)
	if(placement_kind == BOUNTY_PLACEMENT_TRADER_OUTPOST)
		board_drop_marker()
		return FALSE
	var/mob/living/basic/bounty_criminal/criminal = criminal()
	if(!criminal)
		return FALSE
	if(!force && world.time < board_next_sighting)
		return FALSE
	board_next_sighting = world.time + BOUNTY_SIGHTING_INTERVAL
	if(criminal.hidden && marker && !QDELETED(marker))
		return FALSE
	var/turf/center = get_turf(criminal)
	if(!center)
		return FALSE
	var/turf/spot = board_sighting_spot(center)
	last_seen = center
	if(!marker || QDELETED(marker))
		marker = new(spot)
		marker.posting_ref = WEAKREF(src)
		board_push_gps()
	else
		marker.forceMove(spot)
	board_ping_gps()
	return TRUE

/**
 * A new sighting is in: whoever holds a GPS unit its beacon was uploaded to (in a hand, a pocket, a
 * bag, or a MOD suit they wear) hears a soft radar ping and sees a "new sighting" balloon (P9).
 * A GPS switched off or scrambled stays quiet. Returns how many holders were told.
 */
/datum/criminal_bounty/proc/board_ping_gps()
	var/told = 0
	for(var/datum/weakref/unit_ref as anything in board_gps_units)
		var/datum/component/gps/item/unit = unit_ref?.resolve()
		if(!unit || !unit.tracking || unit.emped || !LAZYACCESS(unit.linked_mission_signals, board_gps_tag))
			continue
		var/mob/living/holder = get(unit.parent, /mob/living)
		if(!holder || holder.stat == DEAD)
			continue
		holder.playsound_local(get_turf(holder), 'sound/machines/radar-ping.ogg', 30, FALSE)
		holder.balloon_alert(holder, "new sighting")
		told++
	return told

/// A blurred spot near `center`: up to BOUNTY_SIGHTING_OFFSET tiles off, kept on the site when the criminal is on it
/datum/criminal_bounty/proc/board_sighting_spot(turf/center)
	var/list/bounds = null
	var/obj/structure/overmap/where = site()
	if(where && !istype(where, /obj/structure/overmap/ship))
		bounds = board_site_bounds(where)
		if(bounds && !bounty_bounds_contain(bounds, center))
			bounds = null
	var/new_x = center.x + rand(-BOUNTY_SIGHTING_OFFSET, BOUNTY_SIGHTING_OFFSET)
	var/new_y = center.y + rand(-BOUNTY_SIGHTING_OFFSET, BOUNTY_SIGHTING_OFFSET)
	if(bounds)
		new_x = clamp(new_x, bounds[1], bounds[3])
		new_y = clamp(new_y, bounds[2], bounds[4])
	new_x = clamp(new_x, 1, world.maxx)
	new_y = clamp(new_y, 1, world.maxy)
	return locate(new_x, new_y, center.z) || center

/// Deletes the sighting marker; the GPS units drop it on their own and get the next one pushed
/datum/criminal_bounty/proc/board_drop_marker()
	if(!marker)
		return
	var/obj/effect/bounty_sighting/old_marker = marker
	marker = null
	if(!QDELETED(old_marker))
		qdel(old_marker)

/// Points every GPS unit it was uploaded to at the current marker
/datum/criminal_bounty/proc/board_push_gps()
	if(!marker || QDELETED(marker) || !board_gps_tag)
		return
	for(var/datum/weakref/unit_ref as anything in board_gps_units.Copy())
		var/datum/component/gps/item/unit = unit_ref?.resolve()
		if(!unit)
			board_gps_units -= unit_ref
			continue
		unit.add_mission_signal(board_gps_tag, marker)

/// Uploads its sighting beacon to `unit`, for `ship` (the mission gps_link pattern). Returns TRUE if it has a beacon to give: none at trader outposts.
/datum/criminal_bounty/proc/board_link_gps(datum/component/gps/item/unit, obj/structure/overmap/ship/ship)
	if(!is_open() || !unit || !board_gps_tag || placement_kind == BOUNTY_PLACEMENT_TRADER_OUTPOST)
		return FALSE
	board_gps_units[WEAKREF(unit)] = ship ? WEAKREF(ship) : null
	if(marker && !QDELETED(marker))
		unit.add_mission_signal(board_gps_tag, marker)
	return TRUE

/// Takes its beacon off the GPS units `ship` linked, as that ship stops hunting it (L2)
/datum/criminal_bounty/proc/board_unlink_gps(obj/structure/overmap/ship/ship)
	for(var/datum/weakref/unit_ref as anything in board_gps_units.Copy())
		var/datum/weakref/owner_ref = board_gps_units[unit_ref]
		if(owner_ref?.resolve() != ship)
			continue
		var/datum/component/gps/item/unit = unit_ref?.resolve()
		unit?.remove_mission_signal(board_gps_tag)
		board_gps_units -= unit_ref

/// Takes its beacon off every GPS unit it was uploaded to
/datum/criminal_bounty/proc/board_clear_gps()
	for(var/datum/weakref/unit_ref as anything in board_gps_units)
		var/datum/component/gps/item/unit = unit_ref?.resolve()
		unit?.remove_mission_signal(board_gps_tag)
	board_gps_units.Cut()

/**
 * A GPS unit tapped on `ship`'s mission board gets the sighting beacon of every criminal the ship
 * hunts. Called from the board's upload_mission_beacons(). Returns how many it linked.
 */
/proc/bounty_link_gps(obj/structure/overmap/ship/ship, datum/component/gps/item/unit)
	var/linked = 0
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(posting.is_open() && posting.is_hunting(ship) && posting.board_link_gps(unit, ship))
			linked++
	return linked

/**
 * Why a GPS tapped on `ship`'s board got no bounty beacon, when that is by design rather than a
 * fault: the ship hunts a fugitive at a trader outpost, where there is no tracker (BUG-15). Null
 * otherwise. The board says it in place of "no beacons to upload".
 */
/proc/bounty_gps_refusal(obj/structure/overmap/ship/ship)
	for(var/datum/criminal_bounty/posting as anything in GLOB.criminal_bounties)
		if(posting.is_open() && posting.is_hunting(ship) && posting.placement_kind == BOUNTY_PLACEMENT_TRADER_OUTPOST)
			return "no signal to track"
	return null
