/**
 * # Bounty hunting: turning a criminal in
 *
 * Owner: P5 board. Do not edit this file outside P5.
 *
 * What it owns: the pad turn-in (the one criminal the posting points at, on the pad's tile, the
 * pad bolted and aboard), pay by capture state through the mission reward system, the beam out,
 * and handing a live catch to the prisoner pool (bounty_pool_add()) (spec section 1, decision 14).
 * There is no custody: any ship that gets the criminal onto its own pad turns it in, whether or
 * not it was hunting it (decision 18); a private offer pays only its own ship (AR-B3). Also the
 * proof of death (/obj/item/bounty_proof), and the guards on older ways to move a criminal as an
 * item: folding it into a bluespace body bag, and sending it through a player bounty offer.
 *
 * The turn-in is atomic (AR-A7): the state is read once at the press (AR-A3), the criminal is
 * frozen and detached, the bounty closes for everyone, then one record goes to the pool and one
 * ship is paid, all without a yield. The shared vars are declared in bounty_types.dm; a var only
 * P5 uses is here with a `board_` prefix.
 */

// ===== THE PAD =====

/**
 * Why the bounty turn-in can't use this pad for `ship` now (unbolted, or not aboard the ship), or
 * null if it can. The bounty turn-in never goes through the pad's item turn-in, so this is the
 * whole check on the pad (AR-A2).
 */
/obj/machinery/mission_pad/proc/bounty_turn_in_refusal(obj/structure/overmap/ship/ship)
	if(QDELETED(src))
		return "no mission pad"
	if(!anchored)
		return "the pad must be bolted down"
	if(!ship || !isturf(loc) || get_ship_from_atom(src) != ship)
		return "the pad must be aboard your ship"
	return null

// ===== TURNING IN =====

/**
 * `ship` turns this bounty in at `pad`: the criminal (or its proof of death) on the pad's own tile,
 * the pad bolted and aboard. Returns list(credits, vouchers) paid, or why not (a short phrase).
 */
/datum/criminal_bounty/proc/turn_in(obj/machinery/mission_pad/pad, obj/structure/overmap/ship/ship, mob/user)
	if(!is_open())
		return "that bounty is closed"
	if(QDELETED(ship))
		return "no ship"
	if(private_to && offered_to() != ship)
		return "that offer is for another crew"
	if(!pad || QDELETED(pad))
		return "no mission pad linked"
	var/refusal = pad.bounty_turn_in_refusal(ship)
	if(refusal)
		return refusal
	var/list/found = list()
	refusal = board_target_refusal(pad, found)
	if(refusal)
		return refusal
	return board_claim(ship, pad, found["target"], found["state"], user)

/**
 * The one thing on `pad` this bounty pays for: its own criminal, standing (or lying) on the pad's
 * tile itself and not in anything, or its proof of death there. Nothing else on the pad is ever
 * looked at or touched (AR-A1).
 */
/datum/criminal_bounty/proc/board_target_on_pad(obj/machinery/mission_pad/pad)
	if(!pad || !isturf(pad.loc))
		return null
	var/mob/living/basic/bounty_criminal/criminal = criminal()
	if(criminal && criminal.loc == pad.loc)
		return criminal
	var/obj/item/bounty_proof/proof = board_proof()
	if(proof && proof.loc == pad.loc && proof.posting_ref?.resolve() == src)
		return proof
	return null

/**
 * Why the pad can't take this bounty's criminal right now, or null. When it can, `found` gets
 * "target" (the criminal or its proof) and "state" (BOUNTY_STATE_*, read here once: the state the
 * turn-in pays on, AR-A3). A criminal with a client or a mind is refused (an admin in it), and so
 * is one standing free.
 */
/datum/criminal_bounty/proc/board_target_refusal(obj/machinery/mission_pad/pad, list/found)
	var/atom/movable/target = board_target_on_pad(pad)
	if(!target)
		var/mob/living/basic/bounty_criminal/criminal = criminal()
		if(criminal && get_turf(criminal) == get_turf(pad))
			return "they're inside [criminal.loc]"
		return "nothing on the pad for this bounty"
	var/state = BOUNTY_STATE_DEAD
	if(istype(target, /mob/living/basic/bounty_criminal))
		var/mob/living/basic/bounty_criminal/criminal = target
		if(criminal.client || criminal.mind)
			return "the pad won't take them"
		state = criminal.capture_state()
		if(!bounty_state_share(state))
			return "they're standing free"
	found["target"] = target
	found["state"] = state
	return null

/**
 * Pays `ship` for `target` (this bounty's criminal or its proof) in `state` at `pad`, and ends the
 * bounty for everyone. No yield from start to end. The share is the worse of `state` and the worst
 * state the criminal ever reached (12.1); a live catch gets its hurt, its captor and its preferred
 * prison and goes to the prisoner pool. Returns list(credits, vouchers), or why not.
 */
/datum/criminal_bounty/proc/board_claim(obj/structure/overmap/ship/ship, obj/machinery/mission_pad/pad, atom/movable/target, state, mob/user)
	// Everything after this line runs once: a second press, or a second ship, finds it closed
	if(!is_open())
		return "that bounty is closed"
	if(QDELETED(target) || QDELETED(ship))
		return "nothing on the pad for this bounty"
	var/mob/living/basic/bounty_criminal/criminal = istype(target, /mob/living/basic/bounty_criminal) ? target : null
	var/obj/item/bounty_proof/proof = istype(target, /obj/item/bounty_proof) ? target : null
	if(!criminal && !proof)
		return "nothing on the pad for this bounty"
	if(proof)
		state = BOUNTY_STATE_DEAD
	var/share = board_share_for(state, criminal ? criminal.worst_state : BOUNTY_STATE_DEAD)
	if(!share)
		return "they're standing free"
	var/list/pay = board_payout(share)
	var/datum/bounty_record/claimed = record
	var/wanted_name = claimed?.name || "the fugitive"
	var/live = criminal && state != BOUNTY_STATE_DEAD && criminal.stat != DEAD
	var/most_wanted = claimed?.tier == BOUNTY_TIER_MOST_WANTED && !private_to
	// Closing lets go of the record and the hunters, so everything read from them is read now
	var/poster_text = (live && share >= 100 && claimed?.tier >= BOUNTY_TIER_WANTED) ? board_poster_text(ship) : null
	var/list/already_told = most_wanted ? hunter_ships() : null

	// Take it: the criminal is frozen for the beam and stops being this bounty's, so closing the bounty doesn't remove it
	if(criminal)
		board_detach_criminal()
		criminal.board_beam_out()
	else
		board_proof_ref = null
		UnregisterSignal(proof, COMSIG_QDELETING)
		var/turf/proof_turf = get_turf(proof)
		if(proof_turf)
			new /obj/effect/temp_visual/transporter_flash/departure(proof_turf)
		qdel(proof)

	// The record: a live catch goes on to the prisons, a dead one ends here. The crew's own prison
	// (P7's lookup) is named only if it would take them now (BUG-3).
	var/datum/outpost_prison/prison
	if(claimed)
		claimed.captor_name = ship.name
		claimed.captor_ship = WEAKREF(ship)
		if(live)
			claimed.hurt_fraction = clamp(1 - criminal.health / max(criminal.maxHealth, 1), 0, 1)
			var/datum/outpost_prison/own = bounty_captor_prison(ship)
			claimed.preferred_prison = own ? WEAKREF(own) : null
			if(own?.bounty_accepts(claimed))
				prison = own
		else
			claimed.status = BOUNTY_RECORD_DEAD

	close(BOUNTY_CLOSE_CLAIMED, ship)

	if(live && claimed)
		if(bounty_pool_add(claimed) && claimed.status == BOUNTY_RECORD_WANTED)
			claimed.status = BOUNTY_RECORD_POOLED
	bounty_pay_ship(ship, pad, pay[1], pay[2])
	if(poster_text)
		bounty_print_captured_poster(get_turf(pad), poster_text, wanted_name)

	var/list/paid = list("[pay[1]] credits")
	if(pay[2] > 0)
		paid += "[pay[2]] trade voucher[pay[2] > 1 ? "s" : ""]"
	var/how = proof ? "confirmed dead" : bounty_state_words(state)
	// Only the crew's own prison is named: the transfer pool is the corrections service's business
	var/after = (live && prison) ? " They're headed for your prison at [prison.outpost?.name || "your outpost"]." : ""
	ship.ship_notify("BOUNTY: [wanted_name] turned in, [how]. Paid [english_list(paid)].[after]", "BOUNTY COMPLETE", SHIP_NOTIFY_NOTICE, 'voidcrew/sound/notify.ogg', 50)
	// A Most Wanted catch is news for every other crew (the hunters already heard from close())
	if(most_wanted)
		var/news = live ? "BOUNTY: the crew of the [ship.name] brought in [wanted_name], Most Wanted." : "BOUNTY: the crew of the [ship.name] took down [wanted_name], Most Wanted."
		SScriminal_bounties.board_announce(news, already_told + ship)
	log_game("BOUNTY: [ship.name] turned in [wanted_name] ([proof ? "proof" : state], [share]%) at [AREACOORD(pad)] for [pay[1]] cr and [pay[2]] voucher(s)[user ? ", pressed by [key_name(user)]" : ""]")
	return pay

/// How the notice describes a capture state
/proc/bounty_state_words(state)
	switch(state)
		if(BOUNTY_STATE_RESTRAINED)
			return "restrained"
		if(BOUNTY_STATE_STUNNED)
			return "subdued"
		if(BOUNTY_STATE_DOWNED)
			return "downed"
		if(BOUNTY_STATE_DEAD)
			return "dead"
	return "free"

/// Credits into `ship`'s account, vouchers onto `pad`, like finish_mission() pays a contract (decision 9)
/proc/bounty_pay_ship(obj/structure/overmap/ship/ship, obj/machinery/mission_pad/pad, credits, vouchers)
	if(credits > 0)
		ship?.ship_account?.adjust_money(credits)
	var/turf/pad_turf = get_turf(pad)
	if(vouchers > 0 && pad_turf)
		new /obj/item/stack/trade_voucher(pad_turf, vouchers)
	if(!QDELETED(pad))
		pad.do_teleport_effect()

/**
 * What the board's card and the pad know about the pad for `ship` (BUG-4, P10): list(can_turn_in,
 * turn_in_state, refusal). The state is the capture state of this bounty's criminal on the pad's tile
 * ("proof" for its proof of death), or null with nothing there. The refusal is why Turn In won't work
 * now, in the same words the press would answer with, or null. Nothing says what a press would pay:
 * the receipt does, after. The press itself still checks everything.
 */
/datum/criminal_bounty/proc/board_pad_preview(obj/structure/overmap/ship/ship, obj/machinery/mission_pad/pad)
	if(!is_open())
		return list(FALSE, null, "that bounty is closed")
	if(!pad || QDELETED(pad))
		return list(FALSE, null, "no mission pad linked")
	var/atom/movable/target = board_target_on_pad(pad)
	var/state = null
	if(target)
		state = "proof"
		if(istype(target, /mob/living/basic/bounty_criminal))
			var/mob/living/basic/bounty_criminal/criminal = target
			state = criminal.capture_state()
	var/refusal
	if(private_to && offered_to() != ship)
		refusal = "that offer is for another crew"
	else
		refusal = board_target_refusal(pad, list()) || pad.bounty_turn_in_refusal(ship)
	return list(!refusal, state, refusal)

/**
 * Why Turn In is off for `ship`, from its `preview` (board_pad_preview()), or null when it is on. A
 * subtype that turns it off without saying why (the kingpin, for a crew that works for him) gives its reason through
 * hunt_refusal().
 */
/datum/criminal_bounty/proc/board_preview_refusal(list/preview, obj/structure/overmap/ship/ship)
	if(preview[1])
		return null
	var/refusal = length(preview) >= 3 ? preview[3] : null
	if(!refusal && preview[2])
		refusal = hunt_refusal(ship) || "you can't turn this one in"
	return refusal

// ===== THE PAD SPEAKS UP (P2) =====

/obj/machinery/mission_pad
	/// Between two things the pad says about a bounty target landing on it
	COOLDOWN_DECLARE(bounty_announce_cooldown)

/**
 * `arrived` (a bounty criminal or proof of death) landed on the pad: the pad says who or what it is,
 * and why Turn In won't take it if it won't, and the linked console chimes. Nothing for a decoy, a companion, another crew's
 * offer or a closed bounty. Once every BOUNTY_PAD_ANNOUNCE_COOLDOWN at most. Returns what it said.
 */
/obj/machinery/mission_pad/proc/bounty_pad_announce(atom/movable/arrived)
	if(QDELETED(src) || QDELETED(arrived) || arrived.loc != loc)
		return null
	if(!COOLDOWN_FINISHED(src, bounty_announce_cooldown))
		return null
	var/line = bounty_pad_line(arrived)
	if(!line)
		return null
	COOLDOWN_START(src, bounty_announce_cooldown, BOUNTY_PAD_ANNOUNCE_COOLDOWN)
	say(line)
	playsound(linked_console || src, 'sound/machines/chime.ogg', 40, FALSE)
	return line

/// What the pad says about `arrived` on it, or null if it says nothing (not a bounty target, or not this ship's to turn in)
/obj/machinery/mission_pad/proc/bounty_pad_line(atom/movable/arrived)
	var/datum/criminal_bounty/posting
	if(istype(arrived, /mob/living/basic/bounty_criminal))
		var/mob/living/basic/bounty_criminal/criminal = arrived
		posting = criminal.posting()
	else if(istype(arrived, /obj/item/bounty_proof))
		var/obj/item/bounty_proof/proof = arrived
		posting = proof.posting_ref?.resolve()
	if(QDELETED(posting) || !posting.is_open() || posting.board_target_on_pad(src) != arrived)
		return null
	var/obj/structure/overmap/ship/ship = get_ship_from_atom(src)
	if(posting.private_to && posting.offered_to() != ship)
		return null
	var/list/preview = posting.board_pad_preview(ship, src)
	var/wanted_name = posting.record?.name || "the fugitive"
	var/refusal = posting.board_preview_refusal(preview, ship)
	var/line
	if(istype(arrived, /obj/item/bounty_proof))
		line = "[istype(arrived, /obj/item/bounty_proof/trophy) ? "Trophy" : "Evidence tag"] for [wanted_name] on the pad."
	else
		var/state = preview[2]
		line = "On the pad: [wanted_name], [state == BOUNTY_STATE_FREE ? "standing free" : bounty_state_words(state)]."
		if(state == BOUNTY_STATE_FREE)
			return line
	return refusal ? "[line] [capitalize(refusal)]." : line

// ===== THE BEAM =====

/**
 * The pad takes them: held still, harmless and untouchable, and fading out in the prisoner's
 * beam (outpost_prison_prisoner.dm beam_out()), then deleted. Never a teleport (AR-A1). Nothing
 * they leave behind counts as proof of death.
 */
/mob/living/basic/bounty_criminal/proc/board_beam_out()
	// Their last words as the pad takes them (P1's beamed_out lines), said before the beam holds them still
	if(stat == CONSCIOUS)
		INVOKE_ASYNC(src, TYPE_PROC_REF(/mob/living, bounty_say), "beamed_out", null, TRUE)
	ADD_TRAIT(src, TRAIT_BOUNTY_REMOVED, BOUNTY_PAD_TRAIT)
	ADD_TRAIT(src, TRAIT_IMMOBILIZED, BOUNTY_PAD_TRAIT)
	ADD_TRAIT(src, TRAIT_INCAPACITATED, BOUNTY_PAD_TRAIT)
	ADD_TRAIT(src, TRAIT_GODMODE, BOUNTY_PAD_TRAIT)
	REMOVE_TRAIT(src, TRAIT_MISSION_FIELD_MOB, BOUNTY_TRAIT)
	ai_controller?.set_ai_status(AI_STATUS_OFF)
	pulledby?.stop_pulling()
	stop_pulling()
	buckled?.unbuckle_mob(src, force = TRUE)
	var/turf/spot = get_turf(src)
	if(spot)
		playsound(spot, 'sound/effects/magic/teleport_diss.ogg', 40, TRUE)
		new /obj/effect/temp_visual/transporter_beam(spot, BOUNTY_BEAM_TIME + 0.5 SECONDS)
	new /obj/effect/abstract/particle_holder(src, /particles/transporter_motes, PARTICLE_ATTACH_MOB)
	transporter_dematerialise(src, BOUNTY_BEAM_TIME)
	addtimer(CALLBACK(src, PROC_REF(board_finish_beam_out)), BOUNTY_BEAM_TIME, TIMER_DELETE_ME)

/mob/living/basic/bounty_criminal/proc/board_finish_beam_out()
	var/turf/spot = get_turf(src)
	if(spot)
		new /obj/effect/temp_visual/transporter_flash/departure(spot)
		transporter_sparks(spot)
		playsound(spot, 'sound/effects/magic/teleport_app.ogg', 50, TRUE)
	qdel(src)

// ===== THE CAPTURED POSTER (P6) =====

/**
 * What a full-share catch of a Wanted or Most Wanted leaves on the pad: a plain paper with their
 * mugshot and a CAPTURED stamp, worth nothing, to pin up. Not a warrant (no posting), so it can never
 * be shown to anyone as one.
 */
/obj/item/paper/bounty_captured
	name = "captured poster"
	desc = "A printed notice of a wanted criminal brought in alive. Worth nothing but the bragging rights."

/// Prints the CAPTURED poster (`text`, made before the bounty closed) for `wanted_name` at `where`. Returns the paper.
/proc/bounty_print_captured_poster(turf/where, text, wanted_name)
	if(!where || !text)
		return null
	var/obj/item/paper/bounty_captured/poster = new(where)
	poster.name = "captured poster ([wanted_name || "unknown"])"
	poster.add_raw_text(text, advanced_html = TRUE)
	poster.update_appearance()
	// The stamp's class comes from the paper spritesheet, which may have to be made ready first
	INVOKE_ASYNC(poster, TYPE_PROC_REF(/obj/item/paper/bounty_captured, stamp_captured))
	return poster

/// The CAPTURED stamp across the poster
/obj/item/paper/bounty_captured/proc/stamp_captured()
	var/datum/asset/spritesheet_batched/sheet = get_asset_datum(/datum/asset/spritesheet/simple/paper)
	if(QDELETED(src) || !sheet)
		return
	add_stamp(sheet.icon_class_name("stamp-hos"), rand(170, 250), rand(40, 110), rand(-20, 20), "stamp-hos")
	update_appearance()

// ===== PROOF OF DEATH =====

/obj/item/bounty_proof
	name = "evidence tag"
	desc = "A sealed evidence tag with what was left of a wanted criminal."
	icon = 'voidcrew/modules/missions/icons/recovery.dmi'
	icon_state = "recovery_proof"
	inhand_icon_state = null
	w_class = WEIGHT_CLASS_TINY
	resistance_flags = INDESTRUCTIBLE | LAVA_PROOF | FIRE_PROOF | ACID_PROOF | UNACIDABLE

/obj/item/bounty_proof/Initialize(mapload)
	. = ..()
	// Thrown into a chasm it is gone for good, not kept in the depths where no pad can reach it (H1): the bounty then relists
	ADD_TRAIT(src, TRAIT_CHASM_DESTROYED, INNATE_TRAIT)

/obj/item/bounty_proof/examine(mob/user)
	. = ..()
	var/datum/criminal_bounty/posting = posting_ref?.resolve()
	if(record?.name)
		. += span_notice("It's marked for [record.name].")
	if(!posting || !posting.is_open())
		. += span_warning("Their bounty is closed. It's worth nothing now.")

/obj/item/bounty_proof/Destroy()
	posting_ref = null
	record = null
	return ..()

/**
 * Leaves proof of death where `criminal` was destroyed (gibbed, dusted, fallen into lava or a chasm),
 * so the dead share can still be claimed at a pad (AR-A6, D-A2). Returns the proof, or null. P2
 * calls it as the body is destroyed, or falls into a chasm. The proof lands on the nearest safe tile
 * within BOUNTY_PROOF_EDGE_RADIUS, never in the chasm or the lava itself (H1), and from then on it is
 * the only thing to bring in: the body is let go. It leaves nothing when the pad or the board took
 * the criminal away (TRAIT_BOUNTY_REMOVED), when its bounty is closed or relisting, or when the
 * criminal went with its site's interior (it comes back at the next load). One proof per bounty.
 */
/proc/bounty_drop_proof(mob/living/basic/bounty_criminal/criminal)
	if(!criminal || HAS_TRAIT(criminal, TRAIT_BOUNTY_REMOVED))
		return null
	var/datum/criminal_bounty/posting = criminal.posting_ref?.resolve()
	if(!posting || !posting.is_open() || posting.board_relisting)
		return null
	var/mob/living/basic/bounty_criminal/current = posting.criminal()
	if(current && current != criminal)
		return null
	var/turf/spot = get_turf(criminal)
	if(!spot)
		return null
	var/obj/structure/overmap/where = posting.site()
	if(where && posting.board_site_unloading(where) && posting.board_site_contains(where, spot))
		return null
	// The body is no longer the bounty's: whatever becomes of it (the chasm's depths, a fishing line) pays nothing
	if(current == criminal)
		posting.board_detach_criminal()
	ADD_TRAIT(criminal, TRAIT_BOUNTY_REMOVED, BOUNTY_PAD_TRAIT)
	var/obj/item/bounty_proof/existing = posting.board_proof()
	if(existing)
		return existing
	var/obj/item/bounty_proof/proof = new(bounty_proof_spot(spot))
	proof.posting_ref = WEAKREF(posting)
	proof.record = posting.record
	if(posting.record?.name)
		proof.name = "evidence tag ([posting.record.name])"
	posting.board_attach_proof(proof)
	return proof

/// Where proof of death dropped at `spot` lands: `spot` if it is safe ground, else the nearest safe tile within BOUNTY_PROOF_EDGE_RADIUS (the chasm's or lava's edge), else `spot`
/proc/bounty_proof_spot(turf/spot)
	if(!spot || bounty_spawn_turf_ok(spot, allow_ship = TRUE))
		return spot
	var/turf/best
	var/best_distance
	for(var/turf/candidate as anything in RANGE_TURFS(BOUNTY_PROOF_EDGE_RADIUS, spot))
		if(!bounty_spawn_turf_ok(candidate, allow_ship = TRUE))
			continue
		var/distance = get_dist(candidate, spot)
		if(!best || distance < best_distance)
			best = candidate
			best_distance = distance
	return best || spot

/// Makes `proof` what this bounty pays the dead share for; if it is destroyed too, the bounty relists
/datum/criminal_bounty/proc/board_attach_proof(obj/item/bounty_proof/proof)
	board_proof_ref = WEAKREF(proof)
	RegisterSignal(proof, COMSIG_QDELETING, PROC_REF(board_on_proof_deleted))
	if(board_lost_timer)
		deltimer(board_lost_timer)
		board_lost_timer = null
	// The GPS follows what is left
	if(placement_kind != BOUNTY_PLACEMENT_TRADER_OUTPOST)
		var/turf/spot = get_turf(proof)
		if(spot)
			last_seen = spot
			if(!marker || QDELETED(marker))
				marker = new(spot)
				marker.posting_ref = WEAKREF(src)
				board_push_gps()
			else
				marker.forceMove(spot)
	log_game("BOUNTY: the [board_log_name()] left proof of death at [AREACOORD(proof)]")

/datum/criminal_bounty/proc/board_on_proof_deleted(datum/source)
	SIGNAL_HANDLER
	UnregisterSignal(source, COMSIG_QDELETING)
	if(source.weak_reference != board_proof_ref)
		return
	board_proof_ref = null
	if(!is_open() || board_relisting || criminal())
		return
	if(board_lost_timer)
		deltimer(board_lost_timer)
	board_lost_timer = addtimer(CALLBACK(src, PROC_REF(board_check_lost)), 1 SECONDS, TIMER_STOPPABLE | TIMER_DELETE_ME)

// ===== OLDER WAYS TO MOVE A CRIMINAL AS AN ITEM =====

/**
 * Called from the bluespace body bag's attempt_fold(): TRUE stops `folder` folding `bag`, because
 * a living bounty criminal is inside (AR-E7). Tells `folder` why.
 */
/proc/bounty_blocks_bag_fold(obj/structure/closet/body_bag/bag, mob/living/folder)
	if(!bag)
		return FALSE
	for(var/mob/living/basic/bounty_criminal/criminal in bag.get_all_contents())
		if(criminal.stat == DEAD)
			continue
		if(folder)
			to_chat(folder, span_warning("[bag] won't fold with someone alive and struggling inside."))
		return TRUE
	return FALSE

/**
 * Called from a player bounty's approve_offer() with the items on the sender's pad: why they can't
 * be sent (one of them holds a living bounty criminal, decoy or companion), or null if they can
 * (AR-H1). Brains in MMIs, positronic brains, pAIs and held pets go through as they always did.
 */
/proc/bounty_offer_refusal(list/items)
	for(var/obj/item/item in items)
		if(bounty_holds_living_criminal(item))
			return "living cargo can't be sent this way"
	return null

/// Whether `thing` holds (not is) a living bounty criminal, decoy or companion anywhere inside it
/proc/bounty_holds_living_criminal(atom/movable/thing)
	if(QDELETED(thing))
		return FALSE
	for(var/mob/living/passenger in thing.get_all_contents())
		if(passenger == thing || passenger.stat == DEAD)
			continue
		if(istype(passenger, /mob/living/basic/bounty_criminal) || istype(passenger, /mob/living/basic/bounty_companion))
			return TRUE
	return FALSE

/**
 * Called from the transporter pad's gather_payload(): TRUE keeps `thing` off the beam. A criminal
 * refuses teleports itself (P2); this stops a locker, a crate or a bag with a living one inside
 * riding the beam instead (the pad is the only way out, D-A10). No side effects: the console asks it
 * every UI tick.
 */
/proc/bounty_blocks_transport(atom/movable/thing)
	if(QDELETED(thing))
		return FALSE
	if(istype(thing, /mob/living/basic/bounty_criminal) || istype(thing, /mob/living/basic/bounty_companion))
		var/mob/living/rider = thing
		return rider.stat != DEAD
	return bounty_holds_living_criminal(thing)
