/**
 * # Bounty lairs: the framework
 *
 * Owner: P10 lairs. Do not edit this file outside P10.
 *
 * Kill-only postings, lair ruins spawned per posting (the drug run's spawn_lab_ruin pattern), gates that open when
 * a lair's gatekeepers die, and the lich kill bounty on GLOB.lich_lair. Spec section 14.1-14.3, decision 20.
 *
 * ## Kill-only postings (/datum/criminal_bounty/kill_only)
 *
 * A P5 posting with no criminal: the boss is not a bounty criminal, so the pad never sees a live body, and nothing
 * can cuff it. It pays 100% of its value, vouchers included, when its trophy (/obj/item/bounty_proof/trophy) is on
 * any ship's linked pad (decision 18). The trophy is the posting's proof of death, so P5's turn-in takes it the way
 * it takes any proof. It never makes a prisoner record. The P5 procs it overrides: board_arm (no criminal to spawn),
 * board_share_for (dead or nothing), the pad target, the card and the warrant, and relist (a kill-only bounty's
 * site is fixed, so losing the site, or the trophy, ends the bounty).
 *
 * ## Lairs (/obj/structure/overmap/space_ruin/bounty_lair)
 *
 * A rare, mission-locked ruin spawned for one posting and released when the posting closes. It stays loaded while
 * the bounty is open (mission_locked stops every cleanup path, and Overmap Management refuses to unload it), so the
 * rooms a crew clears stay cleared: the zone_mobs markers delete themselves after spawning and are never stamped
 * again. On its first load it indexes its own footprint once: it spawns the boss and the gatekeepers on their
 * landmarks, finds its gate poddoors (id BOUNTY_LAIR_GATE_ID), and keeps the boss, the gatekeepers and the goons to
 * the rooms they started in. When the last gatekeeper dies, the gate opens. When the last boss dies (the mech, then
 * the don who climbs out of it), the trophy drops where he fell, unless the boss's own death dropped it through
 * bounty_lair_drop_trophy().
 *
 * ## The lair clock (SSbounty_lairs)
 *
 * Each lair kind (/datum/bounty_lair_kind) is posted rarely: the first 45-60 minutes into the round once 3 or more
 * crews are out, the next 60-90 minutes after the last one's bounty closed, never two of a kind at once. Lairs and
 * the lich don't take one of the board's public slots.
 *
 * ## The lich
 *
 * surface_lich_lair() posts "Ilthuun, the Lich" on GLOB.lich_lair; on_lich_slain() sends COMSIG_BOUNTY_LICH_SLAIN,
 * and the shard of his crown drops at the corpse. The bounty's clock holds while he lives; it closes if the lair
 * goes away before the kill. Nothing about the lich himself changes.
 */

// ===== TROPHIES =====

/obj/item/bounty_proof/trophy
	name = "trophy"
	desc = "Proof of a kill."
	w_class = WEIGHT_CLASS_SMALL

/obj/item/bounty_proof/trophy/lich
	name = "cracked crown shard"
	desc = "A cracked shard of the lich's gold crown. It's proof that Ilthuun is dead."
	icon = 'icons/obj/debris.dmi'
	icon_state = "titaniummedium"
	color = "#d8b24a"

// ===== LANDMARKS =====

/obj/effect/landmark/bounty_lair_boss
	name = "bounty lair boss"

/obj/effect/landmark/bounty_lair_gatekeeper
	name = "bounty lair gatekeeper"

// ===== KILL-ONLY POSTINGS (spec 14.1) =====

/**
 * A kill-only bounty: WANTED: DEAD. No criminal, no capture, no prisoner record. Its boss drops a trophy that pays the
 * whole value at any ship's pad. The subtypes are a lair's posting and the lich's.
 */
/datum/criminal_bounty/kill_only
	/// The trophy its boss drops (/obj/item/bounty_proof/trophy)
	var/kill_trophy_type = /obj/item/bounty_proof/trophy
	/// What the card says the boss is, in place of a species
	var/kill_species = "Unknown"

/// No criminal to spawn: the boss belongs to its lair or its event
/datum/criminal_bounty/kill_only/board_arm()
	return FALSE

/// Its site is fixed, so a lost site or a lost trophy ends it instead of moving it
/datum/criminal_bounty/kill_only/relist(reason)
	if(!is_open())
		return FALSE
	log_game("BOUNTY: the [board_log_name()] can't go on ([reason || "no reason given"]), closing it")
	close(BOUNTY_CLOSE_LAIR_GONE)
	return FALSE

/// Dead, and only dead: the trophy pays in full, anything else pays nothing
/datum/criminal_bounty/kill_only/board_share_for(state, worst_state)
	return state == BOUNTY_STATE_DEAD ? 100 : 0

/// The pad takes its trophy only: the one it dropped, or any trophy bound to it, lying on the pad's own tile
/datum/criminal_bounty/kill_only/board_target_on_pad(obj/machinery/mission_pad/pad)
	if(!pad || !isturf(pad.loc))
		return null
	var/obj/item/bounty_proof/proof = board_proof()
	if(proof && proof.loc == pad.loc)
		return proof
	for(var/obj/item/bounty_proof/trophy/trophy in pad.loc)
		if(!QDELETED(trophy) && trophy.posting_ref?.resolve() == src)
			return trophy
	return null

/datum/criminal_bounty/kill_only/board_target_refusal(obj/machinery/mission_pad/pad, list/found)
	if(!board_target_on_pad(pad))
		return "no trophy on the pad"
	return ..()

/datum/criminal_bounty/kill_only/board_pad_preview(obj/structure/overmap/ship/ship, obj/machinery/mission_pad/pad)
	var/list/preview = ..()
	if(length(preview) >= 2 && preview[2] == "proof")
		preview[2] = "trophy"
	return preview

/datum/criminal_bounty/kill_only/board_terms()
	return "Wanted dead"

/datum/criminal_bounty/kill_only/board_species_name()
	return kill_species

/// A lair or the lich's tomb goes by its real name, never "encrypted signal"
/datum/criminal_bounty/kill_only/board_describe_site(obj/structure/overmap/where)
	if(istype(where, /obj/structure/overmap/space_ruin))
		var/obj/structure/overmap/space_ruin/ruin = where
		if(ruin.true_name)
			return format_text(ruin.true_name)
	return ..()

/datum/criminal_bounty/kill_only/board_place_text()
	return "Holed up in [board_site_name || "an unknown site"]"

/datum/criminal_bounty/kill_only/board_warrant_text()
	var/list/lines = list()
	lines += "<center><h2>WANTED: DEAD</h2></center>"
	var/mugshot = record ? bounty_mugshot_asset(record) : ""
	if(mugshot)
		lines += "<center><img src='data:image/png;base64,[mugshot]' width='96' height='96'></center>"
	lines += "<b>Name:</b> [record?.name || "Unknown"]<br>"
	lines += "<b>Species:</b> [board_species_name()]. <b>Sex:</b> [board_sex_name()].<br>"
	if(record?.crime)
		lines += "<b>Wanted for:</b> [record.crime].<br>"
	lines += "[board_place_text()], [board_zone_name()].<br>"
	lines += "<b>Reward:</b> [board_reward_text()].<br>"
	return lines.Join("\n")

/**
 * Drops its trophy (`trophy_type`, or its own kind) at `where`, or beside it when `where` is a chasm, lava or open
 * space, bound to it as its proof of death. One trophy per bounty: a second call returns the first. Null once it is
 * closed.
 */
/datum/criminal_bounty/kill_only/proc/kill_drop_trophy(atom/where, trophy_type)
	if(!is_open())
		return null
	var/obj/item/bounty_proof/existing = board_proof()
	if(existing)
		return existing
	var/turf/origin = get_turf(where)
	// A boss that fell inside its site leaves its trophy inside it
	var/obj/structure/overmap/site = site()
	var/datum/map_footprint/inside = site?.get_interior_footprint()
	if(!inside?.contains_turf(origin))
		inside = null
	var/turf/spot = bounty_lair_trophy_spot(origin, inside)
	if(!spot)
		return null
	if(!ispath(trophy_type, /obj/item/bounty_proof/trophy))
		trophy_type = kill_trophy_type
	var/obj/item/bounty_proof/trophy/trophy = new trophy_type(spot)
	kill_bind_trophy(trophy)
	return trophy

/// Makes `trophy` this bounty's proof of death: the pad pays on it, the GPS follows it, and losing it ends the bounty
/datum/criminal_bounty/kill_only/proc/kill_bind_trophy(obj/item/bounty_proof/trophy/trophy)
	if(QDELETED(trophy) || !is_open() || board_proof())
		return FALSE
	trophy.posting_ref = WEAKREF(src)
	trophy.record = record
	board_attach_proof(trophy)
	return TRUE

/**
 * Puts it on the board at `site` in zone band `zone`: the value fixed now from the record's base (AR-A9), `vouchers`
 * on the trophy, `lifetime` on its clock, and the site held on the chart by P5's claim.
 */
/datum/criminal_bounty/kill_only/proc/kill_publish(obj/structure/overmap/site, zone, vouchers, lifetime)
	placement_kind = SScriminal_bounties.board_kind_of_site(site) || BOUNTY_PLACEMENT_RUIN
	board_zone = zone
	value = SScriminal_bounties.board_value_for(record.base_value, zone)
	board_vouchers = vouchers
	board_posted_at = world.time
	expires_at = world.time + lifetime
	board_gps_tag = "[BOUNTY_GPS_TAG_PREFIX]-[record.id]"
	GLOB.criminal_bounties += src
	board_set_site(site)
	SScriminal_bounties.board_changed()
	log_game("BOUNTY: posted the kill-only [board_log_name()] in zone [zone], worth [value] cr and [board_vouchers] voucher(s)")

/// Tells every player crew a kill-only bounty is up
/datum/criminal_bounty/kill_only/proc/kill_announce()
	var/message = "WANTED: DEAD. [record?.name || "Unknown"]. [board_place_text()], [board_zone_name()]."
	for(var/obj/structure/overmap/ship/ship as anything in SSovermap.simulated_ships)
		if(QDELETED(ship) || ship.abandoned || istype(ship, /obj/structure/overmap/ship/npc))
			continue
		ship.ship_notify(message, "MISSION CONTROL", SHIP_NOTIFY_NOTICE, 'voidcrew/sound/notify.ogg', 50)

/**
 * A record for a kill-only boss: the card's name, sex, crime and picture. A Most Wanted mini-boss on the board, but
 * it has no look (no one is rebuilt from it) and never goes to the prisoner pool.
 */
/proc/bounty_kill_record(name, crime, gender, base_value, mugshot)
	var/datum/bounty_record/record = new
	record.name = name
	record.gender = gender
	record.crime = crime
	record.tier = BOUNTY_TIER_MOST_WANTED
	record.archetype = BOUNTY_ARCHETYPE_BOSS
	record.base_value = base_value
	record.status = BOUNTY_RECORD_WANTED
	record.features = list()
	record.prison_traits = list()
	// Set now, so nothing builds a human mugshot for it (P1's builder only runs while this is empty)
	record.mugshot = mugshot || bounty_kill_mugshot()
	return record

/// The card's picture of a boss: `icon_state` of `icon_file`, the top square of a tall sprite. Base64 PNG, never empty.
/proc/bounty_kill_mugshot(icon_file, icon_state)
	if(!icon_file || !icon_state || !(icon_state in icon_states(icon_file)))
		icon_file = 'voidcrew/modules/missions/icons/recovery.dmi'
		icon_state = "recovery_proof"
	var/icon/portrait = icon(icon_file, icon_state, SOUTH, 1)
	var/width = portrait.Width()
	var/height = portrait.Height()
	if(height > width)
		portrait.Crop(1, height - width + 1, width, height)
	var/encoded = icon2base64(portrait)
	return (istext(encoded) && length(encoded)) ? encoded : "?"

/**
 * Where a trophy dropped at `spot` lands: there, or the nearest safe floor reached from it without going through a
 * wall (a short flood fill). With `inside` (a footprint) it stays inside it and off any docked ship. Null when no
 * safe floor is near: never space or a chasm.
 */
/proc/bounty_lair_trophy_spot(turf/spot, datum/map_footprint/inside)
	if(!spot)
		return null
	var/list/queue = list(spot)
	var/list/seen = list()
	seen[spot] = TRUE
	var/index = 1
	while(index <= length(queue) && index <= BOUNTY_LAIR_TROPHY_SEARCH)
		var/turf/here = queue[index]
		index++
		if(bounty_lair_trophy_turf_ok(here) && !(inside && istype(here.loc, /area/shuttle)))
			return here
		for(var/direction in GLOB.cardinals)
			var/turf/next = get_step(here, direction)
			if(!next || seen[next] || isclosedturf(next))
				continue
			if(inside && !inside.contains_turf(next))
				continue
			seen[next] = TRUE
			queue += next
	return null

/// Whether a trophy can lie on `spot`: a floor, not space, a chasm, lava, water or an open drop
/proc/bounty_lair_trophy_turf_ok(turf/spot)
	if(!isopenturf(spot) || isspaceturf(spot))
		return FALSE
	if(istype(spot, /turf/open/lava) || istype(spot, /turf/open/chasm) || istype(spot, /turf/open/openspace) || istype(spot, /turf/open/water))
		return FALSE
	return TRUE

/// The open kill-only bounty a lair boss is wanted on (its posting_ref), or null
/proc/bounty_kill_posting_of(mob/living/boss)
	if(!istype(boss, /mob/living/basic/bounty_lair_boss))
		return null
	var/mob/living/basic/bounty_lair_boss/lair_boss = boss
	var/datum/criminal_bounty/kill_only/posting = lair_boss.posting_ref?.resolve()
	if(!istype(posting) || !posting.is_open())
		return null
	return posting

/**
 * The API for a lair boss's death (P12's don calls it when he dies): drops `trophy_type` at `boss`'s body, bound to
 * the kill-only bounty `boss` is wanted on. One trophy per bounty; a second call returns the first. Returns the
 * trophy, or null when `boss` is wanted on no open bounty (an admin spawn), which drops nothing.
 */
/proc/bounty_lair_drop_trophy(mob/living/boss, trophy_type)
	var/datum/criminal_bounty/kill_only/posting = bounty_kill_posting_of(boss)
	if(!posting)
		return null
	return posting.kill_drop_trophy(boss, trophy_type)

// ===== LAIR POSTINGS (spec 14.2) =====

/// A lair's kill-only bounty. Its lair listens for it to close, and lets itself go then.
/datum/criminal_bounty/kill_only/lair
	/// The kind of lair it was posted for (/datum/bounty_lair_kind)
	var/datum/bounty_lair_kind/lair_kind

/datum/criminal_bounty/kill_only/lair/Destroy()
	lair_kind = null
	return ..()

/// Its clock also waits while anyone is inside the lair: a crew deep in it never loses the bounty to the clock
/datum/criminal_bounty/kill_only/lair/board_clock_held(now = world.time)
	if(..())
		return TRUE
	var/obj/structure/overmap/space_ruin/bounty_lair/lair = site()
	return istype(lair) && lair.lair_has_crew_inside()

// ===== THE LAIR SITE (spec 14.2) =====

/obj/structure/overmap/space_ruin/bounty_lair
	/// The kind of lair it is (/datum/bounty_lair_kind)
	var/datum/bounty_lair_kind/lair_kind
	/// Weakrefs to its gate poddoors (id BOUNTY_LAIR_GATE_ID) inside its footprint, found when it links
	var/list/lair_gate_doors = list()
	/// Weakrefs to its living gatekeepers; the gate opens when the last one is gone
	var/list/lair_gatekeepers = list()
	/// Weakrefs to the bosses it is waiting on (the mech, then the don who climbs out of it)
	var/list/lair_bosses = list()
	/// The gate is open: it stays open, and the gatekeepers never come back
	var/lair_gate_open = FALSE
	/// The last boss is dead: the trophy is out, and the boss never comes back
	var/lair_boss_killed = FALSE
	/// The interior has been indexed for this load and its boss and gatekeepers spawned
	var/lair_link_done = FALSE
	/// Where the last boss fell, for the trophy
	var/turf/lair_last_death_spot
	/// Whether the last boss to go died (FALSE: it was deleted alive, and nobody earned a trophy)
	var/lair_last_boss_died = FALSE
	/// Timer: after a boss falls, whether anything takes over from it, or the trophy drops
	var/lair_trophy_timer
	/// Timer: the second pass that keeps late goons in their rooms
	var/lair_goon_timer
	/// Timer: letting the lair go once a load in progress has finished
	var/lair_release_timer

/obj/structure/overmap/space_ruin/bounty_lair/Initialize(mapload, datum/map_template/ruin/space/template)
	. = ..()
	// The bounty owns it: never a contract's site, a criminal's hideout or a prison lead
	mission_exclusive = TRUE
	RegisterSignal(src, COMSIG_VOIDCREW_PLANET_LOADED, PROC_REF(lair_on_loaded))
	RegisterSignal(src, COMSIG_VOIDCREW_RUIN_UNLOADING, PROC_REF(lair_on_unloading))

/obj/structure/overmap/space_ruin/bounty_lair/Destroy()
	lair_unhook_mobs()
	lair_clear_timers()
	if(lair_release_timer)
		deltimer(lair_release_timer)
		lair_release_timer = null
	var/datum/criminal_bounty/posting = posting_ref?.resolve()
	if(posting)
		UnregisterSignal(posting, COMSIG_BOUNTY_POSTING_CLOSED)
	posting_ref = null
	lair_kind = null
	lair_gate_doors = null
	lair_last_death_spot = null
	return ..()

/obj/structure/overmap/space_ruin/bounty_lair/categorize_ruin()
	ruin_category = "station"

/// Its posting, while that is still open
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_posting()
	var/datum/criminal_bounty/kill_only/lair/posting = posting_ref?.resolve()
	if(!istype(posting) || !posting.is_open())
		return null
	return posting

/// Binds it to `posting`: when that closes, the lair lets itself go
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_bind_posting(datum/criminal_bounty/kill_only/lair/posting)
	posting_ref = WEAKREF(posting)
	RegisterSignal(posting, COMSIG_BOUNTY_POSTING_CLOSED, PROC_REF(lair_on_posting_closed))

/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_on_posting_closed(datum/source, reason, obj/structure/overmap/ship/winner)
	SIGNAL_HANDLER
	lair_release()

/**
 * The bounty is over (release_lab): unhook, clear the lock, then delete a lair that never loaded, or leave a loaded
 * one to the normal cleanup, which takes it once nobody is inside. It is rare, so nothing replaces it.
 */
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_release()
	var/datum/criminal_bounty/posting = posting_ref?.resolve()
	if(posting)
		UnregisterSignal(posting, COMSIG_BOUNTY_POSTING_CLOSED)
	posting_ref = null
	lair_unhook_mobs()
	lair_clear_timers()
	if(QDELETED(src))
		return
	mission_locked = FALSE
	log_game("BOUNTY: [name] was released to cleanup")
	// Next tick: close() is still running and drops the posting's claim on us after this signal, and a claimed
	// ruin holds its position instead of going
	if(lair_release_timer)
		deltimer(lair_release_timer)
	lair_release_timer = addtimer(CALLBACK(src, PROC_REF(lair_finish_release)), 1, TIMER_STOPPABLE)

/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_finish_release()
	lair_release_timer = null
	if(QDELETED(src))
		return
	// A load in progress would finish on a deleted signal and strand its slot: let it land first
	if(loading)
		lair_release_timer = addtimer(CALLBACK(src, PROC_REF(lair_finish_release)), 10 SECONDS, TIMER_STOPPABLE)
		return
	if(!mapzone)
		qdel(src)
		return
	// Can wait on the worldgen queue
	INVOKE_ASYNC(src, PROC_REF(check_and_respawn))

/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_clear_timers()
	if(lair_trophy_timer)
		deltimer(lair_trophy_timer)
		lair_trophy_timer = null
	if(lair_goon_timer)
		deltimer(lair_goon_timer)
		lair_goon_timer = null

/// Stops listening to its bosses and gatekeepers
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_unhook_mobs()
	for(var/datum/weakref/ref as anything in lair_bosses + lair_gatekeepers)
		var/mob/living/lair_mob = ref?.resolve()
		if(lair_mob)
			lair_unwatch(lair_mob)
	lair_bosses = list()
	lair_gatekeepers = list()

/**
 * Watches `lair_mob` (a boss or a gatekeeper) with `gone_proc`: its death, or its deletion (an admin, or a DEL_ON_DEATH
 * body). Also refuses polymorph and type changes on it while the lair watches: those delete it without a death, and
 * would open the gate or end the fight for free.
 */
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_watch(mob/living/lair_mob, gone_proc)
	RegisterSignals(lair_mob, list(COMSIG_LIVING_DEATH, COMSIG_QDELETING), gone_proc, override = TRUE)
	RegisterSignal(lair_mob, COMSIG_LIVING_PRE_WABBAJACKED, PROC_REF(lair_refuse_polymorph), override = TRUE)
	RegisterSignal(lair_mob, COMSIG_PRE_MOB_CHANGED_TYPE, PROC_REF(lair_refuse_type_change), override = TRUE)
	// The don climbing out of his mech (P12) is the fight's next phase: taken on the moment he appears
	RegisterSignal(lair_mob, COMSIG_BOUNTY_MAFIA_DON_EJECTED, PROC_REF(lair_on_next_phase), override = TRUE)

/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_unwatch(mob/living/lair_mob)
	UnregisterSignal(lair_mob, list(COMSIG_LIVING_DEATH, COMSIG_QDELETING, COMSIG_LIVING_PRE_WABBAJACKED, COMSIG_PRE_MOB_CHANGED_TYPE, COMSIG_BOUNTY_MAFIA_DON_EJECTED))

/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_on_next_phase(datum/source, mob/living/next_boss)
	SIGNAL_HANDLER
	if(lair_posting() && !QDELETED(next_boss))
		lair_adopt_boss(next_boss)

/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_refuse_polymorph(datum/source, what_to_randomize)
	SIGNAL_HANDLER
	return STOP_WABBAJACK

/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_refuse_type_change(datum/source)
	SIGNAL_HANDLER
	return COMPONENT_BLOCK_MOB_CHANGE

/// Whether a living player is inside the lair itself: its footprint, but not aboard a ship docked there
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_has_crew_inside()
	if(!footprint)
		return FALSE
	for(var/mob/living/player in GLOB.player_list)
		if(player.stat == DEAD)
			continue
		var/turf/spot = get_turf(player)
		if(spot && footprint.contains_turf(spot) && !istype(spot.loc, /area/shuttle))
			return TRUE
	return FALSE

/// The middle of its template, where it landed (the slot is bigger than the club), or null when it isn't loaded
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_interior_center()
	if(ruin_bottom_left && ruin_template?.width && ruin_template?.height)
		return locate(ruin_bottom_left.x + round(ruin_template.width / 2), ruin_bottom_left.y + round(ruin_template.height / 2), ruin_bottom_left.z)
	return footprint?.get_center_turf()

// ----- Loading -----

/// The interior loaded: index it once, while its bounty is open
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_on_loaded(datum/source, loaded_ok)
	SIGNAL_HANDLER
	if(lair_linked || !loaded || !footprint)
		return
	if(!lair_posting())
		return
	lair_linked = TRUE
	// The sweep yields on a big footprint
	INVOKE_ASYNC(src, PROC_REF(lair_link_interior))

/**
 * Walks its own footprint once (up to four sites can share a z-level, so never the level): spawns the boss and the
 * gatekeepers on their landmarks, finds the gate poddoors, and keeps the boss, the gatekeepers and the goons to their
 * rooms. A boss already killed or a gate already open (a lair given back and loaded again) is not undone.
 */
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_link_interior()
	var/list/turfs = footprint?.get_block()
	if(!length(turfs))
		log_mapping("BOUNTY LAIR: [name] loaded with no footprint to index")
		lair_link_done = TRUE
		return
	var/list/boss_marks = list()
	var/list/keeper_marks = list()
	var/list/doors = list()
	for(var/turf/spot as anything in turfs)
		CHECK_TICK
		if(QDELETED(src) || !loaded)
			return
		if(!length(spot.contents) || istype(spot.loc, /area/shuttle))
			continue
		for(var/atom/movable/thing as anything in spot)
			if(istype(thing, /obj/effect/landmark/bounty_lair_boss))
				boss_marks += thing
			else if(istype(thing, /obj/effect/landmark/bounty_lair_gatekeeper))
				keeper_marks += thing
			else if(istype(thing, /obj/machinery/door/poddoor))
				var/obj/machinery/door/poddoor/door = thing
				if(door.id == BOUNTY_LAIR_GATE_ID)
					doors += door
	// The bounty may have closed while the sweep yielded: then there is nobody to spawn for
	if(QDELETED(src) || !loaded || !lair_posting())
		return

	lair_gate_doors = list()
	for(var/obj/machinery/door/poddoor/door as anything in doors)
		if(!QDELETED(door))
			lair_gate_doors += WEAKREF(door)

	for(var/obj/effect/landmark/bounty_lair_boss/mark as anything in boss_marks)
		if(QDELETED(mark))
			continue
		var/turf/home = get_turf(mark)
		var/boss_type = mark.boss_type
		qdel(mark)
		if(lair_boss_killed)
			continue
		if(!ispath(boss_type, /mob/living))
			log_mapping("BOUNTY LAIR: [name] has a boss landmark with no mob type at [AREACOORD(home)]")
			continue
		lair_adopt_boss(new boss_type(home))

	for(var/obj/effect/landmark/bounty_lair_gatekeeper/mark as anything in keeper_marks)
		if(QDELETED(mark))
			continue
		var/turf/home = get_turf(mark)
		var/keeper_type = mark.gatekeeper_type
		qdel(mark)
		if(lair_gate_open)
			continue
		if(!ispath(keeper_type, /mob/living))
			log_mapping("BOUNTY LAIR: [name] has a gatekeeper landmark with no mob type at [AREACOORD(home)]")
			continue
		lair_add_gatekeeper(new keeper_type(home))

	lair_leash_goons()
	lair_goon_timer = addtimer(CALLBACK(src, PROC_REF(lair_leash_goons)), BOUNTY_LAIR_GOON_LEASH_DELAY, TIMER_STOPPABLE)
	// Nobody left to hold the gate (none mapped, or it was opened before a reload): it stands open
	if(lair_gate_open || !length(lair_gatekeepers))
		lair_open_gate(silent = TRUE)
	lair_link_done = TRUE
	log_game("BOUNTY: [name] linked its interior: [length(lair_bosses)] boss(es), [length(lair_gatekeepers)] gatekeeper(s), [length(lair_gate_doors)] gate door(s)")

/**
 * The interior is being given back while the bounty is open (nothing does this while it is mission-locked, so this is
 * an admin or a bug): forget what was indexed, and link again at the next load. The rooms come back full then.
 */
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_on_unloading(datum/source)
	SIGNAL_HANDLER
	lair_unhook_mobs()
	lair_clear_timers()
	lair_gate_doors = list()
	lair_last_death_spot = null
	lair_linked = FALSE
	lair_link_done = FALSE
	if(lair_posting())
		log_game("BOUNTY: [name] gave its interior back while its bounty was open; it links again at the next load")

// ----- The boss -----

/// Takes `boss` on as one of the lair's bosses: wanted on its bounty, watched until it dies, kept to its room
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_adopt_boss(mob/living/boss)
	if(QDELETED(boss))
		return FALSE
	if(istype(boss, /mob/living/basic/bounty_lair_boss))
		var/mob/living/basic/bounty_lair_boss/lair_boss = boss
		lair_boss.posting_ref = posting_ref
	lair_bosses |= WEAKREF(boss)
	lair_watch(boss, PROC_REF(lair_on_boss_gone))
	lair_leash(boss)
	return TRUE

/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_on_boss_gone(mob/living/source)
	SIGNAL_HANDLER
	lair_unwatch(source)
	if(!(source.weak_reference in lair_bosses))
		return
	lair_bosses -= source.weak_reference
	var/turf/spot = get_turf(source)
	if(spot)
		lair_last_death_spot = spot
	// Death sets DEAD before its signal; a deletion of a living boss (an admin) comes here alive
	lair_last_boss_died = source.stat == DEAD
	if(lair_boss_killed || !lair_posting())
		return
	// Give its next phase (the don out of his wrecked mech) a moment to appear before calling it done
	if(lair_trophy_timer)
		deltimer(lair_trophy_timer)
	lair_trophy_timer = addtimer(CALLBACK(src, PROC_REF(lair_check_trophy)), BOUNTY_LAIR_TROPHY_GRACE, TIMER_STOPPABLE)

/**
 * A boss fell a moment ago. A lair boss still standing in the footprint (one we spawned, or the next phase of it,
 * which we take on now) means the fight goes on. Otherwise the boss is dead: its trophy, if its death dropped one,
 * becomes the bounty's proof, and if it didn't, one drops where it fell. A boss deleted alive (an admin) earned
 * nobody a trophy and can't come back, so the bounty closes.
 */
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_check_trophy()
	lair_trophy_timer = null
	var/datum/criminal_bounty/kill_only/lair/posting = lair_posting()
	if(!posting || lair_boss_killed)
		return
	var/standing = FALSE
	for(var/mob/living/basic/bounty_lair_boss/boss as anything in lair_bosses_inside())
		if(boss.stat == DEAD)
			continue
		if(!boss.weak_reference || !(boss.weak_reference in lair_bosses))
			lair_adopt_boss(boss)
		standing = TRUE
	for(var/datum/weakref/ref as anything in lair_bosses.Copy())
		var/mob/living/boss = ref?.resolve()
		if(QDELETED(boss))
			lair_bosses -= ref
			continue
		if(boss.stat != DEAD)
			standing = TRUE
	if(standing)
		return
	lair_boss_killed = TRUE
	if(posting.board_proof())
		return
	var/obj/item/bounty_proof/trophy/loose = lair_find_trophy(posting)
	if(loose)
		posting.kill_bind_trophy(loose)
		return
	if(!lair_last_boss_died)
		log_game("BOUNTY: [name]'s boss was deleted without dying; closing its bounty")
		posting.close(BOUNTY_CLOSE_LAIR_GONE)
		return
	var/obj/item/bounty_proof/trophy/trophy = posting.kill_drop_trophy(lair_last_death_spot || lair_interior_center())
	if(!trophy)
		trophy = posting.kill_drop_trophy(lair_interior_center())
	if(trophy)
		log_game("BOUNTY: [name]'s boss is dead; its trophy dropped at [AREACOORD(trophy)]")
		return
	// Nowhere safe to put it: better a closed bounty than one nobody can ever finish
	log_game("BOUNTY: [name]'s boss is dead but there was no safe floor for its trophy; closing its bounty")
	posting.close(BOUNTY_CLOSE_LAIR_GONE)

/// Every lair boss standing in its footprint
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_bosses_inside()
	. = list()
	if(!footprint)
		return
	for(var/mob/living/basic/bounty_lair_boss/boss in GLOB.mob_living_list)
		if(!QDELETED(boss) && footprint.contains_turf(get_turf(boss)))
			. += boss

/// A trophy already bound to `posting` near where the boss fell (a boss's death that made its own)
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_find_trophy(datum/criminal_bounty/kill_only/posting)
	if(!lair_last_death_spot)
		return null
	for(var/turf/spot as anything in RANGE_TURFS(7, lair_last_death_spot))
		for(var/obj/item/bounty_proof/trophy/trophy in spot)
			if(!QDELETED(trophy) && trophy.posting_ref?.resolve() == posting)
				return trophy
	return null

// ----- The gate -----

/// Takes `keeper` on as a gatekeeper: the gate opens once it and every other one are dead or gone
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_add_gatekeeper(mob/living/keeper)
	if(QDELETED(keeper))
		return FALSE
	lair_gatekeepers |= WEAKREF(keeper)
	// Troopers delete themselves on death and leave a corpse spawner: either signal counts, whichever comes first.
	// An admin deleting one counts as gone too: a gate that never opens is worse.
	lair_watch(keeper, PROC_REF(lair_on_gatekeeper_gone))
	lair_leash(keeper)
	return TRUE

/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_on_gatekeeper_gone(mob/living/source)
	SIGNAL_HANDLER
	lair_unwatch(source)
	if(!(source.weak_reference in lair_gatekeepers))
		return
	lair_gatekeepers -= source.weak_reference
	lair_check_gate()

/// Opens the gate if no gatekeeper is left standing. Returns TRUE if it opened now.
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_check_gate()
	if(lair_gate_open)
		return FALSE
	for(var/datum/weakref/ref as anything in lair_gatekeepers.Copy())
		var/mob/living/keeper = ref?.resolve()
		if(QDELETED(keeper) || keeper.stat == DEAD)
			lair_gatekeepers -= ref
			continue
		return FALSE
	lair_open_gate()
	return TRUE

/// Opens its gate poddoors, the ones in its own footprint only, and tells everyone inside unless `silent`
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_open_gate(silent = FALSE)
	lair_gate_open = TRUE
	var/list/opened = list()
	for(var/datum/weakref/ref as anything in lair_gate_doors)
		var/obj/machinery/door/poddoor/door = ref?.resolve()
		if(QDELETED(door) || !footprint?.contains_turf(get_turf(door)))
			continue
		opened += door
		INVOKE_ASYNC(door, TYPE_PROC_REF(/obj/machinery/door, open))
	if(!silent && length(opened))
		var/message = lair_kind?.gate_message || "Somewhere deeper in, a heavy door grinds open."
		for(var/mob/living/listener in GLOB.player_list)
			if(listener.stat != DEAD && footprint.contains_turf(get_turf(listener)))
				to_chat(listener, span_boldwarning(message))
	if(length(opened))
		log_game("BOUNTY: [name] opened its gate ([length(opened)] door(s))")
	return length(opened)

// ----- Keeping them in their rooms -----

/// Keeps `lair_mob` in the room it stands in now (balance/lairs.md 9.2: rooms never merge). Never a room of a docked ship.
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_leash(mob/living/lair_mob)
	if(QDELETED(lair_mob) || !footprint?.contains_turf(get_turf(lair_mob)))
		return FALSE
	var/area/home = get_area(lair_mob)
	if(!home || istype(home, /area/shuttle))
		return FALSE
	lair_mob.AddElement(/datum/element/bounty_lair_room_leash, home.type)
	return TRUE

/// Keeps every living goon of its kind in the room it stands in. Runs at the link, and again once every marker has spawned.
/obj/structure/overmap/space_ruin/bounty_lair/proc/lair_leash_goons()
	lair_goon_timer = null
	var/goon_type = lair_kind?.goon_type
	if(!goon_type || !footprint || !loaded)
		return 0
	var/count = 0
	for(var/mob/living/goon as anything in GLOB.mob_living_list)
		if(QDELETED(goon) || goon.stat == DEAD || !istype(goon, goon_type))
			continue
		if(lair_leash(goon))
			count++
	return count

/**
 * Keeps a lair mob in the room (area) it started in: it won't step out of it on its own, so it fights from the
 * doorway and a fight never drags the next room in (balance/lairs.md 9.2). Moves it doesn't make itself are never
 * stopped (pulled, thrown, or dead), and once it is out of its room it walks freely, so it can never be stuck.
 */
/datum/element/bounty_lair_room_leash
	element_flags = ELEMENT_BESPOKE
	argument_hash_start_idx = 2
	/// The area type it is kept to. A type, not the area: a lair's areas are per-load instances, and no ref is held.
	var/home_area_type

/datum/element/bounty_lair_room_leash/Attach(datum/target, home_area_type)
	. = ..()
	if(!isliving(target) || !ispath(home_area_type, /area))
		return ELEMENT_INCOMPATIBLE
	src.home_area_type = home_area_type
	RegisterSignal(target, COMSIG_MOVABLE_PRE_MOVE, PROC_REF(on_pre_move), override = TRUE)

/datum/element/bounty_lair_room_leash/Detach(datum/source)
	UnregisterSignal(source, COMSIG_MOVABLE_PRE_MOVE)
	return ..()

/datum/element/bounty_lair_room_leash/proc/on_pre_move(mob/living/source, atom/new_location)
	SIGNAL_HANDLER
	if(source.stat == DEAD || source.pulledby || source.throwing)
		return NONE
	var/area/here = get_area(source)
	if(here?.type != home_area_type)
		return NONE
	var/area/there = get_area(new_location)
	if(!there || there.type == home_area_type)
		return NONE
	return COMPONENT_MOVABLE_BLOCK_PRE_MOVE

// ===== KINDS OF LAIR =====

/**
 * One kind of lair: its template, the boss the card names, its pay and its trophy, and the clock that posts it. One
 * of each kind lives in SSbounty_lairs; at most one of a kind is on the board at a time.
 */
/datum/bounty_lair_kind
	/// Key in SSbounty_lairs.lair_kinds
	var/id
	/// What admins call it
	var/name
	/// Its ruin template (a /datum/map_template/ruin/space/bounty_lair subtype)
	var/template_type
	/// The card's name for the boss
	var/boss_name
	/// The card's crime, a lower-case phrase
	var/crime
	/// The card's species line
	var/species_name = "Human"
	/// The boss's sex on the card
	var/gender = MALE
	/// The boss's trophy (/obj/item/bounty_proof/trophy)
	var/trophy_type = /obj/item/bounty_proof/trophy
	/// The card's picture: an icon file and state
	var/mugshot_icon
	var/mugshot_state
	/// The goons it keeps to their rooms (its zone_mobs markers spawn them)
	var/goon_type
	/// What everyone inside is told when the gate opens
	var/gate_message
	/// Base credits, before the zone multiplier
	var/pay_min = BOUNTY_PAY_LAIR_MIN
	var/pay_max = BOUNTY_PAY_LAIR_MAX
	/// Trade vouchers; red space adds BOUNTY_RED_VOUCHER_BONUS
	var/vouchers = BOUNTY_VOUCHERS_LAIR
	/// Weakref to its open posting (/datum/criminal_bounty/kill_only/lair), if any
	var/datum/weakref/lair_live
	/// world.time it may be posted next; null until the clock first looks at it
	var/lair_next_due
	/// Its template is missing: the clock gives up on it for the round
	var/lair_disabled = FALSE

/datum/bounty_lair_kind/Destroy()
	lair_live = null
	return ..()

/// Its open posting, or null
/datum/bounty_lair_kind/proc/live()
	var/datum/criminal_bounty/kill_only/lair/posting = lair_live?.resolve()
	if(!istype(posting) || !posting.is_open())
		return null
	return posting

/// Its template, SSmapping's size-preloaded instance, or null
/datum/bounty_lair_kind/proc/find_template()
	for(var/template_name in SSmapping.space_ruins_templates)
		var/datum/map_template/ruin/space/candidate = SSmapping.space_ruins_templates[template_name]
		if(candidate?.type == template_type)
			return candidate
	return null

/// A zone band for it: yellow or red (spec 14.4)
/datum/bounty_lair_kind/proc/roll_band()
	return prob(100 * BOUNTY_LAIR_WEIGHT_RED / (BOUNTY_LAIR_WEIGHT_YELLOW + BOUNTY_LAIR_WEIGHT_RED)) ? ZONE_RED : ZONE_YELLOW

/// Its card's picture
/datum/bounty_lair_kind/proc/mugshot()
	return bounty_kill_mugshot(mugshot_icon, mugshot_state)

/// Watches `posting`: when it closes, the next of this kind waits BOUNTY_LAIR_GAP_MIN to _MAX
/datum/bounty_lair_kind/proc/lair_track(datum/criminal_bounty/kill_only/lair/posting)
	lair_live = WEAKREF(posting)
	RegisterSignal(posting, COMSIG_BOUNTY_POSTING_CLOSED, PROC_REF(lair_on_closed))

/datum/bounty_lair_kind/proc/lair_on_closed(datum/source, reason, obj/structure/overmap/ship/winner)
	SIGNAL_HANDLER
	UnregisterSignal(source, COMSIG_BOUNTY_POSTING_CLOSED)
	lair_live = null
	lair_next_due = world.time + rand(BOUNTY_LAIR_GAP_MIN, BOUNTY_LAIR_GAP_MAX)

/**
 * The clock's look at this kind at `now`, with `ships` active crews: posts it when its time has come, 3 or more crews
 * are out, and none of its kind is up. The first comes BOUNTY_LAIR_FIRST_AFTER plus up to BOUNTY_LAIR_FIRST_SPREAD
 * into the round. Returns the posting, or null.
 */
/datum/bounty_lair_kind/proc/lair_maybe_post(now = world.time, ships = 0)
	if(lair_disabled || live())
		return null
	if(isnull(lair_next_due))
		lair_next_due = SSticker.round_start_time + BOUNTY_LAIR_FIRST_AFTER + rand(0, BOUNTY_LAIR_FIRST_SPREAD)
	if(now < lair_next_due || ships < BOUNTY_LAIR_MIN_SHIPS)
		return null
	if(!find_template())
		lair_disabled = TRUE
		log_mapping("BOUNTY LAIR: the [name] template ([template_type]) is not registered; no [name] lair this round")
		return null
	var/datum/criminal_bounty/kill_only/lair/posting = bounty_post_lair(src)
	if(!posting)
		lair_next_due = now + BOUNTY_LAIR_RETRY
	return posting

/// Club Volga: the Russian mafia's club, cleared room by room to the don's mech in the garage (spec 14.4)
/datum/bounty_lair_kind/mafia_club
	id = "mafia_club"
	name = "Club Volga"
	template_type = /datum/map_template/ruin/space/bounty_lair/mafia_club
	boss_name = "Arkady Sokolov"
	crime = "racketeering and murder"
	trophy_type = /obj/item/bounty_proof/trophy/mafia_don
	mugshot_icon = 'icons/mob/rideables/mecha.dmi'
	mugshot_state = "mauler"
	goon_type = /mob/living/basic/trooper/russian/mafia
	gate_message = "The garage door grinds open."

/**
 * Posts a `kind` lair now: its template (or `template`), on a free overmap square in zone band `band` (or a yellow or
 * red one it rolls, then the other if that is full), rare, surveyed, mission-locked and claimed by its kill-only
 * bounty. Returns the posting, or null (one of the kind is already up, no template, or no free square).
 */
/proc/bounty_post_lair(datum/bounty_lair_kind/kind, band, datum/map_template/ruin/space/template)
	if(!kind || kind.live())
		return null
	template ||= kind.find_template()
	if(!template)
		log_mapping("BOUNTY LAIR: no template for [kind.name] ([kind.template_type]); it can't be posted")
		return null
	band ||= kind.roll_band()
	var/turf/spawn_turf = SSovermap.get_unused_overmap_square_in_zone_band(band, tries = BOUNTY_LAIR_OVERMAP_TRIES)
	if(!spawn_turf)
		band = band == ZONE_RED ? ZONE_YELLOW : ZONE_RED
		spawn_turf = SSovermap.get_unused_overmap_square_in_zone_band(band, tries = BOUNTY_LAIR_OVERMAP_TRIES)
	if(!spawn_turf)
		log_game("BOUNTY: no free square in yellow or red space for a [kind.name] lair")
		return null

	// The posting first (the icon work can't fail halfway through a locked lair)
	var/datum/criminal_bounty/kill_only/lair/posting = new
	posting.lair_kind = kind
	posting.kill_trophy_type = kind.trophy_type
	posting.kill_species = kind.species_name
	posting.record = bounty_kill_record(kind.boss_name, kind.crime, kind.gender, rand(kind.pay_min, kind.pay_max), kind.mugshot())

	var/obj/structure/overmap/space_ruin/bounty_lair/lair = new(spawn_turf)
	if(QDELETED(lair))
		qdel(posting)
		return null
	lair.lair_kind = kind
	lair.set_ruin_template(template)
	// Rare: never replaced when it is cleaned up. Surveyed: the bounty is public, and so is where it is.
	lair.mark_rare()
	lair.on_surveyed()
	var/zone = SScriminal_bounties.board_site_zone(lair)
	var/vouchers = kind.vouchers + (zone == ZONE_RED ? BOUNTY_RED_VOUCHER_BONUS : 0)
	posting.kill_publish(lair, zone, vouchers, BOUNTY_LAIR_EXPIRY)
	lair.lair_bind_posting(posting)
	kind.lair_track(posting)
	// Locked last: a lair is never held for the round without the bounty that lets it go
	lair.mission_locked = TRUE
	posting.kill_announce()
	return posting

// ===== THE LAIR CLOCK =====

SUBSYSTEM_DEF(bounty_lairs)
	name = "Bounty Lairs"
	wait = BOUNTY_LAIR_TICK
	// Nothing to set up while the world loads: the kinds are made the first time they are asked for
	flags = SS_BACKGROUND | SS_NO_INIT
	runlevels = RUNLEVEL_GAME
	/// Every kind of lair (/datum/bounty_lair_kind), by id. Use lair_kinds().
	var/list/lair_kinds
#ifdef UNIT_TESTS
	/// Whether the clock posts lairs on its own. Off in tests, which post their own.
	var/lair_auto_post = FALSE
#else
	/// Whether the clock posts lairs on its own. Off in tests, which post their own.
	var/lair_auto_post = TRUE
#endif

/datum/controller/subsystem/bounty_lairs/fire(resumed)
	lair_tick()

/datum/controller/subsystem/bounty_lairs/stat_entry(msg)
	var/live = 0
	var/list/kinds = lair_kinds()
	for(var/id in kinds)
		var/datum/bounty_lair_kind/kind = kinds[id]
		if(kind.live())
			live++
	msg = "L:[live]"
	return ..()

/// Every kind of lair, by id, made the first time it is asked for
/datum/controller/subsystem/bounty_lairs/proc/lair_kinds()
	if(isnull(lair_kinds))
		lair_kinds = list()
		for(var/kind_type in subtypesof(/datum/bounty_lair_kind))
			var/datum/bounty_lair_kind/kind = new kind_type
			lair_kinds[kind.id] = kind
	return lair_kinds

/// The clock: each kind of lair that is due goes up
/datum/controller/subsystem/bounty_lairs/proc/lair_tick(now = world.time)
	if(!lair_auto_post)
		return
	var/ships = SScriminal_bounties.board_active_ships()
	var/list/kinds = lair_kinds()
	for(var/id in kinds)
		var/datum/bounty_lair_kind/kind = kinds[id]
		kind.lair_maybe_post(now, ships)

ADMIN_VERB(post_bounty_lair, R_ADMIN, "Post Bounty Lair", "Post a kill-only lair bounty now, ignoring its clock and the number of crews.", ADMIN_CATEGORY_EVENTS)
	var/list/choices = list()
	var/list/kinds = SSbounty_lairs.lair_kinds()
	for(var/id in kinds)
		var/datum/bounty_lair_kind/kind = kinds[id]
		choices[kind.name] = kind
	var/choice = tgui_input_list(user, "Which lair?", "Post Bounty Lair", choices)
	if(!choice)
		return
	var/datum/bounty_lair_kind/chosen = choices[choice]
	if(chosen.live())
		to_chat(user, span_warning("[chosen.name] is already on the board."))
		return
	var/datum/criminal_bounty/kill_only/lair/posting = bounty_post_lair(chosen)
	if(!posting)
		to_chat(user, span_warning("Could not post [chosen.name]: no free square in yellow or red space, or its template is missing."))
		return
	var/obj/structure/overmap/site = posting.site()
	var/list/coords = site?.get_relative_overmap_coords()
	var/where = coords ? " at grid [coords[1]], [coords[2]]" : ""
	message_admins("[key_name_admin(user)] posted the [chosen.name] lair bounty[where].")
	log_admin("[key_name(user)] posted the [chosen.name] lair bounty[where].")
	BLACKBOX_LOG_ADMIN_VERB("Post Bounty Lair")

// ===== THE LICH (spec 14.3) =====

/// Ilthuun's kill-only bounty, on GLOB.lich_lair. Its clock holds while he lives.
/datum/criminal_bounty/kill_only/lich
	kill_trophy_type = /obj/item/bounty_proof/trophy/lich
	kill_species = "Undead"
	/// Ilthuun is dead, and the clock runs
	var/lich_slain = FALSE

/datum/criminal_bounty/kill_only/lich/Destroy()
	var/obj/structure/overmap/site = site_ref?.resolve()
	if(site)
		UnregisterSignal(site, COMSIG_BOUNTY_LICH_SLAIN)
	return ..()

/datum/criminal_bounty/kill_only/lich/board_clock_held(now = world.time)
	if(!lich_slain && site())
		return TRUE
	return ..()

/**
 * Once his lair has linked, he has to still be there: removed without dying (a polymorph, an admin), nothing can ever
 * drop his shard and the lair never unloads, so the bounty closes. Checked on the board's tick, never from the card.
 */
/datum/criminal_bounty/kill_only/lich/board_process(elapsed)
	if(is_open() && !lich_slain)
		var/obj/structure/overmap/space_ruin/lich_lair/site = site()
		if(istype(site) && site.linked && !site.spent && !site.lich_ref?.resolve())
			log_game("BOUNTY: Ilthuun is gone from [site.name] without dying; closing his bounty")
			close(BOUNTY_CLOSE_LAIR_GONE)
			return
	return ..()

/// He died: the shard of his crown drops at the corpse, and the bounty's clock starts
/datum/criminal_bounty/kill_only/lich/proc/lich_on_slain(datum/source, mob/living/slain)
	SIGNAL_HANDLER
	if(!is_open() || lich_slain)
		return
	lich_slain = TRUE
	var/atom/where = slain
	if(!get_turf(where))
		var/obj/structure/overmap/space_ruin/lich_lair/site = source
		where = istype(site) ? (site.hoard_turf || site.footprint?.get_center_turf()) : null
	var/obj/item/bounty_proof/trophy/shard = kill_drop_trophy(where)
	expires_at = max(expires_at, world.time + BOUNTY_LICH_EXPIRY_AFTER_KILL)
	log_game("BOUNTY: Ilthuun is dead; [shard ? "the crown shard dropped at [AREACOORD(shard)]" : "there was nowhere to drop the crown shard"]")

/// The open lich bounty on `site`, or null
/proc/bounty_lich_posting(obj/structure/overmap/space_ruin/lich_lair/site)
	for(var/datum/criminal_bounty/kill_only/lich/posting in GLOB.criminal_bounties)
		if(posting.is_open() && posting.site() == site)
			return posting
	return null

/**
 * Posts Ilthuun's kill-only Most Wanted on `site`, the lair that just surfaced (surface_lich_lair() calls this): the
 * Most Wanted band times BOUNTY_LICH_PAY_MULT in its zone, plus the Most Wanted vouchers. One per lair, and none once
 * he is dead. Returns the posting.
 */
/proc/bounty_post_lich(obj/structure/overmap/space_ruin/lich_lair/site)
	if(QDELETED(site) || site.spent)
		return null
	var/datum/criminal_bounty/kill_only/lich/existing = bounty_lich_posting(site)
	if(existing)
		return existing
	var/base_value = round(SScriminal_bounties.board_roll_base_value(BOUNTY_TIER_MOST_WANTED) * BOUNTY_LICH_PAY_MULT, 10)
	var/datum/criminal_bounty/kill_only/lich/posting = new
	posting.record = bounty_kill_record("Ilthuun, the Lich", "necromancy and mass murder", MALE, base_value, bounty_kill_mugshot('voidcrew/modules/lich/icons/lich.dmi', "lich"))
	var/zone = SScriminal_bounties.board_site_zone(site)
	posting.kill_publish(site, zone, SScriminal_bounties.board_vouchers_for(BOUNTY_TIER_MOST_WANTED, zone), BOUNTY_LICH_EXPIRY_AFTER_KILL)
	posting.RegisterSignal(site, COMSIG_BOUNTY_LICH_SLAIN, TYPE_PROC_REF(/datum/criminal_bounty/kill_only/lich, lich_on_slain))
	posting.kill_announce()
	return posting
