//Shuttle unlocks
#define SHUTTLE_UNLOCK_EMAGGED "emagged"

#define SHUTTLE_DOCKER_BLOCKED_BY_MOB 4
#define SHUTTLE_DOCKER_BLOCKED_BY_AREA 5

// max reserve shuttle dock size defines

// neither of the shuttle's dimensions should exceed this size if it is to dock at encounters
#define RESERVE_DOCK_MAX_SIZE_LONG 56
// only one of the shuttle's dimensions may exceed this size if it is to dock at encounters
#define RESERVE_DOCK_MAX_SIZE_SHORT 40
// default # of tiles of padding around an autogenerated reserve shuttle dock
#define RESERVE_DOCK_DEFAULT_PADDING 3

// Jump status defines
#define BS_JUMP_IDLE 0
#define BS_JUMP_CALLED 1
#define BS_JUMP_INITIATED 2
#define BS_JUMP_COMPLETED 3

// Cargo shuttle state defines
#define CARGO_SHUTTLE_AWAY 0
#define CARGO_SHUTTLE_ARRIVING 1
#define CARGO_SHUTTLE_DOCKED 2
#define CARGO_SHUTTLE_DEPARTING 3

#define CARGO_SHUTTLE_WARMUP (30 SECONDS)
#define CARGO_SHUTTLE_DEPARTURE_WARMUP (5 SECONDS)

/// How far past its own warmup a cargo shuttle may run before check_stalled() tears it
/// down. Has to clear the slowest legitimate arrival - a load_level() retry plus the
/// docking move itself - without leaving a wedged ship parked for long.
#define CARGO_SHUTTLE_STALL_GRACE (60 SECONDS)
/// Ceiling on the once-a-second "wait for the encounter to finish loading" retries in
/// complete_arrival(), so a level that never loads can't spin the warmup forever.
#define CARGO_SHUTTLE_MAX_LOAD_RETRIES 60
