/**
 * # Outpost prison: bounty prisoners
 *
 * Owner: P7 prison (bounty hunting). Owns this file, voidcrew/_DEFINES/outpost_prison_bounty.dm, the
 * bounty badge in tgui/packages/tgui/interfaces/OutpostPrison.tsx, the bounty block in
 * OutpostManipulator.tsx and the tests in
 * voidcrew/modules/unit_tests/voidcrew_outpost_prison_bounty.dm. Do not edit this file outside P7.
 *
 * What it owns (spec section 8, with 12.1-12.3): the prisoner pool (GLOB.bounty_prisoner_pool) and
 * the intake picker; rebuilding a caught criminal as a prisoner from their record; their danger in
 * the wing by tier; what they earn the outpost; closing their record on every way out; keeping
 * Kessler's experiments off them; the warden's intake setting and the notice of the next bounty
 * arrival; the warden roster badge, the examine line and the admin block.
 *
 * The pool. A criminal caught alive joins the pool (bounty_pool_add()), reserved for a while for
 * their captor's own running prison, and leaves it closed after BOUNTY_RECORD_LIFE if no prison
 * takes them. While the pool holds anyone its clock (bounty_pool_tick()) runs: once a wing's next
 * arrival is BOUNTY_PRISON_NOTICE_WINDOW seconds off, it picks the wing's next bounty arrival and
 * names it in the log, and on the warden's console once it is the arrival due next. The wing's
 * arrival lanes take that record only
 * once it has been named for BOUNTY_PRISON_NOTICE_TIME (bounty_pool_take()); until then, and
 * whenever no record is named, an arrival is an ordinary prisoner, exactly as before. The picker
 * takes records reserved for the wing first, oldest first, then open records. A record is open when
 * it has no captor's prison, that prison is gone or not running or refuses it, it has waited
 * BOUNTY_RECORD_RESERVE, that prison has had no cell ready for an arrival for
 * BOUNTY_RECORD_RESERVE_NO_CELL, or that prison already has one reserved record a lane waiting.
 * A wing takes no more bounty prisoners than its warden's setting allows, at most half its cells at
 * once and at most one Most Wanted a lane. The record leaves the pool as it is taken, before the
 * prisoner is built, with nothing in between that sleeps, so no two wings ever draw one record.
 *
 * The prison calls in here from one-line hooks in its own files (P0): admit_next() takes a record;
 * a prisoner's Initialize(mapload, record) applies it; pay, blows, mood, threats, riots, tension,
 * breakouts and cuffing ask the helpers below; every way a prisoner leaves closes their record.
 * Records, the prisoner's `bounty_record` and the shared enums are declared elsewhere
 * (bounty_types.dm, outpost_prison_prisoner.dm, voidcrew/_DEFINES/bounties.dm); a var only P7 uses
 * goes here with a `prison_` prefix.
 *
 * Meek bounty prisoners also go over an open serving hatch sooner and faster, and hang about by the
 * staff door to dart through it when staff open it. Both are leisure activities below, which the
 * prisoner's routine picks by weight like any other.
 *
 * A bounty prisoner remembers the crew who caught them: they name that ship as they beam in
 * (bounty_arrival_speech(), from finish_beam_in()) and now and then call its crew out in the yard
 * (bounty_extra_speech(), from extra_speech()). Those lines are in strings/outpost_prison_bounty.json,
 * one of the extras' dialogue files, since they name the ship through {place}.
 *
 * The prisoner procs here are new procs, never overrides of the prisoner's own: this file is
 * included before outpost_prison_prisoner.dm, so an override here would run inside that file's
 * definition, or not at all.
 */

// What an activity's tick() wants next, as in outpost_prison_routine.dm (which undefines its own)
#define BOUNTY_PRISON_ACTIVITY_CONTINUE 0
#define BOUNTY_PRISON_ACTIVITY_DONE 1

/// What a Most Wanted prisoner says they are in for in the yard ({crime}): their real crime is no line to toss off (BUG-12)
#define BOUNTY_PRISON_MOST_WANTED_YARD_CRIME "a lot of things"
/// Percent chance a bounty prisoner with a captor in view calls them out, when the yard's talk comes round to them
#define BOUNTY_PRISON_CAPTOR_LINE_CHANCE 30
/// How long a bounty prisoner waits before calling out their captors again
#define BOUNTY_PRISON_CAPTOR_LINE_GAP (3 MINUTES)
/// How far a bounty prisoner looks for someone off the ship that caught them
#define BOUNTY_PRISON_CAPTOR_VIEW 5

// ===== PRIVATE STATE =====

/datum/bounty_record
	/// world.time they joined the prisoner pool
	var/prison_pooled_at = 0
	/// Weakref to the prison they are named to as its next bounty arrival (/datum/outpost_prison), and the world.time they were
	var/datum/weakref/prison_notice_ref
	var/prison_notice_at = 0
	/// REF() of every prison they have been named to, so a wing's log and crew hear about them once however often the name drops and comes back
	var/list/prison_announced_to

/datum/outpost_prison
	/// Which bounty prisoners the warden takes: BOUNTY_PRISON_INTAKE_ALL, _NO_MOST_WANTED or _NONE
	var/prison_bounty_intake = BOUNTY_PRISON_INTAKE_ALL
	/// world.time since which the wing has had no cell ready for an arrival, while the pool holds anyone; null while it has one
	var/prison_bounty_no_cell_since
	/// For tests: whether a meek prisoner watching the staff door darts when it opens (TRUE or FALSE) instead of rolling for it
	var/prison_bounty_forced_dart

/mob/living/basic/outpost_prisoner
	/// Running after a bounty prisoner called out someone off the ship that caught them (bounty_extra_speech())
	COOLDOWN_DECLARE(prison_captor_line_cooldown)

/// The pool's clock (bounty_pool_tick()), while the pool holds anyone
GLOBAL_VAR(bounty_pool_timer)

// ===== THE POOL =====

/**
 * A criminal caught alive joins the pool, marked POOLED and reserved for the capturing crew's own
 * running prison if it has one and the board named none. A capture is never refused for room: at
 * BOUNTY_POOL_CAP the oldest open record leaves instead. A record that has been in prison, or ended
 * any other way, never comes back. Returns TRUE if it is in the pool.
 */
/proc/bounty_pool_add(datum/bounty_record/record)
	if(!istype(record) || QDELETED(record))
		return FALSE
	bounty_pool_prune()
	if(record in GLOB.bounty_prisoner_pool)
		return TRUE
	if(record.status != BOUNTY_RECORD_WANTED && record.status != BOUNTY_RECORD_POOLED)
		return FALSE
	record.status = BOUNTY_RECORD_POOLED
	record.prison_pooled_at = world.time
	record.prison_notice_ref = null
	record.prison_notice_at = 0
	if(!bounty_prison_running(record.preferred_prison?.resolve()))
		var/datum/outpost_prison/own = bounty_captor_prison(record.captor_ship?.resolve())
		record.preferred_prison = own ? WEAKREF(own) : null
	GLOB.bounty_prisoner_pool += record
	while(length(GLOB.bounty_prisoner_pool) > BOUNTY_POOL_CAP)
		var/datum/bounty_record/dropped = bounty_pool_drop_pick(record)
		if(!dropped)
			break
		bounty_pool_remove(dropped, BOUNTY_RECORD_CLOSED, "the pool was full")
	var/datum/outpost_prison/reserved = record.preferred_prison?.resolve()
	log_game("BOUNTY POOL: [record.name] ([bounty_tier_name(record.tier)]) joined the prisoner pool[reserved ? ", reserved for the prison at '[reserved.outpost?.name]'" : ""], [length(GLOB.bounty_prisoner_pool)] waiting")
	bounty_pool_start_tick()
	return TRUE

/**
 * The record `prison`'s next arrival is rebuilt from, taken out of the pool: the record named on
 * its console as its next bounty arrival, once named for BOUNTY_PRISON_NOTICE_TIME and still
 * acceptable to it. Null otherwise, and the arrival is an ordinary prisoner. The record leaves the
 * pool here, before the prisoner is built, with nothing in between that sleeps (AR-F7).
 */
/proc/bounty_pool_take(datum/outpost_prison/prison)
	if(QDELETED(prison))
		return null
	bounty_pool_prune()
	var/datum/bounty_record/record = prison.bounty_next_record()
	if(!record || world.time - record.prison_notice_at < BOUNTY_PRISON_NOTICE_TIME)
		return null
	bounty_pool_remove(record)
	record.status = BOUNTY_RECORD_IMPRISONED
	log_game("BOUNTY POOL: [record.name] ([bounty_tier_name(record.tier)]) taken by the prison at '[prison.outpost?.name]', [length(GLOB.bounty_prisoner_pool)] waiting")
	return record

/**
 * The record `prison` would take next, whether or not it is due an arrival: acceptable to it
 * (bounty_accepts()) and not named to another wing; those reserved for it first, then open ones,
 * oldest first. Null with none.
 */
/proc/bounty_pool_pick(datum/outpost_prison/prison)
	if(!bounty_prison_running(prison))
		return null
	var/datum/bounty_record/open_pick
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool)
		var/datum/outpost_prison/named = bounty_record_named_to(record)
		if(named && named != prison)
			continue
		if(!prison.bounty_accepts(record))
			continue
		var/datum/outpost_prison/reserved = bounty_record_reserved_for(record)
		if(reserved == prison)
			return record
		if(!reserved && !open_pick)
			open_pick = record
	return open_pick

/**
 * The prison `record` is still reserved for, or null when it is open to all: its captor's prison,
 * while that runs and would take it, for BOUNTY_RECORD_RESERVE at most, less once that wing has
 * had no cell ready for BOUNTY_RECORD_RESERVE_NO_CELL, and only for the oldest records waiting for
 * it, one a lane (AR-F3).
 */
/proc/bounty_record_reserved_for(datum/bounty_record/record)
	var/datum/outpost_prison/prison = record?.preferred_prison?.resolve()
	if(!bounty_prison_running(prison) || !bounty_reservation_holds(record, prison))
		return null
	var/ahead = 0
	for(var/datum/bounty_record/other in GLOB.bounty_prisoner_pool)
		if(other == record)
			break
		if(other.preferred_prison?.resolve() == prison && bounty_reservation_holds(other, prison))
			ahead++
	return ahead < prison.arrival_lanes() ? prison : null

/**
 * Whether `record`'s wait for `prison` has not run out: the wing would take them now (its setting,
 * its share of bounty prisoners, one Most Wanted a lane), they have not waited BOUNTY_RECORD_RESERVE,
 * and it has not been without a ready cell for BOUNTY_RECORD_RESERVE_NO_CELL. A wing that can't take
 * them holds no place for them in the "ahead" tally either.
 */
/proc/bounty_reservation_holds(datum/bounty_record/record, datum/outpost_prison/prison)
	if(world.time - record.prison_pooled_at >= BOUNTY_RECORD_RESERVE)
		return FALSE
	if(!isnull(prison.prison_bounty_no_cell_since) && world.time - prison.prison_bounty_no_cell_since >= BOUNTY_RECORD_RESERVE_NO_CELL)
		return FALSE
	return prison.bounty_accepts(record)

/// The prison `record` is named to as its next bounty arrival, while that stands (the wing runs and would still take them), or null
/proc/bounty_record_named_to(datum/bounty_record/record)
	var/datum/outpost_prison/prison = record?.prison_notice_ref?.resolve()
	if(!bounty_prison_running(prison) || !prison.bounty_accepts(record))
		return null
	return prison

/// Whether `prison` is a live prison wing its owner still runs: the outpost's own wing, on an outpost someone owns
/proc/bounty_prison_running(datum/outpost_prison/prison)
	if(QDELETED(prison) || !(prison in GLOB.outpost_prisons))
		return FALSE
	var/obj/structure/overmap/dynamic/player_outpost/home = prison.outpost
	return !QDELETED(home) && home.running_prison() == prison && !!home.founder_ckey

/// The capturing ship's own running prison: the first outpost founded whose owner crews `ship` and that runs a prison wing (AR-F5), or null
/proc/bounty_captor_prison(obj/structure/overmap/ship/ship)
	if(QDELETED(ship))
		return null
	for(var/obj/structure/overmap/dynamic/player_outpost/home as anything in GLOB.player_outposts)
		if(QDELETED(home) || !home.is_owner_crew_ship(ship))
			continue
		var/datum/outpost_prison/prison = home.running_prison()
		if(bounty_prison_running(prison))
			return prison
	return null

/// Which record leaves a full pool: the oldest open one (reserved for nobody and named to no wing), else the oldest named to no wing, else the oldest; never `keep`
/proc/bounty_pool_drop_pick(datum/bounty_record/keep)
	var/datum/bounty_record/unnamed
	var/datum/bounty_record/oldest
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool)
		if(record == keep)
			continue
		if(!oldest)
			oldest = record
		if(bounty_record_named_to(record))
			continue
		if(!unnamed)
			unnamed = record
		if(!bounty_record_reserved_for(record))
			return record
	return unnamed || oldest

/// Takes `record` out of the pool, setting `status` if given and logging `why` if given
/proc/bounty_pool_remove(datum/bounty_record/record, status, why)
	if(!record)
		return
	GLOB.bounty_prisoner_pool -= record
	record.prison_notice_ref = null
	record.prison_notice_at = 0
	if(status)
		record.status = status
	if(why)
		log_game("BOUNTY POOL: [record.name] ([bounty_tier_name(record.tier)]) left the prisoner pool: [why]")

/// Drops anything that is not a live record, and closes records left in the pool BOUNTY_RECORD_LIFE
/proc/bounty_pool_prune()
	var/list/pool = GLOB.bounty_prisoner_pool
	for(var/entry in pool.Copy())
		var/datum/bounty_record/record = entry
		if(!istype(record) || QDELETED(record))
			pool -= entry
			continue
		if(world.time - record.prison_pooled_at >= BOUNTY_RECORD_LIFE)
			bounty_pool_remove(record, BOUNTY_RECORD_CLOSED, "no prison took them in [DisplayTimeText(BOUNTY_RECORD_LIFE)]")
	list_clear_nulls(pool)

/// Closes every record in the pool and stops its clock. Returns how many there were.
/proc/bounty_pool_clear(why)
	var/count = 0
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool.Copy())
		bounty_pool_remove(record, BOUNTY_RECORD_CLOSED, why)
		count++
	GLOB.bounty_prisoner_pool.Cut()
	if(GLOB.bounty_pool_timer)
		deltimer(GLOB.bounty_pool_timer)
		GLOB.bounty_pool_timer = null
	return count

/// The record in the pool with this id, or null
/proc/bounty_pool_find(id)
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool)
		if("[record.id]" == "[id]")
			return record
	return null

/// Starts the pool's clock, unless it is running or the pool is empty
/proc/bounty_pool_start_tick()
	if(GLOB.bounty_pool_timer || !length(GLOB.bounty_prisoner_pool))
		return
	GLOB.bounty_pool_timer = addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(bounty_pool_tick)), BOUNTY_POOL_TICK, TIMER_STOPPABLE)

/**
 * The pool's clock, every BOUNTY_POOL_TICK while it holds anyone: old records leave, and each
 * running wing, in a random order so the first wing built gets no head start (AR-F6), updates its
 * no-ready-cell clock and its named next bounty arrival. With the pool empty the clock stops, and
 * the wings' no-ready-cell clocks start afresh with the next record. The next tick is set up first,
 * so a runtime in one wing can't stop the clock.
 */
/proc/bounty_pool_tick()
	GLOB.bounty_pool_timer = null
	bounty_pool_start_tick()
	bounty_pool_prune()
	if(!length(GLOB.bounty_prisoner_pool))
		if(GLOB.bounty_pool_timer)
			deltimer(GLOB.bounty_pool_timer)
			GLOB.bounty_pool_timer = null
		for(var/datum/outpost_prison/prison as anything in GLOB.outpost_prisons)
			prison.prison_bounty_no_cell_since = null
		return
	for(var/datum/outpost_prison/prison as anything in shuffle(GLOB.outpost_prisons))
		if(!bounty_prison_running(prison))
			continue
		prison.bounty_note_ready_cells()
		prison.bounty_update_notice()

// ===== THE WING'S INTAKE =====

/// Whether the warden's setting lets `record` in
/datum/outpost_prison/proc/bounty_setting_allows(datum/bounty_record/record)
	switch(prison_bounty_intake)
		if(BOUNTY_PRISON_INTAKE_NONE)
			return FALSE
		if(BOUNTY_PRISON_INTAKE_NO_MOST_WANTED)
			return record?.tier != BOUNTY_TIER_MOST_WANTED
	return TRUE

/// Whether the wing would take `record` now: the warden's setting, at most half its cells in bounty prisoners, and at most one Most Wanted a lane
/datum/outpost_prison/proc/bounty_accepts(datum/bounty_record/record)
	if(!record || !bounty_setting_allows(record))
		return FALSE
	if(bounty_prisoner_count() >= bounty_prisoner_max())
		return FALSE
	if(record.tier == BOUNTY_TIER_MOST_WANTED && bounty_prisoner_count(BOUNTY_TIER_MOST_WANTED) >= arrival_lanes())
		return FALSE
	return TRUE

/// Living bounty prisoners on the roster who are not leaving, of `tier` when given
/datum/outpost_prison/proc/bounty_prisoner_count(tier)
	. = 0
	for(var/mob/living/basic/outpost_prisoner/prisoner in prisoners)
		if(!prisoner.bounty_record || prisoner.stat == DEAD || prisoner.phase == PRISONER_LEAVING)
			continue
		if(tier && prisoner.bounty_record.tier != tier)
			continue
		.++

/// Bounty prisoners the wing holds at once: half its cells
/datum/outpost_prison/proc/bounty_prisoner_max()
	return OUTPOST_PRISON_BOUNTY_MAX(capacity)

/// Whether a cell could take an arrival now: empty, ready, and taking arrivals
/datum/outpost_prison/proc/bounty_has_ready_cell()
	if(!free_slots())
		return FALSE
	for(var/datum/outpost_prison_cell/cell as anything in cells)
		if(!cell.occupant && cell.ready_at <= world.time && cell_takes_arrivals(cell))
			return TRUE
	return FALSE

/// Runs the no-ready-cell clock: records reserved for this wing open to all once it has had no cell ready for BOUNTY_RECORD_RESERVE_NO_CELL
/datum/outpost_prison/proc/bounty_note_ready_cells()
	if(bounty_has_ready_cell())
		prison_bounty_no_cell_since = null
	else if(isnull(prison_bounty_no_cell_since))
		prison_bounty_no_cell_since = world.time

/// The record named as the wing's next bounty arrival, while that stands, or null
/datum/outpost_prison/proc/bounty_next_record()
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool)
		if(record.prison_notice_ref?.resolve() == src && bounty_record_named_to(record) == src)
			return record
	return null

/**
 * Keeps the wing's named next bounty arrival up to date. A name that no longer stands (the wing
 * stopped taking arrivals, or would refuse them now) is dropped, and the record is free for any
 * wing again. With no name, once the wing's next arrival is BOUNTY_PRISON_NOTICE_WINDOW seconds
 * off, the picker's record is named: on the console, and the first time it is named to this wing,
 * in the log and to the crew for a Most Wanted. Returns the named record, or null.
 */
/datum/outpost_prison/proc/bounty_update_notice()
	var/due = next_arrival_in()
	var/datum/bounty_record/named
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool)
		if(record.prison_notice_ref?.resolve() != src)
			continue
		if(named || isnull(due) || bounty_record_named_to(record) != src)
			record.prison_notice_ref = null
			record.prison_notice_at = 0
			continue
		named = record
	if(named || isnull(due) || due > BOUNTY_PRISON_NOTICE_WINDOW)
		return named
	named = bounty_pool_pick(src)
	if(!named)
		return null
	named.prison_notice_ref = WEAKREF(src)
	named.prison_notice_at = world.time
	// Told once per wing: a name dropped when the wing filled up and named again says nothing new.
	if(REF(src) in named.prison_announced_to)
		return named
	LAZYADD(named.prison_announced_to, REF(src))
	add_log(named.tier == BOUNTY_TIER_MOST_WANTED ? "Bounty transfer due: [named.name], Most Wanted." : "Bounty transfer due: [named.name].")
	if(named.tier == BOUNTY_TIER_MOST_WANTED)
		announce("Prison wing: a Most Wanted prisoner, [named.name], is being transferred in.", SHIP_NOTIFY_WARNING)
	return named

/**
 * Sets the warden's bounty intake setting (BOUNTY_PRISON_INTAKE_*). A named arrival the wing no
 * longer takes goes back to the pool for another wing. Returns FALSE for a setting that isn't one.
 */
/datum/outpost_prison/proc/set_bounty_intake(setting, mob/user)
	if(!(setting in list(BOUNTY_PRISON_INTAKE_ALL, BOUNTY_PRISON_INTAKE_NO_MOST_WANTED, BOUNTY_PRISON_INTAKE_NONE)))
		return FALSE
	if(setting == prison_bounty_intake)
		return TRUE
	prison_bounty_intake = setting
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool)
		if(record.prison_notice_ref?.resolve() == src && !bounty_setting_allows(record))
			record.prison_notice_ref = null
			record.prison_notice_at = 0
	add_log("Bounty transfers: [bounty_intake_text(setting)].")
	if(user)
		log_game("PLAYER OUTPOST: [key_name(user)] set bounty transfers to [setting] at '[outpost?.name]'")
	return TRUE

/// How the console and the log put a bounty intake setting
/proc/bounty_intake_text(setting)
	switch(setting)
		if(BOUNTY_PRISON_INTAKE_NO_MOST_WANTED)
			return "no Most Wanted"
		if(BOUNTY_PRISON_INTAKE_NONE)
			return "none"
	return "all"

/**
 * Beams the prisoner `record` names into the first free cell now, ready or not: the admin panel's
 * forced admission, which takes this record and no other from the pool. Returns the prisoner, or
 * null with no free cell or the record gone from the pool.
 */
/datum/outpost_prison/proc/bounty_admit_record(datum/bounty_record/record)
	if(!(record in GLOB.bounty_prisoner_pool) || !free_slots())
		return null
	for(var/datum/outpost_prison_cell/cell as anything in cells)
		if(cell.occupant)
			continue
		var/turf/spot = cell.arrival_turf()
		if(!spot)
			continue
		bounty_pool_remove(record)
		record.status = BOUNTY_RECORD_IMPRISONED
		var/mob/living/basic/outpost_prisoner/prisoner = new(spot, record)
		admit(prisoner, cell)
		prisoner.beam_in()
		start_arrival_gap(soonest_lane())
		arrival_countdown = next_arrival_in()
		return prisoner
	return null

// ===== A PRISONER FROM A RECORD =====

/**
 * Before the prisoner's Initialize() calls ..(): the body their record says (gender, and health by
 * tier), so tg sizes max_stamina from the right maxHealth. A record still in the pool leaves it now,
 * before they exist.
 */
/mob/living/basic/outpost_prisoner/proc/apply_bounty_body(datum/bounty_record/record)
	if(record in GLOB.bounty_prisoner_pool)
		bounty_pool_remove(record)
	if(record.gender == MALE || record.gender == FEMALE)
		gender = record.gender
	maxHealth = bounty_by_tier(record.tier, BOUNTY_PRISONER_HEALTH_PETTY, BOUNTY_PRISONER_HEALTH_WANTED, BOUNTY_PRISONER_HEALTH_MOST_WANTED)
	health = maxHealth

/**
 * At the end of the prisoner's Initialize(), before their look is built: who their record says
 * they are (name, gender, crime, personality by archetype, arriving as hurt as they were caught,
 * but with at least BOUNTY_PRISONER_MIN_ARRIVAL_HEALTH percent of their health), with no gear. Their look comes from build_look(), which dresses them in the record's face and
 * the plain prison jumpsuit, the kingpin included. The crime stays the plain phrase ("smuggling"),
 * since the yard says "I'm in for {crime}"; the console and examine say "wanted for". A Most Wanted
 * prisoner's crime is too grim for the yard's lines ("Got pinched for {crime}. Long story."), so the
 * yard hears BOUNTY_PRISON_MOST_WANTED_YARD_CRIME, as a Most Wanted criminal never names theirs in
 * its own lines (BUG-12); the console and examine still read the record's.
 */
/mob/living/basic/outpost_prisoner/proc/apply_bounty_record(datum/bounty_record/record)
	if(record.gender == MALE || record.gender == FEMALE)
		gender = record.gender
	if(length(record.name))
		real_name = record.name
		name = real_name
	var/plain_crime = bounty_plain_crime(record.crime)
	if(record.tier == BOUNTY_TIER_MOST_WANTED)
		crime = BOUNTY_PRISON_MOST_WANTED_YARD_CRIME
	else if(plain_crime)
		crime = plain_crime
	var/list/personalities = bounty_archetype_personalities(record.archetype)
	if(length(personalities))
		personality = pick(personalities)
	// The plain jumpsuit: the glasses and beanie variants would hide their hair or fake their eyewear
	outfit_path = /datum/outfit/outpost_prisoner
	// As hurt as they were caught, but never below BOUNTY_PRISONER_MIN_ARRIVAL_HEALTH percent
	arrival_brute = round(maxHealth * clamp(record.hurt_fraction || 0, 0, 1 - BOUNTY_PRISONER_MIN_ARRIVAL_HEALTH / 100))
	record.status = BOUNTY_RECORD_IMPRISONED

/// The personalities a criminal of `archetype` can have in prison: meek nervous or quiet, normal grumpy or chatty, a mini-boss grumpy, the kingpin calm and quiet or grumpy
/proc/bounty_archetype_personalities(archetype)
	switch(archetype)
		if(BOUNTY_ARCHETYPE_MEEK)
			return list("nervous", "quiet")
		if(BOUNTY_ARCHETYPE_NORMAL)
			return list("grumpy", "chatty")
		if(BOUNTY_ARCHETYPE_BOSS)
			return list("grumpy")
		if(BOUNTY_ARCHETYPE_KINGPIN)
			return list("quiet", "grumpy")
	return null

/// A record's crime as the prison's plain phrase ("smuggling"), without a leading "wanted for", or null
/proc/bounty_plain_crime(crime)
	if(!istext(crime))
		return null
	crime = trim(crime)
	if(findtext(crime, "wanted for ") == 1)
		crime = trim(copytext(crime, length("wanted for ") + 1))
	return length(crime) ? crime : null

/// `petty`, `wanted` or `most_wanted` by `tier` (BOUNTY_TIER_*); a record without a tier counts as Petty
/proc/bounty_by_tier(tier, petty, wanted, most_wanted)
	switch(tier)
		if(BOUNTY_TIER_WANTED)
			return wanted
		if(BOUNTY_TIER_MOST_WANTED)
			return most_wanted
	return petty

/**
 * `prisoner` is leaving the wing, or has died: closes their bounty record with `status`
 * (BOUNTY_RECORD_*). The first close decides the status; later calls for the same record change
 * nothing (a release is followed by forget(), for one). A closed record never returns to the pool
 * (bounty_pool_add() refuses it). Returns TRUE if this call closed it.
 */
/proc/close_bounty_record(mob/living/basic/outpost_prisoner/prisoner, status)
	var/datum/bounty_record/record = prisoner?.bounty_record
	if(!record || record.status != BOUNTY_RECORD_IMPRISONED)
		return FALSE
	bounty_pool_remove(record, status || BOUNTY_RECORD_CLOSED)
	log_game("BOUNTY PRISON: [record.name] ([bounty_tier_name(record.tier)]) left prison: [record.status]")
	return TRUE

/// Why Kessler's experiments refuse `prisoner`, or null: a bounty prisoner's identity would be lost
/proc/bounty_experiment_refusal(mob/living/basic/outpost_prisoner/prisoner)
	return prisoner?.bounty_record ? "Kessler won't touch a bounty prisoner." : null

// ===== PAY =====

/// What `prisoner` earns the treasury (stipend, pay rate and release bonus) as a multiple of an ordinary prisoner's: x1.5, x2 or x2.5 by tier
/datum/outpost_prison/proc/bounty_pay_mult(mob/living/basic/outpost_prisoner/prisoner)
	var/datum/bounty_record/record = prisoner?.bounty_record
	if(!record)
		return 1
	return bounty_by_tier(record.tier, OUTPOST_PRISON_BOUNTY_MULT_PETTY, OUTPOST_PRISON_BOUNTY_MULT_WANTED, OUTPOST_PRISON_BOUNTY_MULT_MOST_WANTED) / 100

// ===== DANGER =====

/// Multiplier on their punches and shiv blows (update_melee() and strike()), by tier and by what they hit with
/mob/living/basic/outpost_prisoner/proc/bounty_damage_mult()
	if(!bounty_record)
		return 1
	if(has_shiv())
		return bounty_by_tier(bounty_record.tier, BOUNTY_PRISON_SHIV_MULT_PETTY, BOUNTY_PRISON_SHIV_MULT_WANTED, BOUNTY_PRISON_SHIV_MULT_MOST_WANTED)
	return bounty_by_tier(bounty_record.tier, BOUNTY_PRISON_PUNCH_MULT_PETTY, BOUNTY_PRISON_PUNCH_MULT_WANTED, BOUNTY_PRISON_PUNCH_MULT_MOST_WANTED)

/// Multiplier on their mood losses (mood_scale())
/mob/living/basic/outpost_prisoner/proc/bounty_mood_scale()
	if(!bounty_record)
		return 1
	return bounty_by_tier(bounty_record.tier, BOUNTY_PRISON_MOOD_SCALE_PETTY, BOUNTY_PRISON_MOOD_SCALE_WANTED, BOUNTY_PRISON_MOOD_SCALE_MOST_WANTED)

/// Mood points added to the line below which they square up to staff (threat_mood_for() and threat_mood_ceiling())
/mob/living/basic/outpost_prisoner/proc/bounty_threat_bonus()
	if(!bounty_record)
		return 0
	return bounty_by_tier(bounty_record.tier, BOUNTY_PRISON_THREAT_BONUS_PETTY, BOUNTY_PRISON_THREAT_BONUS_WANTED, BOUNTY_PRISON_THREAT_BONUS_MOST_WANTED)

/// Mood points added to the line below which they join a riot (riot_join_bonus())
/mob/living/basic/outpost_prisoner/proc/bounty_riot_bonus()
	if(!bounty_record)
		return 0
	return bounty_by_tier(bounty_record.tier, BOUNTY_PRISON_RIOT_BONUS_PETTY, BOUNTY_PRISON_RIOT_BONUS_WANTED, BOUNTY_PRISON_RIOT_BONUS_MOST_WANTED)

/// Multiplier on the damage their blows do to the wing's ways out (hit_exit())
/mob/living/basic/outpost_prisoner/proc/bounty_breakout_mult()
	if(!bounty_record)
		return 1
	return bounty_by_tier(bounty_record.tier, BOUNTY_PRISON_BREAKOUT_MULT_PETTY, BOUNTY_PRISON_BREAKOUT_MULT_WANTED, BOUNTY_PRISON_BREAKOUT_MULT_MOST_WANTED)

/// Multiplier on how long cuffing them takes (cuff_time())
/mob/living/basic/outpost_prisoner/proc/bounty_cuff_mult()
	if(!bounty_record)
		return 1
	return bounty_by_tier(bounty_record.tier, BOUNTY_PRISON_CUFF_MULT_PETTY, BOUNTY_PRISON_CUFF_MULT_WANTED, BOUNTY_PRISON_CUFF_MULT_MOST_WANTED)

/// Whether they were a meek criminal: they back off, go over hatches and slip out of doors
/mob/living/basic/outpost_prisoner/proc/bounty_is_meek()
	return bounty_record?.archetype == BOUNTY_ARCHETYPE_MEEK

/// Multiplier on how likely they are to back off when a player hits them: twice as likely for a meek bounty prisoner (hit_reaction(), through bounty_hit_reaction_weights())
/mob/living/basic/outpost_prisoner/proc/bounty_back_off_mult()
	return bounty_is_meek() ? BOUNTY_PRISON_MEEK_BACK_OFF_MULT : 1

/// Multiplier on how likely they are to hit back when a player hits them: a Wanted or Most Wanted prisoner who is not meek hits back like a grumpy one (hit_reaction(), through bounty_hit_reaction_weights())
/mob/living/basic/outpost_prisoner/proc/bounty_hit_back_mult()
	if(!bounty_record || bounty_is_meek())
		return 1
	return bounty_by_tier(bounty_record.tier, 1, BOUNTY_PRISON_HIT_BACK_MULT_WANTED, BOUNTY_PRISON_HIT_BACK_MULT_MOST_WANTED)

/**
 * A calm prisoner's hit-back and back-off weights (outpost_prisoner_hit_reaction_weights()'s list,
 * which is theirs to change), scaled for a bounty prisoner. Returns the same list. hit_reaction() rolls on it.
 */
/mob/living/basic/outpost_prisoner/proc/bounty_hit_reaction_weights(list/weights)
	if(!bounty_record || !islist(weights))
		return weights
	weights[PRISONER_HIT_FIGHT] = max(1, round(weights[PRISONER_HIT_FIGHT] * bounty_hit_back_mult()))
	weights[PRISONER_HIT_COWER] = max(1, round(weights[PRISONER_HIT_COWER] * bounty_back_off_mult()))
	return weights

/// Their speed while loose, or null for the usual: a meek bounty prisoner runs faster than the others (go_loose())
/mob/living/basic/outpost_prisoner/proc/bounty_loose_speed()
	return bounty_is_meek() ? BOUNTY_PRISON_MEEK_LOOSE_SPEED : null

/// The speed they go back to when not running from anything: a loose meek bounty prisoner keeps their loose speed (update_flee_speed(), back_in_custody())
/mob/living/basic/outpost_prisoner/proc/bounty_base_speed()
	if(trouble == PRISONER_TROUBLE_LOOSE)
		var/loose_speed = bounty_loose_speed()
		if(loose_speed)
			return loose_speed
	return initial(speed)

/// How long going over a serving hatch takes them, or null for the usual: a meek bounty prisoner is quicker (start_climb())
/mob/living/basic/outpost_prisoner/proc/bounty_climb_time()
	return bounty_is_meek() ? BOUNTY_PRISON_MEEK_CLIMB_TIME : null

/// Multiplier on their weight as the wildcard "snap" prisoner: a Most Wanted ringleader's is doubled (pick_snapper())
/mob/living/basic/outpost_prisoner/proc/bounty_snap_weight_mult()
	return bounty_record?.tier == BOUNTY_TIER_MOST_WANTED ? BOUNTY_PRISON_RINGLEADER_SNAP_MULT : 1

/// `rioters` with any Most Wanted first, so a ringleader is among the first to shout when a riot starts (start_riot()). Returns a new list.
/proc/bounty_ringleaders_first(list/rioters)
	var/list/leaders = list()
	var/list/others = list()
	for(var/mob/living/basic/outpost_prisoner/rioter as anything in rioters)
		if(rioter.bounty_record?.tier == BOUNTY_TIER_MOST_WANTED)
			leaders += rioter
		else
			others += rioter
	return leaders + others

/// An awake, uncuffed Most Wanted prisoner out in the yard, not shut in a cell, who stirs the others up, or null
/datum/outpost_prison/proc/bounty_ringleader()
	for(var/mob/living/basic/outpost_prisoner/prisoner in prisoners)
		if(prisoner.bounty_record?.tier != BOUNTY_TIER_MOST_WANTED || !counts_for_tension(prisoner))
			continue
		if(prisoner.stat != CONSCIOUS || prisoner.cuffs || !in_cell_block(prisoner) || prisoner.is_confined())
			continue
		return prisoner
	return null

/// Tension the wing's bounty prisoners add: a Most Wanted ringleader (compute_tension())
/datum/outpost_prison/proc/bounty_tension()
	return bounty_ringleader() ? BOUNTY_PRISON_RINGLEADER_TENSION : 0

/// A few words each on how the bounty prisoners stir the yard up, for the restless log line (restless_causes())
/datum/outpost_prison/proc/bounty_restless_causes()
	if(BOUNTY_PRISON_RINGLEADER_TENSION <= 0)
		return list()
	var/mob/living/basic/outpost_prisoner/ringleader = bounty_ringleader()
	return ringleader ? list("[ringleader.real_name] stirring them up") : list()

// ===== MEEK BOUNTY PRISONERS: HATCHES AND DOORS =====

/**
 * A meek bounty prisoner goes over a serving hatch left open on both sides sooner than the others
 * (below BOUNTY_PRISON_MEEK_CLIMB_MOOD), while a member of the wing is home. Below
 * PRISONER_CLIMB_MOOD the routine's own climb duty comes first anyway. Picked as leisure, with a
 * weight that puts it ahead of anything else. Every climb of theirs is quicker (bounty_climb_time()).
 */
/datum/prisoner_activity/climb_hatch/bounty_meek
	leisure = TRUE
	weight = BOUNTY_PRISON_MEEK_CLIMB_WEIGHT

/datum/prisoner_activity/climb_hatch/bounty_meek/get_weight()
	if(!bounty_meek_may_climb() || !prisoner.prison.open_hatch_for(prisoner))
		return 0
	return weight

/datum/prisoner_activity/climb_hatch/bounty_meek/setup()
	if(!bounty_meek_may_climb())
		return FALSE
	var/obj/structure/table/reinforced/prison_hatch/hatch = prisoner.prison.open_hatch_for(prisoner)
	if(!hatch)
		return FALSE
	hatch_ref = WEAKREF(hatch)
	spot = hatch.yard_side_turf()
	return !!spot

/// Whether they are a meek bounty prisoner in a mood to go over an open hatch, with the crew home (nothing new starts in an empty wing)
/datum/prisoner_activity/climb_hatch/bounty_meek/proc/bounty_meek_may_climb()
	return prisoner?.bounty_is_meek() && prisoner.mood < BOUNTY_PRISON_MEEK_CLIMB_MOOD && prisoner.prison?.trouble_enabled && prisoner.prison.crew_home()

/**
 * A meek bounty prisoner below BOUNTY_PRISON_MEEK_DART_MOOD, with a member of the wing home, hangs
 * about BOUNTY_PRISON_MEEK_DART_RANGE tiles from a staff door (never right in front of it) for
 * BOUNTY_PRISON_MEEK_WATCH_TIME, glancing at it: the tell, which examine shows too. If the door opens
 * while they are that close, at BOUNTY_PRISON_MEEK_DART_CHANCE (once a watch) they dart for it: up to
 * the door, and through the doorway to the far side in one go once the door is open and both are
 * clear, so they are never left standing in the doorway. Past it they are an ordinary runner
 * (prisoner_escaped()), with the usual loose clock. Stopped short (the door shut, someone in the
 * way until the dart runs out, knocked down, grabbed, the crew gone) they stay in the yard and the
 * watch is over.
 */
/datum/prisoner_activity/bounty_door_watch
	name = "watching the door"
	leisure = TRUE
	weight = BOUNTY_PRISON_MEEK_WATCH_WEIGHT
	min_duration = BOUNTY_PRISON_MEEK_WATCH_TIME
	max_duration = BOUNTY_PRISON_MEEK_WATCH_TIME
	/// The staff door they are watching (/obj/machinery/door/airlock/security/prison_staff)
	var/datum/weakref/door_ref
	/// They have had their chance at the door this watch
	var/tried = FALSE
	/// Darting for the door now, and the steps taken
	var/darting = FALSE
	var/dart_steps = 0

/datum/prisoner_activity/bounty_door_watch/get_weight()
	if(!prisoner?.bounty_may_watch_door())
		return 0
	return ..()

/datum/prisoner_activity/bounty_door_watch/setup()
	if(!prisoner.bounty_may_watch_door())
		return FALSE
	if(!prisoner.walkable)
		prisoner.prison.refresh_prisoner_reach(prisoner)
	if(!prisoner.walkable || !prisoner.reachable)
		return FALSE
	var/list/doors = list()
	for(var/turf/tile as anything in prisoner.reachable)
		if(prisoner.walkable[tile])
			continue
		var/obj/machinery/door/airlock/security/prison_staff/door = locate() in tile
		if(door)
			doors += door
	while(length(doors))
		var/obj/machinery/door/airlock/security/prison_staff/door = pick_n_take(doors)
		var/list/options = list()
		for(var/turf/tile as anything in RANGE_TURFS(BOUNTY_PRISON_MEEK_DART_RANGE, door))
			// Not right in front of the door, where they would stand in the way of staff coming in
			if(get_dist(tile, door) <= 1 || !prisoner.walkable[tile] || prisoner.prison.cell_at(tile) || !prisoner.may_loiter(tile))
				continue
			if(tile != prisoner.loc && prisoner.tile_taken(tile))
				continue
			options += tile
		if(length(options))
			door_ref = WEAKREF(door)
			spot = pick(options)
			return TRUE
	return FALSE

/datum/prisoner_activity/bounty_door_watch/begin()
	..()
	var/obj/machinery/door/airlock/door = door_ref?.resolve()
	if(!door)
		return
	RegisterSignal(door, COMSIG_AIRLOCK_OPEN, PROC_REF(on_door_open))
	prisoner.face_atom(door)
	prisoner.manual_emote("keeps glancing at [door].")

/datum/prisoner_activity/bounty_door_watch/tick(seconds)
	if(darting)
		return BOUNTY_PRISON_ACTIVITY_CONTINUE
	var/obj/machinery/door/airlock/door = door_ref?.resolve()
	// Their chance came and went: the watch is over
	if(!door || tried || !prisoner.bounty_may_watch_door())
		return BOUNTY_PRISON_ACTIVITY_DONE
	prisoner.face_atom(door)
	return ..()

/datum/prisoner_activity/bounty_door_watch/finish()
	stop_watching()
	return ..()

/datum/prisoner_activity/bounty_door_watch/Destroy()
	stop_watching()
	door_ref = null
	return ..()

/datum/prisoner_activity/bounty_door_watch/proc/stop_watching()
	darting = FALSE
	var/obj/machinery/door/airlock/door = door_ref?.resolve()
	if(door)
		UnregisterSignal(door, COMSIG_AIRLOCK_OPEN)

/// The door they are watching opened: close enough and still free to, they may go for it
/datum/prisoner_activity/bounty_door_watch/proc/on_door_open(obj/machinery/door/airlock/door, forced)
	SIGNAL_HANDLER
	if(tried || darting || !started || prisoner?.activity != src)
		return
	if(get_dist(prisoner, door) > BOUNTY_PRISON_MEEK_DART_RANGE || !prisoner.routine_allowed() || !prisoner.prison?.crew_home())
		return
	tried = TRUE
	var/forced_dart = prisoner.prison.prison_bounty_forced_dart
	if(isnull(forced_dart) ? prob(BOUNTY_PRISON_MEEK_DART_CHANCE) : forced_dart)
		start_dart()

/// Off they go: a step every BOUNTY_PRISON_MEEK_DART_STEP, through the door and out of the cell block. Returns TRUE if they went.
/datum/prisoner_activity/bounty_door_watch/proc/start_dart()
	var/obj/machinery/door/airlock/door = door_ref?.resolve()
	if(!door || prisoner?.activity != src)
		return FALSE
	darting = TRUE
	dart_steps = 0
	prisoner.ai_controller?.CancelActions()
	prisoner.visible_message(span_warning("[prisoner] darts for [door]!"))
	addtimer(CALLBACK(src, PROC_REF(dart_step)), BOUNTY_PRISON_MEEK_DART_STEP, TIMER_DELETE_ME)
	return TRUE

/**
 * One step of a dart. Up to the tile in front of the door, waiting a step while it is in the way;
 * then, once the door stands open and both the doorway and the tile past it are clear, through to
 * that far tile in one go. A staff door never lets a prisoner through on their own feet
 * (outpost_prison_doors.dm), so the hop is the one way a prisoner gets past it, and they are never
 * left standing in the doorway, where they could be swapped or walk into the office. Out of the cell
 * block they have escaped. Anything else ends the dart (dart_stopped()): the door shut, knocked down,
 * grabbed, in trouble, the crew gone, or the steps run out with the way still blocked.
 */
/datum/prisoner_activity/bounty_door_watch/proc/dart_step()
	var/obj/machinery/door/airlock/door = door_ref?.resolve()
	var/datum/outpost_prison/prison = prisoner?.prison
	if(!darting || !prison || prisoner.activity != src)
		darting = FALSE
		return
	if(!door || prisoner.stat != CONSCIOUS || prisoner.can_be_dragged() || prisoner.pulledby || prisoner.in_trouble() || !prison.crew_home())
		dart_stopped(door)
		return
	if(++dart_steps > BOUNTY_PRISON_MEEK_DART_STEPS)
		dart_stopped(door)
		return
	var/turf/here = get_turf(prisoner)
	var/turf/door_turf = get_turf(door)
	if(get_dist(here, door_turf) == 1 && (get_dir(here, door_turf) in GLOB.cardinals))
		if(door.density && !door.operating)
			dart_stopped(door)
			return
		var/turf/beyond = get_step(door_turf, get_dir(here, door_turf))
		// Open, with the doorway and the far side clear: through in one go
		if(!door.density && beyond && !prison.in_cell_block(beyond) && !door_turf.is_blocked_turf(exclude_mobs = FALSE) && !beyond.is_blocked_turf(exclude_mobs = FALSE))
			darting = FALSE
			prisoner.hop_to(beyond)
			if(!prison.in_cell_block(prisoner))
				prison.prisoner_escaped(prisoner)
				return
			dart_stopped(door)
			return
		// Still swinging open, or someone in the way: wait a step
	else
		var/turf/approach = dart_approach(door_turf, here)
		var/turf/next = approach ? get_step_towards(prisoner, approach) : null
		if(!next)
			dart_stopped(door)
			return
		// Someone in the way: wait a step
		prisoner.Move(next, get_dir(here, next))
	addtimer(CALLBACK(src, PROC_REF(dart_step)), BOUNTY_PRISON_MEEK_DART_STEP, TIMER_DELETE_ME)

/**
 * The dart is over without them getting out: they stay in the yard (back off the door's tile if they
 * are somehow on it), what they can reach is worked out afresh, and the watch ends.
 */
/datum/prisoner_activity/bounty_door_watch/proc/dart_stopped(obj/machinery/door/airlock/door)
	darting = FALSE
	tried = TRUE
	ends_at = min(ends_at, world.time)
	var/datum/outpost_prison/prison = prisoner?.prison
	if(!prison)
		return
	var/turf/here = get_turf(prisoner)
	var/turf/door_turf = get_turf(door)
	if(door_turf && here == door_turf && !prisoner.pulledby)
		var/turf/back = dart_approach(door_turf, here)
		if(back)
			prisoner.hop_to(back)
	prison.refresh_prisoner_reach(prisoner)
	if(prisoner.stat == CONSCIOUS && door)
		prisoner.visible_message(span_notice("[prisoner] pulls up short of [door]."))

/// The tile straight in front of the door on their side (one they can walk), nearest to `from`, or null
/datum/prisoner_activity/bounty_door_watch/proc/dart_approach(turf/door_turf, turf/from)
	var/turf/best
	var/best_distance = INFINITY
	for(var/direction in GLOB.cardinals)
		var/turf/front = get_step(door_turf, direction)
		if(!front || !prisoner.walkable?[front])
			continue
		var/distance = get_dist(from, front)
		if(distance < best_distance)
			best = front
			best_distance = distance
	return best

/// Whether they are a meek bounty prisoner in a mood to watch the staff door for their chance, with a member of the wing home (nothing new starts in an empty wing)
/mob/living/basic/outpost_prisoner/proc/bounty_may_watch_door()
	return bounty_is_meek() && mood < BOUNTY_PRISON_MEEK_DART_MOOD && !!prison?.trouble_enabled && prison.crew_home()

// ===== CONSOLES =====

/**
 * The roster row's "bounty" entry for the warden console, or null for an ordinary prisoner: the
 * "wanted for" line and whether they are Most Wanted, the one tier a wanted poster names. Petty and
 * Wanted show nothing more, and no pay multiplier.
 */
/datum/outpost_prison/proc/bounty_roster_badge(mob/living/basic/outpost_prisoner/prisoner)
	var/datum/bounty_record/record = prisoner?.bounty_record
	if(!record)
		return null
	var/plain_crime = bounty_plain_crime(record.crime) || prisoner.crime
	return list(
		"wanted_for" = plain_crime ? "wanted for [plain_crime]" : null,
		"most_wanted" = record.tier == BOUNTY_TIER_MOST_WANTED,
	)

/**
 * An examine sentence or two, or null (examine_extra_lines()): "Brought in on a bounty by the crew
 * of the Meridian.", and the door-watching tell. A Most Wanted is named as one, with their crime,
 * since the yard's "In for ..." leaves it out (BUG-12): "Most Wanted, for smuggling. The crew of the
 * Meridian brought him in."
 */
/datum/outpost_prison/proc/bounty_examine(mob/living/basic/outpost_prisoner/prisoner, mob/user)
	var/datum/bounty_record/record = prisoner?.bounty_record
	if(!record)
		return null
	var/has_captor = length(record.captor_name)
	var/text
	if(record.tier == BOUNTY_TIER_MOST_WANTED)
		var/plain_crime = bounty_plain_crime(record.crime)
		text = plain_crime ? "Most Wanted, for [plain_crime]." : "Most Wanted."
		if(has_captor)
			text += " The crew of the [record.captor_name] brought [prisoner.p_them()] in."
	else
		text = has_captor ? "Brought in on a bounty by the crew of the [record.captor_name]." : "Brought in on a bounty."
	if(istype(prisoner.activity, /datum/prisoner_activity/bounty_door_watch))
		text += " [prisoner.p_They()] keep[prisoner.p_s()] glancing at the door."
	return text

// ===== WHO CAUGHT THEM =====

/**
 * Values for their lines that name the ship that caught them, list("{place}" = "Meridian"), or null
 * for an ordinary prisoner or a record with no captor. The lines say "the {place}".
 */
/mob/living/basic/outpost_prisoner/proc/bounty_captor_values()
	if(!length(bounty_record?.captor_name))
		return null
	return list("{place}" = bounty_record.captor_name)

/**
 * A bounty prisoner's first words as the beam ends name the crew who caught them ("So this is where
 * the Meridian crew sends people."), in place of the usual hello. Returns TRUE if they said it.
 * finish_beam_in() calls it before its own arrival lines.
 */
/mob/living/basic/outpost_prisoner/proc/bounty_arrival_speech()
	var/list/values = bounty_captor_values()
	return values ? say_context_with("bounty_arrival", values) : FALSE

/// Someone awake off the ship that caught them, within BOUNTY_PRISON_CAPTOR_VIEW tiles and in sight, or null
/mob/living/basic/outpost_prisoner/proc/bounty_captor_in_view()
	var/obj/structure/overmap/ship/captor_ship = bounty_record?.captor_ship?.resolve()
	if(QDELETED(captor_ship))
		return null
	for(var/mob/living/person in view(BOUNTY_PRISON_CAPTOR_VIEW, src))
		if(person != src && person.stat == CONSCIOUS && get_crew_ship(person) == captor_ship)
			return person
	return null

/**
 * The yard's talk (extra_speech()): now and then, with someone off the ship that caught them in
 * sight, a bounty prisoner turns to them and calls them out ("I know you. You're off the Meridian.").
 * Rolled at `chance` percent, and at most once every BOUNTY_PRISON_CAPTOR_LINE_GAP each; the sight
 * check runs only once the roll comes up. Returns list(context, null, values), or null.
 */
/datum/outpost_prison/proc/bounty_extra_speech(mob/living/basic/outpost_prisoner/prisoner, chance = BOUNTY_PRISON_CAPTOR_LINE_CHANCE)
	var/list/values = prisoner?.bounty_captor_values()
	if(!values || !COOLDOWN_FINISHED(prisoner, prison_captor_line_cooldown) || !prob(chance))
		return null
	var/mob/living/captor = prisoner.bounty_captor_in_view()
	if(!captor)
		return null
	COOLDOWN_START(prisoner, prison_captor_line_cooldown, BOUNTY_PRISON_CAPTOR_LINE_GAP)
	prisoner.face_atom(captor)
	return list("bounty_captor_seen", null, values)

/**
 * The warden console's bounty block (OutpostPrison.tsx), for the top-level payload: the intake
 * setting, and the next bounty arrival once it is theirs, which the console puts on the intake line
 * ("Next transfer 0:20: Dana Notice"). It is theirs once the notice has run by the time the lane's
 * next arrival is due; "in" is the seconds until it beams in. Until then an ordinary prisoner comes
 * first, and the console names nobody.
 */
/datum/outpost_prison/proc/bounty_console_payload(mob/user)
	var/datum/bounty_record/next = bounty_next_record()
	var/list/next_block
	if(next)
		var/notice_left = max(0, (next.prison_notice_at + BOUNTY_PRISON_NOTICE_TIME - world.time) / (1 SECONDS))
		var/due = next_arrival_in()
		if(!isnull(due) && due >= notice_left)
			next_block = list(
				"name" = next.name,
				"most_wanted" = next.tier == BOUNTY_TIER_MOST_WANTED,
				"in" = round(due),
			)
	return list(
		"setting" = prison_bounty_intake,
		"can_manage" = !!outpost?.can_manage(user),
		"next" = next_block,
	)

/**
 * A warden console action for bounty prisoners: "set_bounty_intake" {setting}, managers only.
 * Returns TRUE if it was one. The console reaches it through extras_act().
 */
/datum/outpost_prison/proc/bounty_warden_act(action, list/params, mob/user)
	if(action != "set_bounty_intake")
		return FALSE
	if(!outpost?.can_manage(user))
		user?.balloon_alert(user, "managers only")
		return TRUE
	set_bounty_intake(params?["setting"], user)
	return TRUE

/// The admin panel's "bounty" block in the extras (extras_admin_payload()): the wing's intake, its named next arrival and the whole pool. Its actions are listed in GLOB.outpost_admin_prison_actions (outpost_admin_prison.dm).
/datum/outpost_prison/proc/bounty_admin_payload()
	bounty_pool_prune()
	var/datum/bounty_record/next = bounty_next_record()
	var/list/rows = list()
	for(var/datum/bounty_record/record in GLOB.bounty_prisoner_pool)
		var/datum/outpost_prison/reserved = bounty_record_reserved_for(record)
		var/datum/outpost_prison/named = bounty_record_named_to(record)
		rows += list(list(
			"id" = "[record.id]",
			"name" = record.name,
			"tier" = bounty_tier_name(record.tier || BOUNTY_TIER_PETTY),
			"level" = record.tier || BOUNTY_TIER_PETTY,
			"archetype" = record.archetype,
			"age" = round((world.time - record.prison_pooled_at) / (1 SECONDS)),
			"left" = max(0, round((record.prison_pooled_at + BOUNTY_RECORD_LIFE - world.time) / (1 SECONDS))),
			"reserved_for" = reserved?.outpost?.name,
			"ours" = reserved == src,
			"named_to" = named?.outpost?.name,
			"accepts" = bounty_accepts(record),
		))
	return list(
		"setting" = prison_bounty_intake,
		"count" = bounty_prisoner_count(),
		"max" = bounty_prisoner_max(),
		"most_wanted" = bounty_prisoner_count(BOUNTY_TIER_MOST_WANTED),
		"lanes" = arrival_lanes(),
		"next" = next ? list("id" = "[next.id]", "name" = next.name, "tier" = bounty_tier_name(next.tier || BOUNTY_TIER_PETTY)) : null,
		"pool" = rows,
	)

/**
 * An admin action for bounty prisoners: a line for the admin log, list("error" = text) when
 * refused, or null when it isn't one (extras_admin_act()).
 * - "prison_bounty_admit" {id}: that record's prisoner beams in now, into the first free cell
 * - "prison_bounty_make" {tier}: a new record of that tier joins the pool, reserved for this wing
 * - "prison_bounty_intake" {setting}: the warden's bounty intake setting
 * - "prison_bounty_clear" {}: every record in the pool is closed
 */
/datum/outpost_prison/proc/bounty_admin_act(action, list/params, mob/user)
	switch(action)
		if("prison_bounty_admit")
			var/datum/bounty_record/record = bounty_pool_find(params?["id"])
			if(!record)
				return list("error" = "That record is no longer in the pool.")
			var/mob/living/basic/outpost_prisoner/arrival = bounty_admit_record(record)
			if(!arrival)
				return list("error" = "No free cell.")
			return "admit bounty prisoner [arrival.real_name] ([bounty_tier_name(record.tier)]) into cell [arrival.cell?.number]"
		if("prison_bounty_make")
			var/tier = params?["tier"]
			if(istext(tier))
				tier = text2num(tier)
			if(!(tier in list(BOUNTY_TIER_PETTY, BOUNTY_TIER_WANTED, BOUNTY_TIER_MOST_WANTED)))
				return list("error" = "Invalid bounty tier.")
			var/archetype = BOUNTY_ARCHETYPE_BOSS
			if(tier == BOUNTY_TIER_PETTY)
				archetype = prob(70) ? BOUNTY_ARCHETYPE_MEEK : BOUNTY_ARCHETYPE_NORMAL
			else if(tier == BOUNTY_TIER_WANTED)
				archetype = prob(70) ? BOUNTY_ARCHETYPE_NORMAL : BOUNTY_ARCHETYPE_MEEK
			var/datum/bounty_record/record = generate_bounty_record(tier, archetype, BOUNTY_PLACEMENT_PLANET)
			record.preferred_prison = WEAKREF(src)
			if(!bounty_pool_add(record))
				return list("error" = "The record did not join the pool.")
			return "add [bounty_tier_name(tier)] bounty record [record.name] to the prisoner pool"
		if("prison_bounty_intake")
			var/setting = params?["setting"]
			if(!set_bounty_intake(setting, user))
				return list("error" = "Invalid bounty intake setting.")
			return "set the prison wing's bounty transfers to [bounty_intake_text(setting)]"
		if("prison_bounty_clear")
			var/count = bounty_pool_clear("cleared by an admin")
			return "clear the prisoner pool ([count] record\s)"
	return null

#undef BOUNTY_PRISON_ACTIVITY_CONTINUE
#undef BOUNTY_PRISON_ACTIVITY_DONE
#undef BOUNTY_PRISON_MOST_WANTED_YARD_CRIME
#undef BOUNTY_PRISON_CAPTOR_LINE_CHANCE
#undef BOUNTY_PRISON_CAPTOR_LINE_GAP
#undef BOUNTY_PRISON_CAPTOR_VIEW
