"""Reject orphaned ship hulls, module maps, and baked preview images."""

import argparse
import json
from pathlib import Path, PurePosixPath
import re


HULLS = Path("_maps/voidcrew/ships")
MODULES = Path("_maps/voidcrew/ship_modules")
PREVIEWS = Path("voidcrew/modules/ship_upgrades/previews")
SHIP = "/datum/map_template/shuttle/voidcrew"
THEME = "/datum/ship_theme"
MODULE = "/datum/ship_upgrade_module"
FIELDS = {
    "suffix", "prefix", "port_id", "template_suffix", "id", "for_ship",
    "map_file", "for_theme", "theme", "parent_type",
}
# Predates the registered ship fleet; retained for a separate NPC-map audit.
LEGACY_MAPS = {HULLS / "trader.dmm"}


def strip_comments(text):
    """Keep strings intact, so quoted // and /* do not hide registrations."""
    tokens = re.compile(r'\{"(?:\\.|(?!"\})[\s\S])*"\}|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|//[^\n]*|/\*')
    delimiters = re.compile(r'/\*|\*/')
    output = []
    depth = 0
    start = 0
    while match := (delimiters if depth else tokens).search(text, start):
        fragment = text[start:match.start()]
        output.append("\n" * fragment.count("\n") if depth else fragment)
        token = match[0]
        if token == "/*":
            depth += 1
        elif token == "*/" and depth:
            depth -= 1
        elif token.startswith("//"):
            output.append("\n" * token.count("\n"))
        else:
            output.append(token)
        start = match.end()
    if depth:
        raise ValueError("Unterminated DM block comment")
    output.append(text[start:])
    return "".join(output)


def included_sources(root):
    """Only included DM files count; editor JSON and unused source do not."""
    seen = set()

    def visit(path):
        path = path.resolve()
        if path in seen:
            return
        seen.add(path)
        text = strip_comments(path.read_text(encoding="utf-8"))
        yield path, text
        for name in re.findall(r'^\s*#include\s+"([^"]+\.(?:dm|dme))"', text, re.M):
            child = path.parent / name.replace("\\", "/")
            # Generated by the ALL_TEMPLATES build target; contains map includes,
            # not ship registrations, and is absent before a clean build.
            if child.resolve() == (root / "_maps/templates.dm").resolve():
                continue
            yield from visit(child)

    yield from visit(root / "tgstation.dme")


def declarations(root):
    """Read declarative fields, not proc bodies, from the fleet's DM types.

    This intentionally supports literal registration fields, not arbitrary DM
    execution. Unsupported expressions fail with a diagnostic instead of making
    potentially orphaned assets silently count as referenced.
    """
    types = {}
    for path, text in included_sources(root):
        current = None
        lines = iter(text.splitlines())
        for line in lines:
            if line and not line[0].isspace() and not line.startswith("#"):
                current = line.strip() if re.fullmatch(r"/[\w/]+", line.strip()) else None
                if current and not any(current == base or current.startswith(base + "/") for base in (SHIP, THEME, MODULE)):
                    current = None
            if not current:
                continue
            fields = types.setdefault(current, {})
            match = re.match(r"^\s+(\w+)\s*=\s*(.+)$", line)
            if not match or match[1] not in FIELDS:
                continue
            value = match[2].strip()
            if value.startswith("list("):
                while value.count("(") > value.count(")"):
                    value += " " + next(lines)
            fields[match[1]] = value
    return types


def inherited(types, typepath, field, seen=()):
    if not typepath:
        return None
    if typepath in seen:
        raise ValueError(f"Cyclic parent_type in {typepath}")
    fields = types.get(typepath, {})
    if field in fields:
        return fields[field]
    parent = fields.get("parent_type", typepath.rpartition("/")[0])
    return inherited(types, parent, field, (*seen, typepath))


def literal(value):
    if value is None or value == "null":
        return None
    if not re.fullmatch(r'"[\w./-]*"', value):
        raise ValueError(f"Expected a literal asset name, got {value!r}")
    return value[1:-1]


def theme_list(value):
    if value is None or value in ("null", "list()"):
        return set()
    if value.startswith('"'):
        return {literal(value)}
    if not re.fullmatch(r'list\(\s*(?:"[\w-]+"\s*,?\s*)*\)', value):
        raise ValueError(f"Expected literal for_theme IDs, got {value!r}")
    return set(re.findall(r'"([\w-]+)"', value))


def registered_maps(root):
    types = declarations(root)
    expected = set()
    ship_themes = {}

    def hull(ship, suffix):
        prefix = literal(inherited(types, ship, "prefix")) or HULLS.as_posix() + "/"
        port = literal(inherited(types, ship, "port_id")) or "ship"
        return Path(prefix) / f"{port}_{suffix}.dmm"

    for typepath in types:
        if typepath.startswith(SHIP + "/"):
            suffix = literal(inherited(types, typepath, "suffix"))
            if suffix:
                expected.add(hull(typepath, suffix))
            theme = literal(inherited(types, typepath, "theme"))
            if theme:
                # Older example ships set theme on a ship subtype directly.
                parent = typepath
                while parent.startswith(SHIP + "/"):
                    ship_themes.setdefault(parent, set()).add(theme)
                    parent = parent.rpartition("/")[0]
        elif typepath.startswith(THEME + "/"):
            ship = inherited(types, typepath, "for_ship")
            if not ship or ship == "null":
                continue
            suffix = literal(inherited(types, typepath, "template_suffix"))
            if suffix:
                expected.add(hull(ship, suffix))
            theme = literal(inherited(types, typepath, "id"))
            if theme:
                ship_themes.setdefault(ship, set()).add(theme)

    for typepath in types:
        if not typepath.startswith(MODULE + "/"):
            continue
        filename = literal(inherited(types, typepath, "map_file"))
        if not filename:
            continue
        ship = inherited(types, typepath, "for_ship")
        if not ship or ship == "null":
            raise ValueError(f"{typepath} has map_file but no for_ship")
        base = MODULES / filename
        expected.add(base)
        restriction = inherited(types, typepath, "for_theme")
        themes = ship_themes.get(ship, set()) if restriction in (None, "null") else theme_list(restriction)
        for theme in themes:
            expected.add(base.with_name(f"{base.stem}_{theme}.dmm"))
    return expected


def preview_metadata(directory):
    """Load the same flat and nested metadata files as the game's asset loader."""
    paths = list(directory.glob("*.preview.json"))
    for group in ("hulls", "modules"):
        paths.extend((directory / group).rglob("*.preview.json"))
    if not paths:
        raise ValueError("No ship preview metadata found. Regenerate previews with Voidworks 0.5.32 or newer.")
    manifest = {"hulls": {}, "modules": {}}
    for path in sorted(paths):
        document = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(document, dict) or document.get("tile_px") != 32:
            raise ValueError(f"Invalid ship preview metadata: {path}")
        count = 0
        for group in manifest:
            entries = document.get(group)
            if not isinstance(entries, dict):
                raise ValueError(f"Invalid preview group in {path}")
            for key, entry in entries.items():
                if not isinstance(entry, dict) or key in manifest[group]:
                    raise ValueError(f"Invalid or duplicate ship preview {key!r} in {path}")
                manifest[group][key] = entry
                count += 1
        if count != 1:
            raise ValueError(f"Expected one hull or module in {path}")
    return manifest


def preview_names(manifest):
    """Match the hull/module/theme entries consumed by ship_preview_assets.dm."""
    names = set()
    for section in ("hulls", "modules"):
        entries = manifest[section]
        if not isinstance(entries, dict):
            raise ValueError(f"Manifest {section} must be an object")
        for entry in entries.values():
            for variant in (entry, *entry.get("themes", {}).values()):
                name = variant.get("png")
                if name is None:
                    continue  # theme-only modules have no unthemed PNG
                if not isinstance(name, str) or PurePosixPath(name).name != name or "\\" in name or not name.endswith(".png"):
                    raise ValueError(f"Invalid preview filename: {name!r}")
                names.add(name)
    return names


def check_assets(root):
    expected = registered_maps(root)
    problems = []
    for directory in (HULLS, MODULES):
        maps = sorted((root / directory).rglob("*.dmm"))
        if not maps:
            raise ValueError(f"No maps found under {directory}")
        for path in maps:
            relative = path.relative_to(root)
            if relative not in expected and relative not in LEGACY_MAPS:
                problems.append((relative, "Map has no included ship/module registration. Remove the obsolete map or register it in DM (including its theme)."))

    manifest = preview_metadata(root / PREVIEWS)
    referenced = preview_names(manifest)
    actual = {path.relative_to(root / PREVIEWS).as_posix() for path in (root / PREVIEWS).rglob("*.png")}
    for name in sorted(actual - referenced):
        problems.append((PREVIEWS / name, "Preview is not referenced by preview metadata. Remove the obsolete PNG or regenerate the previews."))
    for name in sorted(referenced - actual):
        problems.append((PREVIEWS / name, "Preview metadata references a missing PNG. Regenerate and commit the previews."))
    return problems


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--github", action="store_true")
    args = parser.parse_args(argv)
    try:
        problems = check_assets(args.root.resolve())
    except (OSError, ValueError, KeyError, TypeError, AttributeError, StopIteration) as error:
        print(f"{'::error::' if args.github else ''}Cannot validate ship assets: {error}")
        return 1
    for path, message in problems:
        prefix = f"::error file={path.as_posix()}::" if args.github else f"{path.as_posix()}: "
        print(prefix + message)
    if not problems:
        print("Ship hulls, modules, and preview references are valid.")
    return int(bool(problems))


if __name__ == "__main__":
    raise SystemExit(main())
