/// Changing a subset of ratings must retain every other protection.
/datum/unit_test/armor_partial_modifiers/Run()
	var/datum/armor/base = get_armor_by_type(/datum/armor/none).generate_new_with_specific(list(MELEE = 30, BOMB = 60, FIRE = 100, ACID = 100))
	var/datum/armor/added = base.generate_new_with_modifiers(list(MELEE = 5))
	var/datum/armor/scaled = base.generate_new_with_multipliers(list(MELEE = 2))
	var/list/original = base.get_rating_list()
	for(var/rating in ARMOR_LIST_ALL())
		TEST_ASSERT_EQUAL(added.get_rating(rating), original[rating] + (rating == MELEE ? 5 : 0), "Additive upgrade changed [rating] incorrectly")
		TEST_ASSERT_EQUAL(scaled.get_rating(rating), original[rating] * (rating == MELEE ? 2 : 1), "Multiplicative upgrade changed [rating] incorrectly")
	TEST_ASSERT_EQUAL(base.get_rating(MELEE), 30, "Upgrading armor mutated the original")
	var/datum/armor/second_tier = added.generate_new_with_modifiers(list(MELEE = 5, BOMB = 10))
	TEST_ASSERT_EQUAL(second_tier.get_rating(BOMB), 70, "Second plating tier lost the original blast protection")
	TEST_ASSERT_EQUAL(second_tier.get_rating(FIRE), 100, "Second plating tier lost fire protection")
	qdel(second_tier)
	qdel(scaled)
	qdel(added)
	qdel(base)
