/datum/unit_test/voidcrew_windoor_survey
	parent_type = /datum/unit_test/voidcrew_hull_survey

/datum/unit_test/voidcrew_windoor_survey/Run()
	TEST_ASSERT(reserved, "Could not reserve the windoor test block.")
	for(var/door_type in list(/obj/machinery/door/window, /obj/machinery/door/window/brigdoor))
		for(var/face in GLOB.cardinals)
			reset_block()
			build_window_room()
			var/turf/door_tile = get_step(spot(3, 3), face)
			var/turf/outside = get_step(door_tile, face)
			for(var/obj/structure/window/pane in door_tile)
				if(pane.dir == face)
					qdel(pane)
			settle()
			// Represent an already-settled glass room, with no pending construction refresh.
			for(var/x_offset in 1 to 12)
				for(var/y_offset in 1 to 12)
					SSair.adjacent_rebuild -= spot(x_offset, y_offset)
			var/obj/machinery/door/window/door = new door_type(door_tile, face)
			var/datum/hull_claim/initial_claim = survey_enclosure(spot(3, 3))
			TEST_ASSERT_NULL(initial_claim.refusal, "New closed windoor [door_type] facing [face] was refused: [initial_claim.refusal]")
			TEST_ASSERT_EQUAL(length(initial_claim.turfs), 9, "New windoor room did not claim exactly nine floor tiles.")
			qdel(initial_claim)
			// Use the real animated open/close procs, not density edits or a test subtype.
			TEST_ASSERT(door.open(BYPASS_DOOR_CHECKS), "Windoor [door_type] facing [face] failed to open.")
			TEST_ASSERT(!door.density, "Opened windoor remains dense.")
			var/datum/hull_claim/open_claim = survey_enclosure(spot(3, 3))
			TEST_ASSERT_NOTNULL(open_claim.refusal, "Open windoor [door_type] facing [face] was accepted as airtight.")
			TEST_ASSERT_EQUAL(open_claim.refusal_turf, outside, "Open windoor leak points at the wrong turf.")
			qdel(open_claim)
			TEST_ASSERT(door.close(BYPASS_DOOR_CHECKS), "Windoor [door_type] facing [face] failed to close.")
			TEST_ASSERT(door.density, "Closed windoor is not dense.")
			var/datum/hull_claim/closed_claim = survey_enclosure(spot(3, 3))
			TEST_ASSERT_NULL(closed_claim.refusal, "Closed windoor [door_type] facing [face] was refused: [closed_claim.refusal]")
			TEST_ASSERT_EQUAL(length(closed_claim.turfs), 9, "Windoor room claimed more than its nine floor tiles.")
			TEST_ASSERT(!closed_claim.turfs[outside], "Windoor claim absorbed exterior space.")
			qdel(closed_claim)
