/// Physical research disks must stay local when nanite equipment or its server moves.
/datum/unit_test/voidcrew_nanite_research
	parent_type = /datum/unit_test/voidcrew_research_movement
	abstract_type = /datum/unit_test/voidcrew_nanite_research

/datum/unit_test/voidcrew_nanite_research/buffers/Run()
	TEST_ASSERT(setup_links(), "No separate site exists for nanite link testing")
	var/obj/machinery/rnd/server/ship/remote_server = allocate(/obj/machinery/rnd/server/ship, remote_turf)
	var/obj/item/computer_disk/ship_disk/remote_disk = allocate(/obj/item/computer_disk/ship_disk)
	remote_server.attacked_by(remote_disk, user)
	for(var/machine_type in list(/obj/machinery/computer/nanite_cloud_controller, /obj/machinery/nanite_chamber, /obj/machinery/public_nanite_chamber))
		check_buffer(machine_type, remote_disk.stored_research)

/datum/unit_test/voidcrew_nanite_research/buffers/proc/check_buffer(machine_type, datum/techweb/remote_web)
	var/obj/machinery/machine = allocate(machine_type)
	tool.buffer = web
	machine.multitool_act(user, tool)
	machine.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(machine.vars["linked_techweb"], web, "[machine_type] could not link its own physical research disk")
	var/registrations = 0
	for(var/atom/consumer as anything in web.connected_machines)
		if(consumer == machine)
			registrations++
	TEST_ASSERT_EQUAL(registrations, 1, "Repeated linking duplicated [machine_type]'s registration")
	tool.buffer = remote_web
	machine.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(machine.vars["linked_techweb"], web, "A foreign buffer replaced [machine_type]'s working link")
	TEST_ASSERT(!(machine in remote_web.connected_machines), "A rejected foreign buffer registered [machine_type]")
	tool.buffer = null
	machine.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(machine.vars["linked_techweb"], web, "An empty buffer cleared [machine_type]'s working link")
	tool.buffer = user
	machine.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(machine.vars["linked_techweb"], web, "An unrelated buffer cleared [machine_type]'s working link")
	var/datum/techweb/deleted_web = allocate(/datum/techweb)
	qdel(deleted_web)
	tool.buffer = deleted_web
	machine.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(machine.vars["linked_techweb"], web, "A deleted buffer cleared [machine_type]'s working link")
	TEST_ASSERT(machine in web.connected_machines, "Rejected buffers unregistered [machine_type]'s working link")

/datum/unit_test/voidcrew_nanite_research/programmer/Run()
	TEST_ASSERT(setup_links(), "No separate site exists for nanite programmer testing")
	web.add_design_by_id("monitoring_nanites")
	for(var/move_server in list(FALSE, TRUE))
		check_programmer(move_server)
		server.forceMove(run_loc_floor_bottom_left)

/datum/unit_test/voidcrew_nanite_research/programmer/proc/check_programmer(move_server)
	var/obj/machinery/computer/nanite_cloud_controller/programmer = allocate(/obj/machinery/computer/nanite_cloud_controller)
	var/datum/nanite_program/old_program = allocate(/datum/nanite_program/self_scan)
	programmer.current_program = old_program
	programmer.multitool_act(user, tool)
	var/list/local_catalog = programmer.ui_static_data(user)
	TEST_ASSERT(length(local_catalog["programs"]), "The local programmer did not expose researched nanite programs")
	var/datum/tgui/ui = allocate(/datum/tgui, user, programmer, "NaniteCloudControl")
	move_apart(programmer, move_server)
	programmer.ui_act("download", list("program_id" = "monitoring_nanites"), ui)
	TEST_ASSERT_EQUAL(programmer.current_program, old_program, "A moved programmer replaced its program with a foreign research download (server moved: [move_server])")
	TEST_ASSERT_NULL(programmer.linked_techweb, "A moved programmer retained its foreign research link")
	TEST_ASSERT(!(programmer in web.connected_machines), "A moved programmer remained registered to its foreign disk")
	var/list/remote_catalog = programmer.ui_static_data(user)
	TEST_ASSERT(!length(remote_catalog["programs"]), "A moved programmer exposed foreign research in its catalog")
	// Moving both endpoints together keeps the same site's own link.
	server.forceMove(get_turf(programmer))
	programmer.multitool_act(user, tool)
	server.forceMove(run_loc_floor_bottom_left)
	programmer.forceMove(run_loc_floor_bottom_left)
	programmer.ui_act("download", list("program_id" = "monitoring_nanites"), ui)
	TEST_ASSERT(istype(programmer.current_program, /datum/nanite_program/monitoring), "A reunited programmer could not download its local program")
	TEST_ASSERT_EQUAL(programmer.linked_techweb, web, "Moving both endpoints together severed the local programmer link")
	move_apart(programmer, move_server)
	programmer.ui_data()
	TEST_ASSERT_NULL(programmer.linked_techweb, "Programmer UI refresh retained a separated research link")
	TEST_ASSERT(istype(programmer.current_program, /datum/nanite_program/monitoring), "Programmer UI refresh erased the program being edited")

/datum/unit_test/voidcrew_nanite_research/chambers/Run()
	TEST_ASSERT(setup_links(), "No separate site exists for nanite chamber testing")
	for(var/move_server in list(FALSE, TRUE))
		check_chamber(move_server)
		server.forceMove(run_loc_floor_bottom_left)
		check_public_chamber(move_server)
		server.forceMove(run_loc_floor_bottom_left)

/datum/unit_test/voidcrew_nanite_research/chambers/proc/check_chamber(move_server)
	var/obj/machinery/nanite_chamber/chamber = allocate(/obj/machinery/nanite_chamber)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent, chamber)
	chamber.occupant = patient
	chamber.multitool_act(user, tool)
	move_apart(chamber, move_server)
	chamber.complete_injection(FALSE)
	TEST_ASSERT_NULL(patient.GetComponent(/datum/component/nanites), "A separated chamber injected nanites using foreign research (server moved: [move_server])")
	TEST_ASSERT_NULL(chamber.linked_techweb, "A separated chamber retained its research link")
	TEST_ASSERT(!chamber.busy && !chamber.locked, "Rejecting a stale injection left the chamber busy or locked")
	server.forceMove(get_turf(chamber))
	chamber.multitool_act(user, tool)
	chamber.complete_injection(FALSE)
	var/datum/component/nanites/nanites = patient.GetComponent(/datum/component/nanites)
	TEST_ASSERT_NOTNULL(nanites, "A reunited chamber could not inject nanites")
	TEST_ASSERT_EQUAL(nanites.linked_techweb, web, "A reunited chamber lost local research attribution")

/datum/unit_test/voidcrew_nanite_research/chambers/proc/check_public_chamber(move_server)
	var/obj/machinery/public_nanite_chamber/chamber = allocate(/obj/machinery/public_nanite_chamber)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent, chamber)
	chamber.occupant = patient
	chamber.cloud_id = 0
	chamber.multitool_act(user, tool)
	move_apart(chamber, move_server)
	chamber.complete_injection(FALSE)
	var/datum/component/nanites/nanites = patient.GetComponent(/datum/component/nanites)
	TEST_ASSERT_NOTNULL(nanites, "A public chamber lost its existing ability to inject without research")
	TEST_ASSERT_NULL(chamber.linked_techweb, "A public chamber retained its separated research link")
	TEST_ASSERT_NULL(nanites.linked_techweb, "A public chamber attributed new nanites to foreign research (server moved: [move_server])")
	var/datum/nanite_program/program = allocate(/datum/nanite_program/monitoring)
	nanites.add_program(null, program)
	chamber.complete_injection(FALSE)
	TEST_ASSERT(program in nanites.programs, "Unlinked injection erased an installed nanite program")
	TEST_ASSERT(!chamber.busy && !chamber.locked, "Public injection left the chamber busy or locked")

/datum/unit_test/voidcrew_nanite_research/cloud/Run()
	TEST_ASSERT(setup_links(), "No separate site exists for nanite cloud testing")
	for(var/move_server in list(FALSE, TRUE))
		check_cloud(move_server)
		server.forceMove(run_loc_floor_bottom_left)

/datum/unit_test/voidcrew_nanite_research/cloud/proc/check_cloud(move_server)
	var/obj/machinery/computer/nanite_cloud_controller/controller = allocate(/obj/machinery/computer/nanite_cloud_controller)
	controller.multitool_act(user, tool)
	var/backup_id = 91 + move_server * 2
	controller.generate_backup(backup_id, user)
	var/datum/nanite_cloud_backup/original = controller.get_backup(backup_id)
	TEST_ASSERT_NOTNULL(original, "A local controller could not create a cloud backup")
	TEST_ASSERT_EQUAL(original.nanites.linked_techweb, web, "A local cloud backup lost its research attribution")
	var/datum/nanite_program/program = allocate(/datum/nanite_program/monitoring)
	original.nanites.add_program(null, program)
	move_apart(controller, move_server)
	controller.generate_backup(backup_id + 1, user)
	var/datum/nanite_cloud_backup/unlinked = controller.get_backup(backup_id + 1)
	TEST_ASSERT_NOTNULL(unlinked, "A controller lost its existing ability to create backups without research")
	TEST_ASSERT_NULL(controller.linked_techweb, "A moved controller retained its foreign research link")
	TEST_ASSERT_NULL(unlinked.nanites.linked_techweb, "A new backup retained foreign research after movement (server moved: [move_server])")
	controller.ui_data()
	TEST_ASSERT_EQUAL(controller.get_backup(backup_id), original, "Research separation discarded an existing cloud backup")
	TEST_ASSERT(program in original.nanites.programs, "Research separation erased an existing cloud program")
	qdel(controller)
