/**
 * Bounty hunting: P1 identity's tests, for voidcrew/modules/bounties/bounty_identity.dm and bounty_looks.dm.
 *
 * Owner: P1 identity. Do not edit this file outside that package. Fork defines are included after the
 * tests, so a test uses the literal value with a comment naming the define.
 */

/// Every tier, archetype and placement gets a record with every field set
/datum/unit_test/voidcrew_bounty_identity_records

/datum/unit_test/voidcrew_bounty_identity_records/Run()
	var/list/styles = list("brawler", "knife", "pistol", "shotgun", "club", "bottle") // BOUNTY_STYLE_*, normal
	var/list/kits = list("juggernaut", "pyromaniac", "demolitionist", "ghost", "heavy") // BOUNTY_KIT_*
	var/list/labels = bounty_feature_labels()
	// BOUNTY_TIER_*, BOUNTY_ARCHETYPE_*, BOUNTY_PLACEMENT_*
	for(var/tier in list(1, 2, 3))
		for(var/archetype in list("meek", "normal", "boss"))
			for(var/placement in list("planet", "ruin", "npc_ship", "trader_outpost"))
				var/datum/bounty_record/record = generate_bounty_record(tier, archetype, placement)
				var/label = "tier [tier] [archetype] at [placement]"
				TEST_ASSERT(record.id, "[label]: no id")
				TEST_ASSERT(istext(record.name) && length(record.name), "[label]: no name")
				TEST_ASSERT(istext(record.alias) && length(record.alias), "[label]: no alias")
				TEST_ASSERT(record.gender == MALE || record.gender == FEMALE, "[label]: gender is [record.gender]")
				TEST_ASSERT(ispath(record.species, /datum/species), "[label]: species is [record.species]")
				TEST_ASSERT(istext(record.crime) && length(record.crime), "[label]: no crime")
				TEST_ASSERT_EQUAL(record.tier, tier, "[label]: wrong tier")
				TEST_ASSERT_EQUAL(record.status, "wanted", "[label]: not wanted") // BOUNTY_RECORD_WANTED
				TEST_ASSERT(islist(record.prison_traits), "[label]: no prison traits list")
				// No mini-bosses at trader outposts (D-A8).
				var/expected = (archetype == "boss" && placement == "trader_outpost") ? "normal" : archetype
				TEST_ASSERT_EQUAL(record.archetype, expected, "[label]: wrong archetype")
				switch(record.archetype)
					if("meek")
						TEST_ASSERT_EQUAL(record.style, "holdout", "[label]: a meek criminal without the holdout") // BOUNTY_STYLE_HOLDOUT
						TEST_ASSERT_NULL(record.kit, "[label]: a meek criminal with a kit")
					if("normal")
						TEST_ASSERT(record.style in styles, "[label]: style [record.style]")
						TEST_ASSERT_NULL(record.kit, "[label]: a normal criminal with a kit")
					if("boss")
						TEST_ASSERT(record.kit in kits, "[label]: kit [record.kit]")
						TEST_ASSERT_NULL(record.style, "[label]: a mini-boss with a style")
				var/datum/bounty_look/look = record.look
				TEST_ASSERT(look, "[label]: no look")
				TEST_ASSERT_EQUAL(look.species, record.species, "[label]: the look is another species")
				TEST_ASSERT_EQUAL(look.physique, record.gender, "[label]: the look's body is the other sex")
				TEST_ASSERT(istext(look.hairstyle) && istext(look.eye_color), "[label]: no hair or eyes")
				// BOUNTY_FEATURES_MIN, BOUNTY_FEATURES_MAX
				TEST_ASSERT(length(record.features) >= 2 && length(record.features) <= 3, "[label]: [length(record.features)] features")
				for(var/kind in record.features)
					TEST_ASSERT(labels[kind], "[label]: unknown feature [kind]")
					TEST_ASSERT(istext(record.features[kind]), "[label]: feature [kind] has no text")
				// A trader-outpost fugitive's mugshot shows an old look (AR-C1).
				if(placement == "trader_outpost")
					TEST_ASSERT(record.old_look, "[label]: no old look for the mugshot")
				else
					TEST_ASSERT_NULL(record.old_look, "[label]: an old look away from a trader outpost")

	// Every species in the pool: a value for each of its visible organs, a skin tone only if it uses
	// one, features it can have, and a plain name.
	for(var/species in GLOB.bounty_species_weights)
		var/datum/species/prototype = GLOB.species_prototypes[species]
		for(var/attempt in 1 to 5)
			var/datum/bounty_record/record = generate_bounty_record(1, "normal", "planet", species)
			TEST_ASSERT_EQUAL(record.species, species, "A forced species was not kept")
			for(var/obj/item/organ/organ_type as anything in prototype.mutant_organs)
				var/datum/bodypart_overlay/mutant/overlay_type = initial(organ_type.bodypart_overlay)
				if(!ispath(overlay_type))
					continue
				var/feature_key = initial(overlay_type.feature_key)
				TEST_ASSERT(istext(record.look.features[feature_key]), "[species]: no [feature_key] in its look")
			if(bounty_species_uses_skin_tones(species))
				TEST_ASSERT(record.look.skin_tone in GLOB.skin_tones, "[species] has skin tone [record.look.skin_tone]")
			else
				TEST_ASSERT_NULL(record.look.skin_tone, "[species] has a skin tone")
			for(var/kind in record.features)
				TEST_ASSERT(bounty_feature_allowed(kind, species), "[species] got a [kind] feature")
		TEST_ASSERT(bounty_species_name(species) != "Unknown", "[species] has no plain name")

	// Rolled archetypes follow the tier.
	for(var/attempt in 1 to 10)
		var/datum/bounty_record/most_wanted = generate_bounty_record(3, null, "planet")
		TEST_ASSERT_EQUAL(most_wanted.archetype, "boss", "A Most Wanted rolled no mini-boss")
		var/datum/bounty_record/petty = generate_bounty_record(1)
		TEST_ASSERT(petty.archetype in list("meek", "normal"), "A Petty criminal rolled a mini-boss")

	// The dialogue file has enough crimes and aliases.
	var/list/crimes = bounty_identity_strings("crimes")
	for(var/tier_key in list("petty", "wanted", "most_wanted"))
		TEST_ASSERT(length(crimes[tier_key]) >= 15, "Only [length(crimes[tier_key])] [tier_key] crimes")
	var/list/aliases = bounty_identity_strings("aliases")
	TEST_ASSERT(length(aliases["any"]) >= 20, "Too few aliases")

	// A bare record (like the seams test makes) gets a look the first time one is needed, and keeps it.
	var/datum/bounty_record/bare = new
	bare.gender = FEMALE
	var/datum/bounty_look/bare_look = bounty_ensure_look(bare)
	TEST_ASSERT(bare_look, "A bare record got no look")
	TEST_ASSERT_EQUAL(bare.species, /datum/species/human, "A bare record isn't human")
	TEST_ASSERT_EQUAL(bare_look.physique, FEMALE, "A bare record's look is the other sex")
	TEST_ASSERT_EQUAL(bounty_ensure_look(bare), bare_look, "A bare record's look changed")

/// Hair reads as the shape the sprite has
/datum/unit_test/voidcrew_bounty_identity_hair_words

/datum/unit_test/voidcrew_bounty_identity_hair_words/Run()
	var/list/expected = list(
		"Pigtails" = "pigtails",
		"Pigtails 3" = "pigtails",
		"Twintails" = "pigtails",
		"Ponytail 3" = "ponytail",
		"Ponytail (Side)" = "ponytail",
		"Braided Tail" = "braided",
		"Short Bangs" = "short",
		"Short Bangs 2" = "short",
		"Very Short Over Eye" = "short",
		"Hime Cut (Short)" = "short",
		"Long Over Eye" = "long",
		"Very Long Hair" = "long",
		"Emo Fringe" = "long fringe",
		"Mohawk (Shaved)" = "mohawk",
		"Balding Hair" = "thinning",
		"Buzzcut" = "cropped short",
		"Afro (Large)" = "afro",
		"Bob Hair 2" = "bob cut",
	)
	for(var/style in expected)
		TEST_ASSERT_EQUAL(bounty_hair_shape(style), expected[style], "The hairstyle [style] reads wrong")
	for(var/style in list("Bald", "Shaved", "Skinhead"))
		TEST_ASSERT_NULL(bounty_hair_shape(style), "The hairstyle [style] reads as hair")

/// The same record looks like the same person in any outfit, and each record and outfit is built once
/datum/unit_test/voidcrew_bounty_identity_same_face

/datum/unit_test/voidcrew_bounty_identity_same_face/Run()
	for(var/species in list(/datum/species/human, /datum/species/lizard, /datum/species/moth, /datum/species/human/felinid))
		var/datum/bounty_record/record = generate_bounty_record(2, "normal", "planet", species)
		var/datum/bounty_look/look = record.look
		var/mob/living/carbon/human/dummy/first = bounty_look_dummy(look, /datum/outfit/bounty_mugshot, record.features)
		var/mob/living/carbon/human/dummy/second = bounty_look_dummy(look, /datum/outfit/outpost_prisoner, record.features)
		TEST_ASSERT(first && second, "A [species] look couldn't be built")
		for(var/mob/living/carbon/human/dummy/dummy as anything in list(first, second))
			TEST_ASSERT_EQUAL(dummy.dna.species.type, species, "A [species] look was built as [dummy.dna.species.type]")
			TEST_ASSERT_EQUAL(dummy.hairstyle, look.hairstyle, "[species]: hairstyle changed with the outfit")
			TEST_ASSERT_EQUAL(dummy.hair_color, look.hair_color, "[species]: hair colour changed with the outfit")
			TEST_ASSERT_EQUAL(dummy.facial_hairstyle, look.facial_hairstyle, "[species]: facial hair changed with the outfit")
			TEST_ASSERT_EQUAL(dummy.physique, look.physique, "[species]: body changed with the outfit")
			if(look.skin_tone)
				TEST_ASSERT_EQUAL(dummy.skin_tone, look.skin_tone, "[species]: skin tone changed with the outfit")
			for(var/feature in look.features)
				TEST_ASSERT_EQUAL(dummy.dna.features[feature], look.features[feature], "[species]: feature [feature] changed with the outfit")
		TEST_ASSERT_EQUAL(first.eye_color_left, second.eye_color_left, "[species]: eye colour changed with the outfit")
		qdel(first)
		qdel(second)

	// apply_bounty_look dresses a mob and builds one look per record and outfit, leaving no dummy behind.
	var/datum/bounty_record/record = generate_bounty_record(1, "meek", "planet")
	var/humans = length(GLOB.human_list)
	var/builds = GLOB.bounty_look_builds
	var/mob/living/basic/mouse/one = allocate(/mob/living/basic/mouse)
	var/mob/living/basic/mouse/two = allocate(/mob/living/basic/mouse)
	var/mob/living/basic/mouse/three = allocate(/mob/living/basic/mouse)
	apply_bounty_look(one, record, /datum/outfit/bounty_mugshot)
	apply_bounty_look(two, record, /datum/outfit/bounty_mugshot/bomber)
	apply_bounty_look(three, record, /datum/outfit/bounty_mugshot)
	TEST_ASSERT_EQUAL(GLOB.bounty_look_builds, builds + 2, "Three mobs in two outfits took [GLOB.bounty_look_builds - builds] builds")
	TEST_ASSERT_EQUAL(length(GLOB.human_list), humans, "Building looks left dummies behind")
	var/first_key = "[record.id]|[/datum/outfit/bounty_mugshot]"
	var/second_key = "[record.id]|[/datum/outfit/bounty_mugshot/bomber]"
	TEST_ASSERT(GLOB.bounty_looks[first_key], "The first outfit's look wasn't cached")
	TEST_ASSERT(GLOB.bounty_looks[second_key], "The second outfit's look wasn't cached")
	TEST_ASSERT_EQUAL(one.icon, 'icons/mob/human/human.dmi', "The dressed mob isn't drawn as a person")
	TEST_ASSERT(length(one.overlays), "The dressed mob has no overlays")
	bounty_forget_looks(record)
	TEST_ASSERT_NULL(GLOB.bounty_looks[first_key], "A forgotten record's look is still cached")
	TEST_ASSERT_NULL(GLOB.bounty_looks[second_key], "A forgotten record's look is still cached")
	apply_bounty_look(one, record, /datum/outfit/bounty_mugshot)
	TEST_ASSERT_EQUAL(GLOB.bounty_look_builds, builds + 3, "A forgotten look wasn't built again")

/// A decoy shares exactly the features asked for, never all of them, and differs in the rest
/datum/unit_test/voidcrew_bounty_identity_decoys

/datum/unit_test/voidcrew_bounty_identity_decoys/Run()
	for(var/attempt in 1 to 20)
		var/datum/bounty_record/wanted = generate_bounty_record(pick(1, 2), null, "trader_outpost")
		var/count = length(wanted.features)
		for(var/shared in 0 to count)
			var/datum/bounty_record/decoy = make_decoy_record(wanted, shared)
			var/expected = min(shared, count - 1)
			var/in_common = 0
			for(var/kind in decoy.features)
				if(decoy.features[kind] == wanted.features[kind])
					in_common++
			TEST_ASSERT_EQUAL(in_common, expected, "A decoy asked to share [shared] of [count] features shares [in_common]")
			TEST_ASSERT_EQUAL(length(decoy.features), count, "A decoy has [length(decoy.features)] features, the fugitive [count]")
			TEST_ASSERT_EQUAL(decoy.species, wanted.species, "A decoy is another species")
			TEST_ASSERT_EQUAL(decoy.gender, wanted.gender, "A decoy is the other sex")
			TEST_ASSERT_EQUAL(decoy.archetype, wanted.archetype, "A decoy talks like another archetype")
			TEST_ASSERT(decoy.id != wanted.id, "A decoy shares the fugitive's record id")
			// Rolled against the current look: the same face but for the hair.
			TEST_ASSERT_EQUAL(decoy.look.skin_tone, wanted.look.skin_tone, "A decoy's skin differs from the fugitive's")
			TEST_ASSERT_EQUAL(decoy.look.eye_color, wanted.look.eye_color, "A decoy's eyes differ from the fugitive's")
			for(var/feature in wanted.look.features)
				TEST_ASSERT_EQUAL(decoy.look.features[feature], wanted.look.features[feature], "A decoy's [feature] differs from the fugitive's")
			var/hair_shared = wanted.features["hair"] && decoy.features["hair"] == wanted.features["hair"] // BOUNTY_FEATURE_HAIR
			if(hair_shared)
				TEST_ASSERT_EQUAL(decoy.look.hairstyle, wanted.look.hairstyle, "A decoy sharing the hair has another hairstyle")
				TEST_ASSERT_EQUAL(decoy.look.hair_color, wanted.look.hair_color, "A decoy sharing the hair has another colour")
			else if(bounty_species_has_hair(wanted.species))
				TEST_ASSERT(bounty_hair_key(decoy.look) != bounty_hair_key(wanted.look), "A decoy's hair reads like the fugitive's without sharing it")
			// Nobody's hair has anything in common with the mugshot's.
			TEST_ASSERT(bounty_hair_nothing_alike(decoy.look, wanted.old_look), "A decoy's hair has something in common with the mugshot's")

/**
 * The trader-outpost lineup (AR-C1): over many bounties, nothing the mugshot shows (face, hair,
 * beard, eyewear) matches the fugitive's current look while matching none of the decoys. The face
 * everyone shares matches all of them; the hair and beard match nobody.
 */
/datum/unit_test/voidcrew_bounty_identity_lineup

/// What someone looks like on a mugshot or across a bar: trait -> value, null for a trait not shown
/datum/unit_test/voidcrew_bounty_identity_lineup/proc/visible_traits(datum/bounty_look/look, list/features)
	var/list/traits = list()
	traits["species"] = look.species
	traits["body"] = look.physique
	traits["skin"] = look.skin_tone
	traits["eyes"] = look.eye_color
	traits["species features"] = json_encode(look.features)
	if(bounty_species_has_hair(look.species))
		traits["hairstyle"] = look.hairstyle
		traits["hair shape"] = bounty_hair_shape(look.hairstyle) || "none"
		if(bounty_species_own_hair_colour(look.species))
			traits["hair colour"] = bounty_hair_colour_name(look.hair_color)
	if(look.physique == MALE && bounty_species_has_facial_hair(look.species))
		traits["beard"] = look.facial_hairstyle || "Shaved"
	traits["eyewear"] = features?["glasses"] // BOUNTY_FEATURE_GLASSES
	return traits

/datum/unit_test/voidcrew_bounty_identity_lineup/Run()
	var/list/pool = list()
	for(var/species in GLOB.bounty_species_weights)
		pool += species
	var/fugitive_hair_matches = 0
	for(var/bounty in 1 to 150)
		// Humans and felinids, whose hair has its own colour, every other time
		var/species = (bounty % 2) ? pick(/datum/species/human, /datum/species/human/felinid) : pick(pool)
		var/datum/bounty_record/wanted = generate_bounty_record(pick(1, 2), null, "trader_outpost", species)
		TEST_ASSERT(wanted.old_look, "Bounty [bounty]: no old look")
		var/list/mugshot_features = bounty_mugshot_features(wanted)
		TEST_ASSERT_NULL(mugshot_features["glasses"], "Bounty [bounty]: the old-look mugshot wears the fugitive's eyewear")
		var/list/mugshot = visible_traits(wanted.old_look, mugshot_features)
		var/list/fugitive = visible_traits(wanted.look, wanted.features)
		var/list/decoys = list()
		var/count = length(wanted.features)
		for(var/decoy_number in 1 to 3) // BOUNTY_DECOY_COUNT
			var/datum/bounty_record/decoy = make_decoy_record(wanted, clamp(rand(1, 2), 1, max(1, count - 1)))
			decoys += list(visible_traits(decoy.look, decoy.features))
		for(var/trait in mugshot)
			var/shown = mugshot[trait]
			if(isnull(shown) || shown != fugitive[trait])
				continue
			if(trait == "hairstyle" || trait == "hair shape" || trait == "hair colour")
				fugitive_hair_matches++
			var/matches_a_decoy = FALSE
			for(var/list/decoy_traits as anything in decoys)
				if(decoy_traits[trait] == shown)
					matches_a_decoy = TRUE
					break
			TEST_ASSERT(matches_a_decoy, "Bounty [bounty] ([species]): the mugshot's [trait] ([shown]) matches the fugitive and no decoy")
	TEST_ASSERT_EQUAL(fugitive_hair_matches, 0, "The mugshot's hair matched the fugitive's current hair [fugitive_hair_matches] times")

	// A planet bounty's mugshot is the true one, eyewear and all.
	var/datum/bounty_record/planet = generate_bounty_record(1, "normal", "planet")
	planet.features = list("glasses" = "round glasses", "scar" = "on the chin")
	TEST_ASSERT_EQUAL(bounty_mugshot_features(planet)["glasses"], "round glasses", "A true mugshot lost its eyewear")

/// A mugshot is built once per record, from a queue that builds one at a time, and every species shows up in it
/datum/unit_test/voidcrew_bounty_identity_mugshot

/datum/unit_test/voidcrew_bounty_identity_mugshot/Run()
	var/datum/bounty_record/record = generate_bounty_record(1, "meek", "planet", /datum/species/human)
	var/builds = GLOB.bounty_mugshot_builds
	var/humans = length(GLOB.human_list)
	var/first = bounty_record_mugshot(record)
	TEST_ASSERT(istext(first) && length(first) > 100, "No mugshot was built")
	TEST_ASSERT_EQUAL(GLOB.bounty_mugshot_builds, builds + 1, "Building one mugshot took [GLOB.bounty_mugshot_builds - builds] builds")
	TEST_ASSERT_EQUAL(bounty_record_mugshot(record), first, "The second call returned another mugshot")
	TEST_ASSERT_EQUAL(bounty_mugshot_cached(record), first, "The UI getter gives something other than the cached mugshot")
	TEST_ASSERT_EQUAL(bounty_mugshot_asset(record), first, "The old UI getter gives something other than the cached mugshot")
	TEST_ASSERT_EQUAL(GLOB.bounty_mugshot_builds, builds + 1, "The mugshot was built again")
	TEST_ASSERT_EQUAL(length(GLOB.human_list), humans, "Building a mugshot left its dummy behind")

	// The UI getter never builds: it answers "" and queues. The queue builds one per call.
	var/list/waiting = list()
	for(var/count in 1 to 3)
		var/datum/bounty_record/unbuilt = generate_bounty_record(1, "meek", "planet")
		TEST_ASSERT_EQUAL(bounty_mugshot_cached(unbuilt), "", "The UI getter built a mugshot itself")
		TEST_ASSERT(unbuilt.identity_mugshot_queued, "The UI getter didn't queue the build")
		bounty_mugshot_cached(unbuilt)
		waiting += unbuilt
	var/queued_before = length(GLOB.bounty_mugshot_queue)
	TEST_ASSERT(queued_before >= 3, "Asking twice queued a record twice, or not at all")
	builds = GLOB.bounty_mugshot_builds
	bounty_build_next_mugshot()
	TEST_ASSERT_EQUAL(GLOB.bounty_mugshot_builds, builds + 1, "One turn of the queue built [GLOB.bounty_mugshot_builds - builds] mugshots")
	TEST_ASSERT_EQUAL(length(GLOB.bounty_mugshot_queue), queued_before - 1, "One turn of the queue took more than one record")
	for(var/turn in 1 to queued_before + 2)
		if(!length(GLOB.bounty_mugshot_queue))
			break
		bounty_build_next_mugshot()
	for(var/datum/bounty_record/unbuilt as anything in waiting)
		TEST_ASSERT(length(unbuilt.mugshot), "A queued mugshot was never built")
		TEST_ASSERT(!unbuilt.identity_mugshot_queued, "A built record is still marked as queued")

	// An old look (AR-C1) keeps the face, has nothing of the hair in common, and the next mugshot shows it.
	var/datum/bounty_look/current = record.look
	var/datum/bounty_look/old = make_old_look(record)
	TEST_ASSERT(old && record.old_look == old, "No old look was made")
	TEST_ASSERT(bounty_hair_nothing_alike(old, current), "The old look's hair has something in common with the current hair")
	TEST_ASSERT_EQUAL(old.species, current.species, "The old look is another species")
	TEST_ASSERT_EQUAL(old.skin_tone, current.skin_tone, "The old look has other skin")
	TEST_ASSERT_EQUAL(old.eye_color, current.eye_color, "The old look has other eyes")
	TEST_ASSERT_NULL(record.mugshot, "The mugshot built before the old look was kept")
	TEST_ASSERT_EQUAL(make_old_look(record), old, "A second call made another old look")
	TEST_ASSERT_EQUAL(bounty_mugshot_cached(record), "", "The old look's mugshot wasn't queued again")

	// Every species in the pool renders someone in the frame.
	for(var/species in GLOB.bounty_species_weights)
		var/datum/bounty_record/sitter = generate_bounty_record(1, "normal", "planet", species)
		var/icon/portrait = bounty_mugshot_icon(sitter.look, sitter.features)
		TEST_ASSERT(portrait, "A [species] mugshot couldn't be built")
		TEST_ASSERT_EQUAL(portrait.Width(), 64, "A [species] mugshot is [portrait.Width()] wide") // (BOUNTY_MUGSHOT_X2 - X1 + 1) * BOUNTY_MUGSHOT_SCALE
		TEST_ASSERT_EQUAL(portrait.Height(), 64, "A [species] mugshot is [portrait.Height()] high")
		var/person = 0
		for(var/x in 1 to 16)
			for(var/y in 1 to 16)
				var/pixel = portrait.GetPixel(x * 4 - 1, y * 4 - 1)
				// BOUNTY_MUGSHOT_BACKDROP, BOUNTY_MUGSHOT_LINES
				if(pixel && lowertext(copytext(pixel, 1, 8)) != "#b9c0c7" && lowertext(copytext(pixel, 1, 8)) != "#949da6")
					person++
		TEST_ASSERT(person >= 40, "A [species] mugshot shows almost nobody ([person] of 256 samples)")

/// Examine lines have one layout, so a fugitive and its decoys read alike
/datum/unit_test/voidcrew_bounty_identity_feature_lines

/datum/unit_test/voidcrew_bounty_identity_feature_lines/Run()
	var/list/order = list("Hair", "Scar", "Tattoo", "Ears", "Eyewear", "Clothing", "Walk")
	var/regex/layout = regex(@"^(Hair|Scar|Tattoo|Ears|Eyewear|Clothing|Walk): [a-z][^<>]*\.$")
	for(var/attempt in 1 to 20)
		var/datum/bounty_record/wanted = generate_bounty_record(pick(1, 2), null, "trader_outpost")
		var/datum/bounty_record/decoy = make_decoy_record(wanted, 1)
		var/list/wanted_lines = wanted.feature_lines()
		var/list/decoy_lines = decoy.feature_lines()
		TEST_ASSERT_EQUAL(length(wanted_lines), length(wanted.features), "Not one line per feature")
		TEST_ASSERT_EQUAL(length(decoy_lines), length(wanted_lines), "A decoy reads [length(decoy_lines)] lines, the fugitive [length(wanted_lines)]")
		for(var/list/lines as anything in list(wanted_lines, decoy_lines))
			var/last_place = 0
			for(var/line in lines)
				TEST_ASSERT(layout.Find(line), "The line \"[line]\" breaks the layout")
				var/place = order.Find(copytext(line, 1, findtext(line, ":")))
				TEST_ASSERT(place > last_place, "The line \"[line]\" is out of order")
				last_place = place
	var/datum/bounty_record/plain = new
	TEST_ASSERT_EQUAL(length(plain.feature_lines()), 0, "A record without features has examine lines")

/// bounty_say(): every context has lines, the cooldown and no-repeat window hold, and each voice speaks its own lines
/datum/unit_test/voidcrew_bounty_identity_say
	/// Lines heard through COMSIG_MOB_SAY
	var/list/heard = list()

/datum/unit_test/voidcrew_bounty_identity_say/proc/on_say(datum/source, list/speech_args)
	SIGNAL_HANDLER
	heard += speech_args[SPEECH_MESSAGE]

/// The lines `voice` can pick for `context`: its own pool and the shared one
/datum/unit_test/voidcrew_bounty_identity_say/proc/pool_of(list/lines, context, voice)
	var/list/pool = list()
	pool += lines[context]["any"]
	if(voice && lines[context][voice])
		pool += lines[context][voice]
	return pool

/// Says `context` through `speaker` `times` times with a fresh memory each time; returns the lines said
/datum/unit_test/voidcrew_bounty_identity_say/proc/sample(mob/living/speaker, context, times, list/values)
	var/datum/component/bounty_identity_voice/voice = speaker.LoadComponent(/datum/component/bounty_identity_voice)
	var/list/said = list()
	for(var/attempt in 1 to times)
		voice.line_cooldown = 0
		voice.recent_lines.Cut()
		if(speaker.bounty_say(context, values))
			said += voice.last_line
	return said

/datum/unit_test/voidcrew_bounty_identity_say/Run()
	var/list/lines = bounty_identity_strings("lines")
	var/list/contexts = list(
		"idle_chat", "bar", "trade_haggle", "explore", "loot", "camp",
		"noticed", "flee", "winded", "hide", "found", "cornered", "draw_gun",
		"fight_start", "hurt", "surrender", "downed", "recover",
		"cuffed", "slipping_cuffs", "beamed_out",
		"accused_wrongly", "accused_rightly", "companion_reply",
	)
	for(var/kit in list("juggernaut", "pyromaniac", "demolitionist", "ghost", "heavy")) // BOUNTY_KIT_*
		// "_posse" is boss_bark("posse", "intro") as the posse grows (BUG-2)
		contexts += list("[kit]_intro", "[kit]_ability", "[kit]_exhausted", "[kit]_posse")
	for(var/context in contexts)
		var/list/by_voice = lines[context]
		TEST_ASSERT(length(by_voice?["any"]) >= 6, "The context [context] has fewer than 6 lines")
	for(var/voice in list("meek", "normal", "boss")) // BOUNTY_ARCHETYPE_*
		TEST_ASSERT(length(lines["idle_chat"][voice]) >= 3, "Too few [voice] small-talk lines")
		TEST_ASSERT(length(lines["bar"][voice]) >= 3, "Too few [voice] bar lines")
		// Last words on the pad (the board's beam-out) in every voice
		TEST_ASSERT(length(lines["beamed_out"][voice]) >= 3, "Too few [voice] beamed-out lines")
	// No crime names a real outpost: a massacre at Waystation Halcyon, the safe hub, would contradict the setting (BUG-8)
	var/list/crimes = bounty_identity_strings("crimes")
	for(var/tier in crimes)
		for(var/crime in crimes[tier])
			for(var/outpost_name in list("Halcyon", "Quartermain", "Undertow", "Longwatch"))
				TEST_ASSERT(!findtext(crime, outpost_name), "The [tier] crime \"[crime]\" names the [outpost_name] outpost")
	// The shared pools are what decoys and blended fugitives say: no taunts, no crime.
	for(var/context in list("hurt", "recover", "cuffed"))
		for(var/line in lines[context]["any"])
			TEST_ASSERT(!findtext(line, "{crime}"), "The shared [context] line \"[line]\" names a crime")
		for(var/taunt in lines[context]["normal"])
			TEST_ASSERT(!(taunt in lines[context]["any"]), "The taunt \"[taunt]\" is in the shared [context] pool")

	var/mob/living/basic/mouse/speaker = allocate(/mob/living/basic/mouse)
	RegisterSignal(speaker, COMSIG_MOB_SAY, PROC_REF(on_say))
	TEST_ASSERT(speaker.bounty_say("flee"), "The first line wasn't said")
	TEST_ASSERT_EQUAL(length(heard), 1, "bounty_say() returned TRUE but nothing was said aloud")
	TEST_ASSERT(!speaker.bounty_say("flee"), "A second line was said inside the cooldown")
	TEST_ASSERT_EQUAL(length(heard), 1, "Something was said inside the cooldown")
	TEST_ASSERT(speaker.bounty_say("flee", force = TRUE), "A forced line was held back by the cooldown")
	TEST_ASSERT_EQUAL(length(heard), 2, "A forced line wasn't said aloud")
	TEST_ASSERT(!speaker.bounty_say("no_such_context", force = TRUE), "A line was said for a context the file doesn't have")

	// Someone who can't speak says nothing, uses no line, and starts no cooldown.
	var/datum/component/bounty_identity_voice/voice = speaker.GetComponent(/datum/component/bounty_identity_voice)
	voice.line_cooldown = 0
	var/remembered = length(voice.recent_lines)
	ADD_TRAIT(speaker, TRAIT_MUTE, "p1_test")
	TEST_ASSERT(!speaker.bounty_say("flee", force = TRUE), "A mute speaker was said to speak")
	TEST_ASSERT(COOLDOWN_FINISHED(voice, line_cooldown), "A mute speaker's silence started the cooldown")
	TEST_ASSERT_EQUAL(length(voice.recent_lines), remembered, "A mute speaker's silence used up a line")
	REMOVE_TRAIT(speaker, TRAIT_MUTE, "p1_test")
	TEST_ASSERT_EQUAL(length(heard), 2, "A mute speaker was heard")

	// "flee" has 6 lines: all of them come up before any repeats.
	var/mob/living/basic/mouse/runner = allocate(/mob/living/basic/mouse)
	var/datum/component/bounty_identity_voice/runner_voice = runner.LoadComponent(/datum/component/bounty_identity_voice)
	var/list/said = list()
	for(var/attempt in 1 to 6)
		runner_voice.line_cooldown = 0
		TEST_ASSERT(runner.bounty_say("flee"), "Line [attempt] of 6 wasn't said")
		said |= runner_voice.last_line
	TEST_ASSERT_EQUAL(length(said), 6, "A line repeated inside the no-repeat window")
	runner_voice.line_cooldown = 0
	TEST_ASSERT(!runner.bounty_say("flee"), "An unforced line repeated inside the no-repeat window")
	TEST_ASSERT(runner.bounty_say("flee", force = TRUE), "A forced line wasn't said once every line was used")
	// Once the window has passed, lines come back.
	for(var/line in runner_voice.recent_lines)
		runner_voice.recent_lines[line] -= 600 // BOUNTY_SAY_NO_REPEAT
	runner_voice.line_cooldown = 0
	TEST_ASSERT(runner.bounty_say("flee"), "Lines didn't come back after the no-repeat window")

	// A line naming a placeholder is said only with a value for it, and the value gets in.
	for(var/line in sample(runner, "accused_rightly", 30))
		TEST_ASSERT(!findtext(line, "{"), "A line was said with an empty placeholder: [line]")
	var/filled = FALSE
	for(var/line in sample(runner, "accused_rightly", 80, list("{crime}" = "stealing a mop")))
		if(findtext(line, "stealing a mop"))
			filled = TRUE
			break
	TEST_ASSERT(filled, "A placeholder value never reached a line")

	// Each archetype speaks its own lines and the shared ones, never another's.
	for(var/archetype in list("meek", "normal", "boss")) // BOUNTY_ARCHETYPE_*
		var/mob/living/basic/bounty_criminal/criminal = allocate(/mob/living/basic/bounty_criminal/normal)
		criminal.record = generate_bounty_record(archetype == "boss" ? 3 : 2, archetype, "planet")
		TEST_ASSERT_EQUAL(criminal.identity_voice(), archetype, "A [archetype] criminal doesn't talk like one")
		var/list/allowed = pool_of(lines, "hurt", archetype)
		var/own_heard = FALSE
		for(var/line in sample(criminal, "hurt", 40))
			TEST_ASSERT(line in allowed, "A [archetype] criminal said another voice's line: [line]")
			if(line in lines["hurt"][archetype])
				own_heard = TRUE
		TEST_ASSERT(own_heard, "A [archetype] criminal never used its own lines")

	// Blended in, a fugitive talks like its decoys; a decoy never names a crime, blended or not.
	var/mob/living/basic/bounty_criminal/fugitive = allocate(/mob/living/basic/bounty_criminal/meek)
	fugitive.record = generate_bounty_record(1, "meek", "trader_outpost")
	fugitive.blended = TRUE
	TEST_ASSERT_NULL(fugitive.identity_voice(), "A blended fugitive talks differently from its decoys")
	TEST_ASSERT_EQUAL(fugitive.identity_line_values()?["{crime}"], fugitive.record.crime, "A fugitive doesn't know its own crime")
	for(var/line in sample(fugitive, "hurt", 20))
		TEST_ASSERT(line in lines["hurt"]["any"], "A blended fugitive said a voiced line: [line]")
	var/mob/living/basic/bounty_criminal/decoy/decoy = allocate(/mob/living/basic/bounty_criminal/decoy)
	decoy.record = make_decoy_record(fugitive.record, 1)
	TEST_ASSERT_NULL(decoy.identity_voice(), "A decoy speaks in an archetype's voice")
	TEST_ASSERT_NULL(decoy.identity_line_values(), "A decoy fills in a crime")
	for(var/line in sample(decoy, "cuffed", 30) + sample(decoy, "accused_rightly", 30))
		TEST_ASSERT(!findtext(line, decoy.record.crime) && !findtext(line, fugitive.record.crime), "A decoy owned up to a crime: [line]")

	// A Most Wanted criminal never tosses off its crime.
	var/mob/living/basic/bounty_criminal/boss = allocate(/mob/living/basic/bounty_criminal/normal)
	boss.record = generate_bounty_record(3, "boss", "planet")
	TEST_ASSERT_NULL(boss.identity_line_values(), "A Most Wanted criminal fills in its crime")
