/// Real scan completion, physical disk removal, and endpoint movement use independent records.
/datum/unit_test/voidcrew_research_movement/survey_records/Run()
	TEST_ASSERT(setup_links(), "No separate site exists for survey testing")
	var/obj/machinery/computer/camera_advanced/shuttle_docker/survey/launch_test/console = allocate(/obj/machinery/computer/camera_advanced/shuttle_docker/survey/launch_test)
	TEST_ASSERT(console.link_to_techweb(web), "An unbound console could not link its local physical server")
	TEST_ASSERT_NOTNULL(console.data, "An unbound console did not initialize a local survey archive")
	TEST_ASSERT(console.data != web.survey_data, "Console and disk share a live survey store")
	console.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(length(web.connected_machines), 1, "Repeated survey links duplicated registration")
	var/obj/machinery/rnd/server/ship/second_server = allocate(/obj/machinery/rnd/server/ship)
	var/obj/item/computer_disk/ship_disk/second_disk = allocate(/obj/item/computer_disk/ship_disk)
	second_server.attacked_by(second_disk, user)
	var/datum/techweb/second_web = second_disk.stored_research
	second_server.forceMove(remote_turf)
	tool.buffer = second_web
	TEST_ASSERT(!console.multitool_act(user, tool), "Survey console reported success for a foreign link")
	TEST_ASSERT_EQUAL(console.linked_techweb, web, "Rejected foreign link removed the local connection")
	second_server.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT(console.link_to_techweb(second_web), "Survey console could not switch local disks")
	TEST_ASSERT(!(console in web.connected_machines), "Survey relink left its old registration")
	var/obj/structure/overmap/star/star = allocate(/obj/structure/overmap/star)
	console.test_candidates = list(star)
	console.survey_research_tiers = list("basic")
	console.survey_celestial_object(user, ref(star))
	TEST_ASSERT(console.survey_in_progress, "A local survey could not start")
	deltimer(console.survey_timer)
	console.complete_survey(star)
	TEST_ASSERT(console.banked_points > 0, "A new local survey did not pay its ordinary reward")
	TEST_ASSERT_EQUAL(length(second_web.survey_data.survey_objects_by_type["stars"]), 1, "Completed scan did not reach its current disk")
	TEST_ASSERT_EQUAL(length(web.survey_data.survey_objects_by_type["stars"]), 0, "Unlinked disk received a later scan")
	var/list/local_records = console.data.survey_objects_by_type["stars"]
	var/list/disk_records = second_web.survey_data.survey_objects_by_type["stars"]
	TEST_ASSERT(local_records[1] != disk_records[1], "Copied survey records still share their mutable datum")
	second_disk.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT_NULL(console.linked_techweb, "Physical disk removal did not detach the survey console")
	TEST_ASSERT(!console.link_to_techweb(second_web), "Survey console accepted the buffer of a removed disk")
	var/obj/structure/overmap/star/later_star = allocate(/obj/structure/overmap/star)
	console.test_candidates = list(later_star)
	console.survey_celestial_object(user, ref(later_star))
	deltimer(console.survey_timer)
	console.complete_survey(later_star)
	TEST_ASSERT_EQUAL(length(disk_records), 1, "Removed physical disk continued receiving live scans")
	second_server.attacked_by(second_disk, user)
	TEST_ASSERT(console.link_to_techweb(second_web), "Reinserted local disk could not reconnect")
	TEST_ASSERT_EQUAL(length(disk_records), 2, "Reconnection did not copy completed local records")
	// A trusted research import arriving during a scan must prevent a second payout.
	var/obj/structure/overmap/star/imported_star = allocate(/obj/structure/overmap/star)
	console.test_candidates = list(imported_star)
	console.survey_celestial_object(user, ref(imported_star))
	deltimer(console.survey_timer)
	var/points_before = console.banked_points
	second_web.survey_data.update_survey_data(imported_star)
	console.complete_survey(imported_star)
	TEST_ASSERT_EQUAL(console.banked_points, points_before, "Importing completed research during a scan paid twice")
	TEST_ASSERT(console.is_object_surveyed(imported_star), "Authorized research records did not reach the local archive")
	QDEL_NULL(console.data)

/datum/unit_test/voidcrew_research_movement/survey_movement/Run()
	TEST_ASSERT(setup_links(), "No separate site exists for survey movement testing")
	for(var/move_server in list(FALSE, TRUE))
		var/obj/machinery/computer/camera_advanced/shuttle_docker/survey/launch_test/console = allocate(/obj/machinery/computer/camera_advanced/shuttle_docker/survey/launch_test)
		TEST_ASSERT(console.link_to_techweb(web), "Local survey link failed")
		var/obj/structure/overmap/star/star = allocate(/obj/structure/overmap/star)
		console.test_candidates = list(star)
		console.survey_research_tiers = list("basic")
		console.survey_celestial_object(user, ref(star))
		deltimer(console.survey_timer)
		move_apart(console, move_server)
		console.complete_survey(star)
		TEST_ASSERT_NULL(console.linked_techweb, "Separated survey endpoints kept their link (server moved: [move_server])")
		TEST_ASSERT_EQUAL(length(web.survey_data.survey_objects_by_type["stars"]), 0, "Separated survey console wrote to another site's disk")
		server.forceMove(run_loc_floor_bottom_left)
		QDEL_NULL(console.data)
