/**
 * Bounty hunting: P6 outposts's tests, for voidcrew/modules/bounties/bounty_outpost.dm.
 *
 * Owner: P6 outposts. Do not edit this file outside that package. Fork defines are included after
 * the tests, so a test uses the literal value with a comment naming the define.
 *
 * The tests make a trader outpost out of the test room (its hangar lift in the top right corner)
 * and drive the procs directly. They pin what the other packages give back where it matters (a
 * test fugitive that records being confronted, a test posting that records being relisted).
 */

/// A fugitive that remembers who confronted it
/mob/living/basic/bounty_criminal/meek/outpost_test
	/// Whoever on_confronted() was last called with
	var/confronted_by

/mob/living/basic/bounty_criminal/meek/outpost_test/on_confronted(mob/user)
	confronted_by = user
	return ..()

/// A posting that remembers being relisted, and doesn't go anywhere
/datum/criminal_bounty/outpost_test
	/// The reason relist() was last called with
	var/relisted_for

/datum/criminal_bounty/outpost_test/relist(reason)
	relisted_for = reason

/// A trader outpost made of the test room, and postings there
/datum/unit_test/voidcrew_bounty_outpost
	abstract_type = /datum/unit_test/voidcrew_bounty_outpost
	/// The outpost the test room stands in for
	var/obj/structure/overmap/trader_outpost/outpost
	/// The crews make_hunter() made, taken apart before the ships go (a team holds its ship)
	var/list/outpost_test_teams = list()
	/// The minds make_hunter() gave a crew, let go of their crew before the teams go
	var/list/outpost_test_minds = list()

/datum/unit_test/voidcrew_bounty_outpost/Destroy()
	GLOB.criminal_bounties -= allocated
	// A mind or a team left pointing at an allocated ship would keep it from being deleted
	for(var/datum/mind/mind as anything in outpost_test_minds)
		mind.ship_teams = null
	for(var/datum/team/voidcrew/team as anything in outpost_test_teams)
		team.ship = null
		qdel(team)
	outpost_test_minds.Cut()
	outpost_test_teams.Cut()
	return ..()

/// A trader outpost whose concourse is the test room, with its hangar lift in the top right corner
/datum/unit_test/voidcrew_bounty_outpost/proc/make_outpost(outpost_type = /obj/structure/overmap/trader_outpost)
	var/obj/structure/overmap/trader_outpost/new_outpost = allocate(outpost_type)
	new_outpost.outpost_template = allocate(/datum/map_template/trader_outpost)
	new_outpost.outpost_template.width = run_loc_floor_top_right.x - run_loc_floor_bottom_left.x + 1
	new_outpost.outpost_template.height = run_loc_floor_top_right.y - run_loc_floor_bottom_left.y + 1
	new_outpost.template_bottom_left = run_loc_floor_bottom_left
	new_outpost.lobby_alcove_turfs = list(run_loc_floor_top_right)
	return new_outpost

/// An open trader-outpost posting at `outpost` with its fugitive standing at `where`
/datum/unit_test/voidcrew_bounty_outpost/proc/make_posting(turf/where, fugitive_type = /mob/living/basic/bounty_criminal/meek/outpost_test)
	var/datum/bounty_record/record = generate_bounty_record(1, "meek", "trader_outpost") // BOUNTY_TIER_PETTY, BOUNTY_ARCHETYPE_MEEK, BOUNTY_PLACEMENT_TRADER_OUTPOST
	var/datum/criminal_bounty/outpost_test/posting = allocate(/datum/criminal_bounty/outpost_test)
	posting.record = record
	posting.placement_kind = "trader_outpost" // BOUNTY_PLACEMENT_TRADER_OUTPOST
	posting.site_ref = WEAKREF(outpost)
	posting.value = 1234
	var/mob/living/basic/bounty_criminal/fugitive = allocate(fugitive_type, where || run_loc_floor_bottom_left)
	fugitive.record = record
	fugitive.posting_ref = WEAKREF(posting)
	posting.criminal_ref = WEAKREF(fugitive)
	GLOB.criminal_bounties += posting
	return posting

/// A person with a mind, crewing `ship` if given. The crew is taken apart when the test ends.
/datum/unit_test/voidcrew_bounty_outpost/proc/make_hunter(obj/structure/overmap/ship/ship)
	var/mob/living/carbon/human/hunter = allocate(/mob/living/carbon/human/consistent)
	hunter.mind_initialize()
	if(ship)
		var/datum/team/voidcrew/team = new
		team.ship = ship
		hunter.mind.ship_teams = list(team)
		outpost_test_teams += team
		outpost_test_minds += hunter.mind
	return hunter

/// The posting's decoys, resolved
/datum/unit_test/voidcrew_bounty_outpost/proc/decoys_of(datum/criminal_bounty/posting)
	. = list()
	for(var/datum/weakref/decoy_ref as anything in posting.decoys)
		var/mob/living/basic/bounty_criminal/decoy/decoy = decoy_ref?.resolve()
		if(decoy)
			. += decoy

/// A mob's examine as plain text, with its own feature lines taken out
/datum/unit_test/voidcrew_bounty_outpost/proc/plain_examine(mob/living/basic/bounty_criminal/patron, mob/viewer)
	var/list/features = list()
	for(var/line in patron.record?.feature_lines())
		features += trim(STRIP_HTML_FULL("[line]", MAX_MESSAGE_LEN))
	var/list/lines = list()
	for(var/line in patron.examine(viewer))
		var/plain = trim(STRIP_HTML_FULL("[line]", MAX_MESSAGE_LEN))
		if(!(plain in features))
			lines += plain
	return lines.Join(" | ")

/// How many of `wanted`'s features `decoy` has exactly: the same kind with the same value
/datum/unit_test/voidcrew_bounty_outpost/proc/shared_features(list/decoy_features, list/wanted_features)
	var/shared = 0
	for(var/kind in decoy_features)
		if((kind in wanted_features) && wanted_features[kind] == decoy_features[kind])
			shared++
	return shared

/// Setting up: the fugitive blends in, three decoys share one or two of its features, and an outpost takes at most two fugitives and never a mini-boss
/datum/unit_test/voidcrew_bounty_outpost/blend

/datum/unit_test/voidcrew_bounty_outpost/blend/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "A trader-outpost posting could not be set up to blend in")
	TEST_ASSERT(fugitive.blended, "The fugitive is not blending in")

	var/list/decoys = decoys_of(posting)
	TEST_ASSERT_EQUAL(length(decoys), 3, "The fugitive did not get three decoys") // BOUNTY_DECOY_COUNT
	TEST_ASSERT_EQUAL(length(posting.outpost_decoy_shares), 3, "The decoys' shared features were not recorded")
	var/list/wanted_features = posting.record.features
	for(var/shared in posting.outpost_decoy_shares)
		TEST_ASSERT(shared >= 1 && shared <= 2, "A decoy was made to share [shared] features, not one or two")
		if(length(wanted_features))
			TEST_ASSERT(shared < length(wanted_features), "A decoy was made to share all [length(wanted_features)] of the fugitive's features")
	for(var/mob/living/basic/bounty_criminal/decoy/decoy as anything in decoys)
		TEST_ASSERT(decoy.blended, "A decoy is not blending in")
		TEST_ASSERT(decoy.record && decoy.record != posting.record, "A decoy has no record of its own")
		TEST_ASSERT_NULL(decoy.posting_ref, "A decoy is linked to the posting as if it were the criminal")
		TEST_ASSERT(decoy.loc != fugitive.loc, "A decoy spawned on the fugitive")
		TEST_ASSERT(!(decoy.loc in outpost.lobby_alcove_turfs), "A decoy spawned on the hangar lift")
		TEST_ASSERT_EQUAL(decoy.record.crime, posting.record.crime, "A decoy's record names a different crime from the fugitive's")
		// P1's features are kind -> value; a shared feature is the same kind with the same value
		if(length(wanted_features) >= 2)
			var/shared = shared_features(decoy.record.features, wanted_features)
			TEST_ASSERT(shared >= 1 && shared <= 2 && shared < length(wanted_features), "A decoy shares [shared] of the fugitive's [length(wanted_features)] features")

	// At most two fugitives at one outpost, and never a mini-boss (AR-C9)
	var/datum/criminal_bounty/outpost_test/second = make_posting(run_loc_floor_bottom_left)
	TEST_ASSERT(second.setup_outpost_blend(), "A second fugitive was refused at the outpost")
	var/datum/criminal_bounty/outpost_test/third = make_posting(run_loc_floor_bottom_left)
	TEST_ASSERT(!third.setup_outpost_blend(), "A third fugitive was let into one outpost")
	var/datum/criminal_bounty/outpost_test/boss_posting = make_posting(run_loc_floor_bottom_left, /mob/living/basic/bounty_criminal/boss)
	boss_posting.record.archetype = "boss" // BOUNTY_ARCHETYPE_BOSS
	second.status = "closed" // BOUNTY_POSTING_CLOSED: the outpost has room again
	TEST_ASSERT(!boss_posting.setup_outpost_blend(), "A mini-boss was set up at a trader outpost")
	TEST_ASSERT(third.setup_outpost_blend(), "A closed posting still counted against the outpost's fugitives")

	// A record whose mugshot is already out keeps the face everyone has seen (M3)
	var/datum/criminal_bounty/outpost_test/published = make_posting(run_loc_floor_bottom_left)
	third.status = "closed" // BOUNTY_POSTING_CLOSED
	published.record.old_look = null
	published.record.mugshot = "published"
	TEST_ASSERT(published.setup_outpost_blend(), "A relisted posting could not be set up")
	TEST_ASSERT_NULL(published.record.old_look, "A published face was given an invented past")
	TEST_ASSERT_EQUAL(published.record.mugshot, "published", "A published mugshot was thrown away")

/// Only customers' floor: a fugitive placed behind a counter moves out onto the concourse, and the decoys come from the same floor (M5)
/datum/unit_test/voidcrew_bounty_outpost/public_floor

/datum/unit_test/voidcrew_bounty_outpost/public_floor/Run()
	outpost = make_outpost()
	// A counter right across the room, two rows up: the bottom two rows are behind it
	var/counter_y = run_loc_floor_bottom_left.y + 2
	for(var/x in run_loc_floor_bottom_left.x to run_loc_floor_top_right.x)
		allocate(/obj/structure/table, locate(x, counter_y, run_loc_floor_bottom_left.z))
	var/datum/criminal_bounty/outpost_test/posting = make_posting(run_loc_floor_bottom_left)
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	var/list/floor = bounty_outpost_public_floor(outpost)
	TEST_ASSERT(!(run_loc_floor_bottom_left in floor), "Floor behind the counter counts as the customers'")
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	TEST_ASSERT(fugitive.y > counter_y, "The fugitive stayed behind the counter")
	for(var/mob/living/basic/bounty_criminal/decoy/decoy as anything in decoys_of(posting))
		TEST_ASSERT(decoy.y > counter_y, "A decoy spawned behind the counter")
	// P5 places fugitives with the same picker
	var/turf/spot = bounty_outpost_spawn_spot(outpost)
	TEST_ASSERT(spot && (spot in floor) && !(spot in outpost.lobby_alcove_turfs), "The spawn picker gave [spot], not the customers' floor")

/// The fugitive and its decoys look alike to a player: the same generic name, never the alias, and the same examine, body, speed and time down
/datum/unit_test/voidcrew_bounty_outpost/names

/datum/unit_test/voidcrew_bounty_outpost/names/Run()
	outpost = make_outpost(/obj/structure/overmap/trader_outpost/outfitter)
	outpost.lobby_alcove_turfs = list(run_loc_floor_top_right)
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys), "No decoys to compare with")
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]

	TEST_ASSERT_EQUAL(fugitive.name, "dockhand", "The fugitive at the outfitter is not called a dockhand")
	TEST_ASSERT_EQUAL(decoy.name, fugitive.name, "A decoy's name differs from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.real_name, fugitive.real_name, "A decoy's voice name differs from the fugitive's")
	TEST_ASSERT(fugitive.name != posting.record.name && fugitive.name != posting.record.alias, "The fugitive shows its name or alias")
	TEST_ASSERT_EQUAL(decoy.desc, fugitive.desc, "A decoy's description differs from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.maxHealth, fugitive.maxHealth, "A decoy's health differs from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.move_resist, fugitive.move_resist, "A decoy's move resistance differs from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.cached_multiplicative_slowdown, fugitive.cached_multiplicative_slowdown, "A decoy's speed differs from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.stamina_regen_time, fugitive.stamina_regen_time, "A decoy's stamina crit lasts a different time from the fugitive's")
	TEST_ASSERT_EQUAL(decoy.max_stamina_slowdown, fugitive.max_stamina_slowdown, "A decoy slows on stamina damage differently from the fugitive")
	TEST_ASSERT_EQUAL(decoy.damage_coeff[STAMINA], fugitive.damage_coeff[STAMINA], "A decoy takes stamina damage differently from the fugitive")
	TEST_ASSERT_EQUAL(decoy.body_recovery_time(), fugitive.body_recovery_time(), "A decoy stays down for a different time from the fugitive")

	// Examine: the same plain text once each one's own feature lines are taken out
	decoy.gender = fugitive.gender
	var/mob/living/carbon/human/viewer = make_hunter()
	TEST_ASSERT_EQUAL(plain_examine(decoy, viewer), plain_examine(fugitive, viewer), "A decoy examines differently from the fugitive")

	// The other zones' names
	TEST_ASSERT_EQUAL(bounty_outpost_display_name(allocate(/obj/structure/overmap/trader_outpost/general)), "patron", "Halcyon's crowd is not patrons")
	TEST_ASSERT_EQUAL(bounty_outpost_display_name(allocate(/obj/structure/overmap/trader_outpost/black_market)), "spacer", "The Undertow's crowd is not spacers")

/// The warrant: on a decoy it raises the alert, on the fugitive it confronts it, and a ship waits between warrants
/datum/unit_test/voidcrew_bounty_outpost/warrant

/datum/unit_test/voidcrew_bounty_outpost/warrant/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/meek/outpost_test/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys) >= 2, "Too few decoys to test with")
	var/obj/structure/overmap/ship/ship = allocate(/obj/structure/overmap/ship)
	var/mob/living/carbon/human/hunter = make_hunter(ship)
	var/obj/item/paper/bounty_warrant/warrant = allocate(/obj/item/paper/bounty_warrant)
	warrant.posting_ref = WEAKREF(posting)

	// A shopper shown the warrant: nothing happens, and it costs no wait
	var/mob/living/carbon/human/shopper = make_hunter()
	warrant.show_warrant(shopper, hunter)
	TEST_ASSERT_EQUAL(posting.alert, 0, "Showing the warrant to a shopper raised the alert")
	TEST_ASSERT_EQUAL(posting.outpost_warrant_wait(hunter), 0, "Showing the warrant to a shopper started the wait")

	// A decoy: it protests, and the alert rises
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]
	warrant.show_warrant(decoy, hunter)
	TEST_ASSERT_EQUAL(posting.alert, 1, "A wrong warrant did not raise the alert")
	TEST_ASSERT(decoy.blended, "A decoy stopped blending in after a wrong warrant")

	// The ship waits 30 seconds (BOUNTY_WARRANT_COOLDOWN) before the next one, whoever shows it
	TEST_ASSERT(posting.outpost_warrant_wait(hunter) > 0, "A wrong warrant started no wait")
	var/mob/living/carbon/human/crewmate = make_hunter(ship)
	warrant.show_warrant(fugitive, crewmate)
	TEST_ASSERT_NULL(fugitive.confronted_by, "A crewmate got round the ship's warrant wait")
	// Another ship does not wait on this one
	var/mob/living/carbon/human/rival = make_hunter(allocate(/obj/structure/overmap/ship))
	TEST_ASSERT_EQUAL(posting.outpost_warrant_wait(rival), 0, "One ship's warrant made another ship wait")

	// The fugitive: confronted, exposed and holding a grudge
	posting.outpost_warrant_ready_at.Cut()
	warrant.show_warrant(fugitive, hunter)
	TEST_ASSERT_EQUAL(fugitive.confronted_by, hunter, "The right warrant did not confront the fugitive")
	TEST_ASSERT(!fugitive.blended, "The fugitive kept blending in after being confronted")
	TEST_ASSERT(fugitive.body_has_grudge(hunter), "The fugitive does not hold a grudge against whoever confronted it")
	TEST_ASSERT(!HAS_TRAIT_FROM(fugitive, "no_containment", "bounty_outpost"), "An exposed fugitive still can't be put in a locker") // TRAIT_NO_CONTAINMENT, BOUNTY_OUTPOST_TRAIT
	TEST_ASSERT_EQUAL(posting.alert, 1, "Confronting the right person raised the alert")

	// A closed posting's warrant does nothing
	posting.outpost_warrant_ready_at.Cut()
	posting.status = "closed" // BOUNTY_POSTING_CLOSED
	warrant.show_warrant(decoys[2], hunter)
	TEST_ASSERT_EQUAL(posting.alert, 1, "An out-of-date warrant raised the alert")

/// Cuffs reached for on someone blending in cost exactly what a punch costs, and a decoy confronted any other way raises the alert (C1)
/datum/unit_test/voidcrew_bounty_outpost/cuffs

/datum/unit_test/voidcrew_bounty_outpost/cuffs/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/meek/outpost_test/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys) >= 2, "Too few decoys to test with")
	var/obj/item/restraints/handcuffs/cuffs = allocate(/obj/item/restraints/handcuffs)

	// A decoy's wrists: a strike and the alert, the cuffs don't go on, and it doesn't just protest for free
	var/mob/living/carbon/human/cuffer = make_hunter()
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]
	cuffs.melee_attack_chain(cuffer, decoy, list())
	TEST_ASSERT_EQUAL(outpost.aggressor_strikes[cuffer.mind], 1, "Cuffs on a decoy were not an outpost strike, as a punch is")
	TEST_ASSERT_EQUAL(posting.alert, 1, "Cuffs on a decoy did not raise the alert, as a punch does")
	TEST_ASSERT(!decoy.is_restrained(), "A decoy on its feet was cuffed")
	TEST_ASSERT(decoy.blended, "A decoy stopped blending in")

	// The fugitive's wrists: the act is over, as for a punch, and nothing is charged
	var/mob/living/carbon/human/other_cuffer = make_hunter()
	cuffs.melee_attack_chain(other_cuffer, fugitive, list())
	TEST_ASSERT(!fugitive.blended, "Cuffs on the fugitive did not end its act")
	TEST_ASSERT_EQUAL(fugitive.confronted_by, other_cuffer, "Cuffs on the fugitive did not confront it")
	TEST_ASSERT(fugitive.body_has_grudge(other_cuffer), "The fugitive holds no grudge against whoever reached for its wrists")
	TEST_ASSERT_NULL(outpost.aggressor_strikes[other_cuffer.mind], "Reaching for the fugitive's wrists was an outpost strike")
	TEST_ASSERT_EQUAL(posting.alert, 1, "Reaching for the fugitive's wrists raised the alert")

	// Any other way of confronting a decoy is a wrong accusation
	var/datum/criminal_bounty/outpost_test/next = make_posting(run_loc_floor_bottom_left)
	TEST_ASSERT(next.setup_outpost_blend(), "The second posting could not be set up to blend in")
	var/list/next_decoys = decoys_of(next)
	TEST_ASSERT(length(next_decoys), "No decoys at the second posting")
	var/mob/living/basic/bounty_criminal/decoy/next_decoy = next_decoys[1]
	next_decoy.on_confronted(make_hunter())
	TEST_ASSERT_EQUAL(next.alert, 1, "Confronting a decoy another way cost nothing")

/// Two alerts: the fugitive and its decoys walk out and the bounty relists; an exposed fugitive stays
/datum/unit_test/voidcrew_bounty_outpost/alert

/datum/unit_test/voidcrew_bounty_outpost/alert/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)

	TEST_ASSERT(posting.raise_alert("a test"), "The alert did not rise")
	TEST_ASSERT_EQUAL(posting.alert, 1, "The first alert did not count")
	TEST_ASSERT_NULL(posting.relisted_for, "The bounty relisted at the first alert")
	TEST_ASSERT(posting.raise_alert("a test"), "The alert did not rise a second time")
	TEST_ASSERT_NOTNULL(posting.relisted_for, "Two alerts did not relist the bounty") // BOUNTY_OUTPOST_ALERT_SLIP
	TEST_ASSERT_NULL(posting.criminal(), "The posting kept hold of a fugitive that slipped away")
	TEST_ASSERT_NULL(fugitive.posting_ref, "A fugitive that slipped away still points at the posting")
	TEST_ASSERT_EQUAL(length(posting.decoys), 0, "The posting kept hold of its decoys")
	TEST_ASSERT(fugitive.GetComponent(/datum/component/bounty_outpost_exit), "The fugitive did not leave")
	for(var/mob/living/basic/bounty_criminal/decoy/decoy as anything in decoys)
		TEST_ASSERT(decoy.GetComponent(/datum/component/bounty_outpost_exit), "A decoy did not leave with the fugitive")

	// Once exposed, the chase is on: no more slipping away
	var/datum/criminal_bounty/outpost_test/exposed = make_posting(run_loc_floor_bottom_left)
	var/mob/living/basic/bounty_criminal/exposed_fugitive = exposed.criminal()
	TEST_ASSERT(exposed.setup_outpost_blend(), "The second posting could not be set up to blend in")
	exposed.outpost_confront(exposed_fugitive, make_hunter())
	exposed.raise_alert("a test")
	exposed.raise_alert("a test")
	TEST_ASSERT_NULL(exposed.relisted_for, "An exposed fugitive slipped away")
	TEST_ASSERT_EQUAL(exposed.criminal(), exposed_fugitive, "An exposed fugitive was let go")

	// Only trader-outpost postings have an alert
	var/datum/criminal_bounty/outpost_test/planet = make_posting(run_loc_floor_bottom_left)
	planet.placement_kind = "planet" // BOUNTY_PLACEMENT_PLANET
	TEST_ASSERT(!planet.raise_alert("a test"), "A planet bounty's alert rose")

/// A deliberate hit on a decoy is an outpost strike and raises the alert; hitting the fugitive only exposes it
/datum/unit_test/voidcrew_bounty_outpost/decoy_hit

/datum/unit_test/voidcrew_bounty_outpost/decoy_hit/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys) >= 2, "Too few decoys to test with")
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]

	// Someone with no mind behind them never counts
	var/mob/living/carbon/human/npc = allocate(/mob/living/carbon/human/consistent)
	npc.combat_mode = TRUE
	decoy.attack_hand(npc, list())
	TEST_ASSERT_EQUAL(posting.alert, 0, "A mindless hit on a decoy raised the alert")

	// A friendly touch never counts
	var/mob/living/carbon/human/hunter = make_hunter()
	decoy.attack_hand(hunter, list())
	TEST_ASSERT_EQUAL(posting.alert, 0, "Patting a decoy raised the alert")
	TEST_ASSERT_NULL(outpost.aggressor_strikes[hunter.mind], "Patting a decoy was an outpost strike")

	// A punch is a strike and an alert
	hunter.combat_mode = TRUE
	decoy.attack_hand(hunter, list())
	TEST_ASSERT_EQUAL(outpost.aggressor_strikes[hunter.mind], 1, "Punching a decoy was not an outpost strike")
	TEST_ASSERT_EQUAL(posting.alert, 1, "Punching a decoy did not raise the alert")

	// A shot aimed at a decoy counts; a shot at someone else passes through it
	var/mob/living/carbon/human/shooter = make_hunter()
	var/obj/projectile/bullet/stray = allocate(/obj/projectile/bullet)
	stray.firer = shooter
	stray.original = hunter
	var/mob/living/basic/bounty_criminal/decoy/other_decoy = decoys[2]
	TEST_ASSERT(SEND_SIGNAL(other_decoy, COMSIG_PROJECTILE_PREHIT, stray) & PROJECTILE_INTERRUPT_HIT_PHASE, "A shot at someone else hit a decoy")
	TEST_ASSERT_EQUAL(posting.alert, 1, "A stray shot through a decoy raised the alert")
	var/obj/projectile/bullet/aimed = allocate(/obj/projectile/bullet)
	aimed.firer = shooter
	aimed.original = other_decoy
	TEST_ASSERT(!(SEND_SIGNAL(other_decoy, COMSIG_PROJECTILE_PREHIT, aimed) & PROJECTILE_INTERRUPT_HIT_PHASE), "A shot aimed at a decoy passed through it")
	TEST_ASSERT_EQUAL(outpost.aggressor_strikes[shooter.mind], 1, "Shooting a decoy was not an outpost strike")
	TEST_ASSERT_NOTNULL(posting.relisted_for, "Two hits on decoys did not send the fugitive away")

	// Hitting the (next) fugitive exposes it: no strike, no alert
	var/datum/criminal_bounty/outpost_test/next = make_posting(run_loc_floor_bottom_left)
	var/mob/living/basic/bounty_criminal/next_fugitive = next.criminal()
	TEST_ASSERT(next.setup_outpost_blend(), "The second posting could not be set up to blend in")
	var/mob/living/carbon/human/brawler = make_hunter()
	brawler.combat_mode = TRUE
	next_fugitive.attack_hand(brawler, list())
	TEST_ASSERT(!next_fugitive.blended, "Punching the fugitive did not expose it")
	TEST_ASSERT(next_fugitive.body_has_grudge(brawler), "The fugitive holds no grudge against whoever hit it")
	TEST_ASSERT_EQUAL(next.alert, 0, "Hitting the fugitive raised the alert")
	TEST_ASSERT_NULL(outpost.aggressor_strikes[brawler.mind], "Hitting the fugitive was an outpost strike")

/// Things thrown straight at a decoy and a mech's fist count as hits; a throw at someone else that lands on one doesn't (H1)
/datum/unit_test/voidcrew_bounty_outpost/thrown

/datum/unit_test/voidcrew_bounty_outpost/thrown/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys) >= 2, "Too few decoys to test with")
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]
	var/mob/living/basic/bounty_criminal/decoy/other_decoy = decoys[2]
	var/obj/item/storage/toolbox/toolbox = allocate(/obj/item/storage/toolbox)
	TEST_ASSERT(toolbox.throwforce > 0, "The toolbox is too light to test with")

	// Thrown at someone else, landing on a decoy: nobody is framed with it
	var/mob/living/carbon/human/thrower = make_hunter()
	var/mob/living/carbon/human/bystander = make_hunter()
	var/datum/thrownthing/stray = new(toolbox, bystander, NORTH, 7, 1, thrower)
	SEND_SIGNAL(decoy, COMSIG_ATOM_PREHITBY, toolbox, stray)
	qdel(stray)
	TEST_ASSERT_EQUAL(posting.alert, 0, "A throw at someone else that hit a decoy raised the alert")
	TEST_ASSERT_NULL(outpost.aggressor_strikes[thrower.mind], "A throw at someone else that hit a decoy was a strike")

	// Thrown at the decoy: a strike and the alert
	var/datum/thrownthing/aimed = new(toolbox, decoy, NORTH, 7, 1, thrower)
	SEND_SIGNAL(decoy, COMSIG_ATOM_PREHITBY, toolbox, aimed)
	qdel(aimed)
	TEST_ASSERT_EQUAL(outpost.aggressor_strikes[thrower.mind], 1, "A toolbox thrown at a decoy was not a strike")
	TEST_ASSERT_EQUAL(posting.alert, 1, "A toolbox thrown at a decoy did not raise the alert")

	// A mech's fist is its pilot's
	var/mob/living/carbon/human/pilot = make_hunter()
	SEND_SIGNAL(other_decoy, COMSIG_ATOM_ATTACK_MECH, null, pilot, 0)
	TEST_ASSERT_EQUAL(outpost.aggressor_strikes[pilot.mind], 1, "A mech punching a decoy was not a strike for its pilot")
	TEST_ASSERT_NOTNULL(posting.relisted_for, "Two hits on decoys did not send the fugitive away")

/// While blending in nobody can pull them, the lift never carries them, and the turrets leave them alone; the fugitive's shots at the outpost reach only its grudge list, and hurting a bystander ends the turrets' leave
/datum/unit_test/voidcrew_bounty_outpost/security

/datum/unit_test/voidcrew_bounty_outpost/security/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys), "No decoys to test with")
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]
	var/mob/living/carbon/human/hunter = make_hunter()

	TEST_ASSERT(!decoy.can_be_pulled(hunter, MOVE_FORCE_OVERPOWERING), "A decoy can be pulled")
	TEST_ASSERT(!fugitive.can_be_pulled(hunter, MOVE_FORCE_OVERPOWERING), "The fugitive can be pulled while blending in")
	TEST_ASSERT(!decoy.may_attack(hunter), "A decoy may attack someone")

	// The hangar lift carries whoever stands on it: they never step onto it (L8)
	var/turf/lift = run_loc_floor_top_right
	var/turf/beside_lift = get_step(lift, WEST)
	decoy.forceMove(beside_lift)
	decoy.Move(lift, EAST)
	TEST_ASSERT_EQUAL(decoy.loc, beside_lift, "A decoy stepped onto the hangar lift")

	// The turrets: this one does shoot a hostile creature, and skips the patrons by faction
	var/obj/machinery/porta_turret/outpost/turret = allocate(/obj/machinery/porta_turret/outpost)
	turret.outpost = outpost
	TEST_ASSERT(turret.valid_target(allocate(/mob/living/basic/carp)), "The test turret won't shoot anything, so it proves nothing")
	TEST_ASSERT(turret.in_faction(decoy) && turret.in_faction(fugitive), "The patrons are not in the turrets' faction")
	TEST_ASSERT(!turret.valid_target(decoy), "The outpost turrets target a decoy")
	TEST_ASSERT(!turret.valid_target(fugitive), "The outpost turrets target a fugitive blending in")

	// The fugitive's own shots pass through anyone who hasn't crossed it
	var/mob/living/carbon/human/bystander = make_hunter()
	var/obj/projectile/bullet/shot = allocate(/obj/projectile/bullet)
	SEND_SIGNAL(fugitive, COMSIG_PROJECTILE_FIRER_BEFORE_FIRE, shot, fugitive, hunter)
	TEST_ASSERT(SEND_SIGNAL(shot, COMSIG_PROJECTILE_SELF_PREHIT, bystander) & PROJECTILE_INTERRUPT_HIT_PHASE, "The fugitive's shot hit a bystander")
	fugitive.body_add_grudge(hunter)
	TEST_ASSERT(!(SEND_SIGNAL(shot, COMSIG_PROJECTILE_SELF_PREHIT, hunter) & PROJECTILE_INTERRUPT_HIT_PHASE), "The fugitive's shot passed through someone on its grudge list")

	// Exposed and fighting those who came for it, the turrets still leave it to the hunters (AR-C8)
	posting.outpost_confront(fugitive, hunter)
	TEST_ASSERT(!turret.in_faction(fugitive), "An exposed fugitive is still in the turrets' faction")
	SEND_SIGNAL(fugitive, COMSIG_HOSTILE_POST_ATTACKINGTARGET, hunter, TRUE)
	TEST_ASSERT(!fugitive.outpost_turret_target(), "Fighting its grudge list made the fugitive a turret target")
	// Hurting someone who never crossed it ends that
	SEND_SIGNAL(fugitive, COMSIG_HOSTILE_POST_ATTACKINGTARGET, bystander, TRUE)
	TEST_ASSERT(fugitive.outpost_turret_target(), "The fugitive hurt a bystander and the turrets still leave it be")
	TEST_ASSERT(!decoy.outpost_turret_target(), "A decoy is a turret target")

/// Traders give a different clue each, once per ship, and only to a ship hunting the fugitive there; a place is never told as true after it has changed
/datum/unit_test/voidcrew_bounty_outpost/clues

/datum/unit_test/voidcrew_bounty_outpost/clues/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting(run_loc_floor_bottom_left)
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	// A haircut since the mugshot, so the hair clue is in the pool whatever P1 makes. Both looks keep
	// the record's species: a look with none can't name a decoy.
	var/datum/bounty_look/now = new
	now.species = posting.record.species
	now.physique = posting.record.gender
	now.hairstyle = "Mohawk"
	now.hair_color = "#101010"
	var/datum/bounty_look/then = new
	then.species = posting.record.species
	then.physique = posting.record.gender
	then.hairstyle = "Bob Hair"
	then.hair_color = "#e0c060"
	posting.record.look = now
	posting.record.old_look = then
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT_EQUAL(length(decoys), 3, "The fugitive did not get three decoys")
	// No lift nearby for this, and one person to a corner, so where each stands picks them out
	outpost.lobby_alcove_turfs = list()
	var/list/corners = list(
		run_loc_floor_top_right,
		locate(run_loc_floor_bottom_left.x, run_loc_floor_top_right.y, run_loc_floor_bottom_left.z),
		locate(run_loc_floor_top_right.x, run_loc_floor_bottom_left.y, run_loc_floor_bottom_left.z),
	)
	for(var/index in 1 to 3)
		var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[index]
		decoy.forceMove(corners[index])

	var/list/traders = list()
	for(var/index in 1 to 4)
		var/mob/living/basic/outpost_trader/trader = allocate(/mob/living/basic/outpost_trader)
		trader.outpost = outpost
		traders += trader

	var/obj/structure/overmap/ship/ship = allocate(/obj/structure/overmap/ship)
	var/mob/living/carbon/human/hunter = make_hunter(ship)
	TEST_ASSERT_NULL(bounty_outpost_ask_posting(traders[1], hunter), "A ship not hunting the fugitive can ask about it")
	posting.claimants += WEAKREF(ship)
	TEST_ASSERT_EQUAL(bounty_outpost_ask_posting(traders[1], hunter), posting, "A ship hunting the fugitive can't ask about it")
	TEST_ASSERT(bounty_outpost_ask(traders[1], hunter), "Asking a trader did nothing")

	var/list/answers = list()
	for(var/index in 1 to 3)
		answers += posting.outpost_clue_for(traders[index], ship)
	TEST_ASSERT_EQUAL(length(unique_list(answers)), 3, "Traders repeated each other: [answers.Join(" / ")]")
	TEST_ASSERT(!("Can't help you there." in answers), "A trader had nothing to say with clues still untold") // BOUNTY_OUTPOST_NO_CLUE

	// Asking again gets the same clue, not a new one
	var/again = posting.outpost_clue_for(traders[1], ship)
	TEST_ASSERT(findtext(again, "I told you what I know"), "Asking twice got a new clue: [again]")

	// Another ship asking the same trader hears the same kind of clue
	var/obj/structure/overmap/ship/rival = allocate(/obj/structure/overmap/ship)
	var/list/kind_before = posting.outpost_trader_clues[REF(traders[2])]
	posting.outpost_clue_for(traders[2], rival)
	TEST_ASSERT_EQUAL(posting.outpost_trader_clues[REF(traders[2])], kind_before, "A trader changed their story for another ship")

	// A decoy ruled out by where it stood, and the fugitive then standing there: never told as true (M4)
	var/mob/living/basic/outpost_trader/witness = traders[4]
	posting.outpost_trader_clues[REF(witness)] = list("ruled_out", 1) // BOUNTY_CLUE_RULED_OUT, the first decoy
	var/first = posting.outpost_clue_for(witness, ship)
	var/place = bounty_outpost_where(decoys[1], outpost)
	TEST_ASSERT(findtext(first, "The one [place]?"), "The ruled-out clue was not about the first decoy: [first]")
	fugitive.forceMove(corners[1])
	var/retold = posting.outpost_clue_for(witness, ship)
	TEST_ASSERT(!findtext(retold, "The one [place]?"), "A trader told the fugitive's place as ruled out: [retold]")
	TEST_ASSERT(findtext(retold, "earlier"), "A trader retold a place that changed without saying it was earlier: [retold]")
	var/fresh = posting.outpost_clue_for(witness, rival)
	TEST_ASSERT(!findtext(fresh, "The one [place]?"), "A trader told another ship the fugitive's place was ruled out: [fresh]")

	// The hair clue says how it changed
	var/hair = bounty_outpost_hair_clue(posting.record)
	TEST_ASSERT(findtext(hair, "mohawk") || findtext(hair, "Mohawk"), "The hair clue does not name the new style: [hair]")
	TEST_ASSERT(findtext(hair, "black"), "The hair clue does not name the new colour: [hair]")

	// A feature clue is only ever the one the printed warrant leaves off (its last), never one it already lists (BUG-10)
	var/list/lines = posting.record.feature_lines()
	var/list/feature_clues = list()
	for(var/list/clue as anything in posting.outpost_build_clue_pool())
		if(clue[1] == "feature") // BOUNTY_CLUE_FEATURE
			feature_clues += clue[2]
	if(length(lines))
		TEST_ASSERT_EQUAL(length(feature_clues), 1, "The traders could give [length(feature_clues)] feature clues, not only the one off the warrant")
		TEST_ASSERT_EQUAL(feature_clues[1], length(lines), "The traders' feature clue is one the warrant already lists")
		// Said the way a person says it, never the examine label ("Scar: ...")
		var/feature_words = posting.outpost_clue_words(list("feature", length(lines)))
		TEST_ASSERT(findtext(feature_words, "I remember one thing about them. "), "The feature clue reads: [feature_words]")
		TEST_ASSERT(!findtext(feature_words, ":"), "The feature clue reads out the examine label: [feature_words]")
	else
		TEST_ASSERT(!length(feature_clues), "A fugitive with no features has a feature clue")

/// The wanted board lists the open public postings and nothing else, never builds a picture on the spot, and is outpost property
/datum/unit_test/voidcrew_bounty_outpost/board

/datum/unit_test/voidcrew_bounty_outpost/board/Run()
	outpost = make_outpost()
	var/obj/structure/bounty_wanted_board/board = allocate(/obj/structure/bounty_wanted_board)
	TEST_ASSERT(HAS_TRAIT(board, "outpost_property"), "The wanted board is not outpost property") // TRAIT_OUTPOST_PROPERTY

	var/datum/criminal_bounty/outpost_test/public_posting = make_posting()
	var/datum/criminal_bounty/outpost_test/private_posting = make_posting()
	private_posting.private_to = WEAKREF(allocate(/obj/structure/overmap/ship))
	var/datum/criminal_bounty/outpost_test/closed_posting = make_posting()
	closed_posting.status = "closed" // BOUNTY_POSTING_CLOSED

	var/list/ids = list()
	for(var/list/entry as anything in board.outpost_board_entries())
		ids[entry["id"]] = entry
	var/list/listed = ids[public_posting.record.id]
	TEST_ASSERT_NOTNULL(listed, "The board does not list a public posting")
	TEST_ASSERT_EQUAL(listed["reward"], 1234, "The board shows the wrong reward")
	TEST_ASSERT_EQUAL(listed["tier_level"], public_posting.record.tier, "The board shows the wrong tier")
	TEST_ASSERT_EQUAL(listed["terms"], "Wanted alive", "The board doesn't say how they're wanted")
	// A poster, not the rules: no clock, no kill-only flag (2026-09-26)
	for(var/key in list("time_left", "kill_only", "here", "tier"))
		TEST_ASSERT(!(key in listed), "The board still sends [key]")
	TEST_ASSERT_EQUAL(listed["place"], "Seen on this concourse", "The board does not say where they were seen: [listed["place"]]")
	TEST_ASSERT(!ids[private_posting.record.id], "The board lists a private offer")
	TEST_ASSERT(!ids[closed_posting.record.id], "The board lists a closed posting")

	// Pictures that aren't built yet are queued, never built in the click (L4)
	public_posting.record.mugshot = null
	var/mob/living/carbon/human/reader = make_hunter()
	var/builds_before = GLOB.bounty_mugshot_builds
	var/list/static_data = board.ui_static_data(reader)
	TEST_ASSERT_EQUAL(GLOB.bounty_mugshot_builds, builds_before, "Opening the board built a mugshot on the spot")
	TEST_ASSERT(islist(static_data["mugshots"]), "The board sends no mugshots")
	// Only ui_data() moves the signature, so every viewer is refreshed when it changes (L7)
	board.ui_data(reader)
	TEST_ASSERT_EQUAL(board.outpost_static_signature, bounty_public_board_signature(), "The board did not notice what it shows")

/// When the posting closes the decoys and an uncaught fugitive walk out to the lift and fade; a walk never outlives its walker, and an unreachable lift means fading in place
/datum/unit_test/voidcrew_bounty_outpost/cleanup

/datum/unit_test/voidcrew_bounty_outpost/cleanup/Run()
	outpost = make_outpost()
	// Closing for real (P5's close() tells P6 before it removes anyone)
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/leaving = decoys_of(posting) + fugitive
	TEST_ASSERT_EQUAL(length(leaving), 4, "Expected the fugitive and three decoys")
	posting.close("expired") // BOUNTY_CLOSE_EXPIRED
	var/list/walks = list()
	for(var/mob/living/walker as anything in leaving)
		if(QDELETED(walker))
			continue
		var/datum/component/bounty_outpost_exit/exit = walker.GetComponent(/datum/component/bounty_outpost_exit)
		TEST_ASSERT(exit, "[walker] neither left nor was removed when the posting closed")
		TEST_ASSERT(HAS_TRAIT(walker, TRAIT_GODMODE), "[walker] can be hurt on the way out")
		if(exit.walk_loop)
			walks += exit.walk_loop
	TEST_ASSERT(length(walks), "Nobody set off for the lift they can reach")
	// One is deleted mid-walk: its walk goes with it, and the pathfinder is never asked about it again
	var/mob/living/deleted_walker = leaving[1]
	var/datum/component/bounty_outpost_exit/deleted_exit = deleted_walker.GetComponent(/datum/component/bounty_outpost_exit)
	var/datum/move_loop/deleted_walk = deleted_exit?.walk_loop
	qdel(deleted_walker)
	TEST_ASSERT(!deleted_walk || QDELETED(deleted_walk), "A walk outlived its walker")
	// The rest fade (their walk would take a few seconds more)
	for(var/mob/living/walker as anything in leaving)
		if(QDELETED(walker))
			continue
		var/datum/component/bounty_outpost_exit/exit = walker.GetComponent(/datum/component/bounty_outpost_exit)
		exit?.fade_out()
		TEST_ASSERT(!exit?.walk_loop, "[walker] kept walking while fading")
	var/deadline = world.time + 5 SECONDS
	UNTIL(world.time > deadline || !length(leaving - get_all_qdeleted(leaving)))
	for(var/mob/living/walker as anything in leaving)
		TEST_ASSERT(QDELETED(walker), "[walker] was still there after the posting closed")

	// Behind a counter the lift can't be reached: they fade where they stand, with no walk at all
	var/counter_y = run_loc_floor_bottom_left.y + 2
	for(var/x in run_loc_floor_bottom_left.x to run_loc_floor_top_right.x)
		allocate(/obj/structure/table, locate(x, counter_y, run_loc_floor_bottom_left.z))
	var/datum/criminal_bounty/outpost_test/released = make_posting(locate(run_loc_floor_bottom_left.x, run_loc_floor_top_right.y, run_loc_floor_bottom_left.z))
	TEST_ASSERT(released.setup_outpost_blend(), "The second posting could not be set up to blend in")
	var/list/walkers = decoys_of(released) + released.criminal()
	var/mob/living/stranded = walkers[1]
	stranded.forceMove(run_loc_floor_bottom_left)
	released.outpost_release_site()
	TEST_ASSERT_EQUAL(length(released.decoys), 0, "The posting kept its decoys")
	TEST_ASSERT_NULL(released.criminal(), "The posting kept its fugitive")
	var/datum/component/bounty_outpost_exit/stranded_exit = stranded.GetComponent(/datum/component/bounty_outpost_exit)
	TEST_ASSERT(stranded_exit?.fading && !stranded_exit.walk_loop, "Someone who can't reach the lift set off for it")
	for(var/mob/living/walker as anything in walkers)
		var/datum/component/bounty_outpost_exit/exit = walker.GetComponent(/datum/component/bounty_outpost_exit)
		TEST_ASSERT(exit, "[walker] did not leave")
		exit.fade_out()
	deadline = world.time + 5 SECONDS
	UNTIL(world.time > deadline || !length(walkers - get_all_qdeleted(walkers)))
	for(var/mob/living/walker as anything in walkers)
		TEST_ASSERT(QDELETED(walker), "[walker] was still there after walking out")

/// Everything in `things` that has been deleted
/datum/unit_test/voidcrew_bounty_outpost/cleanup/proc/get_all_qdeleted(list/things)
	. = list()
	for(var/datum/thing as anything in things)
		if(QDELETED(thing))
			. += thing

/// Each trader outpost map has one wanted board, on a wall of its concourse
/datum/unit_test/voidcrew_bounty_outpost_maps

/datum/unit_test/voidcrew_bounty_outpost_maps/Run()
	for(var/outpost_type in list(
		/obj/structure/overmap/trader_outpost/general,
		/obj/structure/overmap/trader_outpost/outfitter,
		/obj/structure/overmap/trader_outpost/black_market,
	))
		var/obj/structure/overmap/trader_outpost/outpost = allocate(outpost_type)
		TEST_ASSERT(outpost.load_level(), "[outpost_type]'s interior failed to load")
		var/turf/bottom_left = outpost.template_bottom_left
		var/turf/top_right = locate(bottom_left.x + outpost.outpost_template.width - 1, bottom_left.y + outpost.outpost_template.height - 1, bottom_left.z)
		var/list/boards = list()
		for(var/turf/interior as anything in block(bottom_left, top_right))
			for(var/obj/structure/bounty_wanted_board/found in interior)
				boards += found
		TEST_ASSERT_EQUAL(length(boards), 1, "[outpost_type] has [length(boards)] wanted boards, not one")
		var/obj/structure/bounty_wanted_board/board = boards[1]
		TEST_ASSERT(isopenturf(board.loc), "[outpost_type]'s wanted board is not on a floor")
		TEST_ASSERT(isclosedturf(get_step(board, board.dir)), "[outpost_type]'s wanted board is not hung on a wall")
		TEST_ASSERT(HAS_TRAIT(board, "outpost_property"), "[outpost_type]'s wanted board is not outpost property") // TRAIT_OUTPOST_PROPERTY
		// The customers' floor reaches the board, and the spawn picker finds room for everyone
		TEST_ASSERT(length(bounty_outpost_public_floor(outpost)) > 50, "[outpost_type] has almost no customers' floor from its lift")
		TEST_ASSERT_EQUAL(length(bounty_outpost_spawn_spots(outpost, 4)), 4, "[outpost_type] has no room for a fugitive and three decoys")
		qdel(outpost)

/// P2's drag rule holds while blending in: anyone down or cuffed can be dragged, the fugitive and its decoys alike (AR-C6); standing, nobody can
/datum/unit_test/voidcrew_bounty_outpost/drag

/datum/unit_test/voidcrew_bounty_outpost/drag/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting()
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	var/list/decoys = decoys_of(posting)
	TEST_ASSERT(length(decoys), "No decoys to test with")
	var/mob/living/basic/bounty_criminal/decoy/decoy = decoys[1]
	var/mob/living/carbon/human/hunter = make_hunter()

	TEST_ASSERT(!fugitive.can_be_pulled(hunter, MOVE_FORCE_OVERPOWERING), "A standing fugitive blending in can be pulled")
	TEST_ASSERT(!decoy.can_be_pulled(hunter, MOVE_FORCE_OVERPOWERING), "A standing decoy can be pulled")
	// Down (a blast, say) while still blending in: both drag, so the drag gives nobody away
	fugitive.downed = TRUE
	decoy.downed = TRUE
	TEST_ASSERT(fugitive.blended, "The fugitive stopped blending in without being hit")
	TEST_ASSERT(fugitive.can_be_pulled(hunter, MOVE_FORCE_OVERPOWERING), "A downed fugitive blending in can't be dragged")
	TEST_ASSERT(decoy.can_be_pulled(hunter, MOVE_FORCE_OVERPOWERING), "A downed decoy can't be dragged, so the fugitive stands out")
	fugitive.downed = FALSE
	decoy.downed = FALSE
	// Walking out, never
	var/datum/component/bounty_outpost_blend/blend = fugitive.GetComponent(/datum/component/bounty_outpost_blend)
	blend.leaving = TRUE
	fugitive.downed = TRUE
	TEST_ASSERT(!fugitive.can_be_pulled(hunter, MOVE_FORCE_OVERPOWERING), "Someone walking out can be pulled")
	fugitive.downed = FALSE
	blend.leaving = FALSE

/// The right warrant: the nearest trader in sight calls out
/datum/unit_test/voidcrew_bounty_outpost/room_reacts

/datum/unit_test/voidcrew_bounty_outpost/room_reacts/Run()
	outpost = make_outpost()
	var/datum/criminal_bounty/outpost_test/posting = make_posting(run_loc_floor_bottom_left)
	var/mob/living/basic/bounty_criminal/fugitive = posting.criminal()
	TEST_ASSERT(posting.setup_outpost_blend(), "The posting could not be set up to blend in")
	fugitive.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT_NULL(posting.outpost_trader_reacts(fugitive), "A trader reacted with no trader there")
	var/mob/living/basic/outpost_trader/far = allocate(/mob/living/basic/outpost_trader, run_loc_floor_top_right)
	var/mob/living/basic/outpost_trader/near = allocate(/mob/living/basic/outpost_trader, locate(run_loc_floor_bottom_left.x + 1, run_loc_floor_bottom_left.y + 1, run_loc_floor_bottom_left.z))
	far.outpost = outpost
	near.outpost = outpost
	TEST_ASSERT_EQUAL(posting.outpost_trader_reacts(fugitive), near, "The nearest trader didn't react to the fugitive being exposed")

/// The wanted board: the ship card's own place words (a lair's real name, BUG-5), "Seen on this concourse" for a fugitive here (P11), and the vouchers and "Wanted dead" (BUG-13)
/datum/unit_test/voidcrew_bounty_outpost/board_card

/datum/unit_test/voidcrew_bounty_outpost/board_card/Run()
	outpost = make_outpost()
	var/obj/structure/bounty_wanted_board/board = allocate(/obj/structure/bounty_wanted_board)
	var/datum/criminal_bounty/outpost_test/here = make_posting()
	here.board_vouchers = 2
	var/datum/criminal_bounty/outpost_test/elsewhere = make_posting()
	elsewhere.site_ref = WEAKREF(allocate(/obj/structure/overmap/trader_outpost/general))
	var/datum/criminal_bounty/kill_only/lair = new
	allocated += lair
	lair.record = bounty_kill_record("Test Don", "running a test club", MALE, 5000, "mugshot")
	lair.placement_kind = "ruin" // BOUNTY_PLACEMENT_RUIN
	lair.board_site_name = "Club Test"
	lair.value = 5000
	lair.expires_at = world.time + 10 MINUTES
	GLOB.criminal_bounties += lair

	var/list/entries = list()
	for(var/list/entry as anything in board.outpost_board_entries())
		entries[entry["id"]] = entry
	var/list/here_entry = entries[here.record.id]
	var/list/elsewhere_entry = entries[elsewhere.record.id]
	var/list/lair_entry = entries[lair.record.id]
	TEST_ASSERT_EQUAL(here_entry?["place"], "Seen on this concourse", "A fugitive on this concourse isn't marked as seen here: [here_entry?["place"]]")
	TEST_ASSERT(elsewhere_entry?["place"] != "Seen on this concourse", "A fugitive at another outpost is marked as seen here")
	TEST_ASSERT_EQUAL(here_entry?["vouchers"], 2, "The board doesn't show the vouchers")
	TEST_ASSERT_EQUAL(here_entry?["terms"], "Wanted alive", "A live bounty reads as [here_entry?["terms"]]")
	TEST_ASSERT_EQUAL(lair_entry?["terms"], "Wanted dead", "A kill-only bounty reads as [lair_entry?["terms"]]")
	TEST_ASSERT(findtext(lair_entry?["place"], "Club Test"), "The board doesn't name the lair: [lair_entry?["place"]]")
	TEST_ASSERT(!findtext(lair_entry?["place"], "encrypted signal"), "The board calls a lair an encrypted signal")
	lair.close("admin") // BOUNTY_CLOSE_ADMIN
