/// Actual claim ground, visiting hull, research disks, survey disk and UI actions.
/datum/unit_test/voidcrew_launch_cargo_fixture/outpost_home/survey_archive/Run()
	save_economy()
	var/obj/structure/overmap/dynamic/player_outpost/home = allocate(/obj/structure/overmap/dynamic/player_outpost)
	home.shell_template = allocate(/datum/map_template/player_outpost/small)
	home.founder_ckey = "surveyarchivefounder"
	TEST_ASSERT(home.load_level(), "The survey archive test home could not load")
	test_ship_tile = home.arrival_turf
	test_original_area = get_area(test_ship_tile)
	test_ship_area = new
	test_ship_tile.change_area(test_original_area, test_ship_area)
	test_port = new(test_ship_tile)
	test_port.width = 1
	test_port.height = 1
	test_port.dwidth = 0
	test_port.dheight = 0
	test_port.shuttle_areas = list()
	test_port.shuttle_areas[test_ship_area] = TRUE
	test_ship_area.shuttle_port = test_port
	test_port.shuttle_id = "survey_archive_visitor"
	test_port.register()
	var/obj/structure/overmap/ship/visitor = allocate(/obj/structure/overmap/ship)
	visitor.survey_data = new // Normal ship loading creates this before its console is bound.
	visitor.shuttle = test_port
	test_port.current_ship = visitor
	visitor.docked = home
	visitor.state = "idle"
	var/turf/home_tile = get_step(test_ship_tile, SOUTH)
	TEST_ASSERT_EQUAL(get_service_site(test_ship_tile), visitor, "Visitor hull did not resolve independently")
	TEST_ASSERT_EQUAL(get_outpost_from_atom(home_tile), home, "Archive floor is not claim ground")
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent, home_tile)
	var/obj/machinery/rnd/server/ship/local_server = allocate(/obj/machinery/rnd/server/ship, home_tile)
	var/obj/machinery/rnd/server/ship/ship_server = allocate(/obj/machinery/rnd/server/ship, test_ship_tile)
	var/obj/item/computer_disk/ship_disk/local_disk = allocate(/obj/item/computer_disk/ship_disk, home_tile)
	var/obj/item/computer_disk/ship_disk/ship_disk = allocate(/obj/item/computer_disk/ship_disk, test_ship_tile)
	local_server.attacked_by(local_disk, user)
	ship_server.attacked_by(ship_disk, user)
	var/obj/machinery/computer/camera_advanced/shuttle_docker/survey/console = allocate(/obj/machinery/computer/camera_advanced/shuttle_docker/survey, test_ship_tile)
	TEST_ASSERT(console.validate_ship_binding(), "Survey console could not bind its actual visiting hull")
	TEST_ASSERT_EQUAL(console.data, visitor.survey_data, "Onboard survey console lost its own ship archive")
	TEST_ASSERT(console.link_to_techweb(ship_disk.stored_research), "Onboard survey console could not use its own server")
	var/list/onboard_ui = console.ui_data(user)
	TEST_ASSERT(!onboard_ui["archiveMode"], "Ordinary docking turned an onboard console into a shore archive")
	TEST_ASSERT_EQUAL(console.linked_techweb, ship_disk.stored_research, "Ordinary docking lost onboard research")
	var/obj/structure/overmap/star/retained = allocate(/obj/structure/overmap/star)
	visitor.survey_data.update_survey_data(retained)
	console.sync_research_surveys()
	var/obj/structure/overmap/star/pending = allocate(/obj/structure/overmap/star)
	visitor.close_overmap_objects = list(pending)
	console.survey_celestial_object(user, ref(pending))
	TEST_ASSERT(console.survey_in_progress, "Actual onboard survey could not start")
	console.forceMove(home_tile)
	console.complete_survey(pending)
	TEST_ASSERT(!console.survey_in_progress, "Moving ashore did not cancel the old ship's pending survey")
	TEST_ASSERT_EQUAL(console.banked_points, 0, "A console ashore earned an orbital survey reward")
	TEST_ASSERT_NULL(visitor.survey_console, "Moved console remained registered as the visitor's survey control")
	TEST_ASSERT_NULL(console.ship_port, "Shore console retained an old ship control link")
	TEST_ASSERT(console.data != visitor.survey_data, "Shore archive retained the visitor's live record store")
	TEST_ASSERT(console.is_object_surveyed(retained), "Moving hardware lost its already completed records")
	visitor.survey_data.update_survey_data(pending)
	TEST_ASSERT(!console.is_object_surveyed(pending), "Shore archive continued reading future visitor records")
	TEST_ASSERT(console.link_to_techweb(local_disk.stored_research), "Shore archive could not link its local server")
	TEST_ASSERT(!(console in ship_disk.stored_research.connected_machines), "Shore archive remained a visitor research consumer")
	var/list/shore_ui = console.ui_data(user)
	TEST_ASSERT(shore_ui["archiveMode"] && shore_ui["researchLinked"], "Shore UI did not expose the functional local archive")
	TEST_ASSERT_EQUAL(length(shore_ui["surveyTargets"]), 0, "Shore UI exposed the visitor's orbital targets")
	TEST_ASSERT_NULL(shore_ui["currentCelestialRef"], "Shore UI retained an orbital target")
	var/obj/item/disk/survey_data_disk/records_disk = allocate(/obj/item/disk/survey_data_disk)
	var/obj/structure/overmap/star/imported = allocate(/obj/structure/overmap/star)
	records_disk.data.update_survey_data(imported)
	user.put_in_hands(records_disk)
	console.attackby(records_disk, user)
	TEST_ASSERT_EQUAL(records_disk.loc, console, "Survey record disk was not physically inserted")
	var/datum/tgui/ui = allocate(/datum/tgui, user, console, "SurveyComputer")
	console.ui_act("downloadData", list(), ui)
	TEST_ASSERT(console.is_object_surveyed(imported), "Shore UI did not import completed physical disk records")
	TEST_ASSERT_EQUAL(length(local_disk.stored_research.survey_data.survey_objects_by_type["stars"]), 2, "Imported records did not unlock local research")
	TEST_ASSERT_EQUAL(length(ship_disk.stored_research.survey_data.survey_objects_by_type["stars"]), 1, "Shore imports modified the visitor's research disk")
	console.ui_act("saveData", list(), ui)
	TEST_ASSERT_EQUAL(length(records_disk.data.survey_objects_by_type["stars"]), 2, "Shore UI did not export all completed records")
	console.ui_act("survey", list("target_ref" = ref(pending)), ui)
	console.ui_act("map", list(), ui)
	console.ui_act("jump", list(), ui)
	TEST_ASSERT(!console.survey_in_progress, "Forged shore UI action started an orbital scan")
	TEST_ASSERT_NULL(console.eyeobj, "Forged shore UI action opened the visitor's map")
	TEST_ASSERT(!console.placeLandingSpot(), "Shore console accepted a direct docking designation")
	TEST_ASSERT(!console.canDesignateTarget(), "Shore console allowed a delayed docking designation")
	console.ui_act("eject", list(), ui)
	TEST_ASSERT_NULL(console.survey_disk, "Shore UI could not eject the record disk")
	TEST_ASSERT_EQUAL(get_turf(records_disk), home_tile, "Shore UI did not return the physical disk")
	user.put_in_hands(records_disk)
	console.attackby(records_disk, user)
	records_disk.forceMove(home_tile)
	var/removed_disk_before = json_encode(records_disk.data.tgui_serialize())
	console.data.update_survey_data(pending)
	console.ui_act("saveData", list(), ui)
	TEST_ASSERT_NULL(console.survey_disk, "Externally removed survey disk remained linked")
	TEST_ASSERT_EQUAL(json_encode(records_disk.data.tgui_serialize()), removed_disk_before, "Stale UI wrote to an externally removed disk")
	// Returning the actual hardware aboard preserves the hull's records and restores its controls.
	console.forceMove(test_ship_tile)
	TEST_ASSERT(console.validate_ship_binding(), "Returned survey hardware could not rejoin its own hull")
	TEST_ASSERT_EQUAL(console.data, visitor.survey_data, "Returned console did not use the visitor's own archive")
	TEST_ASSERT(console.is_object_surveyed(pending), "Returning aboard lost research completed by the ship")
	TEST_ASSERT_EQUAL(console.linked_techweb, ship_disk.stored_research, "Returned console did not regain its own ship research")
	console.forceMove(home_tile)
	SEND_SIGNAL(visitor, "voidcrew_ship_moved") // COMSIG_VOIDCREW_SHIP_MOVED is defined after test includes.
	TEST_ASSERT_NULL(console.ship_port, "An old ship movement signal did not detach its relocated console")
	test_port.current_ship = null
	visitor.shuttle = null
	qdel(visitor)
	// A separately built shore console must also work after the founding/visiting ship is gone.
	var/obj/machinery/computer/camera_advanced/shuttle_docker/survey/shore_console = allocate(/obj/machinery/computer/camera_advanced/shuttle_docker/survey, home_tile)
	TEST_ASSERT_NOTNULL(shore_console.data, "A newly built shore console has no archive")
	TEST_ASSERT(shore_console.link_to_techweb(local_disk.stored_research), "New shore console could not use completed local research")
	var/list/new_shore_ui = shore_console.ui_static_data(user)
	TEST_ASSERT_NOTNULL(new_shore_ui["surveyData"], "A newly built shore console could not display its archive")
	user.put_in_hands(records_disk)
	shore_console.attackby(records_disk, user)
	records_disk.forceMove(test_ship_tile)
	qdel(shore_console)
	TEST_ASSERT_EQUAL(get_turf(records_disk), test_ship_tile, "Destroying a console moved a previously removed disk")
