/// Real physical disks and two service sites; no research or material operations are mocked.
/datum/unit_test/voidcrew_research_movement
	abstract_type = /datum/unit_test/voidcrew_research_movement
	var/mob/living/carbon/human/user
	var/obj/item/multitool/tool
	var/obj/machinery/rnd/server/ship/server
	var/datum/techweb/web
	var/turf/remote_turf

/datum/unit_test/voidcrew_research_movement/proc/setup_links()
	user = allocate(/mob/living/carbon/human/consistent)
	tool = allocate(/obj/item/multitool)
	server = allocate(/obj/machinery/rnd/server/ship)
	var/obj/item/computer_disk/ship_disk/disk = allocate(/obj/item/computer_disk/ship_disk)
	server.attacked_by(disk, user)
	web = disk.stored_research
	tool.buffer = web
	for(var/level in 1 to world.maxz)
		var/turf/candidate = locate(1, 1, level)
		if(!same_service_site(server, candidate))
			remote_turf = candidate
			return TRUE
	return FALSE

/datum/unit_test/voidcrew_research_movement/proc/move_apart(atom/movable/machine, move_server)
	server.forceMove(move_server ? remote_turf : run_loc_floor_bottom_left)
	machine.forceMove(move_server ? run_loc_floor_bottom_left : remote_turf)

/datum/unit_test/voidcrew_research_movement/fabricators/Run()
	TEST_ASSERT(setup_links(), "No separate service site exists for movement testing")
	for(var/move_server in list(FALSE, TRUE))
		check_lathe(move_server)
		server.forceMove(run_loc_floor_bottom_left)
		check_exofab(move_server)
		server.forceMove(run_loc_floor_bottom_left)
		check_components(move_server)
		server.forceMove(run_loc_floor_bottom_left)

/datum/unit_test/voidcrew_research_movement/fabricators/proc/check_lathe(move_server)
	var/obj/machinery/rnd/production/protolathe/launch_fabrication_test/lathe = allocate(/obj/machinery/rnd/production/protolathe/launch_fabrication_test)
	lathe.materials.set_local_size(1000 * SHEET_MATERIAL_AMOUNT)
	lathe.connect_techweb(web)
	var/datum/design/design = SSresearch.techweb_design_by_id("cable_coil")
	web.add_design(design)
	for(var/material in design.materials)
		lathe.materials.mat_container.insert_amount_mat(10000, material)
	var/before = json_encode(lathe.materials.mat_container.materials)
	move_apart(lathe, move_server)
	lathe.set_machine_stat(NONE)
	// This is the per-item timer callback: queued lathes have not paid for the next item yet.
	lathe.print_test_design(design, 1)
	TEST_ASSERT_EQUAL(json_encode(lathe.materials.mat_container.materials), before, "Separated lathe consumed materials for a foreign design (server moved: [move_server])")
	TEST_ASSERT_NULL(lathe.stored_research, "Separated lathe retained its research link")
	TEST_ASSERT(!lathe.busy, "Rejected queued production left the lathe busy")
	// Moving both endpoints together must keep their link, as when their ship changes levels.
	server.forceMove(get_turf(lathe))
	lathe.connect_techweb(web)
	server.forceMove(run_loc_floor_bottom_left)
	lathe.forceMove(run_loc_floor_bottom_left)
	lathe.set_machine_stat(NONE)
	lathe.print_test_design(design, 1)
	TEST_ASSERT(json_encode(lathe.materials.mat_container.materials) != before, "Reunited physical endpoints could not manufacture")
	TEST_ASSERT_EQUAL(lathe.stored_research, web, "Moving endpoints together lost their own research link")

/datum/unit_test/voidcrew_research_movement/fabricators/proc/check_exofab(move_server)
	var/obj/machinery/mecha_part_fabricator/fabricator = allocate(/obj/machinery/mecha_part_fabricator)
	fabricator.drop_direction = 0
	fabricator.rmat.set_local_size(1000 * SHEET_MATERIAL_AMOUNT)
	fabricator.connect_techweb(web)
	var/datum/design/design = SSresearch.techweb_design_by_id("basic_cell")
	web.add_design(design)
	for(var/material in design.materials)
		fabricator.rmat.mat_container.insert_amount_mat(10000, material)
	var/before = json_encode(fabricator.rmat.mat_container.materials)
	fabricator.add_to_queue(design, ID_DATA(user))
	move_apart(fabricator, move_server)
	TEST_ASSERT(!fabricator.build_next_in_queue(FALSE), "Separated exofab started a new foreign job (server moved: [move_server])")
	TEST_ASSERT_EQUAL(json_encode(fabricator.rmat.mat_container.materials), before, "Rejected exofab job consumed materials")
	TEST_ASSERT_NULL(fabricator.stored_research, "Separated exofab retained its research link")
	server.forceMove(run_loc_floor_bottom_left)
	fabricator.forceMove(run_loc_floor_bottom_left)
	fabricator.connect_techweb(web)
	TEST_ASSERT(fabricator.build_next_in_queue(FALSE), "Relinked exofab could not start its queued job")
	var/paid = json_encode(fabricator.being_built_materials)
	move_apart(fabricator, move_server)
	fabricator.ui_data(user)
	TEST_ASSERT_NULL(fabricator.stored_research, "Moved exofab UI retained a foreign link")
	TEST_ASSERT_EQUAL(fabricator.being_built, design, "Movement discarded an already-paid job")
	TEST_ASSERT_EQUAL(json_encode(fabricator.being_built_materials), paid, "Movement changed the captured payment")
	TEST_ASSERT(fabricator.dispense_built_part(design), "Movement prevented an already-paid job from completing")
	var/obj/item/stock_parts/power_store/cell/empty/product = locate() in get_turf(fabricator)
	TEST_ASSERT_NOTNULL(product, "Paid exofab job did not produce its physical cell")
	qdel(product)

/datum/unit_test/voidcrew_research_movement/fabricators/proc/check_components(move_server)
	var/obj/machinery/component_printer/printer = allocate(/obj/machinery/component_printer)
	printer.materials.set_local_size(1000 * SHEET_MATERIAL_AMOUNT)
	printer.connect_techweb(web)
	var/datum/design/design = SSresearch.techweb_design_by_id("comp_arithmetic")
	TEST_ASSERT_NOTNULL(design, "Missing component printer regression design")
	web.add_design(design)
	for(var/material in design.materials)
		printer.materials.mat_container.insert_amount_mat(10000, material)
	var/before = json_encode(printer.materials.mat_container.materials)
	move_apart(printer, move_server)
	TEST_ASSERT_NULL(printer.print_component(design.build_path, ID_DATA(user)), "Separated circuit print consumed a foreign design (server moved: [move_server])")
	TEST_ASSERT_EQUAL(json_encode(printer.materials.mat_container.materials), before, "Rejected component print consumed materials")
	TEST_ASSERT_NULL(printer.techweb, "Separated component printer retained its link")
	TEST_ASSERT_EQUAL(length(printer.current_unlocked_designs), 0, "Separated printer retained its disk's cached designs")

/datum/unit_test/voidcrew_research_movement/medical/Run()
	TEST_ASSERT(setup_links(), "No separate service site exists for movement testing")
	web.add_design_by_id("surgery_heal_brute_upgrade")
	for(var/move_server in list(FALSE, TRUE))
		check_surgeries(move_server)
		server.forceMove(run_loc_floor_bottom_left)
		check_experiments(move_server)
		server.forceMove(run_loc_floor_bottom_left)
		check_mutations(move_server)
		server.forceMove(run_loc_floor_bottom_left)

/datum/unit_test/voidcrew_research_movement/medical/proc/check_surgeries(move_server)
	var/obj/machinery/computer/operating/operating = allocate(/obj/machinery/computer/operating)
	operating.multitool_act(user, tool)
	move_apart(operating, move_server)
	operating.sync_surgeries()
	TEST_ASSERT_EQUAL(length(operating.advanced_surgeries), 0, "Moved operating console downloaded foreign protocols (server moved: [move_server])")
	TEST_ASSERT_NULL(operating.linked_techweb, "Moved operating console retained its link")
	server.forceMove(run_loc_floor_bottom_left)
	operating.forceMove(run_loc_floor_bottom_left)
	operating.multitool_act(user, tool)
	operating.sync_surgeries()
	TEST_ASSERT(length(operating.advanced_surgeries), "Reunited operating console could not download local protocols")
	var/learned_surgeries = json_encode(operating.advanced_surgeries)
	move_apart(operating, move_server)
	operating.sync_surgeries()
	TEST_ASSERT_EQUAL(json_encode(operating.advanced_surgeries), learned_surgeries, "Movement erased already-downloaded surgery protocols")
	server.forceMove(run_loc_floor_bottom_left)
	var/mob/living/basic/bot/medbot/bot = allocate(/mob/living/basic/bot/medbot)
	bot.bot_access_flags &= ~BOT_COVER_LOCKED
	bot.multitool_act(user, tool)
	var/datum/tgui/ui = allocate(/datum/tgui, user, bot, "BotMedbot")
	var/old_healing = bot.heal_amount
	move_apart(bot, move_server)
	bot.ui_act("sync_tech", list(), ui)
	TEST_ASSERT_EQUAL(bot.heal_amount, old_healing, "Moved medbot downloaded foreign upgrades")
	TEST_ASSERT_NULL(bot.linked_techweb, "Moved medbot retained its research link")
	server.forceMove(run_loc_floor_bottom_left)
	bot.forceMove(run_loc_floor_bottom_left)
	bot.multitool_act(user, tool)
	bot.ui_act("sync_tech", list(), ui)
	TEST_ASSERT(bot.heal_amount > old_healing, "Reunited medbot could not download local upgrades")
	var/learned_healing = bot.heal_amount
	move_apart(bot, move_server)
	bot.ui_act("sync_tech", list(), ui)
	TEST_ASSERT_EQUAL(bot.heal_amount, learned_healing, "Movement erased already-learned medbot upgrades")

/datum/unit_test/voidcrew_research_movement/medical/proc/check_experiments(move_server)
	var/obj/machinery/computer/operating/operating = allocate(/obj/machinery/computer/operating)
	operating.multitool_act(user, tool)
	var/datum/component/experiment_handler/handler = operating.experiment_handler
	handler.config_flags &= ~EXPERIMENT_CONFIG_ALWAYS_ACTIVE
	var/datum/experiment/autopsy/human/experiment = allocate(/datum/experiment/autopsy/human)
	web.available_experiments |= experiment
	handler.selected_experiment = experiment
	var/points = json_encode(web.research_points)
	move_apart(operating, move_server)
	TEST_ASSERT(!handler.action_experiment(operating, user), "Moved experiment handler completed work on a foreign web (server moved: [move_server])")
	TEST_ASSERT(!experiment.completed, "Rejected experiment was marked complete")
	TEST_ASSERT_EQUAL(json_encode(web.research_points), points, "Rejected experiment changed foreign research points")
	TEST_ASSERT_NULL(handler.linked_web, "Moved experiment handler retained its foreign link")

/datum/unit_test/voidcrew_research_movement/medical/proc/check_mutations(move_server)
	var/obj/machinery/computer/dna_console/console = allocate(/obj/machinery/computer/dna_console)
	console.multitool_act(user, tool)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	patient.dna.add_mutation(/datum/mutation/hulk, MUTATION_SOURCE_ACTIVATED)
	var/datum/mutation/mutation = patient.dna.get_mutation(/datum/mutation/hulk)
	TEST_ASSERT_NOTNULL(mutation, "Could not create the mutation discovery fixture")
	var/datum/mutation/known_mutation = GET_INITIALIZED_MUTATION(mutation.type)
	TEST_ASSERT_NOTNULL(known_mutation.alias, "The mutation fixture has no discovery alias")
	console.scanner_occupant = patient
	web.discovered_mutations -= mutation.type
	move_apart(console, move_server)
	TEST_ASSERT(!console.check_discovery(known_mutation.alias), "Moved DNA console uploaded a discovery to a foreign web (server moved: [move_server])")
	TEST_ASSERT(!(mutation.type in web.discovered_mutations), "Foreign web received a mutation discovery")
	TEST_ASSERT_NULL(console.stored_research, "Moved DNA console retained its link")

/datum/unit_test/voidcrew_research_movement/console/Run()
	TEST_ASSERT(setup_links(), "No separate service site exists for movement testing")
	for(var/move_server in list(FALSE, TRUE))
		check_notes(move_server)
		server.forceMove(run_loc_floor_bottom_left)
	var/obj/machinery/computer/rdconsole/console = allocate(/obj/machinery/computer/rdconsole)
	tool.buffer = null
	TEST_ASSERT(console.multitool_act(user, tool), "Empty R&D multitool was not handled")
	TEST_ASSERT_NULL(console.stored_research, "Empty R&D multitool invented a link")
	tool.buffer = web
	console.multitool_act(user, tool)
	console.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(length(web.consoles_accessing), 1, "Repeated console linking duplicated the web's console registration")
	var/registered = length(web.connected_machines)
	tool.buffer = null
	console.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(console.stored_research, web, "An empty buffer replaced a working R&D link")
	TEST_ASSERT_EQUAL(length(web.connected_machines), registered, "An empty buffer duplicated the console registration")

/datum/unit_test/voidcrew_research_movement/console/proc/check_notes(move_server)
	var/obj/machinery/computer/rdconsole/console = allocate(/obj/machinery/computer/rdconsole)
	console.multitool_act(user, tool)
	var/obj/item/research_notes/notes = allocate(/obj/item/research_notes)
	notes.value = 10
	var/points = json_encode(web.research_points)
	move_apart(console, move_server)
	console.attackby(notes, user)
	TEST_ASSERT_EQUAL(json_encode(web.research_points), points, "Moved R&D console credited a foreign disk (server moved: [move_server])")
	TEST_ASSERT(!QDELETED(notes), "Rejected research notes were consumed")
	TEST_ASSERT_NULL(console.stored_research, "Moved R&D console retained its link")
