/datum/unit_test/voidcrew_research_movement/science_program_linking/Run()
	TEST_ASSERT(setup_links(), "No separate site exists for Science Hub link testing")
	var/obj/item/modular_computer/tablet = allocate(/obj/item/modular_computer)
	var/datum/computer_file/program/science/program = allocate(/datum/computer_file/program/science)
	TEST_ASSERT(tablet.store_file(program), "Science Hub could not install normally")
	TEST_ASSERT_EQUAL(program.multitool_act(user, tool), ITEM_INTERACT_SUCCESS, "Science Hub refused its local physical disk")
	var/obj/machinery/rnd/server/ship/foreign_server = allocate(/obj/machinery/rnd/server/ship, remote_turf)
	var/obj/item/computer_disk/ship_disk/foreign_disk = allocate(/obj/item/computer_disk/ship_disk)
	foreign_server.attacked_by(foreign_disk, user)
	tool.buffer = foreign_disk.stored_research
	TEST_ASSERT_EQUAL(program.multitool_act(user, tool), ITEM_INTERACT_BLOCKING, "Science Hub accepted a foreign server buffer")
	TEST_ASSERT_EQUAL(program.stored_research, web, "A refused program link replaced the local research disk")
	tool.buffer = null
	TEST_ASSERT_EQUAL(program.multitool_act(user, tool), ITEM_INTERACT_BLOCKING, "Science Hub did not handle an empty buffer")
	TEST_ASSERT_EQUAL(program.stored_research, web, "An empty program buffer discarded the local research link")

/datum/unit_test/voidcrew_research_movement/science_program_actions/Run()
	TEST_ASSERT(setup_links(), "No separate site exists for Science Hub action testing")
	for(var/move_server in list(FALSE, TRUE))
		check_actions(move_server)
		server.forceMove(run_loc_floor_bottom_left)

/datum/unit_test/voidcrew_research_movement/science_program_actions/proc/check_actions(move_server)
	var/obj/item/modular_computer/tablet = allocate(/obj/item/modular_computer)
	var/datum/computer_file/program/science/program = allocate(/datum/computer_file/program/science)
	TEST_ASSERT(tablet.store_file(program), "Science Hub could not install normally")
	program.multitool_act(user, tool)
	var/datum/techweb_node/candidate
	for(var/node_id in web.available_nodes)
		var/datum/techweb_node/node = SSresearch.techweb_node_by_id(node_id)
		if(!length(node.required_experiments) && !length(node.required_surveyed_objects) && length(node.research_costs))
			candidate = node
			break
	TEST_ASSERT_NOTNULL(candidate, "No ordinary available node exists for real research testing")
	web.add_point_list(list(TECHWEB_POINT_TYPE_GENERIC = 10000))
	var/points_before = json_encode(web.research_points)
	move_apart(tablet, move_server)
	TEST_ASSERT(!program.enqueue_node(candidate.id, user), "Moved Science Hub queued research on a foreign disk (server moved: [move_server])")
	TEST_ASSERT(!(candidate.id in web.research_queue_nodes), "Foreign disk received a queued program request")
	TEST_ASSERT_NULL(program.stored_research, "Moved Science Hub retained its foreign link")
	// Test direct research independently from the queue action's invalidation.
	program.stored_research = web
	TEST_ASSERT(!program.research_node(candidate.id, user), "Moved Science Hub spent foreign research points")
	TEST_ASSERT_EQUAL(json_encode(web.research_points), points_before, "Rejected program research changed another site's points")
	TEST_ASSERT(!web.researched_nodes[candidate.id], "Rejected program research unlocked a foreign node")
	web.enqueue_node(candidate.id, user)
	program.stored_research = web
	TEST_ASSERT(!program.dequeue_node(candidate.id, user), "Moved Science Hub cancelled another site's queued work")
	TEST_ASSERT(candidate.id in web.research_queue_nodes, "Rejected program action removed the server's existing work")
	// Restoring the physical endpoints must permit actual queue management and research.
	server.forceMove(run_loc_floor_bottom_left)
	tablet.forceMove(run_loc_floor_bottom_left)
	program.multitool_act(user, tool)
	TEST_ASSERT(program.dequeue_node(candidate.id, user), "Local Science Hub could not remove its own queued work")
	TEST_ASSERT(program.enqueue_node(candidate.id, user), "Local Science Hub could not queue research")
	TEST_ASSERT(program.dequeue_node(candidate.id, user), "Local Science Hub could not cancel research")
	TEST_ASSERT(program.research_node(candidate.id, user), "Local Science Hub could not research an available funded node")
	TEST_ASSERT(web.researched_nodes[candidate.id], "Successful local program research did not unlock the node")
	TEST_ASSERT(json_encode(web.research_points) != points_before, "Successful local program research did not pay for the node")

/datum/unit_test/voidcrew_research_movement/science_program_disk/Run()
	TEST_ASSERT(setup_links(), "No physical server exists for Science Hub disk testing")
	var/obj/item/modular_computer/tablet = allocate(/obj/item/modular_computer)
	var/datum/computer_file/program/science/program = allocate(/datum/computer_file/program/science)
	TEST_ASSERT(tablet.store_file(program), "Science Hub could not install normally")
	program.multitool_act(user, tool)
	var/obj/machinery/rnd/production/protolathe/lathe = allocate(/obj/machinery/rnd/production/protolathe)
	lathe.connect_techweb(web)
	var/obj/item/computer_disk/ship_disk/disk = server.source_code_hdd
	disk.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT_NULL(program.stored_research, "Physical disk removal did not immediately disconnect its installed program")
	TEST_ASSERT_NULL(lathe.stored_research, "A mixed program/machine consumer list failed to disconnect machinery")
	TEST_ASSERT(!(program in web.connected_machines), "Physical disk removal retained the program consumer")
	var/list/data = program.ui_data(user)
	TEST_ASSERT(!data["stored_research"], "Science Hub displayed research from a removed physical disk")
	TEST_ASSERT_NULL(program.stored_research, "Science Hub retained a disk with no installed server")
	TEST_ASSERT_EQUAL(program.multitool_act(user, tool), ITEM_INTERACT_BLOCKING, "Science Hub accepted a stale buffer for an ejected disk")
	server.attacked_by(disk, user)
	TEST_ASSERT_EQUAL(program.multitool_act(user, tool), ITEM_INTERACT_SUCCESS, "Science Hub could not reconnect the reinserted local disk")
	data = program.ui_data(user)
	TEST_ASSERT(data["stored_research"], "Science Hub could not display its reinserted local disk")
	program.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(length(web.connected_machines), 1, "Repeated program linking duplicated its consumer registration")
	TEST_ASSERT(tablet.remove_file(program), "The installed Science Hub could not be removed normally")
	TEST_ASSERT_EQUAL(length(web.connected_machines), 0, "Removing the program retained a consumer reference on the disk")
