/** Behavioral checks for biological sourcing, commanded development and adaptive counters. */

/datum/unit_test/vestige_chrysalis_tissue/Run()
	var/mob/living/carbon/human/keeper = allocate(/mob/living/carbon/human/consistent)
	keeper.mind_initialize()
	var/datum/vestige_trial/birth/trial = allocate(/datum/vestige_trial/birth, keeper.mind)
	keeper.mind.active_vestige_trial = trial
	trial.on_accepted(keeper)
	var/mob/living/basic/carp/carcass = allocate(/mob/living/basic/carp, get_step(keeper, NORTH))
	TEST_ASSERT(vestige_chrysalis_fauna(carcass, keeper), "Ordinary carp must provide a practical source without a human DNA datum.")
	TEST_ASSERT(!vestige_chrysalis_fauna(keeper, keeper), "Human players are not fauna tissue sources.")
	TEST_ASSERT(!trial.egg.sow(carcass, keeper), "A living host must never be consumed as a cradle.")
	carcass.death()
	var/meat_type = vestige_chrysalis_meat(carcass)
	var/meat_before = carcass.butcher_results[meat_type]
	TEST_ASSERT(trial.egg.sow(carcass, keeper), "An unharvested carp corpse must hatch a child.")
	TEST_ASSERT_EQUAL(carcass.butcher_results[meat_type], meat_before - 1, "Hatching must consume exactly one actual harvestable tissue yield.")
	TEST_ASSERT_EQUAL(trial.child.growth, 0, "Hatching alone must not grow the child.")
	TEST_ASSERT(!HAS_TRAIT(trial.child, TRAIT_VENTCRAWLER_ALWAYS), "The child must not inherit headslug vent escape.")
	var/turf/path_tile = get_step(keeper, EAST)
	var/original_type = path_tile.type
	path_tile = path_tile.ChangeTurf(/turf/open/space)
	var/can_follow_in_space = path_tile.can_cross_safely(trial.child)
	path_tile.ChangeTurf(original_type)
	TEST_ASSERT(can_follow_in_space, "The child's avoidance AI must permit the documented space-carp route.")
	TEST_ASSERT(trial.child.egg_lain && !trial.child.sentience_type, "The loan must not be a route to a fertile player headslug.")
	TEST_ASSERT(!length(trial.child.butcher_results) && !length(trial.child.guaranteed_butcher_results), "A loaned child must not provide free harvestable organs or meat.")
	TEST_ASSERT(!trial.egg.sow(carcass, keeper), "An existing live child must prevent a duplicate hatch.")
	TEST_ASSERT(!QDELETED(carcass), "Hatching must preserve the corpse and its remaining player property.")
	var/obj/item/vestige_egg/old_egg = trial.egg
	var/mob/living/basic/headslug/vestige_child/old_child = trial.child
	var/datum/vestige_trial/birth/replacement = allocate(/datum/vestige_trial/birth, keeper.mind)
	keeper.mind.active_vestige_trial = replacement
	TEST_ASSERT(!old_egg.get_trial(keeper), "An old egg cannot resolve a replacement trial of the same type.")
	TEST_ASSERT(!old_child.get_trial(), "An old child cannot develop under a replacement trial.")
	qdel(trial)
	TEST_ASSERT(QDELETED(old_egg) && QDELETED(old_child), "Ending the old trial must reclaim both original and deployed loans.")
	carcass.butcher_results.Cut()
	TEST_ASSERT_NULL(vestige_chrysalis_meat(carcass), "An exhausted carcass cannot provide imaginary tissue.")

/datum/unit_test/vestige_chrysalis_child_development/Run()
	var/mob/living/carbon/human/keeper = allocate(/mob/living/carbon/human/consistent)
	keeper.mind_initialize()
	var/datum/vestige_trial/birth/trial = allocate(/datum/vestige_trial/birth, keeper.mind)
	keeper.mind.active_vestige_trial = trial
	trial.on_accepted(keeper)
	var/mob/living/basic/headslug/vestige_child/child = allocate(/mob/living/basic/headslug/vestige_child)
	child.trial_ref = WEAKREF(trial)
	trial.child = child
	trial.register_loan(child)
	var/mob/living/basic/carp/prey = allocate(/mob/living/basic/carp, get_step(child, NORTH))
	var/undamaged_health = prey.health
	child.melee_attack(prey, ignore_cooldown = TRUE)
	TEST_ASSERT_EQUAL(prey.health, undamaged_health, "Direct melee calls cannot bypass the required current command.")
	TEST_ASSERT_EQUAL(child.growth, 0, "An uncommanded attack cannot advance growth.")
	TEST_ASSERT(trial.egg.command_child(prey, keeper), "The real egg control must establish the attack command.")
	prey.adjustBruteLoss(prey.maxHealth - 3)
	TEST_ASSERT(child.melee_attack(prey, ignore_cooldown = TRUE), "A commanded larva must perform a real attack.")
	TEST_ASSERT_EQUAL(prey.stat, DEAD, "The small prey must actually die in this setup.")
	TEST_ASSERT_EQUAL(child.growth, 3, "A nearly dead target provides only its remaining living tissue, not the full nominal hit.")
	child.melee_attack(prey, ignore_cooldown = TRUE)
	TEST_ASSERT_EQUAL(child.growth, 3, "Repeated corpse attacks must not develop the child.")
	child.adjust_health(30)
	keeper.dropItemToGround(keeper.get_inactive_held_item())
	var/obj/item/food/fishmeat/carp/food = allocate(/obj/item/food/fishmeat/carp)
	keeper.put_in_hands(food)
	TEST_ASSERT(child.nourish(food, keeper), "Ordinary carp fillets must provide recovery without a previous boon.")
	TEST_ASSERT_EQUAL(child.health, 40, "A meal heals exactly 25 of the child's 45 health.")
	TEST_ASSERT_EQUAL(child.growth, 3, "Feeding safe food cannot substitute for commanded hunting.")
	var/mob/living/basic/carp/next_prey = allocate(/mob/living/basic/carp, get_step(child, NORTH))
	child.prey_ref = WEAKREF(next_prey)
	next_prey.forceMove(get_step(get_step(child, EAST), EAST))
	TEST_ASSERT(!child.melee_attack(next_prey, ignore_cooldown = TRUE), "Direct melee calls must still require adjacency.")
	next_prey.forceMove(get_step(child, NORTH))
	keeper.death()
	TEST_ASSERT(!child.melee_attack(next_prey, ignore_cooldown = TRUE), "A dead keeper cannot keep earning development from autonomous attacks.")
	TEST_ASSERT_EQUAL(child.growth, 3, "Death must leave the previous progress unchanged.")

/datum/unit_test/vestige_chrysalis_adaptive_counter/Run()
	var/mob/living/carbon/human/keeper = allocate(/mob/living/carbon/human/consistent)
	keeper.mind_initialize()
	var/datum/vestige_trial/faces/trial = allocate(/datum/vestige_trial/faces, keeper.mind)
	keeper.mind.active_vestige_trial = trial
	trial.on_accepted(keeper)
	var/obj/item/vestige_proboscis/organ = trial.proboscis
	var/mob/living/basic/carp/prey = allocate(/mob/living/basic/carp, get_step(keeper, NORTH))
	TEST_ASSERT(!organ.begin_brace(keeper), "The adaptation needs actual sampled tissue first.")
	trial.sampled = TRUE
	TEST_ASSERT(!organ.counter_lash(prey, keeper), "Repeated unprepared pokes cannot award tissue.")
	TEST_ASSERT(organ.begin_brace(keeper), "A sampled organ must offer the defensive form.")
	TEST_ASSERT(HAS_TRAIT(keeper, TRAIT_IMMOBILIZED), "Bracing must impose its real movement cost.")
	var/before = keeper.getBruteLoss()
	prey.melee_attack(keeper, ignore_cooldown = TRUE)
	TEST_ASSERT_EQUAL(keeper.getBruteLoss(), before, "The brace must block a real basic-fauna melee strike.")
	TEST_ASSERT(!HAS_TRAIT(keeper, TRAIT_IMMOBILIZED), "Catching a bite must release the brace for repositioning.")
	TEST_ASSERT_EQUAL(organ.attacker_ref?.resolve(), prey, "The counter must be bound to the actual attacker.")
	TEST_ASSERT(!organ.counter_lash(prey, keeper), "Standing at the impact point must not finish the counter.")
	var/turf/retreat = get_step(get_step(keeper, EAST), EAST)
	keeper.forceMove(retreat)
	var/mob/living/basic/carp/other = allocate(/mob/living/basic/carp, get_step(keeper, NORTH))
	TEST_ASSERT(!organ.counter_lash(other, keeper), "A different animal cannot be substituted after a safe block.")
	TEST_ASSERT(organ.counter_lash(prey, keeper), "Moving away and countering the same live attacker must assimilate real tissue.")
	TEST_ASSERT_EQUAL(trial.assimilated, 20, "The counter credits actual damage.")
	TEST_ASSERT(!organ.counter_lash(prey, keeper), "A counter is consumed exactly once.")
	var/tissue_before_ordinary_hit = trial.assimilated
	prey.adjustBruteLoss(1)
	TEST_ASSERT_EQUAL(trial.assimilated, tissue_before_ordinary_hit, "Ordinary combat damage cannot advance the adaptation trial.")
	prey.adjustBruteLoss(-1)
	organ.brace_ready_at = world.time
	prey.forceMove(get_step(keeper, NORTH))
	TEST_ASSERT(organ.begin_brace(keeper), "The form can be retried once its cooldown ends.")
	prey.melee_attack(keeper, ignore_cooldown = TRUE)
	keeper.forceMove(get_step(get_step(keeper, EAST), EAST))
	TEST_ASSERT(organ.counter_lash(prey, keeper), "The remaining living tissue can be assimilated in a second actual counter.")
	TEST_ASSERT_EQUAL(trial.assimilated, 25, "A five-health target must not provide twenty more tissue.")

/datum/unit_test/vestige_chrysalis_adaptation_cleanup/Run()
	var/mob/living/carbon/human/keeper = allocate(/mob/living/carbon/human/consistent)
	keeper.mind_initialize()
	var/datum/vestige_trial/faces/trial = allocate(/datum/vestige_trial/faces, keeper.mind)
	keeper.mind.active_vestige_trial = trial
	trial.on_accepted(keeper)
	trial.sampled = TRUE
	var/obj/item/vestige_proboscis/organ = trial.proboscis
	TEST_ASSERT(organ.begin_brace(keeper), "Begin the old body's brace.")
	var/mob/living/carbon/human/new_body = allocate(/mob/living/carbon/human/consistent)
	keeper.mind.transfer_to(new_body)
	TEST_ASSERT(!HAS_TRAIT(keeper, TRAIT_IMMOBILIZED), "Body transfer must clean the old body's root immediately.")
	TEST_ASSERT_NULL(organ.body_ref, "A body transfer must discard the old counter, not transfer a borrowed defensive state.")
	TEST_ASSERT(!organ.get_trial(keeper), "The old body may not use a mind-bound kit.")
	keeper.dropItemToGround(organ)
	new_body.put_in_hands(organ)
	organ.brace_ready_at = world.time
	TEST_ASSERT(organ.begin_brace(new_body), "The same mind can explicitly use its organ in the new body.")
	new_body.dropItemToGround(organ)
	TEST_ASSERT(!HAS_TRAIT(new_body, TRAIT_IMMOBILIZED), "Dropping the loan must immediately remove its temporary root.")
	new_body.put_in_hands(organ)
	organ.brace_ready_at = world.time
	organ.begin_brace(new_body)
	var/mob/living/basic/carp/attacker = allocate(/mob/living/basic/carp, get_step(new_body, NORTH))
	attacker.melee_attack(new_body, ignore_cooldown = TRUE)
	TEST_ASSERT(organ.attacker_ref, "Prepare a real pending counter before death.")
	new_body.death()
	TEST_ASSERT_NULL(organ.attacker_ref, "Death must discard even a counter whose brace has already ended.")
	qdel(trial)
	TEST_ASSERT(QDELETED(organ), "Ending the attempt must reclaim its adaptation organ.")
	TEST_ASSERT(!HAS_TRAIT_FROM(new_body, TRAIT_IMMOBILIZED, TRAIT_STATUS_EFFECT("vestige_chrysalis_brace")), "Reclaiming the organ must remove its own brace restraint.")
	TEST_ASSERT(HAS_TRAIT_FROM(new_body, TRAIT_IMMOBILIZED, TRAIT_KNOCKEDOUT), "Removing the brace must preserve the body's legitimate death restraint.")
