/// A timed adaptation belongs to its body, but replacing it must retire the old trait set.
/datum/unit_test/vestige_status_held_breath_replacement/Run()
	var/mob/living/carbon/human/strong_body = allocate(/mob/living/carbon/human/consistent)
	var/mob/living/carbon/human/base_body = allocate(/mob/living/carbon/human/consistent, get_step(strong_body, EAST))
	var/mob/living/carbon/human/spare_body = allocate(/mob/living/carbon/human/consistent, get_step(strong_body, NORTH))
	strong_body.mind_initialize()
	base_body.mind_initialize()
	var/datum/action/cooldown/spell/vestige_held_breath/long_exposure/long_spell = allocate(/datum/action/cooldown/spell/vestige_held_breath/long_exposure, strong_body.mind)
	var/datum/action/cooldown/spell/vestige_held_breath/base_spell = allocate(/datum/action/cooldown/spell/vestige_held_breath, base_body.mind)
	long_spell.Grant(strong_body)
	base_spell.Grant(base_body)
	ADD_TRAIT(strong_body, TRAIT_RESISTCOLD, TRAIT_SOURCE_UNIT_TESTS)
	TEST_ASSERT(long_spell.Trigger(strong_body), "The actual Long Exposure action must apply its adaptation.")
	var/datum/status_effect/vestige_held_breath/long_exposure/long_effect = strong_body.has_status_effect(/datum/status_effect/vestige_held_breath)
	TEST_ASSERT(istype(long_effect), "Long Exposure did not install its stronger status subtype.")
	TEST_ASSERT(HAS_TRAIT(strong_body, TRAIT_SPACEWALK) && HAS_TRAIT(strong_body, TRAIT_NO_BREATHLESS_DAMAGE), "The stronger adaptation must first grant both extra protections.")
	strong_body.mind.transfer_to(spare_body)
	base_body.mind.transfer_to(strong_body)
	TEST_ASSERT_EQUAL(base_spell.owner, strong_body, "The real mind transfer must bring the base lesson into the adapted body.")
	TEST_ASSERT_EQUAL(strong_body.has_status_effect(/datum/status_effect/vestige_held_breath), long_effect, "Changing minds must preserve the intentionally body-bound timed adaptation until it is replaced.")
	TEST_ASSERT(!spare_body.has_status_effect(/datum/status_effect/vestige_held_breath), "Moving the lesson must not duplicate an already-cast body adaptation.")
	TEST_ASSERT(base_spell.Trigger(strong_body), "The incoming mind must cast its actual base adaptation.")
	var/datum/status_effect/vestige_held_breath/base_effect = strong_body.has_status_effect(/datum/status_effect/vestige_held_breath)
	TEST_ASSERT(QDELETED(long_effect) && base_effect.type == /datum/status_effect/vestige_held_breath, "The base cast must replace the old stronger effect.")
	TEST_ASSERT(!HAS_TRAIT(strong_body, TRAIT_SPACEWALK) && !HAS_TRAIT(strong_body, TRAIT_NO_BREATHLESS_DAMAGE), "Replacing Long Exposure retained its stronger traits without a status to remove them.")
	TEST_ASSERT(HAS_TRAIT(strong_body, TRAIT_RESISTLOWPRESSURE), "The new base adaptation must retain its own protection.")
	base_effect.duration = world.time - 1
	base_effect.process(0)
	TEST_ASSERT(QDELETED(base_effect) && !HAS_TRAIT(strong_body, TRAIT_RESISTLOWPRESSURE), "Normal status expiry must remove the replacement's borrowed protection.")
	TEST_ASSERT(HAS_TRAIT_FROM(strong_body, TRAIT_RESISTCOLD, TRAIT_SOURCE_UNIT_TESTS), "Replacement or expiry stripped an independently owned cold-resistance source.")
	base_spell.ResetCooldown()
	TEST_ASSERT(base_spell.Trigger(strong_body), "The normal base adaptation must remain reusable after expiry.")
	base_effect = strong_body.has_status_effect(/datum/status_effect/vestige_held_breath)
	qdel(strong_body)
	TEST_ASSERT(QDELETED(base_effect), "Deleting the adapted body must retire its status without retaining the body.")
	TEST_ASSERT_NULL(base_spell.owner, "Deleting the body must remove its action while leaving the mind-owned lesson intact.")

/// Borrowed names continuously refresh the generic Oracle call with their own four-second duration.
/datum/unit_test/vestige_status_borrowed_name_refresh/Run()
	var/turf/center = get_step(get_step(get_step(run_loc_floor_bottom_left, NORTH), NORTH), EAST)
	var/turf/first_floor = get_step(center, WEST)
	var/turf/second_floor = get_step(get_step(center, EAST), EAST)
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent, first_floor)
	user.mind_initialize()
	var/obj/item/borrowed_name/first_token = allocate(/obj/item/borrowed_name)
	TEST_ASSERT(user.put_in_active_hand(first_token), "The first real name token must be held for planting.")
	user.execute_mode()
	var/obj/structure/borrowed_name/first_name = locate() in first_floor
	TEST_ASSERT(first_name, "The real token's in-hand control did not plant its caller.")
	STOP_PROCESSING(SSobj, first_name)
	user.dropItemToGround(first_token)
	user.forceMove(second_floor)
	var/obj/item/borrowed_name/second_token = allocate(/obj/item/borrowed_name)
	TEST_ASSERT(user.put_in_active_hand(second_token), "The second real name token must be held for planting.")
	user.execute_mode()
	var/obj/structure/borrowed_name/second_name = locate() in second_floor
	TEST_ASSERT(second_name, "The second physical token did not plant an independent caller.")
	STOP_PROCESSING(SSobj, second_name)
	var/mob/living/basic/carp/listener = allocate(/mob/living/basic/carp, center)
	listener.ai_controller.PauseAi(1 MINUTES)
	first_name.process(1)
	var/datum/status_effect/oracle_called/summons = listener.has_status_effect(/datum/status_effect/oracle_called)
	TEST_ASSERT(summons && summons.caller_ref.resolve() == first_name, "The first real caller must establish the creature's call.")
	first_name.process(1)
	TEST_ASSERT_EQUAL(listener.has_status_effect(/datum/status_effect/oracle_called), summons, "A repeated pulse should refresh the same effect rather than stack pulls.")
	TEST_ASSERT_EQUAL(summons.duration, world.time + first_name.pull_duration, "Refreshing a borrowed name silently substituted the boss's longer call duration.")
	second_name.process(1)
	TEST_ASSERT_EQUAL(summons.caller_ref.resolve(), second_name, "A new physical caller did not replace the retained source of a refreshed call.")
	TEST_ASSERT_EQUAL(summons.duration, world.time + second_name.pull_duration, "The replacement caller's duration was ignored.")
	qdel(first_name)
	summons.tick(1)
	TEST_ASSERT(!QDELETED(summons) && listener.x > center.x, "Deleting the superseded caller canceled the new call or kept pulling toward the old source.")
	qdel(second_name)
	summons.tick(1)
	TEST_ASSERT(QDELETED(summons), "Deleting the active caller must release the retained status.")

/// Two real blades can overlap guard; refreshing must retain the player's three-second contract.
/datum/unit_test/vestige_status_sparring_guard_refresh/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/sparring_blade/first_blade = allocate(/obj/item/sparring_blade)
	var/obj/item/sparring_blade/second_blade = allocate(/obj/item/sparring_blade)
	TEST_ASSERT(user.put_in_hands(first_blade) && user.put_in_hands(second_blade), "The guard regression must wield two physical sparring blades.")
	var/datum/action/cooldown/mob_cooldown/warframe_guard/held/first_guard = locate() in first_blade.actions
	var/datum/action/cooldown/mob_cooldown/warframe_guard/held/second_guard = locate() in second_blade.actions
	TEST_ASSERT(first_guard?.owner == user && second_guard?.owner == user, "Each held blade must grant its own actual guard control.")
	TEST_ASSERT(first_guard.Trigger(user), "The first blade must raise its real guard.")
	var/datum/status_effect/warframe_guard/stance = user.has_status_effect(/datum/status_effect/warframe_guard)
	TEST_ASSERT(stance && stance.riposte_damage == 16, "The held blade must establish the player's counter, not the boss's.")
	TEST_ASSERT(second_guard.Trigger(user), "The independently ready second blade must refresh the existing stance.")
	TEST_ASSERT_EQUAL(user.has_status_effect(/datum/status_effect/warframe_guard), stance, "Overlapping guards must retain a single stance and counter cooldown.")
	TEST_ASSERT_EQUAL(stance.duration, world.time + second_guard.guard_duration, "The second blade extended guard to the boss's duration instead of its advertised three seconds.")
	TEST_ASSERT_EQUAL(stance.riposte_damage, 16, "Refreshing the player's stance replaced its existing counter configuration.")
	user.dropItemToGround(first_blade)
	user.dropItemToGround(second_blade)
	TEST_ASSERT_EQUAL(user.has_status_effect(/datum/status_effect/warframe_guard), stance, "An already-raised timed stance must remain body-bound when its blades are dropped.")
	stance.duration = world.time - 1
	stance.process(0)
	TEST_ASSERT(QDELETED(stance) && !user.get_filter("warframe_guard"), "Expiring the refreshed stance must remove its status and visible guard.")
