/// Revoking an experiment link must cancel pending physical callbacks and rewards.
/datum/unit_test/voidcrew_relay_experiment_lifecycle/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent)
	var/obj/machinery/rnd/server/ship/server = allocate(/obj/machinery/rnd/server/ship)
	var/obj/item/computer_disk/ship_disk/disk = allocate(/obj/item/computer_disk/ship_disk)
	server.attacked_by(disk, user)
	var/points_before = disk.stored_research.research_points[TECHWEB_POINT_TYPE_GENERIC]
	var/obj/item/experi_scanner/scanner = allocate(/obj/item/experi_scanner)
	var/datum/component/experiment_handler/handler = scanner.GetComponent(/datum/component/experiment_handler)
	TEST_ASSERT_NOTNULL(handler, "Scanner has no experiment handler")
	var/datum/experiment/physical/arcade_winner/experiment = allocate(/datum/experiment/physical/arcade_winner)
	disk.stored_research.available_experiments |= experiment
	handler.link_techweb(disk.stored_research, TRUE)
	handler.link_experiment(experiment)
	var/obj/machinery/computer/arcade/arcade = allocate(/obj/machinery/computer/arcade)
	TEST_ASSERT(handler.action_experiment(null, arcade), "Physical experiment did not register its callback")
	handler.unlink_techweb()
	TEST_ASSERT_NULL(experiment.linked_experiment_handler, "Revocation retained the physical handler")
	TEST_ASSERT_NULL(experiment.currently_scanned_atom, "Revocation retained the tracked object")
	SEND_SIGNAL(arcade, COMSIG_ARCADE_PRIZEVEND)
	TEST_ASSERT(!experiment.completed, "A revoked callback completed research")
	TEST_ASSERT_EQUAL(disk.stored_research.research_points[TECHWEB_POINT_TYPE_GENERIC], points_before, "A revoked callback awarded points")
	handler.link_techweb(disk.stored_research, TRUE)
	TEST_ASSERT(!experiment.finish_experiment(handler), "Relinking revived an unselected physical callback")
	handler.link_experiment(experiment)
	TEST_ASSERT(handler.action_experiment(null, arcade), "A fresh selection could not restart the experiment")
	SEND_SIGNAL(arcade, COMSIG_ARCADE_PRIZEVEND)
	TEST_ASSERT(experiment.completed, "An authorized physical callback did not complete")
	var/reward = disk.stored_research.research_points[TECHWEB_POINT_TYPE_GENERIC]
	TEST_ASSERT(reward > 0, "Completed physical experiment did not award points")
	SEND_SIGNAL(arcade, COMSIG_ARCADE_PRIZEVEND)
	TEST_ASSERT(!experiment.finish_experiment(handler), "Completed physical experiment accepted a duplicate callback")
	TEST_ASSERT_EQUAL(disk.stored_research.research_points[TECHWEB_POINT_TYPE_GENERIC], reward, "Duplicate completion paid points twice")

/// Maintenance wiring must not be mistaken for uploading a research link.
/datum/unit_test/voidcrew_rnd_panel_wires/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/multitool/tool = allocate(/obj/item/multitool)
	var/obj/machinery/rnd/production/protolathe/lathe = allocate(/obj/machinery/rnd/production/protolathe)
	lathe.panel_open = TRUE
	TEST_ASSERT(lathe.multitool_act(user, tool), "An unlinked lathe must permit maintenance wiring")
	TEST_ASSERT_NULL(lathe.stored_research, "Opening wires invented a research link")
	var/datum/techweb/original = allocate(/datum/techweb)
	var/datum/techweb/replacement = allocate(/datum/techweb)
	lathe.panel_open = FALSE
	tool.buffer = original
	lathe.multitool_act(user, tool)
	TEST_ASSERT(lathe in original.connected_machines, "The initial multitool link was not registered")
	lathe.panel_open = TRUE
	tool.buffer = replacement
	lathe.multitool_act(user, tool)
	TEST_ASSERT_EQUAL(lathe.stored_research, original, "Opening wires replaced the research link")
	TEST_ASSERT_EQUAL(length(original.connected_machines), 1, "Opening wires changed the existing consumer registration")
	TEST_ASSERT(!(lathe in replacement.connected_machines), "Opening wires registered an unused buffer")

/// All connection paths must follow the physical disk and remove old design signals.
/datum/unit_test/voidcrew_rnd_disk_lifecycle/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent)
	var/obj/machinery/rnd/server/ship/server = allocate(/obj/machinery/rnd/server/ship)
	var/obj/item/computer_disk/ship_disk/disk = allocate(/obj/item/computer_disk/ship_disk)
	server.attacked_by(disk, user)
	var/datum/techweb/first_web = disk.stored_research
	var/obj/machinery/rnd/server/ship/replacement = allocate(/obj/machinery/rnd/server/ship)
	var/obj/item/computer_disk/ship_disk/new_disk = allocate(/obj/item/computer_disk/ship_disk)
	replacement.attacked_by(new_disk, user)
	var/datum/techweb/new_web = new_disk.stored_research
	var/obj/machinery/rnd/production/protolathe/lathe = allocate(/obj/machinery/rnd/production/protolathe)
	lathe.connect_techweb(first_web)
	lathe.connect_techweb(first_web)
	TEST_ASSERT_EQUAL(length(first_web.connected_machines), 1, "Repeated direct linking must register one consumer")
	lathe.connect_techweb(new_web)
	TEST_ASSERT(!(lathe in first_web.connected_machines), "Relinking retained the old consumer registration")
	TEST_ASSERT(lathe in new_web.connected_machines, "Relinking omitted the replacement registration")
	first_web.remove_design_by_id("cable_coil")
	first_web.add_design_by_id("cable_coil")
	TEST_ASSERT(!lathe.techweb_updating, "The old disk still sent design updates to a relinked lathe")
	var/turf/remote_turf
	for(var/level in 1 to world.maxz)
		var/turf/candidate = locate(1, 1, level)
		if(!same_service_site(lathe, candidate))
			remote_turf = candidate
			break
	TEST_ASSERT_NOTNULL(remote_turf, "No separate physical site exists for the rejected-link regression")
	server.forceMove(remote_turf)
	lathe.connect_techweb(first_web)
	TEST_ASSERT_EQUAL(lathe.stored_research, new_web, "A rejected remote link replaced the current local disk")
	new_web.remove_design_by_id("cable_coil")
	new_web.add_design_by_id("cable_coil")
	TEST_ASSERT(lathe.techweb_updating, "A rejected remote link stopped the current disk's design updates")
	lathe.update_designs()
	TEST_ASSERT(length(lathe.cached_designs), "The current physical disk did not supply any designs")
	new_disk.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT_NULL(lathe.stored_research, "Removing the physical disk left a direct-linked lathe connected")
	TEST_ASSERT_EQUAL(length(lathe.cached_designs), 0, "Removing the physical disk retained cached fabrication designs")
	TEST_ASSERT(!(lathe in new_web.connected_machines), "A detached lathe remained registered to its old disk")
	var/datum/tgui/ui = allocate(/datum/tgui, user, lathe, "Fabricator")
	TEST_ASSERT(lathe.ui_act("build", list("ref" = "cable_coil", "amount" = "1"), ui), "A stale print request after disk removal was not safely consumed")
	TEST_ASSERT(!lathe.busy, "An unlinked lathe started a stale print request")

/// A removable server drive must unlink the exofab without losing its paid work.
/datum/unit_test/voidcrew_exofab_disk_lifecycle/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/multitool/tool = allocate(/obj/item/multitool)
	var/obj/machinery/rnd/server/ship/server = allocate(/obj/machinery/rnd/server/ship)
	var/obj/item/computer_disk/ship_disk/disk = allocate(/obj/item/computer_disk/ship_disk)
	server.attacked_by(disk, user)
	var/datum/techweb/web = disk.stored_research
	web.add_design_by_id("basic_cell")
	var/obj/machinery/mecha_part_fabricator/fabricator = allocate(/obj/machinery/mecha_part_fabricator)
	fabricator.drop_direction = 0
	fabricator.rmat.set_local_size(1000 * SHEET_MATERIAL_AMOUNT)
	tool.buffer = web
	fabricator.multitool_act(user, tool)
	var/datum/design/design = SSresearch.techweb_design_by_id("basic_cell")
	TEST_ASSERT(design in fabricator.cached_designs, "The installed disk did not provide its cell design")
	for(var/material in design.materials)
		fabricator.rmat.mat_container.insert_amount_mat(10000, material)
	TEST_ASSERT(fabricator.build_part(design, FALSE), "The exofab could not start a paid physical job")
	var/list/paid_materials = fabricator.being_built_materials.Copy()
	disk.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT_NULL(fabricator.stored_research, "Removing the physical disk left the exofab connected")
	TEST_ASSERT_EQUAL(length(fabricator.cached_designs), 0, "A disconnected exofab retained the disk's designs")
	TEST_ASSERT(!(fabricator in web.connected_machines), "A disconnected exofab retained its consumer registration")
	TEST_ASSERT_EQUAL(fabricator.being_built, design, "Removing the disk discarded an already-paid job")
	TEST_ASSERT_EQUAL(json_encode(fabricator.being_built_materials), json_encode(paid_materials), "Removing the disk changed the job's captured payment")
	TEST_ASSERT(fabricator.dispense_built_part(design), "Removing the disk prevented an already-paid job from completing")
	var/obj/item/stock_parts/power_store/cell/empty/product = locate() in run_loc_floor_bottom_left
	TEST_ASSERT_NOTNULL(product, "The paid job did not produce a physical cell")
	var/datum/tgui/ui = allocate(/datum/tgui, user, fabricator, "ExosuitFabricator")
	fabricator.ui_act("build", list("designs" = list("basic_cell")), ui)
	TEST_ASSERT_EQUAL(length(fabricator.queue), 0, "An unlinked exofab accepted a stale build request")
	server.attacked_by(disk, user)
	fabricator.connect_techweb(web)
	fabricator.connect_techweb(web)
	TEST_ASSERT_EQUAL(length(web.connected_machines), 1, "Repeated exofab linking created duplicate consumer registrations")
	qdel(server)
	TEST_ASSERT_NULL(fabricator.stored_research, "Destroying the server left the exofab connected")
	TEST_ASSERT_EQUAL(disk.stored_research, web, "Destroying the server erased its surviving physical disk")

/// A newly built exofab must support inspection and maintenance before receiving a disk link.
/datum/unit_test/voidcrew_exofab_unlinked/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/multitool/tool = allocate(/obj/item/multitool)
	var/obj/machinery/mecha_part_fabricator/fabricator = allocate(/obj/machinery/mecha_part_fabricator)
	TEST_ASSERT(fabricator.multitool_act(user, tool), "The unlinked exofab did not handle an empty multitool")
	fabricator.update_menu_tech()
	TEST_ASSERT_NULL(fabricator.stored_research, "An empty buffer invented a research link")
	TEST_ASSERT_EQUAL(length(fabricator.cached_designs), 0, "The unlinked exofab invented researched designs")
	var/datum/design/local_design = SSresearch.techweb_design_by_id("basic_cell")
	fabricator.illegal_local_designs |= local_design
	fabricator.update_menu_tech()
	TEST_ASSERT(local_design in fabricator.cached_designs, "Disconnecting research erased an independent local design")
	var/datum/tgui/ui = allocate(/datum/tgui, user, fabricator, "ExosuitFabricator")
	fabricator.ui_act("build", list("designs" = list("basic_cell")), ui)
	TEST_ASSERT_EQUAL(length(fabricator.queue), 1, "The unlinked exofab rejected its own local design")

/// A foreign-site rejection must leave the existing links usable and report failure.
/datum/unit_test/voidcrew_fabricator_refused_link/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/multitool/tool = allocate(/obj/item/multitool)
	var/obj/machinery/rnd/server/ship/server = allocate(/obj/machinery/rnd/server/ship)
	var/obj/item/computer_disk/ship_disk/disk = allocate(/obj/item/computer_disk/ship_disk)
	server.attacked_by(disk, user)
	var/datum/techweb/local_web = disk.stored_research
	var/obj/machinery/mecha_part_fabricator/fabricator = allocate(/obj/machinery/mecha_part_fabricator)
	var/obj/machinery/component_printer/printer = allocate(/obj/machinery/component_printer)
	fabricator.connect_techweb(local_web)
	printer.connect_techweb(local_web)
	var/turf/remote_turf
	for(var/level in 1 to world.maxz)
		var/turf/candidate = locate(1, 1, level)
		if(!same_service_site(fabricator, candidate))
			remote_turf = candidate
			break
	TEST_ASSERT_NOTNULL(remote_turf, "No separate site exists for the refused-link regression")
	var/obj/machinery/rnd/server/ship/remote_server = allocate(/obj/machinery/rnd/server/ship, remote_turf)
	var/obj/item/computer_disk/ship_disk/remote_disk = allocate(/obj/item/computer_disk/ship_disk)
	remote_server.attacked_by(remote_disk, user)
	tool.buffer = remote_disk.stored_research
	TEST_ASSERT(!fabricator.multitool_act(user, tool), "The exofab reported a successful foreign-site link")
	TEST_ASSERT(!printer.multitool_act(user, tool), "The component printer reported a successful foreign-site link")
	TEST_ASSERT_EQUAL(fabricator.stored_research, local_web, "Refusing a foreign disk replaced the exofab's local link")
	TEST_ASSERT_EQUAL(printer.techweb, local_web, "Refusing a foreign disk replaced the printer's local link")
	local_web.remove_design_by_id("comp_arithmetic")
	local_web.add_design_by_id("comp_arithmetic")
	TEST_ASSERT_EQUAL(printer.current_unlocked_designs[/obj/item/circuit_component/arithmetic], "comp_arithmetic", "The refusal stopped local component design updates")
	local_web.remove_design_by_id("basic_cell")
	sleep(2.1 SECONDS)
	var/datum/design/cell_design = SSresearch.techweb_design_by_id("basic_cell")
	TEST_ASSERT(!(cell_design in fabricator.cached_designs), "The refusal stopped local exofab design removal updates")
	local_web.add_design_by_id("basic_cell")
	sleep(2.1 SECONDS)
	TEST_ASSERT(cell_design in fabricator.cached_designs, "The refusal stopped local exofab design addition updates")
	remote_server.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT(fabricator.multitool_act(user, tool), "The exofab refused the replacement disk after it joined this site")
	TEST_ASSERT_EQUAL(fabricator.stored_research, remote_disk.stored_research, "A valid relink did not use the replacement disk")
	disk.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT_EQUAL(fabricator.stored_research, remote_disk.stored_research, "Removing an old disk disconnected the exofab's replacement link")
	TEST_ASSERT_NULL(printer.techweb, "Disk removal left the component printer linked")
	TEST_ASSERT_EQUAL(length(printer.current_unlocked_designs), 0, "Disk removal retained component designs")
	remote_disk.forceMove(run_loc_floor_bottom_left)
	TEST_ASSERT_NULL(fabricator.stored_research, "Removing the current disk retained the exofab's link")
